### ISSUE TITLE
sample compiles with errors

### ISSUE THREAD

**Issue by paulusyeung** [CrossGeeks/FirebasePushNotificationPlugin#1]
First of all, thank you for sharing your project!

Your plugin looks promising and comes with very good documentation. But, the sample within your source code doesn't compile without twisting. It would be great if you can review the sample projects and  provide a sample solution which could be compiled and hence tested.

-- paulus

## Bug Information

Version Number of Plugin: 1.0.4
Device Tested On: 
Simulator Tested On:
Version of VS: 7.0.1 (build 24) on macOS 10.12.6
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

1. Download the complete project from Github
2. Open the sample solution, FirebasePushSample, in VS for Mac
3. Restore Nuget Packages
4. Clean the FirebasePushSample
5. Rebuild the FirebasePushSample

### Screenshotst
`/Users/paulus/Projects/FirebasePushNotificationPlugin-master/samples/FirebasePushSample/FirebasePushSample/FirebasePushSample.csproj(5,5): Error: This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ../../../packages/Xamarin.Forms.2.3.4.247/build/portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20/Xamarin.Forms.targets. (FirebasePushSample)`

**Comment by rdelrosario** [comment]
Seems you need to restore NuGet packages. Did you?

**Comment by rdelrosario** [comment]
Just found the issue, were some reference that were messed up. Just pushed a fix

**Comment by LucioMSP** [comment]
Hi, I download the sample within your source code, but this doesn't send the notification. It would be great if you can review the sample projects and provide a sample solution which could be compiled and hence tested.
