### ISSUE TITLE
iOS Local notification won't work

### ISSUE THREAD

**Issue by claudiocleberson** [CrossGeeks/FirebasePushNotificationPlugin#10]
Hi @rdelrosario,

I am implementing local notification with other plugin(Acr.Notification), but for some reason, all local notification on iOS get dragged by the PushNotificationHandler and doesn't work as expected.

I am handling all the push(Android/iOS) via your plugin.  but local notification for my app is crucial. Do you have a suggestion how to disable the current behavior on iOS?,  Without losing the push notification?

Android is working without problem so far.

**Comment by rdelrosario** [comment]
Hi

You mean to actually control when to display the notification for ios and when not?

**Comment by rdelrosario** [comment]
Are you calling local notification on the ui thread?

**Comment by claudiocleberson** [comment]
Hi, 
That is correct, I mean when to display the notification. I am using another plugin to do that when the app is in background/foreground for local notification. and for some reason the PushNotificationHandler drags the local notification, and won't show.  When the app send a location notification. If the app is in background nothing happens. In foreground the event below is called.


            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("Received " + p.Data );
            };


According with the  Acr.Notification doc, iOS notifications is handled by the UIThread.

**Comment by rdelrosario** [comment]
But when in background you get the notification shown on the notification tray?

What payload are you sending?

**Comment by claudiocleberson** [comment]
On the notification tray nothing appears.

the payload is according with the Acr.Notification docs.

 CrossNotifications.Current.Send(new Plugin.Notifications.Notification
                            {
                                Title = message.Name,
                                Message = message.Body,
                                Vibrate = true,
                                When = TimeSpan.FromMilliseconds(1000),
                                
                            //});

I know it probably has nothing to do with your plugin. but I'm just trying to combine your Push plugin with that localnotification one.

I tried other plugin Xam.Plugins.Notifier, and again the same event PushNotificationHandler, capture the notification.

**Comment by claudiocleberson** [comment]
@rdelrosario,

I was able to handled the iOS Foreground/Background Local notification by creating that delegate below

public class UserNotificationCenterDelegate : UNUserNotificationCenterDelegate
    {
        [Export("userNotificationCenter:willPresentNotification:withCompletionHandler:")]
        public override void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
        {
                completionHandler(UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Sound);
                Console.WriteLine(notification);
        }
    }

called from the  FinishedLaunching method
 
UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();

with that I could get all the local notification through.

Taken from StackOverflow
[https://stackoverflow.com/questions/40942988/how-do-i-use-delegates-within-xamarin-specifically-unusernotificationcenterdele]

thanks once more.

**Comment by rdelrosario** [comment]
Glad you figured out a fix. We will add a way to customize this maybe by using Push Notification Handler on next version.

**Comment by angelru** [comment]
@claudiocleberson 
in this way the push notifications do not work, only the local ones. Did you get both of them to work?
