### ISSUE TITLE
FirebasePushNotificationManager is not Recognized by compiler in android

### ISSUE THREAD

**Issue by rashi2010** [CrossGeeks/FirebasePushNotificationPlugin#100]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:  2.2.3
Device Tested On:  mac
Simulator Tested On:  
Version of VS:  VS 2017
Version of Xamarin:   
Versions of other things you are using:

### Steps to reproduce the Behavior
  When i copy the code in Android,it is not recognizing the FirebasePushNotificationManager  class .I install the plugin of version 2.2.3.

**Comment by rdelrosario** [comment]
Try this:
1º Uninstall nuget "FirebasePushNotificationPlugin"
2º Android Properties > Target Framework: "Use Latest Platform (Android 8.0 Oreo) or Android 8.0 Oreo"
3º Close Visual Studio and open again
4º Install nuget "FirebasePushNotificationPlugin 2.2.3"

**Comment by dramos1138** [comment]
I have the same problem, I did what you write but the problem persist.

**Comment by rdelrosario** [comment]
Are you sure you have installed the package correctly on the android project? On the sample is using this version and this class exists

**Comment by dramos1138** [comment]
Yeah, I'm sure

VS 2017 15.5.6
Target Platform: Android 7.1 (API 25 - Nougat)

Only works with Android 8.0 Oreo?

![image](https://user-images.githubusercontent.com/34686505/35829319-22b9023c-0a88-11e8-858b-3b0fb04fefc9.png)

**Comment by rdelrosario** [comment]
no, target must be Android O but works with android previous versions

**Comment by rdelrosario** [comment]
Your target is Target Platform: Android 7.1 (API 25 - Nougat) Should be Android 8.0 Oreo

**Comment by dramos1138** [comment]
Ok Thanks, I will download the Android platform for SDK Level 26 then.

Do you know where I can download that version? I update my VS to the latest but the Android SDK version is still the same (7.1)

**Comment by rdelrosario** [comment]
On Android SDK Manager is on Tools -> Android menu on VS

**Comment by dramos1138** [comment]
Thank You Very Much Dude! I appreciate your help
