### ISSUE TITLE
native linking error, IOS release

### ISSUE THREAD

**Issue by Shaboo** [CrossGeeks/FirebasePushNotificationPlugin#101]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 2017 community
Version of Xamarin: 4.8.0.753
Version of Xamarin.iOS: 11.6.1.2
Versions of other things you are using:
Xamarin.build.download 0.4.7
xamarin.firebase.ios.cloudmessaging: 2.0.4.1

### Steps to reproduce the Behavior
just following the sample, and build it as release build
### Expected Behavior
to build and generate an IPA
### Actual Behavior
the following error shown:

Native linking error: truncated fat file. Slice from 4611984 to 6449696 is past end of file with length 5144576 file '/Users/mohammadshaban/Library/Caches/Xamarin/mtbs/builds/HBRS.iOS/7757187b09de98f2bb163c41d580c1ef/obj/iPhone/AppStore/mtouch-cache/FirebaseMessaging' for architecture arm64
### Code snippet
exactly as the sample

**Comment by rdelrosario** [comment]
Clean and rebuild project.

**Comment by rdelrosario** [comment]
Are you still having this issue?

**Comment by Shaboo** [comment]
I have cleaned an rebuilt for 1000 times, nothing changed,
I going to create a new project and test this library with it,
and feed back you ASAP

thanks

**Comment by Shaboo** [comment]
when set supported Architectures to ARM7 it build without any problem,
but in this case I cannot upload it to App store,

when set supported Architectures to ARM64 the problem happened again,
note that I have created a new project and test the library

**Comment by Shaboo** [comment]
am I the only one having this issue?

**Comment by rdelrosario** [comment]
Have you deleted the cache from this directory:

'/Users/mohammadshaban/Library/Caches/Xamarin/mtbs/builds/HBRS.iOS/7757187b09de98f2bb163c41d580c1ef'

And tested after that?

**Comment by Shaboo** [comment]
yes,

I have deleted every thing, even xcode, and reinstall every thing, the problem still exist,

xcode version is 9.2, Do I have to update it?

**Comment by rdelrosario** [comment]
Still having this issue?

**Comment by Shaboo** [comment]
yes,
I have to publish my app next friday and still have no notification in it :(

**Comment by rdelrosario** [comment]
Did you try the sample? It deploys fine on ios on release. Check the config set there and compare with your project.

**Comment by rdelrosario** [comment]
Not reproducible. Have built and run the sample without any issues.
