### ISSUE TITLE
iOS Push notification not displayed in foreground.

### ISSUE THREAD

**Issue by manonaga2188** [CrossGeeks/FirebasePushNotificationPlugin#102]
Hi,

I'm using 2.2.1 version. Push notification received but not displayed in foreground in iOS. This works fine in background. I'm using real device to test notification.

The following is my payload :-
{
  "to": "some-deviceid",
  "data": {
    "title": "A request has been sent to you for review.",
    "detail": "test",
    "RecID": "1",
    "GroupID": "2",
    "DeptID": "3",
    "ClientID": "sample",
    "Username": "mano"
  },
  "notification": {
    "title": "test",
    "body": "A request has been sent to you for review."
  }
}

**Comment by rdelrosario** [comment]
On appdelegate set:

FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Badge;

**Comment by manonaga2188** [comment]
Thanks for quick reply. I understand the functionality now.

Thanks. This has fixed my problem.

**Comment by VictorK1902** [comment]
This does not work anymore. I had to change to UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Sound; to at least have the sound, otherwise user won't notice anything.
Plugin version v2.3.5
XF 3.1.0.637273

**Comment by rdelrosario** [comment]
@VictorK1902 will fix on next version for now you can include "priority" :"high" on iOS payload inside data key.

```json
 "data" :{
      "priority": "high"
  }
```

Example:

 ```json
{
   "notification" : {
    "body" : "hello",
    "title": "firebase",
    "sound" : "test"
  },
 "data" :{
      "priority": "high"
  }
  "condition": "'general' in topics"
}

**Comment by VictorK1902** [comment]
@rdelrosario That solved the problem for now. Thanks

**Comment by DrewBrasher** [comment]
@rdelrosario  Any idea when the next version will be released?

**Comment by Ananyanair** [comment]
@rdelrosario Is there any other option in the code to fix this issue other than the payload change ?
