### ISSUE TITLE
Notification not firing in release mode

### ISSUE THREAD

**Issue by johnxy84** [CrossGeeks/FirebasePushNotificationPlugin#104]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.3.3
Device Tested On: iPad
Simulator Tested On: 
Version of VS: VS for Mac 7.4
Version of Xamarin: xamarin.ios 7.4
Versions of other things you are using:
nothing else
### Steps to reproduce the Behavior
Add plugin,  subscribe to onReceiveNotification, deploy app on release mode, send Push Notification (Data Message)
### Expected Behavior
Fire onReceiveNotification when receives message in background
### Actual Behavior
Doesn't fire but once i open the app all of them I sent starts showing up. It only does this on release and works fine in debug mode

**Comment by rdelrosario** [comment]
Did you uninstall the debug app before running in release or increase the build number?

**Comment by johnxy84** [comment]
I uninstalled it but didn'tdo an incremental build. Could that be a reason?

**Comment by rdelrosario** [comment]
Are you using HTTP/2 Token based or certificates to configure Apple APS?

**Comment by rdelrosario** [comment]
Try installing:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.2.7

If doesn't solve your issue please reopen this ticket.
