### ISSUE TITLE
CrossFirebasePushNotification.Current.OnNotificationReceived not firing

### ISSUE THREAD

**Issue by krazazian** [CrossGeeks/FirebasePushNotificationPlugin#106]
Version Number of Plugin: 2.1.3
Device Tested On:  Samsung Galaxy S7
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 4.8.0.760
Versions of other things you are using:
GooglePlayService packages and Xamarin.Firebase Packages v.42.1021.1
### Steps to reproduce the Behavior
I am only experiencing this in Android.  I've tried updating to the latest stable release, but I am having issues build errors when I upgrade to the latest stable release.  The Xamarin Build Download v0.4.7 is giving me issues that I can't find any help on, so I am stuck on 0.4.6 which keeps me on Google and Firebase packages v42.1021.1 and keeps me from updating your plugin past 2.1.3.

I have put the CrossFirebasePushNotification.Current.OnNotificationReceived += *FUNCTION* in my MainApplication file as you have shown in your guides, but it doesn't ever fire when I receive a notification.  I am getting the message, but the function is never triggered.  I also created my own notification handler and have that implemented correctly, but my OnOpened function is never fired too.  The OnReceived event is fired, but I am trying to get to the notification payload while the my app is backgrounded. 

I have looked at the source code https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/src/Plugin.FirebasePushNotification.Android/PNFirebaseMessagingService.cs

but i can't figure out why it shouldn't be triggering those actions.

**Comment by rdelrosario** [comment]
Do you have your compilation target set to Android 8.0?

Did you tried or check the sample on this repository?

**Comment by krazazian** [comment]
Yes, I have my target set to Android 8.0.  I have followed the sample version to a tee.  As i mentioned, the other aspects work.  I do receive the notification and the OnReceived in the Notification Handler does get triggered when I am in the app, but not when the app is backgrounded.  I am basically trying to push some intent extras in the notification when it is clicked.  

I found out that the reason that I can't upgrade to the latest stable release is because Xamarin.Build.Download v0.4.7 doesnt seem to build correctly with an GooglePlayServices v60.1142.

Are you able to successfully build with those packages in your project?

**Comment by rdelrosario** [comment]
Yes the sample is using those versions you mention and builds properly

**Comment by krazazian** [comment]
Ok, all of my packages are up to date now, but I am still unable to hit the CrossFirebasePushNotification.Current.OnNotificationReceived
or 
public void OnOpened(NotificationResponse response) in my NotificationHandler

Any ideas why?

**Comment by rdelrosario** [comment]
How are you initializing the plugin?

Are you using a custom notification handler? if so, any particular reason why need to?

**Comment by krazazian** [comment]
I am initializing the plugin as shown in your guides
[Application]
    public class MainApplication : Application
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer) :base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            
            //If debug you should reset the token each time.
            #if DEBUG
              FirebasePushNotificationManager.Initialize(this,true);
            #else
              FirebasePushNotificationManager.Initialize(this,false);
            #endif

              //Handle notification when app is closed here
              CrossFirebasePushNotification.Current.OnNotificationReceived += (s,p) =>
              {


              };

			//Set the default notification channel for your app when running Android Oreo
            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                FirebasePushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";

                //Change for your default notification channel name here
                FirebasePushNotificationManager.DefaultNotificationChannelName = "General";
            }
         }
    }
I have tried with and without a notification handler, but the code in here
 **CrossFirebasePushNotification.Current.OnNotificationReceived += (s,p) =>
              {
              };**
is still never reached when i receive a notification.  Everything works for me, except that right now.

**Comment by rdelrosario** [comment]
Can you put here your android manifest?

**Comment by krazazian** [comment]
I removed the sensitive information

<uses-sdk android:minSdkVersion="20" android:targetSdkVersion="26" />
	<uses-feature android:glEsVersion="0x00020000" android:required="true" />
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="com.test.mobile.permission.C2D_MESSAGE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<permission android:name="com.test.mobile.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<application android:label="Test" android:icon="@drawable/HECO_Icon">
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
				<category android:name="${applicationId}" />
			</intent-filter>
		</receiver>
		<meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="" />
		<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/HECO_Icon" />
	</application>

**Comment by krazazian** [comment]
> <uses-sdk android:minSdkVersion="20" android:targetSdkVersion="26" />
	<uses-feature android:glEsVersion="0x00020000" android:required="true" />
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="com.test.mobile.permission.C2D_MESSAGE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<permission android:name="com.test.mobile.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<application android:label="Test" android:icon="@drawable/HECO_Icon">
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
				<category android:name="${applicationId}" />
			</intent-filter>
		</receiver>
		<meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="" />
		<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/HECO_Icon" />
	</application>

>

**Comment by rdelrosario** [comment]
How are you sending the payload?

**Comment by krazazian** [comment]
Thru the Firebase Console.

**Comment by rdelrosario** [comment]
Don't use firebase console, the problem is it sents Notification messages, not Data Messages that's why is not reaching this. I explain the difference here:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FirebaseNotifications.md

**Comment by krazazian** [comment]
Ah, got it.  Thank you!
