### ISSUE TITLE
Version Conflicting Issue while trying to install 2.2.7 using vs 2017 

### ISSUE THREAD

**Issue by dksingh605** [CrossGeeks/FirebasePushNotificationPlugin#107]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.2.7
Device Tested On: Windows Machine
Simulator Tested On: Android orio
Version of VS:  2017
Version of Xamarin: 10
Versions of other things you are using:

### Screenshots
![capture](https://user-images.githubusercontent.com/12871729/36352969-31e5b120-14e6-11e8-97c4-252a65ad5375.PNG)

**Comment by rdelrosario** [comment]
The issue seems to be with the Android Support packages you have installed, the plugin requires version 26.0.2 as minimum. You seem to have version 25.4.0.2 that's why you are having the issue and can't install.
