### ISSUE TITLE
App Reload on Push Notification Click Xamarin Forms

### ISSUE THREAD

**Issue by Nikdm46** [CrossGeeks/FirebasePushNotificationPlugin#11]
I have implemented push notifications on my app and they work fine. The problem I have is that when I click them in the pull down menu they immediately reload the app.  How to fix it?

I am using Xamarin Forms with PCL.

**Comment by rdelrosario** [comment]
What platform Android or iOS are you testing on?

What payload are you sending?

**Comment by Nikdm46** [comment]
Android about the fact that I'm sending exactly can only reply tomorrow.
But something like that 
{
    "data": {
        "message" : "my_custom_value",
        "other_key" : true,
        "body":"test"
     },
     "notification": {
       "body" : "hello",
       "title": "firebase",
       "sound": "default",
        "content_available" : true
     },
     "priority": "high",
     "condition": "'general' in topics"
}

**Comment by Nikdm46** [comment]
$fields = array (
        'registration_ids' => array (  
            $_POST['token']
        ),
        'data' => array (
                "message" => $message,
                "target" => $_POST['target'],
                "type" => $messageType,
                'ownerId' => $id
        ),
        'notification' => array (
                "body" => $message,
                "title" => "Message",
                "sound" => "default",
                "content_available" => true
        ),
        "priority" => "high"
    );

**Comment by Nikdm46** [comment]
https://www.youtube.com/watch?v=EWWhJ0nZFHo&feature=youtu.be

**Comment by claudiocleberson** [comment]
@Nikdm46 

I had that problem, end it was that flag:  LaunchMode = LaunchMode.SingleTop. On MainActivity, maybe that could help:

 [Activity(
        LaunchMode = LaunchMode.SingleTop,
        Label = "xxxxxxxxx",
        Theme = "@style/AppTheme",
        Icon = "@android:color/transparent",
        ScreenOrientation = ScreenOrientation.Portrait,
        MainLauncher = false)
    ]

**Comment by Nikdm46** [comment]
Yes, i did it, but in singleTop mod i can't use NotificationOpened event.
CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>
{
	System.Diagnostics.Debug.WriteLine($"TOKEN : {p.Token}"); --- WORK
};

CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
{
       System.Diagnostics.Debug.WriteLine("Received"); -----WORK
};
CrossFirebasePushNotification.Current.OnNotificationOpened += (s, p) =>
{
	Debug.WriteLine("Opened"); -------- DON'T WORK
};

Reload current page and all)

**Comment by Nikdm46** [comment]
`[ Activity(LaunchMode = LaunchMode.SingleTop, Label = "NetNego", Icon = "@drawable/icon", Theme = "@style/MyTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
	public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
	{

        //public static Context AppContext;

		protected override void OnCreate(Bundle bundle)
		{
			TabLayoutResource = Resource.Layout.Tabbar;
			ToolbarResource = Resource.Layout.Toolbar;

			base.OnCreate(bundle);

			Forms.Init(this, bundle);
			
            SegmentedControlRenderer.Init();
			
            LoadApplication(new App());

            FirebasePushNotificationManager.ProcessIntent(Intent);

			ImageCircleRenderer.Init();

            CachedImageRenderer.Init();

            var ignore = new CircleTransformation();

			var config = new FFImageLoading.Config.Configuration()
			{
				VerboseLogging = false,
				VerbosePerformanceLogging = false,
				VerboseMemoryCacheLogging = false,
				VerboseLoadingCancelledLogging = false,
				Logger = new CustomLogger(),
			};

			ImageService.Instance.Initialize(config);
		}`

**Comment by Nikdm46** [comment]
MainActivity
https://pastebin.com/m68K3zjg
MainApplication
https://pastebin.com/Ax0GB2bP
App
https://pastebin.com/CaUuQRu5

**Comment by rdelrosario** [comment]
On your MainActivity try adding:

protected override void OnNewIntent(Intent intent)
{
       FirebasePushNotificationManager.ProcessIntent(intent)
}

**Comment by Nikdm46** [comment]
Helped, seems)
