### ISSUE TITLE
OnTokenRefresh is not firing in iOS

### ISSUE THREAD

**Issue by SkillerSKL** [CrossGeeks/FirebasePushNotificationPlugin#111]
When I start the app, not fire OnTokenRefresh in iOS

## Bug Information

Version Number of Plugin: 2.3.0
Device Tested On: IPad
Simulator Tested On:
Version of VS: 2017 15.4.2
Version of Xamarin: 2.5.0.121934

### Code snippet
My App.Delegate

        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {                    
            global::Xamarin.Forms.Forms.Init();
            if (!Resolver.IsSet)
                SetIoc();

            // define useragent android like
            string userAgent = "Mozilla/5.0 (Linux; Android 5.1.1; Nexus 5 Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.65 Mobile Safari/537.36";

            // set default useragent
            NSDictionary dictionary = NSDictionary.FromObjectAndKey(NSObject.FromObject(userAgent), NSObject.FromObject("UserAgent"));
            NSUserDefaults.StandardUserDefaults.RegisterDefaults(dictionary);

            DependencyService.Register<ToastNotification>();
            ToastNotification.Init();
            CachedImageRenderer.Init();            
            LoadApplication(new App());
            FirebasePushNotificationManager.Initialize(options, true);
            return base.FinishedLaunching(app, options);
        }

        private void SetIoc()
        {
            var resolverContainer = new SimpleContainer();
            Resolver.SetResolver(resolverContainer.GetResolver());
        }

        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken);
        }

        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);
        }

        // To receive notifications in foregroung on iOS 9 and below.
        // To receive notifications in background in any iOS version
        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            // If you are receiving a notification message while your app is in the background,
            // this callback will not be fired 'till the user taps on the notification launching the application.

            // If you disable method swizzling, you'll need to call this method. 
            // This lets FCM track message delivery and analytics, which is performed
            // automatically with method swizzling enabled.
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
            // Do your magic to handle the notification data
            System.Console.WriteLine(userInfo);
        }

        public override void OnActivated(UIApplication uiApplication)
        {
            FirebasePushNotificationManager.Connect();
            base.OnActivated(uiApplication);
        }

        public override void DidEnterBackground(UIApplication application)
        {
            // Use this method to release shared resources, save user data, invalidate timers and store the application state.
            // If your application supports background exection this method is called instead of WillTerminate when the user quits.
            FirebasePushNotificationManager.Disconnect();
        }

**Comment by rdelrosario** [comment]
Are you using HTTP/2 Token or push aps certificates  on Apple portal?

**Comment by philmoz** [comment]
OnTokenRefresh is called when using Xamarin.Firebase.iOS.CloudMessaging version 2.0.4.1.

If I update to Xamarin.Firebase.iOS.CloudMessaging version 2.0.8, then OnTokenRefresh is never called (even if the app is uninstalled and reinstalled). 
I have also tried calling CrossFirebasePushNotification.Current.UnregisterForPushNotifications() and CrossFirebasePushNotification.Current.RegisterForPushNotifications() but OnTokenRefresh is never called.

**Comment by SkillerSKL** [comment]
@rdelrosario I'm using aps certificates. I tested here and only not fired in IPad's. Iphone's works.

**Comment by rdelrosario** [comment]
mmm that's weird is same code for iphone or ipad

**Comment by SkillerSKL** [comment]
I guess that's the version. I'm using a IPad with the version 9.2.

I tried to use the methods UnregisterForPushNotifications and RegisterForPushNotifications but not worked ;s 

In the Android works.

**Comment by SkillerSKL** [comment]
The strange thing is that I'm getting a different token than the normal one, look at this for example: 7b24f0e2 987cf307 e733826a 523a3e37 74b2633e 07f0dd28 020e80c8 cb568bc0

**Comment by SkillerSKL** [comment]
Does have any solution @rdelrosario ?

**Comment by rdelrosario** [comment]
This doesn't seem to be a plugin issue.

**Comment by rdelrosario** [comment]
You need to use the latest Firebase Cloud Messaging version package?

**Comment by rdelrosario** [comment]
You need to use the latest Firebase Cloud Messaging version package?

**Comment by rdelrosario** [comment]
will support latest version on next release over the weekend.

**Comment by rdelrosario** [comment]
Hi did you get to test this?

Did it solve your issue?

**Comment by MonkeyBrush** [comment]
I had the same issue.  2.0.8 wasn't getting token refresh.  I've just installed 2.3.1-rc and I'm now getting the token.  Thank you.
