### ISSUE TITLE
Notification not shown on Android 8 (Oreo) when app in foreground.

### ISSUE THREAD

**Issue by philmoz** [CrossGeeks/FirebasePushNotificationPlugin#112]
Version Number of Plugin: 2.3.0
Device Tested On: Pixel Phone, Android 8.0.0 (Oreo)
Simulator Tested On: n/a
Version of VS: 7.3.3 (MacOS)
Version of Xamarin: 2.5.0.122203
Versions of other things you are using:

### Steps to reproduce the Behavior

Send a push notification to application running in the foreground on Android 8.

### Expected Behavior

Notification pops up, plays sound, vibrates and displays icon in the notification centre.

### Actual Behavior

No notification is displayed, no sound, no vibration.

### Code snippet

Problem occurs using initialisation as per the example on the getting started page. The notification channel is created with the default values, not the app defined values.
The setting of FirebasePushNotificationManager.DefaultNotificationChannelId and FirebasePushNotificationManager.DefaultNotificationChannelName needs to be done before the call to FirebasePushNotificationManager.Initialize not after (as shown in the getting started example).

**Comment by ashishbpatil1** [comment]
I am also facing the same problem.

**Comment by ashishbpatil1** [comment]
@philmoz , @rdelrosario
This is my **MainApplication.cs** code. Please let me know what to change to get notifications on android version 8.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Plugin.FirebasePushNotification;

namespace Jvp.Droid
{
    [Application]
    public class MainApplication : Application
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer) : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();

            //If debug you should reset the token each time.
#if DEBUG
            FirebasePushNotificationManager.Initialize(this, true);
#else
              FirebasePushNotificationManager.Initialize(this,false);
#endif

            //Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                

            };

            //Set the default notification channel for your app when running Android Oreo
            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                FirebasePushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";

                //Change for your default notification channel name here
                FirebasePushNotificationManager.DefaultNotificationChannelName = "General";
            }
        }
    }
}
```

**Comment by ashishbpatil1** [comment]
Solved. Thanks to @philmoz for his comment.
Just move "default notification channel for your app when running Android Oreo" section before the Initialize section.

This is working **MainApplication.cs**:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Plugin.FirebasePushNotification;

namespace Jvp.Droid
{
    [Application]
    public class MainApplication : Application
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer) : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();

			//Set the default notification channel for your app when running Android Oreo
			if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
			{
				//Change for your default notification channel id here
				FirebasePushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";

				//Change for your default notification channel name here
				FirebasePushNotificationManager.DefaultNotificationChannelName = "General";
			}

			//If debug you should reset the token each time.
#if DEBUG
			FirebasePushNotificationManager.Initialize(this, true);
#else
              FirebasePushNotificationManager.Initialize(this,false);
#endif

            //Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                

            };


        }
    }
}

```

**Comment by rizwan49** [comment]
I also faced the same issue, then I find the solution, you need to remove your app from **battery optimization list** mark your app **not optimize**, I did this in **onePlus5**, after killing an app also notification is working.

**step** : 

 1. goto **setting**
 2. click on **Battery** option 
 3. click on **Battery optimization** , it will show list of app which is under optimation.
 4. find your app select **don't optimiza** and done!

just now I find out so now I need to see how to do this using code.
for mean while let me know if you faced the same issue or it will resolve your issue. :)
