### ISSUE TITLE
Behavior change when displaying multiple notifications on Android in new version?

### ISSUE THREAD

**Issue by HeikkiDev** [CrossGeeks/FirebasePushNotificationPlugin#113]
I think this is not a Bug report.

In version 2.2.7 I sent multiple notifications to the same Android device (actually an emulator), and all of them shows on device notification panel. The notifications are grouped when there are 4 or more.

Now I´ve just update to version 2.3.0 to use CrossFirebasePushNotification.Current.UnegisterForPushNotifications() when user log out.
When I send multiple notifications only one is displayed at the same time. The previous notification is replaced with the newest I´ve sent.

There are some change in version 2.3.0 related with this?
The other possible cause is that at the same time i´ve update yours plugin, i´ve update XF from 2.5.0.122203 to 2.5.0.280555.

Thanks in advance.

**Comment by rdelrosario** [comment]
Send “id” and “tag” on payload to show multiple notifications.

Same tag will group the notificacions, use a diferent id for each notification.

Id is integer and tag is string

**Comment by HeikkiDev** [comment]
Ok... I deleted ‘tag’ in Postman by error and the version update has confused me.

Thanks and sorry for the waste of time!
