### ISSUE TITLE
Package Failed To install in android project

### ISSUE THREAD

**Issue by Cliffy786** [CrossGeeks/FirebasePushNotificationPlugin#114]
## Bug Information

Version Number of Plugin: 2.3.0
Device Tested On: NA
Simulator Tested On: NA
Version of VS: Visual Studio 2017 
Version of Xamarin: 2.5.0.121934
Versions of other things you are using: Can be found in` package manager console` log [here](https://gist.github.com/Cliffy786/418e617df7b1fbff8816eedcc3e1e41a)

Hi 

I've been trying to install, this plugin, it failed twice and both times it took a really long time to install as you can see [here](https://gist.github.com/Cliffy786/418e617df7b1fbff8816eedcc3e1e41a) in the nuget package manager log, I don't know why its failing to install because when I installed the package into my 
pcl there were no problems. Please assist

**Comment by rdelrosario** [comment]
You need to have AppCompat 26.0.2

**Comment by rdelrosario** [comment]
Did you get to solve your issue?

**Comment by Cliffy786** [comment]
No I did not resolve my issue manage to resolve my issue, you say that I need AppCompat 26.0.2 If I do install that will it have an effect on any of my GooglePlayServices packages?

**Comment by rdelrosario** [comment]
What GooglePlayService package version are you using?

**Comment by Cliffy786** [comment]
I'm using version 42.1021.1. When I install FirebaseMessaging I ensure that it matches that version

**Comment by rdelrosario** [comment]
Plugin requires Xamarin.Firebase.Messaging 60.1142.0.

Which requires version 60.1142.0 as seen here:


![image](https://user-images.githubusercontent.com/2547751/37497983-fc627938-2891-11e8-8fb6-ac39144e51da.png)
