### ISSUE TITLE
DefaultPushNotificationHandler.OnReceive error under Android (both 7.1.1 & 8.1.0)

### ISSUE THREAD

**Issue by c0rnh0li0** [CrossGeeks/FirebasePushNotificationPlugin#115]
Version Number of Plugin: 2.3.0
Device Tested On: Google Pixel XL (Android 8.1.0)
Simulator Tested On: AVD for Nexus 6, (Android 7.1.1)
Version of VS: 15.5.6
Version of Xamarin: 2.5.0.122203
Versions of other things you are using: 
- Xamarin.Android.Support.v4: 26.1.0.1,
- All other Xamarin.Android.Support libs are version 25.3.1

Hi, 

I'm implementing your plugin for a solution in both iOS and Android. iOS works pretty fine, no issues there. But on Android I have null references when I receive a notification from FCM. I've set up everything as in your guides/examples using the DefaultPushNotificationHandler. Now everything is fine until i receive the notification under Android:

### Actual Behavior: Error in method CrossFirebasePushNotification.Current.NotificationHandler.OnReceived(p.Data);

03-09 13:21:23.471 I/MonoDroid(17066): UNHANDLED EXCEPTION:
03-09 13:21:23.480 I/MonoDroid(17066): System.MissingMethodException: Method 'Android.Support.V4.App.NotificationCompat/Builder..ctor' not found.
03-09 13:21:23.481 I/MonoDroid(17066):   at Plugin.FirebasePushNotification.PNFirebaseMessagingService.OnMessageReceived (Firebase.Messaging.RemoteMessage message) [0x001d3] in C:\Plugins\FirebasePushNotification\src\Plugin.FirebasePushNotification.Android\PNFirebaseMessagingService.cs:64 
03-09 13:21:23.481 I/MonoDroid(17066):   at Firebase.Messaging.FirebaseMessagingService.n_OnMessageReceived_Lcom_google_firebase_messaging_RemoteMessage_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_message) [0x0000f] in <c9c78f979e004ecbb4a1706c3d5c466b>:0 
03-09 13:21:23.481 I/MonoDroid(17066):   at (wrapper dynamic-method) System.Object:eefe38d2-cd7d-44f0-8cfa-a2ed5f5d3ebd (intptr,intptr,intptr)

### Code snippet:
`CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
 {
     try {   
          CrossFirebasePushNotification.Current.NotificationHandler.OnReceived(p.Data);
     }
     catch (Exception ex)
     {
          Debug.WriteLine(ex.Message);
     }
};`

**Comment by rdelrosario** [comment]
What AppCompat version you have installed?

Is the project targeting Android 8?

**Comment by rdelrosario** [comment]
Any reason why you are using ?
```
CrossFirebasePushNotification.Current.NotificationHandler.OnReceived(p.Data); } catch (Exception ex) { Debug.WriteLine(ex.Message); } };
```
You dont need this call.

**Comment by c0rnh0li0** [comment]
I'm using Xamarin.Android.Support.v7.AppCompat v25.3.1. And yes, project is targeting Android 8, min target is Android 6 and compiling against Android 8 also. 

The try/catch block was there just because it was crashing my app due to null object reference. Again, here is a little stack trace: 

> 03-09 15:52:13.042 I/MonoDroid( 4115): UNHANDLED EXCEPTION:
03-09 15:52:13.044 I/MonoDroid( 4115): System.MissingMethodException: Method 'Android.Support.V4.App.NotificationCompat/Builder..ctor' not found.
03-09 15:52:13.044 I/MonoDroid( 4115):   at Plugin.FirebasePushNotification.PNFirebaseMessagingService.OnMessageReceived (Firebase.Messaging.RemoteMessage message) [0x001d3] in C:\Plugins\FirebasePushNotification\src\Plugin.FirebasePushNotification.Android\PNFirebaseMessagingService.cs:64 
03-09 15:52:13.044 I/MonoDroid( 4115):   at Firebase.Messaging.FirebaseMessagingService.n_OnMessageReceived_Lcom_google_firebase_messaging_RemoteMessage_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_message) [0x0000f] in <c9c78f979e004ecbb4a1706c3d5c466b>:0 
03-09 15:52:13.044 I/MonoDroid( 4115):   at (wrapper dynamic-method) System.Object:9852b492-3869-49a1-b31c-455e50919ed1 (intptr,intptr,intptr)
03-09 15:52:13.067 W/art     ( 4115): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
03-09 15:52:13.072 D/Mono    ( 4115): DllImport searching in: '__Internal' ('(null)').
03-09 15:52:13.072 D/Mono    ( 4115): Searching for 'java_interop_jnienv_throw'.
03-09 15:52:13.072 D/Mono    ( 4115): Probing 'java_interop_jnienv_throw'.
03-09 15:52:13.072 D/Mono    ( 4115): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

03-09 15:52:14.530 E/mono    ( 4115): 
03-09 15:52:14.530 E/mono    ( 4115): Unhandled Exception:
03-09 15:52:14.530 E/mono    ( 4115): System.MissingMethodException: Method 'Android.Support.V4.App.NotificationCompat/Builder..ctor' not found.
03-09 15:52:14.530 E/mono    ( 4115):   at (wrapper dynamic-method) System.Object:9852b492-3869-49a1-b31c-455e50919ed1 (intptr,intptr,intptr)
03-09 15:52:14.530 E/mono-rt ( 4115): [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Android.Support.V4.App.NotificationCompat/Builder..ctor' not found.
03-09 15:52:14.530 E/mono-rt ( 4115):   at (wrapper dynamic-method) System.Object:9852b492-3869-49a1-b31c-455e50919ed1 (intptr,intptr,intptr)

**Comment by rdelrosario** [comment]
You need AppCompat 26.0.2 is a dependency of the plugin

**Comment by c0rnh0li0** [comment]
I've had different versions of the Android support libs. Made them all same version and it's all good now. Issue solved, thank you very much!
