### ISSUE TITLE
Background notifications Android and IOS problem.

### ISSUE THREAD

**Issue by skyritsis** [CrossGeeks/FirebasePushNotificationPlugin#118]
Hello, I have 2 separate problems here.

1. When sending only data payload, I am able to intercept it both in background and in foreground in my android device. Though, on some devices the background notification never arrives. 

2. On IOS, I am able to intercept data payload in foreground, but not in background (which is excepted. Though, when I add notification payload too, the notification is not intercepted both on foreground and background. I am using the content-available flag, set as True, from a django rest server on the notification payload. 
Any guesses?

I appreciate the help,
-SK

**Comment by rdelrosario** [comment]
1. Did you check the FAQ section on the docs?

2. Is content-available: 1 when using FCM

**Comment by skyritsis** [comment]
First of all, thank you for your replay.
1. The first problem seemed to be connected to some xiaomi and lenovo devices, and it is not something concerning the plugin. So my first question was off.

2. Regarding the second part of the answer, I just checked it, and I still have the same behaviour. Though, I was only able to test it with an old iphone 4 with ios 9 on it.
Could that be a problem?

**Comment by rdelrosario** [comment]
Hey sorry I was mistaken is like this on iOS:

```json
{
     "notification": {
        "content_available" : true
     },
     "priority": "high",
     "condition": "'general' in topics"
}
```

**Comment by skyritsis** [comment]
So, the topic subsription is mandatory?

**Comment by rdelrosario** [comment]
No

**Comment by skyritsis** [comment]
Ok, let me see if I got this straight. The condition for IOS, is targetting all devices that are subscribed to the topic 'general'. Is that correct?
If not, could you please elaborate?

**Comment by rdelrosario** [comment]
Right, you need to subscribe the device to topic if you want to send in mass efficiently. Just as I'm doing in the sample subscribing all devices to 'general' topic. More on this here:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FirebaseNotifications.md

**Comment by rdelrosario** [comment]
Did you get to solve your issue?

**Comment by skyritsis** [comment]
Unfortunately not. My purpose is to send device specific notifications, and not topic wide notifications. I am still having the aforementioned issue, in which I am not able to receive messages containing notification payload in ios devices. Which means, atm I am not able to have any background notifications in ios.

**Comment by rdelrosario** [comment]
How are you sending the payload?

**Comment by skyritsis** [comment]
data = {
        'title' : title,
        'message' : mes,
        'type' : 'order',
        'number' : order.oid
    }
    notification = {
        'title' : title,
        'body' : body,
        'content_available' : True
    }

and I use a django library for sending the message
v.send_message(data=data,notification=notification, priority='high')

**Comment by rdelrosario** [comment]
Have you tried sending using postman just to verify first you receive the notification?

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/TestingPushNotifications.md

```
"data" : {
"title" : title,
"message" : mes,
"type" : "order",
"number" : order.oid
}
"notification": {
'"title": title,
"body": body,
"content_available" : true
},
"registration_ids": ["{device-token}"]
```
**Replace {device-token} with your token**

**Comment by skyritsis** [comment]
I've tried both with postman and with the Firebase console method. And the problem only happens with ios devices, cause in android, I can detect both data and notification payload messages.

**Comment by skyritsis** [comment]
Well, I finally found it. The problem was neither the server, nor the deployment on the device. The problem was the apn configuration on firebase. I renewed the licences, and everything works like a charm. Thank you for your time and help.
