### ISSUE TITLE
On tap to open notification : System.NullReferenceException

### ISSUE THREAD

**Issue by ikhaled-ali** [CrossGeeks/FirebasePushNotificationPlugin#119]
hello ,
i've following all steps implemented in docs 
All thinks works fine but when application is in background then i'm trying to tap on notification 
this error threw :
(using Android API 21 )
```
System.NullReferenceException: Object reference not set to an instance of an object.
  at Plugin.FirebasePushNotification.FirebasePushNotificationManager.ProcessIntent (Android.App.Activity activity, Android.Content.Intent intent, System.Boolean enableDelayedResponse) [0x0008e] in C:\Plugins\FirebasePushNotification\src\Plugin.FirebasePushNotification.Android\FirebasePushNotificationManager.cs:106 
  at Notifications.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle)
```

in MainActivity : 
`try     {`
`             FirebasePushNotificationManager.ProcessIntent(this, Intent); // <-- here error threw`
`           }`
`             catch(Exception e)`
`            {`
`                System.Diagnostics.Debug.WriteLine($"Exception: {e}");`
`            }`

**Comment by rdelrosario** [comment]
What code you have on your OnNotificationOpened event handler?

**Comment by ikhaled-ali** [comment]
```
CrossFirebasePushNotification.Current.OnNotificationOpened += (s, p) =>
            {

                System.Diagnostics.Debug.WriteLine("Opened");
                foreach (var data in p.Data)
                {
                    System.Diagnostics.Debug.WriteLine($"{data.Key} : {data.Value}");
                }

                if (!string.IsNullOrEmpty(p.Identifier))
                {
                    System.Diagnostics.Debug.WriteLine($"ActionId: {p.Identifier}");
                }

            };
```

or if i commented all code also the same bugs threw

**Comment by rdelrosario** [comment]
Do you have Android 8 set as compilation target?

**Comment by rdelrosario** [comment]
Must compile against 26+ as plugin is using API 26 specific things. Here is a great breakdown: http://redth.codes/such-android-api-levels-much-confuse-wow/ (Android project must be compiled using 8.0+ target framework)

**Comment by ikhaled-ali** [comment]
Yes i’m using Android 8.0 as target

**Comment by rdelrosario** [comment]
Are you calling ProcessIntent OnNewIntent too?

Did you initialize the plugin on MainApplication class?

**Comment by ikhaled-ali** [comment]
i’ll share with you my sample code please just wait for me ... 

but i have a question, if i haven’t used a navigation page stack 
MainPage = new MainPage() 
not 
MainPage = new NavigationPage ( ) 
is this a problem?

**Comment by ikhaled-ali** [comment]
contains :  
```
MainApplication.cs
MainActivity.cs
App.xaml.cs
MainPage.xaml.cs
```


[Notifications.Android.zip](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1810354/Notifications.Android.zip)
[Notifications.zip](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1810355/Notifications.zip)

**Comment by ikhaled-ali** [comment]
my code

[Notifications.Android.zip](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1810374/Notifications.Android.zip)
[Notifications.zip](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1810375/Notifications.zip)

**Comment by rdelrosario** [comment]
One thing I saw is that you don't need to call:

```cs
            CrossFirebasePushNotification.Current.RegisterForPushNotifications();
```
Because you are not using on demand registration you are initializing with auto registration.

**Comment by ikhaled-ali** [comment]
Sorry for inconvenience .. 
After two days of trying :( the problem was that i forgot to write this line `[Application]`  above `MainApplication ` class 
for this reason `FirebasePushNotificationManager ` not initialize yet 

and thank you again for your interest .. GREAT PLUGIN 👍
