### ISSUE TITLE
App crashes on startup with the sample code w/ Xamarin forms

### ISSUE THREAD

**Issue by Fireprufe15** [CrossGeeks/FirebasePushNotificationPlugin#12]
```
Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process
Make sure to call FirebaseApp.initializeApp(Context) first.
```
This is the error that is thrown.  I've looked into the previously solved issue on here that had the same problem, but the solution listed there doesn't work at all on my side (clean/rebuild as well as adding the target entry to csproj).

[Here](https://gist.github.com/Fireprufe15/b306867b30dfbb6e444940e8856af037) is a gist of the exception stack trace.

## Bug Information

Version Number of Plugin: v.1.0.4
Device Tested On: Galaxy S7
Simulator Tested On: n/a
Version of VS: 2017 latest
Version of Xamarin: 4.5.0.486
Versions of other things you are using: X.Forms version 2.3.4.267

**Comment by claudiocleberson** [comment]
@Fireprufe15 

According the Docs, and after checking with the community, that is a bug.

When that happens, I just clean the app and rebuild. That works for a while, until that exceptions happens again. Fortunately, Clean again gives you some more shots.

**Comment by rdelrosario** [comment]
Thank you very much!

Solution:

Add this code to Android .csproj

<Target Name="RemoveGoogleServicesJsonStampFiles" BeforeTargets="BeforeBuild"> <Delete Files="$(IntermediateOutputPath)\ProcessGoogleServicesJson.stamp" /> </Target>

**Comment by rdelrosario** [comment]
Also check the build action for your google play services json should be as the documentation specifies

**Comment by rdelrosario** [comment]
Make sure after checking this to delete /bin /obj files and clean project.

**Comment by SavikPavel** [comment]
After applying @rdelrosario's fix Android project gets fully rebuilt on every run and cleans all the stored application data. As a result, debug process (which is not very pleasant in Xamarin.Android by itself) becomes a real hell. Maybe there is some other solution?

**Comment by rdelrosario** [comment]
What plugin version are you using?

This doesn't happen on latest version FCM Messaging package latest version fixed this.

**Comment by SavikPavel** [comment]
I'm using Xamarin.Firebase.Messaging plugin, not this one, but the problem was the same with the version 42.1021.1. Now I've updated the library to the latest version and seems like the problem disappeared. Thank you!

**Comment by SavikPavel** [comment]
@rdelrosario, but the problem I mentioned with the cleaning and rebuilding project on every run now exists permanent and doesn't even require adding anything to Android .csproj. So I guess, it can be actual for the current package as well

**Comment by SavikPavel** [comment]
Forget it, it's just Samsung devices problem, looks like it has nothing to do with your fix. Sorry)

**Comment by joshuatantonflynn** [comment]
@rdelrosario Currently on 60.1142.1 Still having this issue. yes the json build action is set to GoogleServicesJson. Yes I've tried the clean and rebuild and obj/bin deletion. I've even added that Target entry manually into the csproj file. Still, everytime I try to get my token it has this error. FirebaseApp.InitializeApp(this) always returns null. Haven't tried yet on a non-Samsung phone but working on Samsung phones is an absolute requirement for this.
