### ISSUE TITLE
Sending notification with a date

### ISSUE THREAD

**Issue by rubenc57** [CrossGeeks/FirebasePushNotificationPlugin#125]
Hello
I'm sending notifications to my app with this code:

                DateTime dt = new DateTime(2018, 03, 22, 10, 45, 00);

                var data = new
                {
                    //to = to,    //deviceId,
                    time = dt.ToString(),   //"Now",   //DateTime.Now.ToString(),
                    priority = "high",
                    notification = new
                    {
                        body = mensaje,
                        title = "CmsApp",
                        sound = sound,
                    },
                    condition = condicion,  //"'general' in topics"
                };

But I receive the notification NOW, what am I missing?

Greetings
rubenc

**Comment by rdelrosario** [comment]
The plugin doesn't support notification scheduling

**Comment by rdelrosario** [comment]
That should be done in server instead
