### ISSUE TITLE
ios OnNotificationReceived not working

### ISSUE THREAD

**Issue by helmishariff** [CrossGeeks/FirebasePushNotificationPlugin#128]
Version Number of Plugin: 2.3
Device Tested On: ipad pro & iphone 6
Version of VS: Mac VS 7.4.2
Version of Xamarin: Xamarin Form 2.5
Versions of other things you are using:

Can received push notification but not trigger OnNotificationReceived

protected override void OnStart ()
{
    CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("Received");
                try
                {
                    if (p.Data.ContainsKey("reply"))
                    {
                        System.Diagnostics.Debug.WriteLine($"{p.Data["reply"]}");

                    }
                }
                catch (Exception ex)
                {

                }
            };

**Comment by rdelrosario** [comment]
You don’t receive it when you tap on the notification?

**Comment by rdelrosario** [comment]
Please reopen issue with more details if still having problems.

**Comment by VuCA** [comment]
Hi @rdelrosario ,

I having the same problem, when app in the foreground, the event OnNotificationReceived is trigger but if the app in the background, still receive notification but the event did not trigger

Version Number of Plugin: 2.3
Device Tested On: Iphone X

Thanks!

**Comment by anhtuan0030** [comment]
I have the same problem. Did i register event right? I register event on App() constructor.

`CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>
            {
                System.Console.WriteLine("OnTokenRefresh:");
                System.Console.WriteLine($"TOKEN : {p.Token}");
            };

            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Console.WriteLine("OnNotificationReceived:");
                foreach (var data in p.Data)
                {
                    System.Console.WriteLine($"{data.Key} : {data.Value}");
                }

                //Save notify
            };

            CrossFirebasePushNotification.Current.OnNotificationOpened += (s, p) =>
            {
                System.Console.WriteLine("OnNotificationOpened:");
                
                foreach (var data in p.Data)
                {
                    System.Console.WriteLine($"{data.Key} : {data.Value}");
                }

                if (!string.IsNullOrEmpty(p.Identifier))
                {
                    System.Console.WriteLine($"ActionId: {p.Identifier}");
                }
            };`

**Comment by HectorOCH** [comment]
Insert this code in the notification (IOS push)

```
 "aps" : {
        "content-available" : 1
    }
```

**Comment by Muhi** [comment]
I have am running in to this problem after updating the version of the plug in from 2.3 to 2.3.5
the OnNotificationReceived and OnNotificationOpened will not fire in IOS only Android works fine.
The notification does get to the app but not to OnNotificationReceived /OnNotificationOpened.
Does any one have any Idea ... Thanks

**Comment by agrobost** [comment]
Up

**Comment by stesvis** [comment]
Did anybody find a solution? I am having this issue now in version 3.3.10
