### ISSUE TITLE
App Icon Badge Android

### ISSUE THREAD

**Issue by jaspervanmegroot** [CrossGeeks/FirebasePushNotificationPlugin#129]
Is there a way to set the icon badge number with this plugin for Android? For iOS is it working.

If not, do you have a example to use a background Service with your plugin?

**Comment by kinfei** [comment]
How can update the badge number beside app icon when push notification is coming? Do you have a example to use a background Service with your plugin?

**Comment by jaspervanmegroot** [comment]
@kinfei I am asking the same question but for iOS you can set the propety badge in the payload. iOS set the badgecount with that propety.

**Comment by kinfei** [comment]
@jaspervanmegroot do I still need to do anything on app side after receieve the push message with property badge?

**Comment by jaspervanmegroot** [comment]
@kinfei nope

**Comment by kinfei** [comment]
@jaspervanmegroot  i think this plugin not support android background service. I done it with extend a firebase messaging service class and update the icon badge count with another plugin (ShortcutBadger)

**Comment by kinfei** [comment]
1. Install Xamarin.Android.ShortcutBadger thru nuget
2. Create a class under Xamarin Android project
3. Copy the code inside ([MyFirebaseMessagingService.txt](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1927360/MyFirebaseMessagingService.txt)) to class
4. Compile and run
*Note: If you run in debug mode (the firebase token might refresh on some time and you may hit error of unregistered of token when app is killed). I tested it on release mode (release ad-hoc apk).

**Comment by jaspervanmegroot** [comment]
@kinfei it is working but the notification will not show anymore. The badge count increase but the notification will not show up.

**Comment by kinfei** [comment]
@jaspervanmegroot do you include following function to construct the push message?
public void SendNotification(string messageTitle, string messageBody)
        {
            var intent = new Intent(this, typeof(MainActivity));
            int notificationId = new Random().Next(0, 1000);
            intent.AddFlags(ActivityFlags.ClearTop);
            var pendingIntent = PendingIntent.GetActivity(this, notificationId, intent, PendingIntentFlags.OneShot);

            var defaultSoundUri = RingtoneManager.GetDefaultUri(RingtoneType.Notification);
            var notificationBuilder = new NotificationCompat.Builder(this)
                .SetSmallIcon(Resource.Drawable.icon)
                .SetContentTitle(messageTitle)
                .SetContentText(messageBody)
                .SetAutoCancel(true)
                .SetSound(defaultSoundUri)
                .SetContentIntent(pendingIntent);

            var notificationManager = NotificationManager.FromContext(this);
            notificationManager.Notify(notificationId, notificationBuilder.Build());
        }

**Comment by jaspervanmegroot** [comment]
Aah i removed that piece of code lol haha but I had a better way:

`CrossFirebasePushNotification.Current.NotificationHandler?.OnReceived(GetParameters(message, notification));`

**Comment by jaspervanmegroot** [comment]
Nevermind, your method is better.

Is there a way to sort the notifcation like Gmail? 

![screenshot_20180420-120709](https://user-images.githubusercontent.com/19607572/39045622-a45b3d92-4493-11e8-987a-10f312bdff95.png)

**Comment by kinfei** [comment]
@jaspervanmegroot no problem. Btw, at the end do you able to sort the notification like Gmail?

**Comment by kinfei** [comment]
@jaspervanmegroot do you mind to share me the code on this?

**Comment by jaspervanmegroot** [comment]
`  
int SUMMARY_ID = 0;
 String GROUP_KEY_APPVISEURS = ""; //random key

public void SendNotification(string messageTitle, string messageBody)
        {
            try
            {
                var intent = new Intent(this, typeof(MainActivity));
                int notificationId = new Random().Next(0, 1000);
                intent.AddFlags(ActivityFlags.ClearTop);
                var pendingIntent = PendingIntent.GetActivity(this, notificationId, intent, PendingIntentFlags.OneShot);

                Notification newMessageNotification1 = new NotificationCompat.Builder(this)
                    .SetSmallIcon(Resource.Drawable.icon)
                    .SetContentTitle(messageTitle)
                    .SetContentText(messageBody)
                    .SetGroup(GROUP_KEY_APPVISEURS)
                    .SetContentIntent(pendingIntent)
                    .SetAutoCancel(true)
                    .Build();

                Notification summaryNotification = new NotificationCompat.Builder(this)
                    .SetContentTitle(messageTitle)
                    .SetContentText("Two new messages")
                    .SetSmallIcon(Resource.Drawable.icon)
                    .SetStyle(new NotificationCompat.InboxStyle().AddLine("Alex Faarborg  Check this out").AddLine("Jeff Chang    Launch Party").SetBigContentTitle("").SetSummaryText("Nieuwe berichten"))
                    .SetGroup(GROUP_KEY_APPVISEURS)
                    .SetGroupSummary(true)
                    .SetContentIntent(pendingIntent)
                    .SetAutoCancel(true)
                    .Build();

                NotificationManagerCompat notificationManager = NotificationManagerCompat.From(this);
                notificationManager.Notify(new Random().Next(1, 1000), newMessageNotification1);
                notificationManager.Notify(SUMMARY_ID, summaryNotification);
            }
            catch(Exception){ }`

**Comment by kinfei** [comment]
Thanks

**Comment by jaspervanmegroot** [comment]
@kinfei How do you fire the onclick notification event? The normal  `CrossFirebasePushNotification.Current.OnNotificationOpened ` is not working anymore
