### ISSUE TITLE
[QUESTION] Hide notification from notification bar

### ISSUE THREAD

**Issue by dstarec** [CrossGeeks/FirebasePushNotificationPlugin#131]
Xamarin.Forms (Android)
I'am receiving a lot of notifications from the server but I don't want them to pop-up in notification bar, just some of them. 
So is it possible for me to force certain notifications (based on notification type) to NOT be displayed in notification bar ?

I hope its clear. Thank you for the answer.

**Comment by yuv4ik** [comment]
There are different types of push notifications: data and notification.
It seems that in your case data push notifications will make more sense.

https://firebase.google.com/docs/cloud-messaging/android/receive

**Comment by rdelrosario** [comment]
Just add "silent" key on the payload.

Notification without UI

If you send a key called silent with value true it won't display a notification.
Silent notification payload sample
```
{
   "data" : {
     "title": "hello",
     "body": "firebase",
     "silent":"true"
  }
}
```
