### ISSUE TITLE
CrossFirebasePushNotification.Current.OnNotificationOpened Event is not firing 

### ISSUE THREAD

**Issue by ashu271994** [CrossGeeks/FirebasePushNotificationPlugin#134]
Hi, I am facing the same problem. I have followed above steps also but no use. Also, my " MainLauncher = true" is set to true and have followed all the steps twice.
Can you please help me to configure this problem am using Latest stable 2.3.0

Version Number of Plugin:  Latest stable 2.3.0
Device Tested On: Mi Redmi Note 4
Simulator Tested On: NA
Version of VS: 15.6.5
Version of Xamarin:4.9.0.753
Versions of other things you are using: Android 7

**Steps to reproduce the Behavior**
Open received notification from Notification Bar

**Expected Behavior**
Code inside CrossFirebasePushNotification.Current.OnNotificationOpened Event executed

**Actual Behavior**
Application goes to main activity and event is not fired

**Code snippet**

MainActivity.cs
 [Activity(Label = "Ivy", Icon = "@drawable/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App());

            FirebasePushNotificationManager.ProcessIntent(this, Intent);

            CrossFirebasePushNotification.Current.Subscribe("All");

        }

        long lastPress;
        public override void OnBackPressed()
        {
            // source https://stackoverflow.com/a/27124904/3814729
            long currentTime = DateTime.UtcNow.Ticks / TimeSpan.TicksPerMillisecond;

            // source https://stackoverflow.com/a/14006485/3814729
            if (currentTime - lastPress > 5000)
            {
                Toast.MakeText(this, "Press back again to exit", ToastLength.Long).Show();
                lastPress = currentTime;
            }
            else
            {
                base.OnBackPressed();
            }

        }
    }

**Comment by ashu271994** [comment]
yes!

**Comment by ashu271994** [comment]
Hey! It's working now, don't know what happens re-installing all the packages in the project works for me.
Thank you !

**Comment by KaizerT** [comment]
Hello,

I'm experiencing this issue as well. "Reinstalling the packages" does not seem an appropriate fix or cause of issue. Can we reopen this please?

My specs:
Version Number of Plugin: Latest stable 2.3.0
Device Tested On: HTC One M9
Simulator Tested On: NA
Version of VS: 14.0.25431.0 Update 3
Version of Xamarin:4.8.0.756
Versions of other things you are using: Android 7

**Comment by KaizerT** [comment]
@rdelrosario

**Comment by KristofferBerge** [comment]
Please re-open this issue. The solution in #32 seems to be deprecated
