### ISSUE TITLE
Plugin don't get Token in iOS 9.*

### ISSUE THREAD

**Issue by SkillerSKL** [CrossGeeks/FirebasePushNotificationPlugin#137]
I'm testing the plugin in version 2.3.1-rc on Iphone version 9.3 and I don't receive the token. OnTokenRefresh not firing. Any idea?

**Comment by rdelrosario** [comment]
This just happens on iOS 9?  iOS 10+ working properly for you?

**Comment by SkillerSKL** [comment]
iOS 10+ works perfectly.

**Comment by apy534** [comment]
I'm also facing the same issue. Wasted 1 whole day working with iOS 9.
After reading this post I tried with iOS10 and its working. Thank you for posting this issue.

**Comment by apy534** [comment]
Please, SomeOne, suggest the solution once you find it.

**Comment by rubenmv** [comment]
Hi! same problem here, my iPad Mini 2 and iOS 9.3.5 is not registering a token. My other device with iOS 11.3.1 works fine. I can't try iOS 10 right now.

**Comment by bMiquelin** [comment]
@rubenmv I'm having the same issue

![image](https://user-images.githubusercontent.com/8808338/41435936-b04adbc4-6ff6-11e8-80c8-92f518f640a5.png)
iPhone 5S iOS 10.3.2

Have you found anything which solves that?

**Comment by rubenmv** [comment]
@bMiquelin no sorry, I haven't had the time to look into it :(

**Comment by bMiquelin** [comment]
I finally made it work!

I've downgraded to these versions:
https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/51#issuecomment-341190583

Those errors appeared:
```
2018-06-15 12:11:51.965 BasicApp.iOS[2117] <Error> [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
2018-06-15 12:11:51.970 BasicApp.iOS[2117] <Error> [Firebase/Core][I-COR000005] No app has been configured yet.
2018-06-15 12:11:55.450 BasicApp.iOS[2117] <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2018-06-15 12:11:55.451 BasicApp.iOS[2117] <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2018-06-15 12:12:03.293 BasicApp.iOS[2117] <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.

```
I found out  that my GoogleService-Info.plist Build Action was set to "None", then changed it into "BundleResource". Had to clean & delete bin/obj, and it worked!

Now i'm gonna check why I can only send messages to iOS via firebase console, and not by postman.
Following POST works only for Android:
```
{
  "to": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "data": {
    "type": "status",
    "title": "Test",
    "body": null,
	"icon": "https://distriqt.github.io/ANE-PushNotifications/images/icon.png",
    "color": "#9DC14C",
  }
}
```

**Comment by rubenmv** [comment]
@bMiquelin Thank you Bruno, I'll try to downgrade next week.

About your message for iOS, try this:

```json
{  
  "to": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",  
  "notification": {
    "title": "Test",  
    "body": null,  
    "sound": "default",
    "content_available": true
},
  "data": {  
    "type": "status",  
    "icon": "https://distriqt.github.io/ANE-PushNotifications/images/icon.png",  
    "color": "#9DC14C",  
  }  
}
```

**Comment by bMiquelin** [comment]
Got it working on iOS10 by changing the GoogleService-Info.plist build-action, not the versions. (Updated version isn't showing anything on the console to warn me about that)

I'm still stuck trying to make it work on an iPhone 4S iOS 9.3.5 device. Even using [2.3.1-rc], [2.3.0], [2.0.1-alpha], etc. Token does not trigger.

About the JSON: Thanks, splitting "notification" and "data" was needed, "content_available" was tricky with --dash or __underscore. iOS doesn't allow the body to be null.

**Comment by rdelrosario** [comment]
Should be fixed on this beta version:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.3.5-beta

Will do an official version release next month
