### ISSUE TITLE
PCL compatibility

### ISSUE THREAD

**Issue by RalphJacobson** [CrossGeeks/FirebasePushNotificationPlugin#138]
## Bug Information

Attempting to add the latest Plugin.FirebasePushNotification NuGet package into a PCL wants to add a plethora of .NET Standard libs.

Version Number of Plugin: 2.3.0
Device Tested On: N/A
Simulator Tested On: N/A
Version of VS: Enterprise 2017 v15.7.1
Version of Xamarin: 3.0.0.446417
Versions of other things you are using: N/A

### Steps to reproduce the Behavior
1. Create a new Xamarin Forms app.
2. Add a Portable Class Library.
3. Attempt to add the latest Plugin.FirebasePushNotification NuGet package into the PCL.

### Expected Behavior
To only add references to the Plugin.FirebasePushNotification.dll and Plugin.FirebasePushNotification.Abstractions.dll.

### Actual Behavior
Wants to add references to a plethora of .NET Standard libs. (Refer to screenshot.)

### Code snippet
N/A

### Screenshots

![firebasepushnotification](https://user-images.githubusercontent.com/34366916/39995350-2c3b4a40-577c-11e8-9545-ef7bee5f8cac.jpg)

**Comment by rdelrosario** [comment]
Unfortunately, Is not on our plan to support PCL since we started this for .NETStandard projects and all new projects are using .NETStandard now.
