### ISSUE TITLE
How to stop opening another copy of the app when a Notification is Opened

### ISSUE THREAD

**Issue by icechat** [CrossGeeks/FirebasePushNotificationPlugin#14]
When I click on a Push Notification, and the app is already open, how do I stop it from opening another copy of the app?

**Comment by claudiocleberson** [comment]
If Android, Put the  LaunchMode = LaunchMode.SingleTop in the MainActivity class. That should do the trick. iOS I didn't have problem.

[Activity(
        LaunchMode = LaunchMode.SingleTop,
        Label = "MyApp",
        Theme = "@style/AppTheme",
        Icon = "@android:color/transparent",
        ScreenOrientation = ScreenOrientation.Portrait,
        MainLauncher = false)
    ]

**Comment by icechat** [comment]
Thank you

**Comment by jonatanrinckus** [comment]
But with this, the app does not hit the OnNotificationOpened method.

**Comment by claudiocleberson** [comment]
@jonatanrinckus 

Try by override that other method on MainActivitity:

/// <summary>
        /// Called when the app is in the background and a notification is clicked on (also called each time the app is minimized and the brought back up), a new <c>Intent</c> is created
        ///     and sent out, since we use <c>LaunchMode</c> set to <c>SingleTop</c> this method is called instead of the app being restarted.
        /// </summary>
        /// <param name="intent">The <c>Intent</c> that was set when the call was made. If started from a notification click, extra <c>string</c> values can be extracted.</param>
        protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            FirebasePushNotificationManager.ProcessIntent(intent);
        }

**Comment by rdelrosario** [comment]
Just released https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.1.3  a new version for better handling of this now by default plugin launches activity with SingleTop flag. More information on about this and how to change the behaviour here:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/AndroidCustomization.md
