### ISSUE TITLE
FirebasePushNotificationManager  error

### ISSUE THREAD

**Issue by JasonSa1993** [CrossGeeks/FirebasePushNotificationPlugin#141]
Hello, I have a problem when implementing the MainApplication class in my Android project, when writing the Using Plugin.FirebasePushNotification statement; everything is fine, but in the code the reserved FirebasePushNotificationManager words are not recognized by the program and it throws me the following error "the name FirebasePushNotificationManager does not exist in the current context" and because I can not execute my application ..

what is this about? already import the plugin both in the pcl and in the android project and only in the android project these names are not recognized.

first of all, Thanks.

**Comment by rdelrosario** [comment]
Do you have Android 8.0 as compilation target?

**Comment by alaatm** [comment]
I am having the same issue, PushNotificationManager does not exist. I have Android 8.0 as compilation target.

I am using NetStandard project. Is this causing it or what am I doing wrong?

**Comment by rdelrosario** [comment]
This is an old version issue related to the FCM NuGet package on Android, that was solved in more recent versions.

**Comment by dbensonviri** [comment]
What package do I need to add? I have the latest version of FirebasePushNotificationPlugin.

**Comment by XamarinInfo** [comment]
I am having the latest version of FirebasePushNotificationPlugin-3.1.6 
bit i am getting the same error

**Comment by waheedakhter** [comment]
@XamarinInfo  same here. were you able to fix it?

**Comment by waheedakhter** [comment]
@rdelrosario  what is the solution?

**Comment by XamarinInfo** [comment]
Hi Waheed,

I didnt get any solution for this issue.So I tried FCM notification implementation in Xamarin android.
I am not using this plugin anymore for xamarin android.
FCm implementation in xamarin android is so simple .try that plz

**Comment by E882** [comment]
I used target Android version is API level 29, and used latest version of FirebasePushNotificationPlugin-3.4.25, but get same error!! But in Xamarin.iOS can run the program.
