### ISSUE TITLE
After killed and started the app will not receive the messages sent during restart

### ISSUE THREAD

**Issue by NikolaStamenov** [CrossGeeks/FirebasePushNotificationPlugin#143]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
After killed and started the app will not receive the messages sent during restart

Version Number of Plugin: 2.1.3
Device Tested On: Huawei X2, P8
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 4.7.10.38
Versions of other things you are using:

### Steps to reproduce the Behavior
Start the app, then kill it from the tasks, and send a notification to it, then start.

### Expected Behavior
App to receive the push send during the restart.

### Actual Behavior
App is not receiving the push send during the restart.

### Screenshots

- It's PCL Android Native app.

**Comment by NikolaStamenov** [comment]
Seems like using the original Chinese firmware of the devices is making the issue, since the Google Play services is installed manually on them,
Going to get more devices for test without chinese firmaware.

**Comment by rdelrosario** [comment]
These phones have a particular quirk that when the app is force closed that you will no longer be able to receive notifications until the app is restarted. In order for you to receive background notifications:

On your Huawei device go to Settings > Protected apps > check "My App" where.
On your Xiaomi make sure your phone has the "Auto-start" property enabled for your app.
On your Asus make sure your phone has the "Auto-start" property enabled for your app.
