### ISSUE TITLE
Cannot update to newer versions of Xam.Firebase.Messaging

### ISSUE THREAD

**Issue by nodoid** [CrossGeeks/FirebasePushNotificationPlugin#144]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:2.3.0
Device Tested On:Android
Simulator Tested On:
Version of VS: 7.6 (build 711)
Version of Xamarin:8.3.0.19
Versions of other things you are using:

### Steps to reproduce the Behavior
Install the plugin
Update Xam.Firebase.Messaging to 60

### Expected Behavior
Updates
### Actual Behavior
Doesn't update (incompatible)

**Comment by rdelrosario** [comment]
Hi 

Which firebase messaging nuget are you updating to?

**Comment by edosusanto** [comment]
Hi,
I'm currently facing this issue too with 2.3.0. My google play services libraries version are 60.1142.1, but the nuget dependency want Xamarin.Firebase.Messaging v60.1142.0, which is not compatible with v60.1142.1

**Comment by rdelrosario** [comment]
Just released this beta with support for newer version of fcm nuget package:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.3.5-beta
