### ISSUE TITLE
Android/Turn display of notifications on/off within app

### ISSUE THREAD

**Issue by leeapted** [CrossGeeks/FirebasePushNotificationPlugin#147]
We make use of the following setting in our ios app:

FirebasePushNotificationManager.CurrentNotificationPresentationOption=None/Alert

We handle the onreceive event always but it's useful to turn display of the notification off in some circumstances.

Is there a corresponding way to do this on Android (short of using a custom UI)?

Thank you.

**Comment by rdelrosario** [comment]
Now is possible by setting FirebasePushNotificationManager.DefaultNotificationChannelImportance in Android
