### ISSUE TITLE
Foundation.You_Should_Not_Call_base_In_This_Method thrown after adding plugin via "Getting Started" instructions

### ISSUE THREAD

**Issue by coldacid** [CrossGeeks/FirebasePushNotificationPlugin#15]
Is the call to `base.FailedToRegisterForRemoteNotifications(application, error)` really necessary for iOS? After following the "getting started" instructions, my application crashed from an uncaught exception stating that the base shouldn't be called here. If it's not actually necessary, it might be good to remove the line from the documentation.

## Bug Information

Version Number of Plugin: 1.0.4
Device Tested On:
Simulator Tested On: iPhone 6 iOS 10.3
Version of VS: 2017 (15.3.0)
Version of Xamarin: 4.6.0.295
Versions of other things you are using:
* Xamarin.Forms 2.3.4.224

### Steps to reproduce the Behavior

1. Follow the instructions at https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/69c9570a00fbe91259071fb296f9f9e327dc5328/docs/GettingStarted.md to add FirebasePushNotificationPlugin to an existing Xamarin.Forms application.
2. Subscribe to a topic in the `App.OnStart()` method in the common Xamarin.Forms application project.

### Expected Behavior

iOS notification asking user to confirm if they want to receive push notifications appears. If the user confirms, then the app should be subscribed to the topic from step 2.

### Actual Behavior

iOS notification asking user to confirm if they want to receive push notifications appears. If the user confirms, then the app crashes in the `FailedToRegisterForRemoteNotifications(UIApplication, NSError)` method of the app delegate class in the Xamarin.Forms iOS project due to `base.FailedToRegisterForRemoteNotifications(application, error)` throwing `Foundation.You_Should_Not_Call_base_In_This_Method`.

### Code snippet

In application project:

```c#
namespace MyApplication
{
    public partial class App : Application
    {
        protected override void OnStart()
        {
            // Handle when your app starts
            MobileCenter.Start(
                @"android={MCAndroidGuid};ios={MCiOSGuid};uwp={MCUwpGuid};",
                typeof(Analytics),
                typeof(Crashes));

            // ReSharper disable once StringLiteralTypo
            DependencyService.Get<ISystemLogger>().AppCode = "MyApplication";

            CrossFirebasePushNotification.Current.Subscribe("news");
        }
    }
}
```

In iOS platform project:

```c#
namespace MyApplication.iOS
{
    [Register("AppDelegate")]
    public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
    {
        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            base.FailedToRegisterForRemoteNotifications(application, error); // this throws the exception
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);
        }
    }
}
```

### Screenshots

See exception stack at https://gist.github.com/coldacid/e284b677336d89e74e75a6189cc7b1bd

**Comment by coldacid** [comment]
Removing `base.FailedToRegisterForRemoteNotifications(application, error)` seems to work, so yeah it should probably be removed from the doc.

**Comment by rdelrosario** [comment]
Yes, you are right this call shouldn't be there. Thanks, just updated the docs

**Comment by NPadrutt** [comment]
I just got the same exception on this method:

```
public override void OnActivated(UIApplication uiApplication)
{
        FirebasePushNotificationManager.Connect();
        base.OnActivated(uiApplication);
}
```

I guess here it is the same: `base.OnActivated(uiApplication);` should not be called.

**Comment by rdelrosario** [comment]
Ok removed that call from the docs to avoid confusion and this issue.
