### ISSUE TITLE
Never got the Token & Never received the Notification sent from FCM Console

### ISSUE THREAD

**Issue by udayb99** [CrossGeeks/FirebasePushNotificationPlugin#150]
I got the Notifications the first time I have implemented this package three days ago (received couple of notifications), but from the next day I haven't got any notifications and the Token is always empty in debug mode. I have tried in Release mode also but i'm not getting Notifications. I have tried all possible troubleshooting methods, re-installed Packages, clean and rebuild, re-installing the application etc., but no success. I am not getting any build/runtime errors, and application is working fine, but just the notifications are not receiving, either in the background or in the foreground.

BTW, I am trying to send sample messages from FCM Console, with and without custom data.
And I believe all the FCM related settings are proper in the application.

I am running Xamarin.Forms with only Android and PCL projects.

Below is the PCL App.xaml.cs file OnStart() method

        protected override void OnStart()
        {
            CrossFirebasePushNotification.Current.Subscribe("general");

            CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine($"TOKEN REC: {p.Token}");
            };

            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                    System.Diagnostics.Debug.WriteLine("Received");
            };

            CrossFirebasePushNotification.Current.OnNotificationOpened += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("Opened");
            };

            CrossFirebasePushNotification.Current.OnNotificationDeleted += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("Dismissed");
            };
        }

Below is the **MainApplication.cs** from Android Platform Project

public override void OnCreate()
        {
            base.OnCreate();
            RegisterActivityLifecycleCallbacks(this);

#if DEBUG
            FirebasePushNotificationManager.Initialize(this, true);
#else
            FirebasePushNotificationManager.Initialize(this, false);
#endif

            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("NOTIFICATION RECEIVED", p.Data);
            };

            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                FirebasePushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";
                FirebasePushNotificationManager.DefaultNotificationChannelName = "General";
            }
        }

I am using below IDE & Packages.

<package id="Plugin.FirebasePushNotification" version="2.3.0" targetFramework="monoandroid81" />
<package id="Xamarin.Build.Download" version="0.4.7" targetFramework="monoandroid81" />
<package id="Xamarin.Firebase.Common" version="60.1142.0" targetFramework="monoandroid81" />
<package id="Xamarin.Firebase.Iid" version="60.1142.0" targetFramework="monoandroid81" />
<package id="Xamarin.Firebase.Messaging" version="60.1142.0" targetFramework="monoandroid81" />
<package id="Xamarin.Forms" version="3.0.0.550146" targetFramework="monoandroid81" />
<package id="Xamarin.GooglePlayServices.Basement" version="60.1142.0" targetFramework="monoandroid81" />
<package id="Xamarin.GooglePlayServices.Tasks" version="60.1142.0" targetFramework="monoandroid81" />

My **MainActivity.cs**

        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);

            LoadApplication(new App(new AndroidInitializer()));

            FirebasePushNotificationManager.ProcessIntent(this, Intent);
      }

        protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            FirebasePushNotificationManager.ProcessIntent(this, intent);
        }

Version Number of Plugin: 2.3.0
Device Tested On: OnePlus 5T with Android 8.1
Version of VS: VS 2017 15.6.4
Version of Xamarin.Forms: 3.0.0.550146

**Comment by bMiquelin** [comment]
Check your google-services.json (redownload it)
That is expected to happen if your key changes, as it's being unable to connect to firebase server.

**Comment by udayb99** [comment]
@bMiquelin, thanks for your response, but unfortunately it didn't worked. I tried downloading the json file again but with no success, i removed the FCM project altogether and re-created a project with a new package name as well, updated the package name in my xamarin andorid project and downloaded the new json file and set the build action to "GoogleServicesJson", but the issue is same.

Do we need to specify a specific Notification Channel ID & Name?
Or is there any issue with the Latest versions of Firebase or Xamarin.forms?

Here is my full Application.cs file

using System;
using System.Collections.Generic;
using Android.App;
using Android.OS;
using Android.Runtime;
using Firebase;
using Plugin.CurrentActivity;
using Plugin.FirebasePushNotification;
using Plugin.FirebasePushNotification.Abstractions;

namespace QNPL.Mobile.Droid
{
    [Application]
    public class MainApplication : Application, Application.IActivityLifecycleCallbacks
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer)
          : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            RegisterActivityLifecycleCallbacks(this);
            
#if DEBUG
            FirebasePushNotificationManager.Initialize(this, new NotificationUserCategory[]
            {
            new NotificationUserCategory("message",new List<NotificationUserAction> {
                new NotificationUserAction("Reply","Reply",NotificationActionType.Foreground),
                new NotificationUserAction("Forward","Forward",NotificationActionType.Foreground)

            }),
            new NotificationUserCategory("request",new List<NotificationUserAction> {
                new NotificationUserAction("Accept","Accept",NotificationActionType.Default,"check"),
                new NotificationUserAction("Reject","Reject",NotificationActionType.Default,"cancel")
            })

            }, true);
#else
	            FirebasePushNotificationManager.Initialize(this,new NotificationUserCategory[]
		    {
			new NotificationUserCategory("message",new List<NotificationUserAction> {
			    new NotificationUserAction("Reply","Reply",NotificationActionType.Foreground),
			    new NotificationUserAction("Forward","Forward",NotificationActionType.Foreground)

			}),
			new NotificationUserCategory("request",new List<NotificationUserAction> {
			    new NotificationUserAction("Accept","Accept",NotificationActionType.Default,"check"),
			    new NotificationUserAction("Reject","Reject",NotificationActionType.Default,"cancel")
			})

		    },false);
#endif

            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("NOTIFICATION RECEIVED", p.Data);
            };

            //Set the default notification channel for your app when running Android Oreo
            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                FirebasePushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";

                //Change for your default notification channel name here
                FirebasePushNotificationManager.DefaultNotificationChannelName = "General";
            }
        }

        public override void OnTerminate()
        {
            base.OnTerminate();
            UnregisterActivityLifecycleCallbacks(this);
        }

        public void OnActivityCreated(Activity activity, Bundle savedInstanceState)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }

        public void OnActivityDestroyed(Activity activity)
        {
        }

        public void OnActivityPaused(Activity activity)
        {
        }

        public void OnActivityResumed(Activity activity)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }

        public void OnActivitySaveInstanceState(Activity activity, Bundle outState)
        {
        }

        public void OnActivityStarted(Activity activity)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }

        public void OnActivityStopped(Activity activity)
        {
        }
    }
}

**Comment by udayb99** [comment]
@bMiquelin i was able to find the issue...culprit is myself...a month ago..i have disabled most of my google background services in mobile data..as they are consuming lot of mobile data....i have realized this after analyzing the debug output of my app with this line "**D/FirebaseInstanceId(32620): background sync failed: SERVICE_NOT_AVAILABLE, retry in 20s**". When I first ran i was in wifi and hence the notifications started working...after that i was testing in office in my mobile data...and so the issue :)
