### ISSUE TITLE
The "LinkingAssemblies" Task Failed Unexpectedly

### ISSUE THREAD

**Issue by dabrarohit** [CrossGeeks/FirebasePushNotificationPlugin#151]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.3.1-RC
Device Tested On: OnePlus 5t
Simulator Tested On: Pixel 2 Xl
Version of VS: VS Mac 7.6 Preview
Version of Xamarin: 3.1
Versions of other things you are using:

### Steps to reproduce the Behavior

Change to Release Mode and Try to Build

### Expected Behavior
Should Be Built successfully and install on device/simulator
### Actual Behavior
Gives an error provided in screenshot, However works perfectly fine in debug mode for both Android/iOS

### Screenshots

![screen shot 2018-06-12 at 3 36 01 pm](https://user-images.githubusercontent.com/2404402/41284483-0a099296-6e57-11e8-8660-8460f4e28d09.png)

**Comment by ziXet** [comment]
I have exactly the same issue.

**Comment by Vaibhavi1710** [comment]
Facing the same issue.

**Comment by mimunoz** [comment]
Why do not you try with plugin version 2.3.5? It's works perfect for me and has new features.

**Comment by Vaibhavi1710** [comment]
I tried by updating the plugin version to 2.3.5 but still get the same error as follows:
![error](https://user-images.githubusercontent.com/14208259/44549754-11745a80-a6f0-11e8-9d15-00d58fcdb32f.png)

**Comment by mjspk** [comment]
I have the same issue here it happen only when setting linker to SDK assemblies only any updates any ideas 
I had to set linker to none in order to get my app on release mode but the app size gets much bigger because of that but when removing this plugin everything goes well and build successfully

**Comment by gaffkins** [comment]
In iOS build settings change Support Architecture to ARMv7 (! without s !) + ARM64. It's help. Best!

**Comment by narendragiri** [comment]
Are you guys able to resolve this issue ?

**Comment by gaffkins** [comment]
@narendragiri  Did you try my solution from post above?

**Comment by narendragiri** [comment]
@gaffkins  Actually i have a issue with Android Release build.

**Comment by narendragiri** [comment]
> I have the same issue here it happen only when setting linker to SDK assemblies only any updates any ideas
> I had to set linker to none in order to get my app on release mode but the app size gets much bigger because of that but when removing this plugin everything goes well and build successfully

@mjspk  Did you solve this issue?

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta
