### ISSUE TITLE
CrossFirebasePushNotification.Current.OnNotificationOpened is not being called when app is in background

### ISSUE THREAD

**Issue by rakeshdkaatkar** [CrossGeeks/FirebasePushNotificationPlugin#154]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:2.3.1
Device Tested On:Android lollypop
Simulator Tested On:
Version of VS: Visual studio 2017 enterprise
Version of Xamarin:4.0.30319
Versions of other things you are using:

**Comment by rdelrosario** [comment]
How are you sending the payload?

**Comment by amelspahic** [comment]
I had the same problem. You need to set LaunchMode = LaunchMode.SingleTop on you main Activity (Splash is still Main Launcher).

![image](https://user-images.githubusercontent.com/10445852/43048522-47e8b5c2-8de9-11e8-9bf9-25e158b5ef25.png)

and you need to push extras from Splash activity

![image](https://user-images.githubusercontent.com/10445852/43048556-c16a0cde-8de9-11e8-9e33-21bb79690e0e.png)

**Comment by rohitvipin** [comment]
I do have the same issue, without having any splash screen activity.

**Comment by alextorres50** [comment]
when the app is on Background Mode, the events doesn't trigger. When the app is on Foreground the events works fine

**Comment by amer2737** [comment]
any solution?
