### ISSUE TITLE
Pushes open multiple times on Android

### ISSUE THREAD

**Issue by ekaterina0214** [CrossGeeks/FirebasePushNotificationPlugin#156]
Does somebody know, how to get push only one time on Android? Is it a bug?

**Comment by jdluzen** [comment]
Do you mean disabling the default notification when you push data only? If so, set `createDefaultNotificationChannel`  to `false` when calling `FirebasePushNotificationManager.Initialize`.

**Comment by rdelrosario** [comment]
What version are you using?

**Comment by tekinc** [comment]
On Droid when receiving a push notification while the app is in the background Im noticing the my App() is relaunched and my home screen is push on to the current screen. This results in my home screen being on the view stack twice.

**Comment by andrewbird1** [comment]
Hi All,

When a push arrives if the app is in background if I click on the push the app seems to compound the messages. In Some cases 1 messages appears more than once.. everytime it is in the background seems to add a new message, The login screen also seems to relaunch then closing it reverts back to app and then sometimes gets the message.

On IOS perfect but in android no good. If the App is in the foreground seems to be fine..

Any ideas as it sounds just like the above.

**Comment by andrewbird1** [comment]
Fixed my Issue it was a problem with not using the singletop flag on the intent...
