### ISSUE TITLE
OnNotificationOpened is not called when app is closed.

### ISSUE THREAD

**Issue by manikandansai** [CrossGeeks/FirebasePushNotificationPlugin#159]
## Bug Information
OnNotificationOpened is not calling when the app is terminated.

Version Number of Plugin: 2.3.0 
Device Tested On Samsung s6 and iPhone 6+
Simulator Tested On:  No 
Version of VS: 15.7.3
Version of Xamarin: 3.1.0.583944
Versions of other things you are using:

### Expected Behavior
OnNotificationOpened should be called.
### Actual Behavior
OnNotificationOpened is not calling.

### Code snippet
**Body:**

```
{
   "to":"/topics/debug", 
   "data":{    
   		"priority":"high",
   		"sound":"default",
   		"id": 3,
    	"message":"msg"
   },
   "notification":{
   		"priority":"max",
      "title":"Sai Mobile Apps"
      "body":"msg",
      "sound":"default",
      "content_available":true
   }
} 

```

**Comment by rdelrosario** [comment]
Remove notification from the payload:

```json
 "notification":{
   		"priority":"max",
      "title":"Sai Mobile Apps"
      "body":"msg",
      "sound":"default",
      "content_available":true
   }
```
Send this instead:

```json
{
   "to":"/topics/debug", 
   "data":{    
   		"priority":"high",
   		"sound":"default",
   		"id": 3,
    	"message":"msg"
   }
} 

```
