### ISSUE TITLE
iOS - Token is empty

### ISSUE THREAD

**Issue by GyllionElderen** [CrossGeeks/FirebasePushNotificationPlugin#160]
I'm trying to retreive a token on iOS from FCM with the FirebasePushNotificationPlugin, but so far no success. I walked through the complete 'Getting Started' section, but by the end, the token still remains an empty string. The 'OnTokenRefresh' event is also never called. I retrieve a token with the static property 'CrossFirebasePushNotification.Current.Token'

Here are the things I tried:
- Generating an APNs key and putting it into the Firebase iOS app
- Generating an APNs certificate and putting it into the Firebase iOS app (development only)
- Checking if the device is registered in the provisioning profile (automatic provisioning is turned on)
- Checking if the 'Push Notifications' service is enabled on the App ID and the provisioning profile
- Checking if the bundle ID's of both the Firebase and the Xamarin.iOS projects are the same
- Making sure the GoogleService-Info.plist is set on 'BundleResource'
- Making sure the correct GoogleService-Info.plist is inside the iOS project root
- Making sure the FirebaseAppDelegateProxyEnabled property exists in the info.plist and is set on 'No'
- Updating to Plugin.FirebasePushNotification v 2.3.5-beta
- Registering not automatically, but through CrossFirebasePushNotification.Current.RegisterForPushNotifications();
- Uninstalling the app and deploying again to the device
- Deleting the bin and obj folders and rebuilding the project

And last but not least...
- Turning all the devices (mac, iPhone, PC with Windows) off and on again

I used an iPhone 6 with iOS 11.4.1.

Are there any more options I could try?

**Comment by rdelrosario** [comment]
When you run your application did you get the Push Notification permission popup and allowed it?

**Comment by GyllionElderen** [comment]
@rdelrosario Yes I did see the popup when using CrossFirebasePushNotification.Current.RegisterForPushNotifications(). I allowed it, but still no token unfortunately

**Comment by altipeak** [comment]
It also happens to me. It's working fine on my device (iPhone 6) using TestFlight with an IPv6, but it doesn't pass the Apple Store review (they used ipad). The token is NULL. I cannot reproduce it.

**Comment by GyllionElderen** [comment]
@altipeak How did you make it work on iPhone 6? Other than using TestFlight with IPv6, did you edit anything in the project to make it work?

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta

**Comment by stesvis** [comment]
@GyllionElderen did you ever solve it? More than two years later i have the same issue.
Also, i never got to see the prompt for permissions, what could prevent that?
@rdelrosario any idea?

**Comment by stesvis** [comment]
> @stesvis Did you solve the problem?

I solved it by removing this plugin and switching to OneSignal. I should have done it earlier!

**Comment by BhaurajBiradar001** [comment]
Any updates?
