### ISSUE TITLE
[ANDROID] FirebaseMessaging: Error while parsing timestamp in GCM event

### ISSUE THREAD

**Issue by MauryZ** [CrossGeeks/FirebasePushNotificationPlugin#162]
It seems that the plugin or system can not handle notification after add action, on "Reply" or "Close" is working but if you click on notification it crash.

## Bug Information
Code in MainApplication.cs
` FirebasePushNotificationManager.Initialize(this, new NotificationUserCategory[]  {
                new NotificationUserCategory("message", new List<NotificationUserAction>
                {
                    new NotificationUserAction("Reply", "Reply", NotificationActionType.Foreground),
                    new NotificationUserAction("Close", "Close", NotificationActionType.Foreground)
                })
            }, true);`

> [NetworkSecurityConfig] No Network Security Config specified, using platform default
[System] ClassLoader referenced unknown path: /system/framework/tcmclient.jar
[Mono] Assembly Ref addref Xamarin.Firebase.Messaging[0xa758cf40] -> Xamarin.GooglePlayServices.Tasks[0xaa035320]: 3
[FirebaseMessaging] Error while parsing timestamp in GCM event
[FirebaseMessaging] java.lang.NumberFormatException: null
[FirebaseMessaging] 	at java.lang.Integer.parseInt(Integer.java:483)
[FirebaseMessaging] 	at java.lang.Integer.valueOf(Integer.java:611)
[FirebaseMessaging] 	at com.google.firebase.messaging.zzd.zzb(Unknown Source)
[FirebaseMessaging] 	at com.google.firebase.messaging.zzd.zzg(Unknown Source)
[FirebaseMessaging] 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
[FirebaseMessaging] 	at com.google.firebase.iid.zzc.run(Unknown Source)
[FirebaseMessaging] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
[FirebaseMessaging] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
[FirebaseMessaging] 	at java.lang.Thread.run(Thread.java:761)
[FirebaseMessaging] Unable to log event: analytics library is missing

Version Number of Plugin: 2.3
Version of Xamarin: 3.1.0

### Steps to reproduce the Behavior
Add "click_action" in notification

**Comment by rdelrosario** [comment]
Are you using GCM or FCM?

**Comment by MauryZ** [comment]
FCM

**Comment by rdelrosario** [comment]
How are you sending the payload?

**Comment by frogerdevs** [comment]
Hi @rdelrosario I have same problem, below is my log, notification has appeared, but event OnNotificationReceived not triggered, I send using postman from your Firebase Postman Collection

08-10 17:23:15.529 D/Mono    (24424): Assembly Ref addref Xamarin.Firebase.Messaging[0x72d4bf1100] -> Xamarin.GooglePlayServices.Tasks[0x72d4bf1700]: 3
08-10 17:23:15.544 W/FirebaseMessaging(24424): Error while parsing timestamp in GCM event
08-10 17:23:15.544 W/FirebaseMessaging(24424): java.lang.NumberFormatException: s == null
08-10 17:23:15.544 W/FirebaseMessaging(24424): 	at java.lang.Integer.parseInt(Integer.java:570)
08-10 17:23:15.544 W/FirebaseMessaging(24424): 	at java.lang.Integer.valueOf(Integer.java:794)
08-10 17:23:15.544 W/FirebaseMessaging(24424): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source:60)
08-10 17:23:15.544 W/FirebaseMessaging(24424): 	at com.google.firebase.messaging.zzd.zzg(Unknown Source:26)
08-10 17:23:15.544 W/FirebaseMessaging(24424): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:160)
08-10 17:23:15.544 W/FirebaseMessaging(24424): 	at com.google.firebase.iid.zzc.run(Unknown Source:4)
08-10 17:23:15.544 W/FirebaseMessaging(24424): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-10 17:23:15.544 W/FirebaseMessaging(24424): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-10 17:23:15.544 W/FirebaseMessaging(24424): 	at java.lang.Thread.run(Thread.java:764)
08-10 17:23:15.545 W/FirebaseMessaging(24424): Unable to log event: analytics library is missing

**Comment by Lukas182** [comment]
Anyone solved this? cos Im having exactly the same problem..

**Comment by rdelrosario** [comment]
Fixed on latest release
