### ISSUE TITLE
Push notification does not receive on foreground when we integrate cross geek facebook plugin

### ISSUE THREAD

**Issue by Yashshree** [CrossGeeks/FirebasePushNotificationPlugin#166]
## Bug Information

Version Number of Plugin: facebook plugin 1.3.0 , firebase plugin 2.3.0
Device Tested On: android lenovo 
Simulator Tested On: ios 7
Version of VS: 7.5.3
Version of Xamarin: 4.4.1.193
Versions of other things you are using:

### Steps to reproduce the Behavior
fire notification . it will receive in background (pop up ui) not in foreground . it is working fine in ios

### Expected Behavior
notification should receive in foreground as well for android

### Actual Behavior
notification not receiving in foreground as well for android

### Code snippet
followed this tutorial only 

### Screenshots
onNotificationReceive is getting called for android but notitification is not getting poped.

**Comment by tinkeringcharlie** [comment]
I'm putting a new PR in now. If your running Oreo, and you want to fix this, set the DefaultNotificationChannelId = "FirebasePushNotificationChannel" (Not DefaultChannel).  When it instantiate firebase push notification it sets the DefaultNotificationChannelId to the former.

**Comment by Yashshree** [comment]
It is not related to oreo. It is for all android devices . Firstly i have integrated firebase push notification plugin then it was working fine. When i have integrated facebook plugin of grossgeek , forground notification are not receiving in android.
