### ISSUE TITLE
OnTokenRefresh not called, no token generated.

### ISSUE THREAD

**Issue by gangaliv** [CrossGeeks/FirebasePushNotificationPlugin#167]
I have a really weird issue. I was able to do everything according to the documentation and tested using two different phones. First, I tested with Android 8.1, the OnTokenRefresh fired correctly and I was able to get the token. Second, I tested the exact code with Android 4.4, the OnTokenRefresh is not firing and I was unable to get the token. What could be the issue?

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta
