### ISSUE TITLE
Refresh token each time start app.

### ISSUE THREAD

**Issue by Atomico001** [CrossGeeks/FirebasePushNotificationPlugin#17]
Hi, is it normal that each time i start the app i register a new token? 

I set: FirebasePushNotificationManager.Initialize(this,false);

**Comment by rdelrosario** [comment]
Token will refresh:

The app deletes Instance ID
The app is restored on a new device
The user uninstalls/reinstall the app
The user clears app data.
If you change the app version

**Comment by Atomico001** [comment]
If you change the app version

wow..this is a usefull feature i didn't know. Thanks

**Comment by Umar3x** [comment]
Hello @rdelrosario ,

What do you mean by "The app deletes Instance ID" ? I want to force renew of the token when a user disconnects from the app and reconnects with another account w/o closing the app. 

Thanks.

**Comment by rdelrosario** [comment]
On Android project use FirebasePushNotificationManager.Reset();

**Comment by Umar3x** [comment]
Hello @rdelrosario 

Thank you for your answer. So I've tried .Reset(), it works, but it does not seems to trigger a renew for the token. It is empty when I log in again after calling this method. Thanks
