### ISSUE TITLE
Android Oreo(8/api >= 26) Sound in Background Notifications?

### ISSUE THREAD

**Issue by poller2810** [CrossGeeks/FirebasePushNotificationPlugin#170]
Since i am not able to get **SOUND** in Background Notifications running no mather what i try i finally need your help.

Here is how i create the channel:

`

                var notificationManager = NotificationManager.FromContext(this);
                var soundName = "intruderalert";

                int soundResId = Resources.GetIdentifier(soundName, "raw", PackageName);
                if (soundResId == 0 && soundName.IndexOf(".") != -1)
                {
                    soundName = soundName.Substring(0, soundName.LastIndexOf('.'));
                    soundResId = Resources.GetIdentifier(soundName, "raw", PackageName);
                }

                var uri = new Android.Net.Uri.Builder()
                                .Scheme(ContentResolver.SchemeAndroidResource)
                                .Path($"{PackageName}/{soundResId}")
                                .Build(); 
                var att = new AudioAttributes.Builder().SetUsage(AudioUsageKind.Notification).Build();

                var channel = new NotificationChannel("intruderalert", "name", NotificationImportance.High);
                channel.SetSound(uri, att);
                

                notificationManager.DeleteNotificationChannel("intruderalert");//Just for debugging purpose

                notificationManager.CreateNotificationChannel(channel);`

And here is My Notification Body wich i send:

>{
	"to":"[my device id]",
	"data": {
		"payload":"[Some Guid]"
	},
	"notification" : {
		"body" : "hello!",
		"sound": "intruderalert",
		"android_channel_id" : "intruderalert"
	}
}

in my Debug output i can find this few lines wich make me a bit suspicious in 2 ways:
- if there is a internal exception maybe my channel will not get processed?
- i never setSound on my side except where i create my channel (I think this might be internal where the NotificationBuilders SetSound is makred as Obsolete?)

> 08-08 09:39:28.146 W/FirebaseMessaging(26082): Error while parsing timestamp in GCM event
08-08 09:39:28.146 W/FirebaseMessaging(26082): java.lang.NumberFormatException: s == null
08-08 09:39:28.146 W/FirebaseMessaging(26082): 	at java.lang.Integer.parseInt(Integer.java:570)
08-08 09:39:28.146 W/FirebaseMessaging(26082): 	at java.lang.Integer.valueOf(Integer.java:794)
08-08 09:39:28.146 W/FirebaseMessaging(26082): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source:60)
08-08 09:39:28.146 W/FirebaseMessaging(26082): 	at com.google.firebase.messaging.zzd.zzg(Unknown Source:26)
08-08 09:39:28.146 W/FirebaseMessaging(26082): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:160)
08-08 09:39:28.146 W/FirebaseMessaging(26082): 	at com.google.firebase.iid.zzg.run(Unknown Source:26)
08-08 09:39:28.146 W/FirebaseMessaging(26082): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-08 09:39:28.146 W/FirebaseMessaging(26082): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-08 09:39:28.146 W/FirebaseMessaging(26082): 	at java.lang.Thread.run(Thread.java:764)
08-08 09:39:28.148 W/FirebaseMessaging(26082): Unable to log event: analytics library is missing
08-08 09:39:28.160 W/FirebaseMessaging(26082): Error while parsing timestamp in GCM event
08-08 09:39:28.160 W/FirebaseMessaging(26082): java.lang.NumberFormatException: s == null
08-08 09:39:28.160 W/FirebaseMessaging(26082): 	at java.lang.Integer.parseInt(Integer.java:570)
08-08 09:39:28.160 W/FirebaseMessaging(26082): 	at java.lang.Integer.valueOf(Integer.java:794)
08-08 09:39:28.160 W/FirebaseMessaging(26082): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source:60)
08-08 09:39:28.160 W/FirebaseMessaging(26082): 	at com.google.firebase.messaging.zzd.zzj(Unknown Source:2)
08-08 09:39:28.160 W/FirebaseMessaging(26082): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:201)
08-08 09:39:28.160 W/FirebaseMessaging(26082): 	at com.google.firebase.iid.zzg.run(Unknown Source:26)
08-08 09:39:28.160 W/FirebaseMessaging(26082): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-08 09:39:28.160 W/FirebaseMessaging(26082): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-08 09:39:28.160 W/FirebaseMessaging(26082): 	at java.lang.Thread.run(Thread.java:764)
08-08 09:39:28.162 W/FirebaseMessaging(26082): Unable to log event: analytics library is missing
Thread started:  #7
08-08 09:39:28.337 W/Notification(26082): Use of stream types is deprecated for operations other than volume control
08-08 09:39:28.337 W/Notification(26082): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case

On Devices with  a lower version than Android 8 all works fine.

Any idea what could be wrong? 

PS: if you need further informations let me know.

**Comment by davwheat** [comment]
It works fine for me. Could you upload some of your code?

**Comment by poller2810** [comment]
What specific parts do you need? how does your initialisation and Push Json data look like?

**Comment by rdelrosario** [comment]
Use this json payload instead:

```json
{
   "to":"[my device id]",
   "data" : {
     "payload":"[Some Guid]",
     "body" : "hello!",
     "sound": "intruderalert",
     "android_channel_id" : "intruderalert"
  }
}
```

**Comment by poller2810** [comment]
Could you maybe update your sample with working custom sound in channels? So far i could not get custom sounds on Android 8 working.

**Comment by poller2810** [comment]
Thank you @larryolocke i am going to give this a try once i finished my current task. i will respond as soon i could verify your solution, so this issue can be resolved.

**Comment by cpiock** [comment]
@poller2810 did you tried this solution above? works or are there any other solutions

**Comment by poller2810** [comment]
I abandoned the plugin and implemented a native solution. I never could get this to work they way we needed.
@cpiock if you need further informations about, feel free to PN me.

**Comment by cpiock** [comment]
@poller2810 maybe you have some hint for use where to start or some samplecode for a native solution on xamarin thanks

**Comment by poller2810** [comment]
@cpiock  please send me private message regarding this there i can supply you my personal contact informations

**Comment by cpiock** [comment]
@poller2810 sorry for my ignorance but how i can send you a private message on github?
