### ISSUE TITLE
When done configuration of android notification give error.

### ISSUE THREAD

**Issue by VikasPawar2112** [CrossGeeks/FirebasePushNotificationPlugin#171]
Error = Severity	Code	Description	Project	File	Line	Suppression State Error The "GenerateJavaStubs" task failed unexpectedly.System.InvalidOperationException: Application cannot have both a type with an [Application] attribute and an [assembly:Application] attribute.at Xamarin.Android.Tasks.ManifestDocument.CreateApplicationElement(XElement manifest, String applicationClass, List`1 subclasses, List`1 selectedWhitelistAssemblies)at Xamarin.Android.Tasks.ManifestDocument.Merge(List`1 subclasses, List`1 selectedWhitelistAssemblies, String applicationClass, Boolean embed, String bundledWearApplicationName, IEnumerable`1 mergedManifestDocuments) at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res) at Xamarin.Android.Tasks.GenerateJavaStubs.Execute() at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()BarberCustomer.Android			

I have used two class those extends Application class. One is used in main project and second in Android project. This error accrued because of we have two application class. We did setup as per video https://www.youtube.com/watch?v=FrxPEMLfV-o&feature=youtu.be 

## Bug Information

Version Number of Plugin: 2.3.5
Device Tested On: Android next 7
Simulator Tested On:
Version of VS: 2017
Version of Xamarin:
Versions of other things you are using:

### Screenshots
![image](https://user-images.githubusercontent.com/34792034/43837279-9fb6725e-9b35-11e8-8e8c-1fdb177f2b1d.png)

**Comment by rdelrosario** [comment]
This issue doesn't seem to be related to the plugin but your project. Do you have two Android application classes?

**Comment by VikasPawar2112** [comment]
No. have only one application class for android. But another application class present in main project. That's why give error at build time.

**Comment by mvangala1** [comment]
@VikasPawar2112 did you resolve this? I am facing same issue
