### ISSUE TITLE
FirebasePushNotificationManager.Initialize seems to auto-register when told not to

### ISSUE THREAD

**Issue by jameslavery** [CrossGeeks/FirebasePushNotificationPlugin#173]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:2.3.5
Device Tested On: Physical iPhone 5C (iOS 10.1.1)
Simulator Tested On: n/a
Version of VS: 7.5.4 (Mac)
Version of Xamarin: Xamarin.Forms 3.0.0.561731
Versions of other things you are using:

### Steps to reproduce the Behavior
In AppDelegate, initialize as follows:

    FirebasePushNotificationManager.Initialize(options,false);

### Expected Behavior
Push Notifications are not initialised, and the _RegisteredForRemoteNotifications_ override is not called.

### Actual Behavior
It appears that Push Notifications _are_ registered, as the _RegisteredForRemoteNotifications_ override is called.

**Note** that the reason I want to delay the registration is that I want to wait until later than the FinishedLaunching to register, so that - hopefully - the permissions dialog from iOS does not appear until later (and Calabash can auto-accept it when running UITests.

**An associated question** is that even if I do manage to delay registration, will the permissions dialog appear at app startup, because iOS is detecting that Push Notifications are used by the app from the settings in _info.plist_?

Possibly linked to #152.

**Comment by Loki606** [comment]
Hi James, the first boolean in the method arguments is for 'reset token" you should add the identifiers for clarity and try again:

FirebasePushNotificationManager.Initialize(context: this, resetToken: true, autoRegistration: false);
