### ISSUE TITLE
iOS InstanceId and Token return NULL.

### ISSUE THREAD

**Issue by tvaniseghem** [CrossGeeks/FirebasePushNotificationPlugin#174]
I have went through all of the steps and testing I can find to get the token to return but nothing is working. Initialize FirebasePushNotificaitonManager, call RegisterForPushNotifications, and have everything set up for my Apple Developer Account / Firebase Console.
For code, I currently have the below for getting the instance id and fcm token. I have tried a few other assorted bits of code found throughout various coding websites but none of them are working for me.
```
public override string InstanceId
        {
            get
            {
                //Get only the instanceId from the Token - found on StackOverflow
                string instanceId = Firebase.InstanceID.InstanceId.SharedInstance.Token.Split(':')[0];
                return instanceId;
            }
        }
```
```
        public override string MessageToken
        {
            get
            {
                string token = Firebase.InstanceID.InstanceId.SharedInstance.Token;
                return token;
            }
        }
```

Any help would be greatly appreciated. I have the Android version working but can't get iOS to even get a token.

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta
