### ISSUE TITLE
What could be a real world implementation of CrossFirebasePushNotification.Current.OnNotificationReceived?

### ISSUE THREAD

**Issue by Denny966** [CrossGeeks/FirebasePushNotificationPlugin#176]
I just followed the getting started tutorial and the android tutorial but I was wondering what an implementation would be for `CrossFirebasePushNotification.Current.OnNotificationReceived`.

There is one in `App.xaml.cs` and one in `MainApplication.cs`, but they both dont really do anything and I'm receiving the notifications without doing anything by myself. Even when my app is minimized or swiped away from the recent app list.

What could they be used for?

**Comment by novjean** [comment]
Using it in a real scenario where based on the content of the notification received triggers a certain set of actions to take place in the app.
