### ISSUE TITLE
silent notification & perform background operation once received

### ISSUE THREAD

**Issue by jaykumarthaker** [CrossGeeks/FirebasePushNotificationPlugin#178]
Hey @rdelrosario , thank you so much for this wonderful plugin!

I was inspired by your "ChatUIXForms" and had implemented the same in my App. Amazing 3 blogs I must say!

Um, I need your help here:
1) I want to send silent notification to both Andorid and iOS. To do so, I am using below payload but still it's getting displayed as Notification:

```
{
	"to" : "<device_token>",
	"data" : {
		"title" : "title",
		"message" : "message",
		"type" : "order"
	},
	"notification" : {
		"body" : "Hello world",
		"title" : "FCM Message",
		"content_available": true
	}
}
```
I want it to be slient, not showing any alert at all! How can we achieve this?

2) Once we receive this notification, I want to perform some background operation, like initiating socket connection (without user opening the notification).
So how do I achieve this? In which method should I write my socket code into?

As per the [Doc](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-techniques/updating-an-application-in-the-background#silent-remote-notifications), once we receive the notification we have 30 Sec. to download of new content, which in my case is to initiate the socket connection!

In advance, thank so much for your help.

**Comment by NPadrutt** [comment]
You send a message with a "notification" tag. AFAIK this is never a silent notification, since the system handles the notification part.

**Comment by rdelrosario** [comment]
Should be:

Payload for silent notifications in Android:

{
  "data" : {
    "title" : "notify_to_wake",
    "silent" : true
  },
  "priority" : "high",
  "registration_ids": ["token_1", "token2"]
}

Payload for silent notifications in iOS:

{
  "data" : {
    "title" : "notify_to_wake"
  },
  "notification" : {
    "content_available" : true
  },
  "priority" : "high",
  "registration_ids": ["token_1", "token2"]
}
