### ISSUE TITLE
GoogleServicesJson deserialization error.

### ISSUE THREAD

**Issue by JHunterSpok** [CrossGeeks/FirebasePushNotificationPlugin#18]
I followed Getting Started instructions to install the FirebasePushNotificationPlugin to my Xamarin Forms application for the Android platform.  

When I try to build the application, I encounter this error.

    /{app folder}/packages/Xamarin.GooglePlayServices.Basement.42.1021.1/build/MonoAndroid70/Xamarin.GooglePlayServices.Basement.targets(61,5): error : Failed to Read or Deserialize GoogleServicesJson file: google-services.json
    /{app folder}/Napa.Mobile/packages/Xamarin.GooglePlayServices.Basement.42.1021.1/build/MonoAndroid70/Xamarin.GooglePlayServices.Basement.targets(61,5): error : System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Xamarin.GooglePlayServices.Tasks.GoogleServices. Encountered an unexpected character 'ï' in JSON.

Any idea what might be causing this exception?

I've used the copy of google-services.json obtained from google for my projects and confirmed it is formed correctly.  My only guess is that perhaps something in the data fields might be confusing the deserializer.

## Bug Information

Version Number of Plugin: 1.0.4
Device Tested On: android emulator
Simulator Tested On: Nexus 6 API 22
Version of VS: VS/Mac 7.1
Version of Xamarin: 
Versions of other things you are using:

### Steps to reproduce the Behavior
Followed instructions to install plugin in Android and build.

### Expected Behavior
compiles correctly.

### Actual Behavior

build fails due to error

**Comment by rdelrosario** [comment]
What build action did you set to the json file?

**Comment by JHunterSpok** [comment]
Thank you for the quick response.

the build action was set to GoogleServicesJson

After looking at the google-services.json file with the hex editor there were a few chars at the front that included the weird ï character.  Removing these characters got past this issue and allowed the app to build.

**Comment by devology-rob** [comment]
Thanks for your comment @JHunterSpok, I had the same  ï character issue, I'm on a Mac and opened the JSON file that I downloaded from Google then copy and paste it into an existing (blank) file I created ready in the Xamarin Studio solution.  

After reading your comment I replaced the file with the one from Google (no copy and paste) and ...

IT WORKED!

Thanks for the nudge in the right direction 👏

**Comment by adamped** [comment]
Just to add more details, its a Byte Order Mark at the start of the file. You can also use Notepad++ to change from UTF8-BOM to just UTF8 and it will remove it for you, just save the file after you change the encoding.

![image](https://user-images.githubusercontent.com/13672662/52326711-b6d08000-2a3d-11e9-89ae-6ef73c2a7e5d.png)
