### ISSUE TITLE
Unhandled Exception: System.MissingException: void Firebase.Messaging.FirebaseMessaging.SubscribeToTopic(string)

### ISSUE THREAD

**Issue by xalves** [CrossGeeks/FirebasePushNotificationPlugin#180]
Hi all,

I'm developing an app, in which I will send some notifications while implementing and following the tutorial, I stumbled into this problem. I've been trying to solve it for 3 days. Some help would be appreciated.

I'm developing this application in Xamarin Forms.

**Comment by xalves** [comment]
Currently looking for ways of linking this dll.
I believe the problem relies in the .dll linking.

**Comment by BasuHuddar** [comment]
Hi Team,

Still this issue not yet fixed.

**Comment by Loki606** [comment]
I have this same issue.

**Comment by rdelrosario** [comment]
Which version are you using?

**Comment by Loki606** [comment]
Latest of everything.

**Comment by Loki606** [comment]
I also have Xamarin.Firebase.Messaging v71, which I believe is causing the issue because they have changed a lot.
