### ISSUE TITLE
no valid “aps-environment” entitlement string found for application

### ISSUE THREAD

**Issue by dev-aritra** [CrossGeeks/FirebasePushNotificationPlugin#181]
I am getting "no valid “aps-environment” entitlement string found for application" in the FailedToRegisterForRemoteNotifications callback.
And 
"Error Domain=NSCocoaErrorDomain Code=3000 \"no valid “aps-environment” entitlement string found for application\" UserInfo={NSLocalizedDescription=no valid “aps-environment” entitlement string found for application}"
on the  CrossFirebasePushNotification.Current.OnNotificationError callback.
I am receiving the token though 

while running on iOS. It runs absolutely fine on Android.

**Comment by dev-aritra** [comment]
That was a problem with the iOS provisioning profiles.

**Comment by mstein11** [comment]
Right now, I am facing the same issue! What did you change to make it work?

**Comment by dev-aritra** [comment]
> Right now, I am facing the same issue! What did you change to make it work?

@mstein11 Check few things 
1. Did you enable remote notification in info.plist?
2. Did you enable push notification in the apple developer console for this app.
3. Are you using the same signing certificate on the firebase console and in your visual studio project.

If all these are true, it should work.
