### ISSUE TITLE
Push Notificatin for iOS - not working when app is in foreground

### ISSUE THREAD

**Issue by deveshgit** [CrossGeeks/FirebasePushNotificationPlugin#183]
Hi,

I am using this plugin to send push notifications to Android & iOS devices. It's working absolutely fine with Android (for all cases either app is in foreground/background/killed). But in case of iOS, i am not getting notification when my app is in foreground. I am not sure what mistake i am doing.

Please find the notification object which i am using in case of iOS. I am testing it from postman.

URL: https://fcm.googleapis.com/fcm/send
Request body:
{
   "notification" : 
   {
    "body" : "hello",
    "title": "firebase",
    "sound": "default",
    "content_available" : true,
   },
    "to" : "eecyuESNNdM:APA91bECj-MziI56FweVA3N1SmIkNWS0wIl8vqs9oAlsGwq3jQF1VWSdngMWPWDnA3ute2brspnKqYlf5UgemSv70hBP4E3RHteDIRcLBlophzpIYKPXW3Llv2OXEb1LcPyRXXs1p1e_"
}

Response Body:
{
    "multicast_id": 8167524977131481026,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1537507680326950%b830306db830306d"
        }
    ]
}

But on device, i am not getting notification. Please let me know, how can i fix it.

**Comment by VansW** [comment]
Did you find any solution to this? I'm also not able to get it working.

**Comment by deveshigate** [comment]
> Did you find any solution to this? I'm also not able to get it working.

No, i am still waiting for a solution. Please let me know, if you find any.

**Comment by rdelrosario** [comment]
If you want to make visible the notification on foreground add priority: "high" inside a "data" key payload.

{
"notification" :
{
"body" : "hello",
"title": "firebase",
"sound": "default",
"content_available" : true,
},
"data" :{
  "priority": "high"
},
"to" : "eecyuESNNdM:APA91bECj-MziI56FweVA3N1SmIkNWS0wIl8vqs9oAlsGwq3jQF1VWSdngMWPWDnA3ute2brspnKqYlf5UgemSv70hBP4E3RHteDIRcLBlophzpIYKPXW3Llv2OXEb1LcPyRXXs1p1e_"
}

**Comment by deveshigate** [comment]
> If you want to make visible the notification on foreground add priority: "high" inside a "data" key payload.
> 
> ```json
> {
> "notification" :
> {
> "body" : "hello",
> "title": "firebase",
> "sound": "default",
> "content_available" : true,
> },
> "data" :{
>   "priority": "high"
> },
> "to" : "eecyuESNNdM:APA91bECj-MziI56FweVA3N1SmIkNWS0wIl8vqs9oAlsGwq3jQF1VWSdngMWPWDnA3ute2brspnKqYlf5UgemSv70hBP4E3RHteDIRcLBlophzpIYKPXW3Llv2OXEb1LcPyRXXs1p1e_"
> }
> ```

Thanks a lot 👍 

Will defenitely try it.

**Comment by deveshigate** [comment]
> If you want to make visible the notification on foreground add priority: "high" inside a "data" key payload.
> 
> ```json
> {
> "notification" :
> {
> "body" : "hello",
> "title": "firebase",
> "sound": "default",
> "content_available" : true,
> },
> "data" :{
>   "priority": "high"
> },
> "to" : "eecyuESNNdM:APA91bECj-MziI56FweVA3N1SmIkNWS0wIl8vqs9oAlsGwq3jQF1VWSdngMWPWDnA3ute2brspnKqYlf5UgemSv70hBP4E3RHteDIRcLBlophzpIYKPXW3Llv2OXEb1LcPyRXXs1p1e_"
> }
> ```

I tried the same, but still it's not working in iOS when app is in foreground.

**Comment by rodrigueslg** [comment]
Same here, but only on iOS 11 or lower. When I run on iOS 12 it works fine on background and foreground, but on iOS 11 or lower it works only in background.

My payload:
{
	"to": "fEB-IpiMpbM:APA91bFOamsoQQHeMg_1eiRqyrqkTuzzQHr9NxxCQYLG2ezl9NjzkENRGD55C-2Z_0iF0ue8alYZRph2PaWfZ-jG0Qnk3MlBhQUG9j565Kqmt_rycYnS7TjPGtciPPwODKpZZETQr16E",
	"notification": 
	{
		"title": "titulo do push",
		"body": "corpo da mensagem do push",
		"click_action": "FCM_PLUGIN_ACTIVITY",
		"sound": "default",
		"badge": "2",
		"content_available" : true
	},
	"data" :
	{
		"priority": "high"
	}
}

Any ideas?

**Comment by AtlasAF01** [comment]
I found this guide from Microsoft/Xamarin that helped me solve this problem.

https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/enhanced-user-notifications?tabs=macos#handling-foreground-app-notifications

Once I created the delegate as outlined, notifications were displayed in the notification center on iOS.

**Comment by deveshgit** [comment]
> I found this guide from Microsoft/Xamarin that helped me solve this problem.
> 
> https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/enhanced-user-notifications?tabs=macos#handling-foreground-app-notifications
> 
> Once I created the delegate as outlined, notifications were displayed in the notification center on iOS.

Thanks, will defenitely try it :)

**Comment by DrewBrasher** [comment]
@AtlasAF01 I'm having this same issue but I'm not sure where to add the code to my FinishedLaunching method.  I'm guessing after the FirebasePushNotificationManager stuff but I'm not sure.  Here is my current FinishedLaunching code:
```
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            Google.MobileAds.MobileAds.Configure("ad-id");

            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new Common.App());

            FirebasePushNotificationManager.Initialize(options, true);
            FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert;

            return base.FinishedLaunching(app, options);
        }
```
