### ISSUE TITLE
IOS - Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by BaqerNaqvi** [CrossGeeks/FirebasePushNotificationPlugin#184]
Version Number of Plugin: **2.3.5**
Device Tested On: **NA**
Simulator Tested On: **NA**
Version of VS: **2015 Professional**
Version of Xamarin: **4.9.0**
Versions of other things you are using:
**Xamarin.iOS 11.8.0**
### Steps to reproduce the Behavior
Install the plugin from package manager in IOS project and try to build the solution.
### Expected Behavior
Solution should be compiled without any compilation error.
### Actual Behavior
There is an error while try to compile the iOS project “Object reference not set to an instance of an object”

### Code snippet
No code written. Just add the plugin in the project.
### Screenshots
![image](https://user-images.githubusercontent.com/7815063/46423462-02051a00-c750-11e8-8de2-2b9162d1d42b.png)

**Comment by mimunoz** [comment]
Are you followed the [Getting Started] (https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/GettingStarted.md) or just you install and build the solution?
