### ISSUE TITLE
unregistered registration token (firebase ios)

### ISSUE THREAD

**Issue by Denn1Ro** [CrossGeeks/FirebasePushNotificationPlugin#186]
I would like to ask if someone could help with a problem i have. I have generated the Authentication Key (.p8). Also i have set it into the firebase console under the tab "Cloud Messaging". While i successfully completed the android push notification process, i get stuck on IOS implementation. I test the APNS with the pusher app and it works just fine. So the certificate is correct. When i use the firebase console the error for the first time is just Failed Send without any error message but mostly is "Unregistered registration token". Of course i use the token which is generated from firebase plugin and not the token from APNS.

How can i solve that issue which it haunted me for days.

Thank you!

**Comment by raymondjstone** [comment]
Any reason why you use a APNS certificate and not the key option that is also there. I use the key with no issues and it saves needing different dev and prod certificates

**Comment by DenniRo** [comment]
Hi,
I tried both. I end up with the key and it is working just fine. 
The problem for me was the automatic provision profile of the visual studio. When i use the manual option with the correct one then the problem was solved. 
Thank you for the reply.

**Comment by arvindrajachourasiya** [comment]
How you are generating token ? Can you show the code

**Comment by Denn1Ro** [comment]
Hi, 
I think this issue should be closed. I solve my issue by changing from automatic to manual provision profile. 
Thank you for your interest.
Regards
