### ISSUE TITLE
didReceiveMessage: not implemented on Mac

### ISSUE THREAD

**Issue by j-ender-garcia-us** [CrossGeeks/FirebasePushNotificationPlugin#187]
[Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

**Comment by rdelrosario** [comment]
Mac platform is not supports just iOS and Android

**Comment by j-ender-garcia-us** [comment]
Buenos días Rendy. Espero que hables español ya que no me es fácil hacerlo
en Ingles.

Primero que todo debo felicitarte porque eres MUY bueno en lo que haces.

Lo que quise decir es que mi ambiente de desarrollo es en Visual Studio for
Mac y ese warning aparece cuando mando una notificación Push a la app en
iOs/IPHONE.

La app recibe perfectamente notificaciones en Android pero no en iPhone.

Qué crees que deba ser?

**Comment by j-ender-garcia-us** [comment]
Ok.

Ya resolví.  Estaba usando uno de los Provisioning Profile que no tenía
habilitada las notificaciones push, y por ende, el compilador omite la
implementación de DidReceiveMessage
