### ISSUE TITLE
got crushed when receiving a notification while the app is open on both ios and android 

### ISSUE THREAD

**Issue by mjspk** [CrossGeeks/FirebasePushNotificationPlugin#189]
got crushed when receiving a notification while the app is open on both ios and android 
Version Number of Plugin: 2.3.5
Device Tested On Nokia 8 & iPhone 6s
Simulator Tested On: no
The version of VS: 15.6
The version of Xamarin: 3.1
Versions of other things you are using: android 8.1 & iOS 12

### Steps to reproduce the Behavior
*open the app and wait until receiving a notification
*when notification received the app crash and close immediately 
### Expected Behavior
*open the app and wait until receiving a notification
* receive a notification  and get the OnNotificationReceived event fired to handle that notification 
### Actual Behavior
*open the app and wait until receiving a notification
*when notification received the app crash and close immediately 
### Code snippet
CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                Device.BeginInvokeOnMainThread( () =>
                {
                    // my code to handle notifications
                });
            };

**Comment by rdelrosario** [comment]
To handle notifications when opened should use instead:

CrossFirebasePushNotification.Current.OnNotificationOpened += (s, p) =>
{
Device.BeginInvokeOnMainThread( () =>
{
// my code to handle notifications
});
};

You shouldn't use OnReceived to handle UI stuff.
