### ISSUE TITLE
FailedToRegisterForRemoteNotifications in IOS

### ISSUE THREAD

**Issue by shreyans-wakekar** [CrossGeeks/FirebasePushNotificationPlugin#19]
FailedToRegisterForRemoteNotifications in IOS IPhone 5s. IOS Version 10.3 and lower.

**Comment by rdelrosario** [comment]
Hi

Could you be more clear on what's your issue?

**Comment by rdelrosario** [comment]
Will close this issue since didn't get enough information, please open another with more details.
