### ISSUE TITLE
Push notifications stopped working on Xamarin.IOS

### ISSUE THREAD

**Issue by katkusmt** [CrossGeeks/FirebasePushNotificationPlugin#191]
## Bug Information

Version Number of Plugin: 2.3.0
Device Tested On: iPhone 8 iOS 12+
Version of Xamarin: 2.5.0

### Steps to reproduce the Behavior
Reinstall application completely, and turn it on.
### Expected Behavior
Requests for push notification permissions
### Actual Behavior
Does not request.
### Code snippet
Every code snippet provided (in getting started/sample) is in place (it worked fine for a year, notifications were OK). My thoughts are that it stopped working on iOS 12+. Can't be too sure, not enough devices and test cases yet, but all of them were iOS12+.

I found a fi, and it is to add this code snippet, it requests permissions:
```
UNUserNotificationCenter.Current.RequestAuthorization(UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound, (approved, err) => {
                // Handle approval
});
```

I checked the code in this repository and found that you were requesting it for iOS10+, these permissions, but since we have a deadline and it stopped working on new downloads we need to get the fix in fast. We have not changed the code in AppDelegate.cs for A LONG time, and it stopped working recently.

**Comment by jaspervanmegroot** [comment]
I think he stopped with this plugin..

**Comment by rdelrosario** [comment]
Will close this issue for now since is not using the most recent version. If occurs on last version create a new issue.
