### ISSUE TITLE
Topic Unsubscribe not working

### ISSUE THREAD

**Issue by raymondjstone** [CrossGeeks/FirebasePushNotificationPlugin#196]
## Bug Information

Version Number of Plugin: 2.3.5
Device Tested On: Android
Simulator Tested On: Android (but same issue reported to me by IOS users)
Version of VS:  2017 15.9.3 (and previous versions)
Version of Xamarin: 3.3.0.967583

### Steps to reproduce the Behavior
            foreach (string lpt in CrossFirebasePushNotification.Current.SubscribedTopics)
            {
                    CrossFirebasePushNotification.Current.Unsubscribe(lpt);
                    System.Diagnostics.Debug.WriteLine("Firebase Topic array unsubscribed: " + lpt);
            }

### Expected Behavior

Topics should be unsubscribed

### Actual Behavior

The subscribed topics list is emptied by the above code but when app is rerun all the topics previously subscribed are back in the array

 CrossFirebasePushNotification.Current.SubscribedTopics

### Code snippet

As above

### Screenshots

N/A

**Comment by djrpascu** [comment]
Did you find a resolution to this by chance? I'm seeing something similar. In my case the SubscribedTopics is showing up empty, but when sending notifications to the old topics, that were removed,

**Comment by djrpascu** [comment]
See my pull request, I think your issue is related. https://github.com/CrossGeeks/FirebasePushNotificationPlugin/pull/221

**Comment by apivovar** [comment]
same issue for me... :(( something is wrong with subscribing\unsubscribing topics in iOS!

**Comment by raymondjstone** [comment]
The workaround was I believe to move the location of the init a bit further down the chain of events

I went a bit overkill in the try/catch but this seems to work better 

        global::Xamarin.Forms.Forms.Init();
#if DEBUG
            //Xamarin.Calabash.Start();
#endif
            Xamarin.FormsMaps.Init();
         bool fbaseStarted = false;
            try
            {
                FirebasePushNotificationManager.Initialize(options, true);
                fbaseStarted = true;
            }
            catch
            { }
            LoadApplication(new App());
            if (!fbaseStarted)
            {
                try
                {
                    FirebasePushNotificationManager.Initialize(options, true);
                }
                catch { }
            }
