### ISSUE TITLE
Notification not displaying on iOS 

### ISSUE THREAD

**Issue by stavroaudi** [CrossGeeks/FirebasePushNotificationPlugin#199]
Version Number of Plugin: 2.3.5
Device Tested On: iPhone 7 Plus
Simulator Tested On: iPhone XS Max
Version of VS: 7.7.2
Xamarin Forms: 3.4.0

Steps to reproduce the Behavior
Send notification to iOS devices from Firebase console 
Send notification using Postman

Expected Behavior
Notification to appear on iOS 

Actual Behavior
iOS receives notification (AFAIK) but does not display it. Postman POST doesn't give any errors. 

I get this in the output: 

> 5.8.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

**Comment by rdelrosario** [comment]
which version of the plugin are you using?

**Comment by stavroaudi** [comment]
2.3.5

**Comment by KristofferBerge** [comment]
The IMessagingDelegate protocol defines this member: 
``` 
[ProtocolMember(IsRequired = false, IsProperty = false, IsStatic = false, Name = "DidReceiveMessage", Selector = "messaging:didReceiveMessage:", ParameterType = new[] { typeof(Messaging), typeof(RemoteMessage) }, ParameterByRef = new[] { false, false })]
```
But in the iOS project, the FirebasePushNotificationManager method `DidReceiveMessage` does not match the protocol member's signature, and is not exported. If I add an overload to this method with the same parameters and export it, I am able to receive notifications by setting a breakpoint in my code where I subscribe to the `CrossFirebasePushNotification.Current.OnNotificationReceived` event. 

```
        [Export("messaging:didReceiveMessage:")]
        public void DidReceiveMessage(Messaging messaging, RemoteMessage remoteMessage) {
            DidReceiveMessage(remoteMessage.AppData);
        }
```

However there are no visible notifications displayed on the device. I'm not sure if this is due to some other reason. Any ideas?

I also noticed that the packages used in this plugin is a bit outdated. The protocol has changed in the later version.

**Comment by Umar3x** [comment]
Hi folks,

I finally fixed this error. I got notification displayed but no vibration. Don't know why, but its not that mendatory, as notification displays well. 

For that I changed the value of FireBaseAppDelegateProxyEnabled to **_TRUE_** and I tested a lot of things in the AppDelegate.cs with a solution. 

```
<key>FirebaseAppDelegateProxyEnabled</key>
	<true/>
```
In the AppDelegate.cs : 

**Old version with bug** 


```
        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
#if DEBUG
            FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken);
#endif
#if RELEASE
		                FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken,FirebaseTokenType.Production);
#endif
        }

        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);
        }

        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
        }

        public override void OnActivated(UIApplication uiApplication)
        {
            FirebasePushNotificationManager.Connect();
            FacebookClientManager.OnActivated();
            base.OnActivated(uiApplication);

        }

        public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
        {
             FacebookClientManager.OpenUrl(app, url, options);
             return true;
        }

        public override bool OpenUrl(UIApplication application, NSUrl url, string sourceApplication, NSObject annotation)
        {
            FacebookClientManager.OpenUrl(application, url, sourceApplication, annotation);
            return true;
        }

        public override void DidEnterBackground(UIApplication application)
        {
            FirebasePushNotificationManager.Disconnect();
        }
```


**New fixed :** 

```
public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken);
        }

        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);
        }
        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
        }

        public override void OnActivated(UIApplication uiApplication)
        {
            //FirebasePushNotificationManager.Connect();
            FacebookClientManager.OnActivated();
            base.OnActivated(uiApplication);

        }

        public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
        {
             FacebookClientManager.OpenUrl(app, url, options);
             return true;
        }

        public override bool OpenUrl(UIApplication application, NSUrl url, string sourceApplication, NSObject annotation)
        {
            FacebookClientManager.OpenUrl(application, url, sourceApplication, annotation);
            return true;
        }

        //public override void DidEnterBackground(UIApplication application)
        //{
        //    // Use this method to release shared resources, save user data, invalidate timers and store the application state.
        //    // If your application supports background exection this method is called instead of WillTerminate when the user quits.
        //    FirebasePushNotificationManager.Disconnect();
        //}

```

**Comment by KristofferBerge** [comment]
@Umar3x this does not solve the issue for me. 

There is a lot of code in your comment, so please correct me if I've missed anything. But from what I see you have done four changes. Removed the calls to Connect and Disconnect, and removed the call to the deprecated overload `DidRegisterRemoteNotifications(deviceToken,FirebaseTokenType.Production);` which manually sets the APN-token and what type of token this is. 

You also set the `FirebaseAppDelegateProxyEnabled` key to `true` in `Info.plist`. What this does is enable method swizzling in obj-c so that firebase handles setting the APN-token itself. I think this means that you can also comment out the call to `FirebasePushNotificationManager.DidRegisterRemoteNotifications` in your override method. When the key is set to false, method swizzling is disabled and you have to set the APN-key manually.

I have tested changes you propose, but unfortunately I'm still getting the same error in my device log output: 
> 5.4.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

I'm not sure which parameters you are referring to in your last sentence, can you show an example?

**Comment by Umar3x** [comment]
@KristofferBerge 

Sorry to hear that. Yep you are right on everything, and I commented out the DidRegisterRemoteNotifications. Just to be sure you got every elements, I also updated to latest version 2.3.5 as I were on 2.3.0 before.

I **think I missed one important change I've made to make it work** about the notification .json. We have a PHP backend (Symfony) that handles push notification. In the Push's .json we had to add this few properties : 

`"priority":"high","content_available":true,"sound":"default"`

About my last sentence, what I meant is that there have been a major update about notification handling in latest iOS (12) that reset to default a lot of things for notifications. 

`Parameters => Notifications => YourApp. `

- I did not notice that my test iPhone had by default a notification behavior for my app that was to show notification only on LockScreen w/o sound or banner. 
- Plus you got an extra menu _"Options"_ at the bottom of this page where you can choose how to preview notifcations, that, was by default too set to _"If unlocked"_ => put it to _Always_ .

**Comment by KristofferBerge** [comment]
I'm sending test-notifications from the firebase console, so I would guess that the payload is correct. 

Ok now I understand. The notification settings for the application is as it should be. All choices are selected and show is set to always.

**Comment by KristofferBerge** [comment]
@rdelrosario Any suggestions here? This is still an issue

**Comment by vincentcastagna** [comment]
@KristofferBerge 

You still do not receive notification on iOS ? Even when app is closed, nothing received ?

**Comment by KristofferBerge** [comment]
As I explained in my previous posts, the app receives the notification, but an error is logged out in the device output. The notification never reaches my application code.

>5.8.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

**Comment by vincentcastagna** [comment]
@KristofferBerge just reviewed this conversation. One question in my mind ... do you use APNs certificate or APNs Auth key ?

**Comment by stavroaudi** [comment]
Still an issue for me. I use APNs certificate

**Comment by dertin** [comment]
What is the solution, to work in a stable way, without depending on the iOS version.?

I have the same error with:
FirebaseAppDelegateProxyEnabled: true

$ sudo idevicesyslog | grep "Firebase"
```
5.8.0 - [Firebase/Messaging][I-FCM012002] Error in application:didFailToRegisterForRemoteNotificationsWithError: no se encontr\M-C\M-3 ninguna cadena de autorizaci\M-C\M-3n \M-b\M^@\M^\aps-environment\M-b\M^@\M^] para la app

5.8.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

```

**Comment by kerbooo** [comment]
Hello all, does anybody solve this problem? Same is for me too.

**Comment by asadullahqmr** [comment]
Anyone managed to resolve this issue?
