### ISSUE TITLE
How to create Heads up when app in background?

### ISSUE THREAD

**Issue by phantanthanh1996** [CrossGeeks/FirebasePushNotificationPlugin#20]
Hello, I have a problem when use the instructions. I want to create Heads up when app in background but i don't know. I created it in foreground. Please help me!

![testimg](https://user-images.githubusercontent.com/26193725/30263723-4766ad92-9700-11e7-86ca-34e3d9ed29cc.jpg)

**Comment by rdelrosario** [comment]
At this moment the plugin doesn't support this, but you can build support by using a Custom Push Notification Handler as specified in the docs. Is this supported on all Android devices or just specific ones?

If you have any ideas on how to implement this on Android I would be glad to add some support for it on the plugin.

**Comment by rdelrosario** [comment]
Just released https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.1.3  a new version that supports setting the priority of the notification to achieve heads up. More information on about this and how to change the behaviour here:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/AndroidCustomization.md
