### ISSUE TITLE
how to use RemoveNotification

### ISSUE THREAD

**Issue by eunma** [CrossGeeks/FirebasePushNotificationPlugin#205]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:    2.3.5
Device Tested On:    Galaxy note 9 
Version of VS:    15.8.7
Version of Xamarin:   4.11.0.776 

### Code snippet

----  i send message  
 "notification": {
     "title": "hello"
    , "body": "1234"
    , "sound": "default"
    , "id": "1"
  }

---- in Xamarin
CrossFirebasePushNotification.Current.OnNotificationReceived  += (s, p) =>
{
  ... 
  // here i want to remove received PushNotification
  // but not work
  // how to use RemoveNotification
  string id = p.Data.ContainsKey("id") ?  p.Data["id"].ToString() : "";
  CrossFirebasePushNotification.Current.RemoveNotification(int.Parse(id)); 
};

**Comment by filipetavares** [comment]
I'm also facing the same problem, haven't been able to use RemoveNotification as well.

**Comment by mimunoz** [comment]
Hi, if you don't want show the icon and vibration, you should use [silent](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/723ce2731101ac8ec4e801fc9d3ad355801c8f8e/src/Plugin.FirebasePushNotification.Android/DefaultPushNotificationHandler.cs#L125) parameter in data object, like this:
`{
    "data": {
        "message" : "my_custom_value",
        "other_key" : true,
        "body":"test",
        "silent" : true
     },
     "notification": {
       "body" : "hello",
       "title": "firebase",
       "sound": "default",
        "content_available" : true
     },
     "priority": "high",
     "condition": "'general' in topics"
}`

Greetings.

**Comment by filipetavares** [comment]
Thanks for the answer, but I do want to receive the notification in full, I just want to be able to remove it from the notification bar programatically... For instance if i'm in the app and I receive a notification which updates some list, I want to press the that item on the list and have it delete the notification.

**Comment by filipetavares** [comment]
Then I would not know which notification were not read (well I would in app, but still its a bad design...). I would like to remove just the one notification that i'm targeting leaving the other notification on the notification bar for the user to eventually remember himself.

**Comment by rdelrosario** [comment]
@eunma 

Try sending the payload with a data message instead of notification:

"data": {
"title": "hello"
, "body": "1234"
, "sound": "default"
, "id": "1"
}

**Comment by kubaizi** [comment]
this is my payload
FCMessage message = new FCMessage()
                {
                    ContentAvailable = true,
                    Data = new Dictionary<string, string>
                    {
                        { "id",msg.Id.ToString() },
                        { "body",msg.MessageContent },
                        { "senderId" , msg.SenderId.ToString() },
                        { "title" , SenderDisplayName }
                    },
                    Condition = $"'{msg.ReceiverId}' in topics"
                };

and this is how i am removing it

Id = Convert.ToInt32(p.Data["id"])
CrossFirebasePushNotification.Current.RemoveNotification(id);

still not removed

**Comment by rdelrosario** [comment]
This is on android? I see you are sending the ContentAvailable not sure why if android, remove this and test again.

**Comment by filipetavares** [comment]
I've figured it out... It only works if you have a tag associated with it. In the DefaultPushNotificationHandler notification are always created with:
notificationManager.Notify(tag, notifyId, notificationBuilder.Build());
Thus I'm assuming that you can only cancel them with: 
CrossFirebasePushNotification.Current.RemoveNotification(tag, id);
