### ISSUE TITLE
[ANDROID] FirebaseMessaging: Error while parsing timestamp in GCM event 

### ISSUE THREAD

**Issue by TheAlphamerc** [CrossGeeks/FirebasePushNotificationPlugin#206]
When App is in foreground it is working fine but when app is in background state it throw error message on debug console 

## Bug Information

Version Number of Plugin: 2.3.5
Device Tested On: Xolo era Xpro
Simulator Tested On: 
Version of VS: 15.9.2
Version of Xamarin: 4.0.0

### Steps to reproduce the Behavior
Using instruction given in plugin doc
### Expected Behavior

1. Notification appear in running background , foreground and also in kill state.
On click notification it should perform desired action like open app or dissappear.

2. Notification has to be sen to specific device or to all device 

### Actual Behavior

1. fine in app foreground state but when app is in background or in kill state only notification appear in system tray but on click neither  open app nor perform any action it simply disappear from system tray

2. Some times notification is not sent to specific device by sending  FCM token in notification json.

### Notification Json
`{
    "data": {
        "message" : "Your report is ready",
        "other_key" : true,
        "body":"tornado",
          	"click_action":"message"
     },
     "notification" : {
    "body" : "You have new notification!",
    "title": "Your Report is ready",	
    "sound": "default",
          	"click_action":"request"
    
  },
     
     "priority": "high",
     "condition":"'general' in topics"

}
`
### Debug trace when notification appear

> 01-11 10:07:00.876 W/FirebaseMessaging(  341): Error while parsing timestamp in GCM event
01-11 10:07:00.876 W/FirebaseMessaging(  341): java.lang.NumberFormatException: Invalid int: "null"
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at java.lang.Integer.invalidInt(Integer.java:138)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at java.lang.Integer.parseInt(Integer.java:358)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at java.lang.Integer.parseInt(Integer.java:334)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at java.lang.Integer.valueOf(Integer.java:525)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at com.google.firebase.messaging.zzd.zzg(Unknown Source)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at com.google.firebase.iid.zzc.run(Unknown Source)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-11 10:07:00.876 W/FirebaseMessaging(  341): 	at java.lang.Thread.run(Thread.java:818)
01-11 10:07:00.878 W/FirebaseMessaging(  341): Unable to log event: analytics library is missing

### Debug Trace on notification click

> 01-11 10:19:02.316 W/FirebaseMessaging(  341): Error while parsing timestamp in GCM event
01-11 10:19:02.316 W/FirebaseMessaging(  341): java.lang.NumberFormatException: Invalid int: "null"
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at java.lang.Integer.invalidInt(Integer.java:138)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at java.lang.Integer.parseInt(Integer.java:358)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at java.lang.Integer.parseInt(Integer.java:334)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at java.lang.Integer.valueOf(Integer.java:525)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at com.google.firebase.messaging.zzd.zzh(Unknown Source)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at com.google.firebase.messaging.FirebaseMessagingService.zzo(Unknown Source)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3011)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at android.app.ActivityThread.-wrap17(ActivityThread.java)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1443)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at android.os.Looper.loop(Looper.java:148)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at android.app.ActivityThread.main(ActivityThread.java:5438)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at java.lang.reflect.Method.invoke(Native Method)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
01-11 10:19:02.316 W/FirebaseMessaging(  341): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
01-11 10:19:02.316 W/FirebaseMessaging(  341): Unable to log event: analytics library is missing

**Comment by bilalsammour** [comment]
I have the same issue

**Comment by akseli** [comment]
Running into the same issue. Any updates or workarounds to get this working? NuGet version 2.3.6 and Xamarin.Forms 4.1.0

**Comment by dertin** [comment]
Same issue

**Comment by rdelrosario** [comment]
Fixed on latest release
