### ISSUE TITLE
Show notification in a DisplayAlert Xamarin.Forms

### ISSUE THREAD

**Issue by AnthonyLatty** [CrossGeeks/FirebasePushNotificationPlugin#207]
This is more of a question rather than an issue, I was wondering can a notification be displayed in a DisplayAlert in Xamarin.Forms when it is clicked on?

**Comment by rdelrosario** [comment]
CrossFirebasePushNotification.Current.OnNotificationOpened += (s, p) =>
            {
               if (p.Data.ContainsKey("title"))
                {
                    Device.BeginInvokeOnMainThread(async () =>
                    {
                       await App.Current.MainPage.DisplayAlert("MyApp",Data["title"],"OK");
                    });

                }
             
            };

**Comment by AnthonyLatty** [comment]
`Data` does not exist in current context
