### ISSUE TITLE
Has anyone got this working ???

### ISSUE THREAD

**Issue by andrewbird1** [CrossGeeks/FirebasePushNotificationPlugin#210]
Hi Al,. Here is my issue, please help !

I have used the demo code here to drive pushes in my app which work fine.. However what doesn't work is when the app app is in the background then a message IS RECEIVED. I click on on the message and this takes me to the app  bringing it to the foreground which is fine but it restarts the main screen creating a second intent not good !

Also I noticed the pushes do not clear if received by the app and processed. 

any thoughts ?  Android 6.0

**Comment by AnthonyLatty** [comment]
Do you have `LaunchMode = LaunchMode.SingleTop` enabled in your MainActivity.cs, that suppose to solved the second intent issue.

**Comment by diseyidiffa** [comment]
It works for Android. I am having a hard time getting it to work with iOS

**Comment by raddesso** [comment]
Did you solved this issue?

**Comment by diseyidiffa** [comment]
Yes i didDiseyi DiffaVision Software LLCwww.visionsoftwareonline.comCell: 713 478 4218Fax: (972) 349-8133Email:ddiffa@visionsoftwareonline.comOn March 13, 2019 at 10:21 PM raddesso <notifications@github.com> wrote:  Did you solved this issue?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by raddesso** [comment]
Can you share what did you do to make it work?

**Comment by diseyidiffa** [comment]
What do you need help with android or ios.

**Comment by raddesso** [comment]
My problem is on ios

**Comment by diseyidiffa** [comment]
Okay. So if you followed all the instructions. 
1) Did you enable push notification on ios certificate. 
2) you also need to create a APN authentication key. This needs to be added to the firebase messaging console  under the cloud messaging tabs in your settings.

**Comment by diseyidiffa** [comment]
I dont have my mac book with me now but if you try that and it didnt work. I will take screen shots later on today.

**Comment by raddesso** [comment]
I have already done this all, the notification doesnt work only when app is forced closed. Does it work for you?

**Comment by diseyidiffa** [comment]
Yes and I have it production. I will get my steps later today.

**Comment by raddesso** [comment]
Thank you! Just to clarify my issue is thst when the app is forced closed, i receive the message notification normally but the  didreceiveremotenotification is not triggered, because of this i am not able to capture click notification event and open a specific page.

**Comment by diseyidiffa** [comment]
I got you.  I will send you my screen shots.

**Comment by diseyidiffa** [comment]
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App());

            FirebasePushNotificationManager.Initialize(options, true);
}


In my Info.plist  I added Remote Notifications

**Comment by diseyidiffa** [comment]
In Entitlement I checked Push Notifications. this was also in my certificate and like I mentioned before I added the APN key to firebase messaging.

Let me know if that help.  If not I can see about sharing my code.

**Comment by andrewbird1** [comment]
HI I do have it working perfect on IOS but Android is an issue . it looks like the older android 6.0 phones do not receive the push when the app is not running. How do you get around this as the demo shows the same problem.

When the app is running it's not an issue. I also specified the app as single task as this worked better for me in my application.
