### ISSUE TITLE
background app

### ISSUE THREAD

**Issue by angelru** [CrossGeeks/FirebasePushNotificationPlugin#214]
When my app is background, I receive the push notification but don't enters the event OnNotificationReceived, only with foreground. I am send the notification with firebase panel.

should I set something else? What am I doing wrong?

**Comment by angelru** [comment]
With api it works.

**Comment by husamdev** [comment]
Hello @angelru , what do you mean with api it works?

**Comment by angelru** [comment]
Hello @husamdev here: [https://github.com/firebase/firebase-admin-dotnet/blob/master/FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessaging.cs](url)
