### ISSUE TITLE
Feature request: is it possible to get the option to vary the name of google-services.json 

### ISSUE THREAD

**Issue by raymondjstone** [CrossGeeks/FirebasePushNotificationPlugin#217]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

For apps where the soloution can build two different types of app (in my case a staff app and a citizen app) we need to have different firebase projects to get the notifications working on each app correctly. It would be helpful if this could be done by altering the IOS and android default firebase files.

**Comment by rdelrosario** [comment]
This is not related to this library.
