### ISSUE TITLE
Can't deploy app using plugin

### ISSUE THREAD

**Issue by MartinGian** [CrossGeeks/FirebasePushNotificationPlugin#22]
Hi,

I'm using the FirebasePushNotification plugin, works fine on the Visual Studio emulator, but when I try to deploy it to my mobile (in debug mode, using Visual Studio), the following error is printed in the output and stop the deploy inmediately

`W/System.err(12717): remove failed: ENOENT (No such file or directory) : /data/user/0/com.home.xxxxxx/shared_prefs/Plugin.FirebasePushNotification.xml.bak`

I can't figure out what can be the issue, on the emulator works fine, but I can't deploy. 
BTW, I already did a clean clone of the repo, I guessed that maybe was a bak file bothering.

Do you have any clue about this issue?

Thanks in advance.

**Comment by rdelrosario** [comment]
This is on Android and iOS?

Also what version are you installing?

**Comment by MartinGian** [comment]
At the moment I'm using it on a Forms application but only for Android, and the version is 1.0.4.

**Comment by rdelrosario** [comment]
Did you try deleting it in the packages folder and restoring it again

**Comment by rdelrosario** [comment]
Also delete bin & obj folders

**Comment by fabrii** [comment]
It worked deleting bin & obj folders. Thank u very much.

**Comment by fabrii** [comment]
It seems it worked doing that!. Thank you!
