### ISSUE TITLE
Error when Initialize XAML preview

### ISSUE THREAD

**Issue by efimomax** [CrossGeeks/FirebasePushNotificationPlugin#224]
When in XAML editor try to preview XAML view throw error like "System Type Initialization Exception"

Now I cant to visual edit my XAML views ^(

## Bug Information

Version Number of Plugin: 2.35.5
Device Tested On: Simulator Tested On: 
Version of VS: 2017 Enterprise
Version of Xamarin: Xamarin Forms 3.6.0.264807
Versions of other things you are using: а lot of

### Steps to reproduce the Behavior

Just preview XAML file

**Comment by Gerben321** [comment]
Same here! Would like to see a fix because I'm now 'blindly' making my XAML...
