### ISSUE TITLE
OnNotificationOpened or OnNotificationAction not being called Android

### ISSUE THREAD

**Issue by Lukas182** [CrossGeeks/FirebasePushNotificationPlugin#228]
Hello!

The problem is only on Android.. When I click the notification , the App goes on Foreground but there is not calls on OnNotificationOpened, so I can't identify if the app is being open from there. OnNotificationRemoved & OnNotificationReceived is being called properly.

I tried to add actions to the push notifications to solve this.. If I add the actions as Default type, It properly calls OnNotificationAction and I know what I have touched but the app don't enter in Foreground.. If I changed the action type to Foreground.. the app bring to foreground when I click on the action, but the OnNotificationAction is not being called.. so I don't know what to do..

All this is working properly on iOs

I added on Android MainActivity:

FirebasePushNotificationManager.ProcessIntent(this, Intent);

#if DEBUG
            FirebasePushNotificationManager.Initialize(this,
                          new NotificationUserCategory[]
                          {
                              new NotificationUserCategory("request",new List<NotificationUserAction> {
                                new NotificationUserAction("Ver","Ver", NotificationActionType.Foreground, "check"),
                                new NotificationUserAction(" Cancelar","Cancelar", NotificationActionType.Default, "cancel")
                                })
                          }, true);
            #else
            FirebasePushNotificationManager.Initialize(this,
                          new NotificationUserCategory[]
                          {
                              new NotificationUserCategory("request",new List<NotificationUserAction> {
                                new NotificationUserAction("Ver","Ver", NotificationActionType.Foreground, "check"),
                                new NotificationUserAction(" Cancelar","Cancelar", NotificationActionType.Default, "cancel")
                                })
                          }, false);
            #endif

Dunno whats happening, could please help me?

Thanks!

**Comment by Lukas182** [comment]
My payload:

{
   "to": "device_ID",
   "data" : 
   {
      "body" : "Hhehe",
      "click_action" : "request",
      "curso" : "123"
    },
    "priority" : "high"
}

**Comment by Muhi** [comment]
add in this to your call 
"notification" : {
      "body" : "Hello world",
      "title" : "FCM Message"
    }

**Comment by amer2737** [comment]
@Lujas182 did you find solution?

**Comment by 15mgm15** [comment]
@amer2737 Did you find the solution?

**Comment by Muhi** [comment]
yes for Android you need to add this to the payload 
"notification" : {
"body" : "Some text",
"title" : "some Text"
}
