### ISSUE TITLE
IOS notifications stopped arriving after 12th April

### ISSUE THREAD

**Issue by raymondjstone** [CrossGeeks/FirebasePushNotificationPlugin#231]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

## Bug Information

Working, unchanged app, after some point on 12th IOS notifications when sent by topic ceased to work (Android still fine). May be unrelated but this was the point when GCM endpoints were finally meant to be switched off in preference to the FCM ones.

Version Number of Plugin: Current release 2.3.5
Device Tested On: 6 different IOS devices
Simulator Tested On: N/a
Version of VS: 2017 and 2019 (V8 on mac)
Version of Xamarin: 3.6
Versions of other things you are using:
v60.1142.1 of Xamarin.Firebase.Common and lid.

### Steps to reproduce the Behavior

Pre installed apps working up until some point on 12th then stopped getting any messages via topics. They can get messages when sent from the firebase console via the device id (when they were already known)

### Expected Behavior
Push notification sent by topic should arrive
### Actual Behavior
fails to arrive on IOS, works fine on Android

**Comment by raymondjstone** [comment]
Update to this.

It look slike a call to subscribe with an array of topics is not causing the subscribed topics to be updated anymore, I call it was an array of 12, it had 10 and after the call it still has 10

**Comment by js-ka** [comment]
Same thing for me.
I don't get any longer notifications via subscribed topics under IOS.
In Android it works without problems.

**Comment by js-ka** [comment]
After having subscribed a few topics the property SubscribedTopics ist still empty on iOS.

**Comment by raymondjstone** [comment]
I found this issue a while back, it ended up that moving the init code around a bit sorted it all, the example, at least the one at the time, I have not rechecked, did some stuff in an order that did not work for topics

**Comment by raymondjstone** [comment]
https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/196

**Comment by js-ka** [comment]
I call **Initialize** right after LoadApplication, but without AutoRegistration.
After the user enabled push notifications I call **RegisterForPushNotifications**.
After that subscribing for topics results in an empty list CrossFirebasePushNotification.Current.SubscribedTopics.
