### ISSUE TITLE
Not receive notifications on iOS

### ISSUE THREAD

**Issue by dertin** [CrossGeeks/FirebasePushNotificationPlugin#235]
## Bug Information

Version Number of Plugin: 2.3.6
Device Tested On: iOS 12.3.1
Version of VS: Mac 8.0.9 (build 5)
Xamarin for Mac: 5.6.0.2
Xamarin.iOS: 12.8.0.2
Xcode: 10.2.1
Operating System: Mac OS X 10.14.5

```
app.iOS(GoogleUtilities)[605] <Notice>: 5.8.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.

app.iOS(GoogleUtilities)[605] <Notice>: 5.8.0 - [Firebase/Core][I-COR000022] Firebase Analytics is not available. To add it, include Firebase/Core in the Podfile or add FirebaseAnalytics.framework to the Link Build Phase
```
AND ( #199 )
```
5.8.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented
```

Any idea why these errors occur?
Do these errors prevent me from receiving notifications on iOS? What is the solution, in which I fix? I followed the instructions in a new project and did not find a solution.

Thank you

**Comment by mimunoz** [comment]
Hi, are you Enable background Modes and your provisioning profile have Push Notifications? this error happens when you are not provisioning with push notifications, then your app don't know what to do when notification arrive.

**Comment by dertin** [comment]
@mimunoz It is correct, using automatic provisioning was not possible. I had to configure it in manual. I also had several problems with the .csproj file, where I had duplicate properties. But in the end it worked. Greetings, have a good day.

**Comment by kerbooo** [comment]
Hello all, does anybody solve this problem? Same is for me too.
