### ISSUE TITLE
Push Notification Icon in Background Mode

### ISSUE THREAD

**Issue by kingbogdan84** [CrossGeeks/FirebasePushNotificationPlugin#237]
Hi.

When using your Plugin in my Xamarin Android App, when the application is running in foreground, the icon set with **FirebasePushNotificationManager.IconResource** works fine and it's displaying the correct notification icon that I set.

But when the app is not running or is in background mode, the icon that it's being displayed is the gray square, (which in this case is the application icon not the notification icon)

Am I missing something, or is this a BUG in your Plugin?

protected override void OnCreate(Bundle bundle)
{
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;
            base.OnCreate(bundle);
            Rg.Plugins.Popup.Popup.Init(this, bundle);
            global::Xamarin.Forms.Forms.Init(this, bundle);
            Xamarin.FormsGoogleMaps.Init(this, bundle);
            CrossCurrentActivity.Current.Init(this, bundle);
            Xamarians.GPS.Droid.GPSServiceAndroid.Initialize(this);
            Plugin.InputKit.Platforms.Droid.Config.Init(this, bundle);
            
            LoadApplication(new App());

            FirebasePushNotificationManager.Color = Android.Graphics.Color.Rgb(239, 51, 64);
            FirebasePushNotificationManager.IconResource = Resource.Drawable.icon;
            FirebasePushNotificationManager.ProcessIntent(this, Intent);
}

**Comment by mimunoz** [comment]
Hi,
I solved with [this](https://stackoverflow.com/a/29207365/5373838) answer in stackoverflow.

Regards!

**Comment by rdelrosario** [comment]
You need to set this on the Application class not on the MainActivity since it only exist when application is opened.

**Comment by Nadezhda-Popova** [comment]
I have the same problem, when application is on foreground the FirebasePushNotificationManager.IconResource is used, when it is on background it uses the application icon. I set it in MainApplication class

**Comment by mimunoz** [comment]
@Nadezhda-Popova just cut your code and put it in Main Application class. If you don't have an Main Application class, you can see it [here](https://github.com/jamesmontemagno/CurrentActivityPlugin) how create.

Regards!

**Comment by Nadezhda-Popova** [comment]
@mimunoz the definition is in MainApplication class
`public override void OnCreate()
        {
            base.OnCreate();
            RegisterActivityLifecycleCallbacks(this);
            //A great place to initialize Xamarin.Insights and Dependency Services!
            CrossCurrentActivity.Current.Init(this);

            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                FirebasePushNotificationManager.DefaultNotificationChannelId = "FirebasePushNotificationChannel";

                //Change for your default notification channel name here
                FirebasePushNotificationManager.DefaultNotificationChannelName = "General";
            }

          

            //If debug you should reset the token each time.
#if DEBUG
            FirebasePushNotificationManager.Initialize(this, true);
#else
              FirebasePushNotificationManager.Initialize(this,false);
#endif
            FirebasePushNotificationManager.IconResource = Droid.Resource.Mipmap.ic_stat_ic_notification;

            //Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {

                System.Diagnostics.Debug.WriteLine("NOTIFICATION RECEIVED", p.Data);
            };
        }`

**Comment by Nadezhda-Popova** [comment]
Any update on this? @mimunoz what I do wrong or is it an issue with the plugin? Thank you!
