### ISSUE TITLE
DidReceiveRemoteNotification not called

### ISSUE THREAD

**Issue by GO74** [CrossGeeks/FirebasePushNotificationPlugin#239]
Hi, I can receive notifications in iOS, but for some reason "DidReceiveRemoteNotification" is never called. I tested with App in forground and in background - no luck. I check with testproject and I've implemented it 1:1. In Android it's working - no problem.
In the console I can see my message coming in - how can I get my hands on it? Any ideas what I could check?
I'm working with FirebasePushNotification 2.3.6

**Comment by mimunoz** [comment]
Hi, are you check this #235 ?

**Comment by GO74** [comment]
I checked again. Background is active and remotenotifications are ticked. I'm using automatic mode for the provisioning profile.

**Comment by rvhamed** [comment]
In my case, I used this deprecated method and it is worked for me.
`override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any])`

**Comment by GO74** [comment]
> 
> 
> In my case, I used this deprecated method and it is worked for me.
> `override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any])`

Using a depricated method can't be the solution. Is this project dead?
