### ISSUE TITLE
FireBase Token only generating first time.  

### ISSUE THREAD

**Issue by varun13487** [CrossGeeks/FirebasePushNotificationPlugin#24]
I am using the plugin for xamarin forms. I am getting the firebase token first time I launch the app in Debug mode. But after that whenever I debug the application without uninstalling. I don't receive any error.

**CrossFirebasePushNotification.Current.Token**  gives me null every time then it goes for 

` CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine($"TOKEN : {p.Token}");
                App.firebaseRegToken = p.Token;
            }
`
And it doesn't come in the event handler.
I have tried even with production environment same thing happens there. 
Double checked the certificates on Firebase console also. 
Do you have any idea why this could be happening ? 

## Bug Information

Version Number of Plugin:
Device Tested On: iOS 10.3.1 iPhone 5
Simulator Tested On:
Version of VS:  7.0.1(build 24)
Version of Xamarin: 2.3.4.270
Versions of other things you are using: iOS 10.3.1 iPhone 5

**Comment by rdelrosario** [comment]
How are you initializing the plugin?

Is this on Debug? If on debug and Android you should specify to reset token each time as the docs says.

Android or iOS?

**Comment by varun13487** [comment]
Its is happening in iOS only. Android is working fine. I have mentioned it in Bug information

**Comment by rdelrosario** [comment]
On iOS you only receive token once registered or if token refreshes at some point, but is only received once so you should persist it on:

CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) => { System.Diagnostics.Debug.WriteLine($"TOKEN : {p.Token}"); App.firebaseRegToken = p.Token; }

**Comment by varun13487** [comment]
ok Thanks for info! Can you please add this in the docs ?

**Comment by rdelrosario** [comment]
Sure will do!

**Comment by varun13487** [comment]
One more question : So i am storing the first generated token for ios and wll hen provide it to the server. But How i will know that token requires refresh because when the **token refresh** event is called it doesn't respond  when the token doesn't need refresh.
To summarise how i will update my persisted token. Because the event doesn't respond when it does not require a refresh.
How will I know to refresh is required ?

**Comment by rdelrosario** [comment]
You should always update your persisted version whenever token refresh event is triggered

**Comment by varun13487** [comment]
Oh I forgot the event handler. Thanks! I am closing the bug.
