### ISSUE TITLE
Not able to do the manual registration using RegisterForPushNotifications method.

### ISSUE THREAD

**Issue by shubhambhosale** [CrossGeeks/FirebasePushNotificationPlugin#241]
I want to request the registration token manually when I am logging into the my app, but I am not able to it.

## Bug Information
I am running app in Release mode.
I have disable the auto registration as well as refresh token by using below method. 
`FirebasePushNotificationManager.Initialize(this,` false, true, false);`

To Refresh the token I am using the below method:
`CrossFirebasePushNotification.Current.RegisterForPushNotifications();`

Refresh token method:.
` CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>{
}`

This not fired when I am calling the RegisterForPushNotifications() method.

**Comment by mimunoz** [comment]
Hi, 
one strategy to do this (I made it), is save the token until the log-in will be correct  and then associate the device token to the user. In the case of log-off you should disassociate this token from the user. The generation of the token from Firebase it's not on demand with this plugin (I tried it).

Regards!

**Comment by akseli** [comment]
Any updates on this issue? We have currently implemented a solution similar to @mimunoz, but it would be great if we could present the user with some extra information about enabling notifications before they are actually prompted to grant permissions.

**Comment by shubhambhosale** [comment]
Sorry for late reply. I have already implemented the solution same as proposed by @mimunoz.
