### ISSUE TITLE
Token expires when the app is closed (Android)

### ISSUE THREAD

**Issue by walter1978** [CrossGeeks/FirebasePushNotificationPlugin#244]
After the user closes the application, notifications are not received anymore, it seems the token expires, Firebase is returning the following error code in my service:  registration-token-not-registered

`Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "UNREGISTERED"
      }
    ]
  }
}`

I see this error in Android logs:
GCM broadcast intent callback: result=CANCELLED

## Bug Information

Version Number of Plugin: 2.3.6
Device Tested On: Samsung S7 - Android 8
Simulator Tested On:
Version of VS: 15.9.2
Version of Xamarin: 3.4.0.1009999

**Comment by mimunoz** [comment]
+1. I'm facing the same issue in Android @rdelrosario. Debugging I found the Firebase.Instance is null when app is in background. I made a little trick, when app is reopen I send  message (MessagingCenter) to check if the instance is null and set to new instance again and get the token to register in my backend.

**Comment by walter1978** [comment]
I see this error in Android logs:
GCM broadcast intent callback: result=CANCELLED

**Comment by walter1978** [comment]
I found that if I deploy the application in RELEASE mode, notifications are always received
