### ISSUE TITLE
iOS Native linking failed

### ISSUE THREAD

**Issue by mheydecke** [CrossGeeks/FirebasePushNotificationPlugin#245]
I am not able to get the plugin to run on iOS. It is working well in my Android Project. I get the following build error. Maybe I missed some configuration, but I followd the getting started guide.

## Bug Information

Version Number of Plugin: 2.3.6
Simulator Tested On: iOS Simulator
Version of VS: VS Professional 2019
Version of Xamarin: 4.0.0.425677

### Steps to reproduce the Behavior

1. Create Xamarin Forms Project
2. Install FirebasePushNotification package on all projects
3. Follow Getting Started Guide
4. Run Debug Config on iOS Simulator

### Actual Behavior
Build Failed

### Output
3>  App1.iOS -> C:\Users\MH\source\repos\App1\App1\App1.iOS\bin\iPhoneSimulator\Debug\App1.iOS.exe
3>  Detected signing identity:
3>    Bundle Id: com.companyname.App1
3>    App Id: com.companyname.App1
3>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/martin/Library/Caches/Xamarin/mtbs/builds/App1.iOS/de81a7b852ce64b5acf94d1823606fec/obj/iPhoneSimulator/Debug/response-file.rsp --gcc_flags=-ObjC 
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(797,3): error : linker command failed with exit code 1 (use -v to see invocation)
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(797,3): error MT5210: Native linking failed, undefined symbol: _FIRLogBasic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(797,3): error MT5211: Native linking failed, undefined Objective-C class: FIROptions. The symbol '_OBJC_CLASS_$_FIROptions' could not be found in any of the libraries or frameworks linked with your application.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(797,3): error MT5211: Native linking failed, undefined Objective-C class: GULAppEnvironmentUtil. The symbol '_OBJC_CLASS_$_GULAppEnvironmentUtil' could not be found in any of the libraries or frameworks linked with your application.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(797,3): error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(797,3): error MT5202: Native linking failed. Please review the build log.

**Comment by idchlife** [comment]
@mheydecke how did you solve it?
