### ISSUE TITLE
Foreground app notification in tray android

### ISSUE THREAD

**Issue by ruhanijeb** [CrossGeeks/FirebasePushNotificationPlugin#246]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

When my app is in foreground i am recieving the notification in notification trray.

Version Number of Plugin:2.3.6
Device Tested On: Emulator Nexus5X
Simulator Tested On:
Version of VS:  2019
Version of Xamarin: 16.1.0.545
Versions of other things you are using: 
Xamarin Forms: 4.0.0425677

### Steps to reproduce the Behavior
Create a shell app from xamarin forms template and add the things as per documentation.
When my app is in foreground i am recieving the notification in notification trray.

### Expected Behavior

When my app is in foreground it should not be reflrect in notification tray.

**Comment by angelru** [comment]
The same issue here, any solution? always show notification
