### ISSUE TITLE
Data push notification when iOS App is killed

### ISSUE THREAD

**Issue by Freddyvdh** [CrossGeeks/FirebasePushNotificationPlugin#247]
Hi,

I'm using the push notifications for Android and iOS. Android is working fine, even if the app is in foreground/background/killed.
The iOS app is working fine if it is in foreground/background, but not if it has been killed. Is there any chance to get a callback of a data push notification on a iOS device, after the app has been killed?

Thanks
Freddy

**Comment by rubiktubik** [comment]
I have the same problem!

When the app is killed and a notification arrive. This method is called correctly:
```cs
public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
            System.Console.WriteLine(userInfo);
            completionHandler(UIBackgroundFetchResult.NewData);
        }
```

As far that i'am understand, the call to  `FirebasePushNotificationManager.DidReceiveMessage(userInfo);` should trigger the events right?

But this is not happening on iOS!

**Comment by 15mgm15** [comment]
@rubiktubik Did you find a workaround?
