### ISSUE TITLE
Token and Microsoft AppCenter Push

### ISSUE THREAD

**Issue by chrisparkeronline** [CrossGeeks/FirebasePushNotificationPlugin#248]
I'm not sure if this is a bug or by design but the "CrossFirebasePushNotification.Current.OnTokenRefresh" is never fired in Xamarin Forms project when using Microsoft AppCenter Push nuget package and functionality. Removing the package and initialization type code, and "CrossFirebasePushNotification.Current.OnTokenRefresh" fires.

## Bug Information

Version Number of Plugin: 2.3.6
Device Tested On: Android Pixel XL & iPhone 7 Plus
Simulator Tested On: N/A
Version of VS: 2019
Version of Xamarin:  3.6.0.344457
Versions of other things you are using:

### Steps to reproduce the Behavior

1.  Include Microsoft.AppCenter.Push nuget in projects

2. Use typeof( Push ) in the AppCenter.Start() method.

### Expected Behavior
I'm not sure if both can work together or not.

**Comment by rdelrosario** [comment]
These plugins shouldn't be used together.

**Comment by chrisparkeronline** [comment]
Thank you for clearing this up for me.
