### ISSUE TITLE
MainActivity Being Duplicated

### ISSUE THREAD

**Issue by clifzero** [CrossGeeks/FirebasePushNotificationPlugin#249]
## Bug Information

Version Number of Plugin: **1.3.0**
Device Tested On: **Huawei P8 Lite Android Version 6.0**
Simulator Tested On: **NA**
Version of VS: **Visual Studio 2019**
Version of Xamarin: **3.4.0.1009999**
Versions of other things you are using:
```
 <PackageReference Include="FluentValidation" Version="7.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.1" />
    <PackageReference Include="Plugin.Share" Version="7.1.1" />
    <PackageReference Include="Prism.Core" Version="6.3.0" />
    <PackageReference Include="Prism.Forms" Version="6.3.0" />
    <PackageReference Include="Prism.Unity.Forms" Version="6.3.0" />
    <PackageReference Include="Rg.Plugins.Popup" Version="1.1.4.158-pre" />
    <PackageReference Include="Xam.Plugins.Settings" Version="3.1.1" />
    <PackageReference Include="Xamarin.Forms" Version="3.4.0.1009999" />
    <PackageReference Include="ZXing.Net.Mobile" Version="2.3.2" />
    <PackageReference Include="ZXing.Net.Mobile.Forms" Version="2.3.2" />
    <PackageReference Include="Unity" Version="4.0.1" />
    <PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.4.4.859" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.4.859" />
    <PackageReference Include="XamEffects" Version="1.5.0" />
    <PackageReference Include="libphonenumber-csharp" Version="8.9.13" />
    <PackageReference Include="Syncfusion.Xamarin.SfRating" Version="16.4.0.42" />
    <PackageReference Include="Syncfusion.Licensing" Version="16.4.0.42" />
    <PackageReference Include="Xamarin.Build.Download" Version="0.4.11" />
    <PackageReference Include="Syncfusion.Xamarin.Buttons" Version="16.4.0.42" />
    <PackageReference Include="Plugin.PushNotification" Version="1.3.0" />
```

### Expected Behavior
I expected the MainActivity to be launched in SingleTop mode once a user taps on the notification.

### Actual Behavior
After sending the notification while the application is in the background I tao on the notification and the application opens as expected. I

 have some code that runs when a notification is received and the application is in the Foreground, which I implemented in the CrossPushNotification.Current.OnNotificationReceived method in my App.xaml.cs(seeing that this event is not fired when the application is in the background). 

The problem I'm having is the CrossPushNotification.Current.OnNotificationReceived in my App.xaml.cs is fired twice after following the steps above.

### Code snippet
**This is the method in my App.xaml.cs file being fired twice.**
**If anymore code is required from somewhere else, I will provide it accordingly.**

```
CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                var notificationData = p.Data;
                bool hasValue = notificationData.TryGetValue(NotificationDataKeys.NotificationIntentNameKey, out object notificationIntentName);
                if (ApplicationStateCache.ApplicationIsInForeground && hasValue && $"{notificationIntentName}" is "confirm_debit")
                {
                    notificationData.TryGetValue(ConfirmPurchaseNotificationDataKeys.CardNumberKey, out object cardNumber);
                    notificationData.TryGetValue(ConfirmPurchaseNotificationDataKeys.LoadAmountKey, out object loadAmount);
                    notificationData.TryGetValue(ConfirmPurchaseNotificationDataKeys.NotificationDescriptionKey, out object notificationDescription);
                    LoyaltyworxSale loyaltyworxSale = new LoyaltyworxSale($"{cardNumber}", Convert.ToDecimal(loadAmount), $"{notificationDescription}");
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        ConfirmCardDebit(loyaltyworxSale.CardNumber, $"{loyaltyworxSale.LoadAmount}", loyaltyworxSale.LoyaltyWorxSaleDescription);
                    });
                }
            };
```

**Comment by Cliffy786** [comment]
Hi 

This might be of some assistance, I managed to replicate the exact same issue on the sample project as well, which gives me the impression that its perhaps a problem within the library.

**Comment by haxor211** [comment]
Im trying to open different page than mainpage in onnotificationopened and the page opens for a few seconds and goes back to the main one from before giving me duplicate activity in the background so I guess its a same thing.

Im doing MainPage = new NavigationPage(new Messages());

**Comment by Chasyl** [comment]
@haxor211 
Hi,
Did you manage to solve the issue? (in OnNotificationOpened the page opens for a few seconds and goes back to the main one from before)

**Comment by clifzero** [comment]
Apologies for the very delayed response but the solution to this can be found [here](https://stackoverflow.com/questions/57199493/firebase-cross-platform-push-notification-plugin-duplicating-mainactivity), if anyone is interested. 

In summary, the issue was occurring because my notification payload had a "notification" object, in the end, we had to determine on the backend whether a user is on iOS or Android and send a notification payload to firebase with or without the notification object based on the latter.
