### ISSUE TITLE
Token unregistered - Android

### ISSUE THREAD

**Issue by claudiocleberson** [CrossGeeks/FirebasePushNotificationPlugin#25]
Hi @rdelrosario, 

I'm having an issue with my Android App. When I deploy the app to the device, All seems work perfectly, the App refresh a new token if in Debug or Release. but for some reason when I try to send a PNS to that token. I'm getting token Unregistered. Do you know any reason why would that happened.

I reviewed the setup. The one thing that I am doing differently from your sample is starting the app with a Custom handler.  I tried already delete Obj/Bin, uninstall the app, install again (it was working later on), but now nothing.

Debug:
FirebasePushNotificationManager.Initialize(this, new CustomPushHandler(), true)
Release:
FirebasePushNotificationManager.Initialize(this, new CustomPushHandler(), false)

Thanks,

**Comment by rdelrosario** [comment]
When you are doing this tests is in debug or release?

**Comment by claudiocleberson** [comment]
I tried in Debug and Release. and the same happens.

**Comment by claudiocleberson** [comment]
I figured out the problem. That was the AndroidManifest.xml. For some reason another tag was messing with the Firebase receiver. thanks once more.
