### ISSUE TITLE
App crashing on launch after updating Google play service new packages

### ISSUE THREAD

**Issue by SagarPanwala** [CrossGeeks/FirebasePushNotificationPlugin#251]
## Bug Information

Version Number of Plugin: 2.3.6
Device Tested On: 
Simulator Tested On: iOS X
Version of VS: 2019 for Mac
Version of Xamarin: Version 8.2 (build 1105)
Versions of other things you are using:

### Steps to reproduce the Behavior
- Update version of Google Playservice to 71.1610.0
- Add plugin latest version

### Expected Behavior
- App should not crash

### Actual Behavior
- App crash with below log
https://gist.github.com/SagarPanwala/f1fe492a7238c4b5eacc27c1bed8b2d0

### Code snippet

> if (Settings.NotificationEnabled) {
				CrossFirebasePushNotification.Current.Subscribe("general");
			} else {
				CrossFirebasePushNotification.Current.Unsubscribe("general");
			}

**Comment by Flokri** [comment]
I get the same error. Does there exist any workaround? I really need these notifications to work again...

**Comment by mabdollahiasl** [comment]
I get the same error too :(.

**Comment by RichardSV15** [comment]
I was getting the same error too.  My workout was to use Xamarin.Firebase.Messagign version: 71.1502.0-preview2 which installs the a previous version of Google Playservice

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta
