### ISSUE TITLE
Android multiple push notification

### ISSUE THREAD

**Issue by Lukas182** [CrossGeeks/FirebasePushNotificationPlugin#256]
Is there any way to save all notifications on Android Notification Center instead of only the last one?

Thanks!

**Comment by Lukas182** [comment]
Solved

You need to add the key "id" on FIREBASE payload with a new id every time you send a push.

You can close the issue!

Thanks :)

**Comment by askinadze** [comment]
When I use 
`notificationManager.Notify(pushCounter, notificationBuilder.Build());`
I am able to add multiple push messages to the notification center.
If I add 3 messages with the ids: 1,2,3 for example, then after tapping on the push with id=3 the app always opens only the push message with id=1 (it opens always the oldest push message instead the message that has been tapped). After tapping then on the other both push messages nothing happens.
