### ISSUE TITLE
Notifications not displaying on iOS

### ISSUE THREAD

**Issue by stavroaudi** [CrossGeeks/FirebasePushNotificationPlugin#259]
This issue still hasn't been fixed for me so I will try again. 

I have my provisioning profiles configured and enabled push notifications in Info.plist

Version Number of Plugin: 2.3.6
Device Tested On: iPhone 7 Plus
Simulator Tested On: iPhone XS Max
Version of VS: 7.7.2
Xamarin Forms: 4.0.0

Steps to reproduce the Behavior
Send notification to iOS devices from Firebase console
Send notification using Postman

Expected Behavior
Notification to appear on iOS

Actual Behavior
iOS receives notification (AFAIK) but does not display it. Postman POST doesn't give any errors.

I get this in the output:

5.8.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

@rdelrosario please help on this. Been stuck on it for a long time now. It used to work before, but after updates on iOS and Xamarin.Forms, it has stopped with this error.

**Comment by asafgo** [comment]
Try this plugin
https://www.nuget.org/packages/Birdie.Plugin.FirebasePushNotification/

It is a fork with version 2.3.7

**Comment by mimunoz** [comment]
Have you set the "APNs Auth Key" in Firebase?

**Comment by stavroaudi** [comment]
Yes, I’ve uploaded the .p8 auth key in Firebase

Thanks @asafgo I will try that. I hope it solves my issue!

**Comment by asafgo** [comment]
Also set a break point at FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error); in AppDelegate.cs and check if error is popup, if yes with "no valid “aps-environment” entitlement string found for application" than it is a provisioning profile problem that needs to be created specific to the app.

**Comment by stavroaudi** [comment]
@asafgo I updated to Birdie.Plugin.FirebasePushNotification and I still get the same problem with the same error. 

I set a breakpoint at             FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);
but it doesn't stop at that breakpoint, so it doesn't get called. 

My notification payload: 
`{
  "to" : "MY_TOKEN",
  "priority": "high",
  "mutable_content": true,
  "content_available": true,
  "sound":"chime.aiff",
  "badge": 1,
  "notification": {
    "title": "my title",
    "body" : "Success"
  },
  "data": {
    "Type" : "A1",
    "AppNumber" : "j72hd14ea2",
    "Status" : "Success",
    "PNum" : "55085384",
    "Name" : "Test Notification"
  }
}`

**Comment by mimunoz** [comment]
In the [Docs](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FirebaseNotifications.md) you can see what is the payload to show notification in the iOS:

`{
    "data": {
        "message" : "my_custom_value",
        "other_key" : true,
        "body":"test"
     },
     "notification": {
       "body" : "hello",
       "title": "firebase",
       "sound": "default",
        "content_available" : true
     },
     "priority": "high",
     "condition": "'general' in topics"
}`

As you can check, your notification object it's missing some fields.

Regards

**Comment by asafgo** [comment]
Try to use Firebase Admin SDK instead of REST API.
https://firebase.google.com/docs/admin/setup/

Here is an example code using Windows Forms that works at my side for both Android & iOS

private async void button1_Click(object sender, EventArgs e)
        {
            //SETUP
            //https://firebase.google.com/docs/admin/setup/
           
            FirebaseApp.Create(new AppOptions()
            {
                Credential = GoogleCredential.FromFile(@"your json key from FireBase")
            });

            //Send Push
            //https://firebase.google.com/docs/cloud-messaging/send-message
            
            var registrationToken = "your device token - d7pnv48jvnE:APA91bGkAX6B...";

            // See documentation on defining a message payload.
            //https://firebase.google.com/docs/reference/admin/node/admin.messaging

            var message = new FirebaseAdmin.Messaging.Message()
            {
                Android = new FirebaseAdmin.Messaging.AndroidConfig()
                {
                    Notification = new FirebaseAdmin.Messaging.AndroidNotification()
                    {
                        ChannelId = "YourChannelID"
                    }
                },
                Notification = new FirebaseAdmin.Messaging.Notification()
                {
                    Title = "Test Test",
                    Body = "This is some test"
                },
                Data = new Dictionary<string, string>()
                {
                    { "score", "850" },
                    { "time", "2:45" }
                },
                Token = registrationToken,
            };

            // Send a message to the device corresponding to the provided registration token.
            string response = await FirebaseAdmin.Messaging.FirebaseMessaging.DefaultInstance.SendAsync(message);
            // Response is a message ID string.
            Console.WriteLine("Successfully sent message: " + response);
        }

**Comment by asafgo** [comment]
What is the iOS version installed on your iPhone 7 Plus?
Is it iOS 13?

**Comment by stavroaudi** [comment]
@mimunoz my payload doesn't look any different. Either way I tried exactly like the Docs and it still doesn't work. I still get:

 5.8.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

@asafgo Yes it's iOS 13, but the simulator is on 12.1 (I'm testing on both)

**Comment by stavroaudi** [comment]
I've:

- Create a key with APNs enabled
- uploaded my APNs Auth Key to Firebase
- created an Ad Hoc as well as an App Store profile, both of which include my iOS Distribution certificate
- created an APNs development iOS as well as Apple Push Services certificates. 
- Manually set the iOS bundle signing identity to Distribution: MY_COMPANY (MY_APP_ID)
- Provisioning profile to Ad Hoc on debug (tried development profile before) and App Store on release. 
- Custom Entitlements: Entitlements.plist on debug, no custom entitlements on Release (error wouldn't allow me to deploy on my device)

Am I doing something wrong or missing something?

**Comment by mimunoz** [comment]
- In the emulator won't work(I tried), work only in real device. 

- Entitlements need configured as dev(APS Environment = development) and prod(APS Environment = production)

- You need get the UUID(by iTunes) of your iPhone 7+ and register as a new device in the developer portal, the generate a new provisioning profile adding this device. Finally download and install(click to open) the prov_profile

- Sign app manually with that prov_file

**Comment by stavroaudi** [comment]
Yes I also figured that notifications don’t work on the simulator.

I’ve configured the entitlements.plist correctly, I’ve also added it to custom entitlements and tested it, but still the same issue. 

I’ve registered my device. The app works on my device but notifications don’t. 

Everything you’ve mentioned I have done before.

**Comment by mimunoz** [comment]
I see, if you have done all the steps, the only way to get this error is because provisional profile. If has not configured with notifications and info.plist [x]Enable Background modes, [x] Remote Notifications, your app don't know how management that throws the error.

**Comment by stavroaudi** [comment]
I have also enabled that. Forgot to mention it too. It’s such a hit and miss with this plugin. I’ve had this error 3 times over the last year, only managed to fix it once but I don’t remember what I did, and my laptop got stolen very recently so I cannot backtrack. 

If my provisioning profile wasn’t set up correctly, surely I wouldn’t be able to run the app on my physical device?

Stavro

**Comment by mimunoz** [comment]
- If my provisioning profile wasn’t set up correctly, surely I wouldn’t be able to run the app on my physical device? A: **Yes**. That was an issue that I've in the past. You could try delete or generate another prov_profile.

Also you will check your GoogleServices-Info.plist anyway. 

I forgot mention, the Entitlements are two files if you has been using the custom. Selected by environment(Debug[Release]/device[Emulator]) in iOS bundle signing.

**Comment by stavroaudi** [comment]
When I try to add custom entitlements to bundle signing, I get this error: 

Your code signing/provisioning profiles are not correctly configured. Probably you have an entitlement not supported by your current provisioning profile, or your device is not part of the current provisioning profile. Please check the iOS Device Log for details (error: 0xe8008016).

This happens when I add Entitlements.plist to my custom entitlements. But it should work?

**Comment by stavroaudi** [comment]
![export](https://user-images.githubusercontent.com/31539911/67015876-84604200-f0f7-11e9-8355-8797745ec5cb.png)

And in my entitlements.plist I have only enabled Keychain and Push Notifications

**Comment by stavroaudi** [comment]
![Screen Shot 2019-10-17 at 16 14 10](https://user-images.githubusercontent.com/31539911/67016880-33514d80-f0f9-11e9-9974-f3512aaeb3d9.png)

I don't see push notifications in entitlements when I try to sign and distribute the app, but I have it enabled everywhere.

**Comment by stavroaudi** [comment]
Might be worth noting that I just checked my app, and I have received the data in the payload from the notification, but the notification never appeared. (I always have the app in the background when testing notifications in case they only work in background)

**Comment by mimunoz** [comment]
Well, as I commented before, your **notification** object it's not complete as it's in the docs, you just have **title** and **body**.

![image](https://user-images.githubusercontent.com/8498224/67024199-633d2880-f0da-11e9-960b-89a4e05dc0fd.png)

**Comment by asafgo** [comment]
Looks like there is a new plugin here
https://github.com/CrossGeeks/PushNotificationPlugin
Maybe you can try it.

**Comment by kerbooo** [comment]
Hello all, does anybody solve this problem? Same is for me too.
