### ISSUE TITLE
Notification click not working when application is in background/killed

### ISSUE THREAD

**Issue by patchimou** [CrossGeeks/FirebasePushNotificationPlugin#26]
First of all, great plugin and nice work !

When my application is in background or killed, i receive the notification, but when i click on it in the notification drawer, nothing happen. I did as you suggested, initialized the manager in the Application OnCreate(). The OnNotificationReceived in the application is not fired when the app is killed.
I tried to specify a click_action on the notification and add a filter in the manifest but it doesn't work.

Do you have an idea how to open the app, so i can handle the action properly ?

**Comment by patchimou** [comment]
I managed to make it work.

I just noticed that i sent notifications with a _click_action_, that's why nothing happened.

I discovered that if you want to use multiple _click_action_ with multiple activities, add `[IntentFilter(new[] { "CLICK_ACTION_NAME"}, Categories = new[] { Intent.CategoryDefault })]` in the activity class you want to start.

**Comment by VinoliyaPrincy** [comment]
Notification click not working when application is in background
