### ISSUE TITLE
Missing method implementation on X.F.M. v 71

### ISSUE THREAD

**Issue by obrocki-fortem** [CrossGeeks/FirebasePushNotificationPlugin#261]
Version Number of Plugin:2.3.6
Device Tested On: Android 7.1, 8, 9.
Simulator Tested On: only physical devices
Version of VS: 16.3.7
Version of Xamarin:16.3.0.277
Versions of other things you are using:
**Xamarin.Firebase.Messaging v71.1740.0**
**Xamarin.Forms v4.3.0.9**
**Android platform packages v28.0.0**

CrossFirebasePushNotification.Current.Subscribe throws missing method exception.

**Comment by obrocki-fortem** [comment]
Duplicate of #251

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta
