### ISSUE TITLE
PushNotificationPlugin or FirebasePushNotificationPlugin

### ISSUE THREAD

**Issue by rubenc57** [CrossGeeks/FirebasePushNotificationPlugin#262]
Hello

I'm confused, I'm a FirebasePushNotificationPlugin user, but now I'm having problems with iOS 13, xcode 11, searching for a solution I notice that you have  PushNotificationPlugin and FirebasePushNotificationPlugin…

Which one should I use?

**Comment by RichardSV15** [comment]
I believe the difference is if you're planning to use Firebase methods like Subcribe.(_TOPIC);

**Comment by rdelrosario** [comment]
Push notification plugin is for using apple APN and firebase for Android. Firebase plugin is to use Firebase cloud messaging solution for both platforms. It will depend on your needs basically.
