### ISSUE TITLE
Error installing the plugin - Native linking failed

### ISSUE THREAD

**Issue by rubenc57** [CrossGeeks/FirebasePushNotificationPlugin#263]
I have VS 2019 16.3.7
I created a new project Mobile App (Xamarin.Forms) Master/Detail And & iOS
Xamarin.forms 4.3.0.947036
Run the iOS project and everything working...
I installed Plugin.FirebasePushNotification 2.3.6
And I get these errors:
App9.iOS
Native linking failed. Please review the build log:
1>------ Build started: Project: App9.iOS, Configuration: Debug iPhoneSimulator ------
...
1> Connecting to Mac server 192.168.x.xx...
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2002,5): warning MSB3341: Could not resolve reference "C:\Users\ruben\AppData\Local\XamarinBuildDownloadCache\FInstncID-3.2.1\Frameworks\FirebaseInstanceID.framework". If this reference is required by your code, you may get compilation errors.
1> No way to resolve conflict between "System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Numerics" that could not be resolved. These reference conflicts are listed in the build log when log verbosity is set to detailed.
1> App9.iOS ->

**Comment by rubenc57** [comment]
If I install version 2.3.5 I don't get the linking error

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta
