### ISSUE TITLE
Change Title and Message Body

### ISSUE THREAD

**Issue by AhmedAdelGadElkareeem** [CrossGeeks/FirebasePushNotificationPlugin#265]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

How can change title and message text in notification body depend on App language English or Arabic 

** note app language user can choose it from setting page in app not related to device language

**Comment by valentin-debris** [comment]
@AhmedAdelGadElkareeem ,

I think the best approch for this is to used differents channels related to the lang.
Example, you have 2 channel, general_en & general_ar. And you translate the notif when you send it, not when you received it. And if the user switch from English to Arabic, you change the channel subscribed.

**Comment by rdelrosario** [comment]
This information is covered on the following section:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/LocalizedFirebasePushNotifications.md
