### ISSUE TITLE
CrossFirebasePushNotification.Current.Subscribe("TOPIC"); Not working on IOS

### ISSUE THREAD

**Issue by RichardSV15** [CrossGeeks/FirebasePushNotificationPlugin#268]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.3.6
Device Tested On: IOS Device

### Steps to reproduce the Behavior
`CrossFirebasePushNotification.Current.Subscribe("TOPIC");`
`var subList = CrossFirebasePushNotification.Current.SubscribedTopics;`
`Debug.WriteLine($"sub count: {newList.Length}");`
`for (int i= 0; i < subList.Length; i++)`
   `{`
      `Debug.WriteLine($"Subscribed to: {subList[i]}");`
   ` }`
### Expected Behavior
IOS device should receive notifications from sub topic and show it is registered to such topic

### Actual Behavior
IOS device doesn't receive notifications to given topic. I have tested that my implementation is properly setup as i can receive topic notifications on android and i can receive push notification to the IOS device with the device token id using a post man request.   

### Code snippet
`try {`
       `Debug.WriteLine("Register FCM subscription topics");`
        `await CrossFirebasePushNotification.Current.RegisterForPushNotifications();`
        `var nToken = CrossFirebasePushNotification.Current.Token;`
        `Debug.WriteLine($"Notification token: {nToken}");`
        `//get sub list`
        `var list = CrossFirebasePushNotification.Current.SubscribedTopics;`
        `CrossFirebasePushNotification.Current.Subscribe(Settings.LinkId);`
        `switch (Settings.Language)`
         `{`
                    `case "en":`
                        `     if (list.Contains("general_es"))`
    `    CrossFirebasePushNotification.Current.Unsubscribe("general_es");`
                        `    if (!list.Contains("general"))  `
  `     CrossFirebasePushNotification.Current.Subscribe("general");`
                       `     break;`
                    `case "es":`
                        `    if (list.Contains("general"))` 
  `    CrossFirebasePushNotification.Current.Unsubscribe("general");`
                        `    if (!list.Contains("general_es"))`
  `    CrossFirebasePushNotification.Current.Subscribe("general_es");`
                        `     break;`
                    `default:`
                        `     CrossFirebasePushNotification.Current.Unsubscribe("general_es");`
                        `     CrossFirebasePushNotification.Current.Subscribe("general");`
                        `     Settings.Language = "en";`
                        `     break;`
                `}`
                `var newList = CrossFirebasePushNotification.Current.SubscribedTopics;`
                `Debug.WriteLine($"sub count: {newList.Length}");`
                `for (int i= 0; i < newList.Length; i++)`
                `{`
                    `Debug.WriteLine($"Subscribed to: {newList[i]}");`
                `}`
            `}
            catch (Exception ex)`
            `{`
                `Debug.WriteLine(ex.Message);`
                `Debug.WriteLine(ex.Source);`
           `}`

**Comment by astralmaster** [comment]
Did you ever find a fix for this? I am having the same issue

**Comment by leeapted** [comment]
I'm experiencing this problem also.

Did you ever find a fix for this?

**Comment by DeanZhuo** [comment]
same issue here. someone got a fix?

**Comment by duncancole** [comment]
Also having this issue - can receive 'normal' notifications but none for topics the device is subscribed to. I suspect something is going wrong with the subscription but I'm not seeing any errors when it happens.

As an aside, why this issue closed with no explanation?

**Comment by Michielvv87** [comment]
Also having this problem with the current version

**Comment by sunnysonic** [comment]
same problem....
