### ISSUE TITLE
NUGET package lacks dependencies on Firebase platform bindings packages

### ISSUE THREAD

**Issue by noahsanook** [CrossGeeks/FirebasePushNotificationPlugin#269]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.3.6
Device Tested On: iPhone XS Max, Android XGODY
Simulator Tested On:  "pixel_3_pie_9.0_api_28 (Android 9.0  - API 28)"
Version of VS: 2019
Version of Xamarin: 4.3.0.991211
Versions of other things you are using:
  - Xamarin.Firebase.iOS.InstanceID: 3.2.1
  - Xamarin.Firebase.Messaging: 60.1142.1
  - Xamarin.GooglePlayServices.Basement: 60.1142.1

### Steps to reproduce the Behavior
Using Nuget "Manage Packages for Solution", install the latest FirebasePushNotificationPlugin to a brand new Xamarin Forms project. You will find that either it doesn't compile on iOS and Android, or compiles but notifications do not work until / unless you also manually install the above 3 packages (InstanceID, Messaging, Basement) of the **exact** versions that are specified above, which are no longer the latest versions. Also, once these 3 packages are added, upgrading them to the latest version will either break the build or break notification functionality of FirebasePushNotificationPlugin

### Expected Behavior
- The NUGET of FirebasePushNotificationPlugin should have explicit dependency and automatically install these 3 packages.
- The latest FirebasePushNotificationPlugin must be compatible with the latest versions of these 3 packages.
- The documentation should mention this situation 

### Actual Behavior
- See the Steps above
- Current documentation / Getting Started does not mention any of this.

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta

**Comment by noahsanook** [comment]
Thank you for a quick response. I will be trying it within the next couple of weeks and will let you know.
