### ISSUE TITLE
OnTokenRefresh not fired on IOS

### ISSUE THREAD

**Issue by eyacoub** [CrossGeeks/FirebasePushNotificationPlugin#27]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On: Iphone 5 + iphone 7s
Simulator Tested On:
Version of VS: visual studio 2017 and Visual studio for mac
Version of Xamarin:
Versions of other things you are using:

**Comment by rdelrosario** [comment]
Did you follow the documentation?

Did you test with the sample?

**Comment by rdelrosario** [comment]
Please give more details and open a new issue if this keeps going for you.

**Comment by SkillerSKL** [comment]
Same issue here :s
I did everything that is in the documentation

**Comment by vinsant** [comment]
> Same issue here :s
> I did everything that is in the documentation

I got the same issue.
Can you handle that issue?
