### ISSUE TITLE
Abandoned Project?

### ISSUE THREAD

**Issue by mimunoz** [CrossGeeks/FirebasePushNotificationPlugin#270]
I noticed what this repo don't have any changed a few months, but [this](https://github.com/CrossGeeks/PushNotificationPlugin) other project(your too) have more recent activity and changes. Where upgrade the Android dependencies it's critical in many cases. So @rdelrosario,  my question is if you will do archive this repo in place the other PushNotificationPlugin.

Regards.

**Comment by rdelrosario** [comment]
This project is still active just haven't find the time to upgrade it.
Planning some work for this week.

**Comment by mimunoz** [comment]
Thanks for quick reply!

**Comment by rohitvipin** [comment]
@rdelrosario - the PR is tested on both iOS and Android. Also being used in a private fork in production more than a month without issues so far.

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta
