### ISSUE TITLE
Initialize on android fails to take NotificationUserCategory

### ISSUE THREAD

**Issue by nodoid** [CrossGeeks/FirebasePushNotificationPlugin#272]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.3.6
Device Tested On:S8+
Simulator Tested On:
Version of VS: 
Version of Xamarin: 8.4
Versions of other things you are using:

### Steps to reproduce the Behavior
Added the following to my Application class

FirebasePushNotificationManager.Initialize(this, new NotificationUserCategory[]
            {
            new NotificationUserCategory("message",new List<NotificationUserAction> {
                new NotificationUserAction("Reply","Reply",NotificationActionType.Foreground),
                new NotificationUserAction("Forward","Forward",NotificationActionType.Foreground)

            }),
            new NotificationUserCategory("request",new List<NotificationUserAction> {
                new NotificationUserAction("Accept","Accept",NotificationActionType.Default,"check"),
                new NotificationUserAction("Reject","Reject",NotificationActionType.Default,"cancel")
            })

            }, false);

(as per the instructions)

### Expected Behavior
Should build fine
### Actual Behavior
Compile error - unable to convert argument 2 to bool

**Comment by rdelrosario** [comment]
Should be fixed in latest version
