### ISSUE TITLE
Does this plugin actually work for IOS?

### ISSUE THREAD

**Issue by Vliesie** [CrossGeeks/FirebasePushNotificationPlugin#274]
I've followed every topic/Discussion Regarding IOS setup 

Every step

I've got a Developer account

My Certifications are setup/ All profiles

Firebase APN's are setup I get a token 

Configurations are all setup, I've followed every step I'm at a loss I've found article's discussing the plugin not working for IOS can someone confirm or deny this? I dont know what to do anymore

**Comment by rdelrosario** [comment]
Hi @Vliesie What version are you trying?

**Comment by husamdev** [comment]
Hello developers,

I am having the same issue as @Vliesie 
I followed every single step in the tutorial and tried it on Xamarin.iOS project

then I tried using the sample project
and added my own GoogleService-Info.plist
chaned the build action of this file to BundleResource

and changed the bundle identifier in Info.plist to match the one on firebase

I tried to send push notification using postman
and it is returning success

the only event that is fired when the application starts in both application is:

`CrossFirebasePushNotification.Current.OnTokenRefresh += (s,p) =>
{
         System.Diagnostics.Debug.WriteLine($"TOKEN REC: {p.Token}");
};` 

and it is returning the token

for me i am using the latest version 2.3.6

I will be grateful for any help
Thank you in advance

**Comment by Lirian21** [comment]
> Hi @Vliesie What version are you trying?

The latest version I always use the latest  so 2.3.6.

I Can post all the code if its needed with my certificates but I have followed everything to the T I just cant get anything threw to my Physical IOS device but Androids working like a breeze

**Comment by Vliesie** [comment]
> Hi @Vliesie What version are you trying?

The latest version I always use the latest  so 2.3.6.

I Can post all the code if its needed with my certificates but I have followed everything to the T I just cant get anything threw to my Physical IOS device but Androids working like a breeze

**Comment by husamdev** [comment]
The plugin actually works on Xamarin.iOS I just forgot to added the APNs certificate

**Comment by rdelrosario** [comment]
Please try latest version.
