### ISSUE TITLE
java.lang.IllegalStateException on 3.0.3

### ISSUE THREAD

**Issue by TopSkillDeveloper** [CrossGeeks/FirebasePushNotificationPlugin#276]
Hello, i get an error "Default FirebaseApp is not initialized in this process <package name>. Make sure to call FirebaseApp.initializeApp(Context) first" when debug.
Didn't change anything else. FAQ read (all also as there). On 2.3.6 everything worked

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: lg g4 (v8.1)
Simulator Tested On: pexel 2 (v8.1, v.9.0)
Version of VS: 16.4.2
Version of Xamarin: 4.4-sr2
Versions of other things you are using: no changes

### Steps to reproduce the Behavior
Occurs immediately when debugging.

### Actual Behavior
Not working. java.lang.IllegalStateException

### Code snippet
`public override void OnCreate()
        {
            base.OnCreate();

            //Set the default notification channel for your app when running Android Oreo
            if (Build.VERSION.SdkInt >= BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                FirebasePushNotificationManager.DefaultNotificationChannelId = "FirebasePushNotificationChannel";

                //Change for your default notification channel name here
                FirebasePushNotificationManager.DefaultNotificationChannelName = "General";
            }

            FirebasePushNotificationManager.Initialize(this, true);  // an error occurs here

        }`

**Comment by Jerome-Liger** [comment]
+1
I've tried to add FirebaseApp.InitializeApp(this) before the Initialization of FirebasePushNotificationManager, but doesn't work... 

` FirebaseApp.InitializeApp(this);
            //Set the default notification channel for your app when running Android Oreo
            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                FirebasePushNotificationManager.DefaultNotificationChannelId = Constantes.ChannelID;

                //Change for your default notification channel name here
                FirebasePushNotificationManager.DefaultNotificationChannelName = Constantes.ChannelName;
            }
            FirebasePushNotificationManager.Initialize(this, true, autoRegistration: false);`

**Comment by AUNDW** [comment]
I got the same problem today after updating from version  2.3.6 (where everything was fine) to the new version 3.0.3.

**Comment by rdelrosario** [comment]
This should be due to some missing dependency please verify you have all dependencies installed.

**Comment by Jerome-Liger** [comment]
Thanks Rendy for your answer.
I've checked and updated all the nugget packages (stable version) in my project, clean/rebuild, and same error. Everything is still working correctly with the 2.3.6.

Are you sure there is no new dependency between 2.3.6 and 3.0.3 ? 
is there "hidden" dependency that are not declared in your nugget package 3.0.3 ?
Or do you have dependency packages in 3.0.3 that are in "preview" ?
Maybe an Android SDK/tools to update too ?

I don't see any bad or missing dependencies in my project build... I'm trying with more verbosity output...

**Comment by Fireflash1** [comment]
Hi, same problem. I'm using Xamarin Forms. Testing on Android Simulator (Android 8.1 API 27).
Both version 3.0.3 and 3.0.8 I have this Error:
`Java.Lang.IllegalStateException: 'Default FirebaseApp is not initialized in this process com.appname.cfd. Make sure to call FirebaseApp.initializeApp(Context) first.'
`
What is missing ? Try everything, but didnt work :(

**Comment by TopSkillDeveloper** [comment]
I cleaned all the caches and reinstalled the libraries again. The error persists. On 2.3.6 everything works.

**Comment by rdelrosario** [comment]
Please try the sample, compare with it to see if you have all the dependencies installed with same version.

**Comment by rdelrosario** [comment]
Will close this issue since didn't get any additional feedback and sample is working properly. Please re-open or create a new issue if this keeps happening to you.

**Comment by TopSkillDeveloper** [comment]
The example works, but my app doesn't. Already checked all. Will have until on 2.3.6 until fix bug

**Comment by Jerome-Liger** [comment]
Ok, I was having the issue but I succeed to resolve... at least !

- First, the provided sample use the "old" way to manage dependencies (with the "package.json way", that has more useless and unreadable low-level dependencies than in the "PackageReference way")
-> more info : https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

- Next, the sample is built on Target Android 10.0, I've changed mine and install the SDK (I was in 9.0). I don't know if it changed anything, but just this update doesn't resolve the problem...

- Finally, I've analysed my Packages references (and the package.json low-level dependencies), and I added to my "2.3.6 working project" only the "Xamarin.Build.Download", "Xamarin.Firebase.Messaging", "Xamarin.GooglePlayServices.Basement" and "Xamarin.GooglePlayServices.Tasks". I thinks it's too much (because these dependencies would normaly be resolved automaticaly with the "PackageReference maner"... because the dependencies declared by the "Plugin.FirebasePushNotification" package would be automaticaly resolved (**maybe because the dependencies declared are targeting "MonoAndroid,Version=V9.0" ?**)

I've clean all, rebuild, redeploy and now all is Ok... :-)

So, for the "PackageReference" users, here are my dependencies :

```
<PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
<PackageReference Include="Plugin.CurrentActivity" Version="2.1.0.4" />
<PackageReference Include="Plugin.FirebasePushNotification" Version="3.0.22" />
<PackageReference Include="Plugin.Permissions" Version="3.0.0.12" />
<PackageReference Include="Xamarin.Build.Download" Version="""0.7.1"/>
<PackageReference Include="Xamarin.Firebase.Messaging" Version="71.1740.0"/>
<PackageReference Include="Xamarin.Forms" Version="4.4.0.991477" />
<PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.3" />
<PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.3" />
<PackageReference Include="Xamarin.Android.Support.v4" Version="28.0.0.3" />
<PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="28.0.0.3" />
<PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="28.0.0.3" />
<PackageReference Include="Xamarin.GooglePlayServices.Basement" Version="71.1620.0"/>
<PackageReference Include="Xamarin.GooglePlayServices.Tasks" Version="71.1601.0"/>
```

Hope this helps...

**Comment by Jerome-Liger** [comment]
Update... as I don't like having too much dependencies declare, I've tested to delete "Xamarin.Build.Download" and "Xamarin.GooglePlayServices.Basement"... and it still works.

So normaly, you just have to add/verify "**Xamarin.Firebase.Messaging**" and "**Xamarin.GooglePlayServices.Tasks**" (and I think remembered that one of these require a "accept licence" and I that's probably why it doesn't restore automatically correctly the package dependency...)

Do not forgot to clean (delete bin/obj) rebuild and it's Ok for me.

**Comment by xamarindevelopervietnam** [comment]
thanks @Jerome-Liger, I will try the same thing, hope it work for me too.

**Comment by valentin-debris** [comment]
I had the same problem with the project I installed on a new computer. The problem was in fact that the build action for the file "google-services.json" wasn't GoogleServicesJson. After that, everything works.

**Comment by pedroyan** [comment]
@Jerome-Liger Thanks for sharing you solution. I was having the same problem despite targeting Android 10 and setting up the code as described on the tutorial. After stalling the following packages, the problem went away:

```
<PackageReference Include="Xamarin.Firebase.Messaging" Version="71.1740.1"/>
<PackageReference Include="Xamarin.GooglePlayServices.Tasks" Version="71.1601.1"/>
```
