### ISSUE TITLE
IOS: FCM notification not working with Release mode

### ISSUE THREAD

**Issue by ashishbpatil1** [CrossGeeks/FirebasePushNotificationPlugin#28]
Hello,

We are using this plugin for xamarin forms And we successfully tested android Ad-Hoc apk.
For **iPhone** we are able to get notification in debug mode but in release/ production mode its not working, we are not getting any notifications.

We added APNs authentication key (.p8) in firebase console project.
also followed every step given in [Getting started](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/GettingStarted.md).

We used `FirebaseNet.Messaging` nuget package to send data and also tested with [Postman](https://www.getpostman.com/)

We also added Apple Push Notification service SSL Certificate and Production SSL Certificate.
We set Background modes : Remote notification checked.
And `FirebaseAppDelegateProxyEnabled` to No in **Info.plist**.

The Json we are sending:

```
{
   "to": "/topics/TSCG230_XXXXX2",
   "priority" : "high",
      "notification": {
    "body": "Hello",
    "title": "This is test message.",
    "content_available" : true,
    "sound": "Alarm.wav"
   },
   "data": {
        "title" : "TSCG230_XXXXX2",
        "infoType" : "LEL#",
        "body" : "00100",
        "notiType" : "Alarm"
     }
}
```

Version Number of Plugin: v1.0.4
Device Tested On: iPhone 4s
Simulator Tested On: -
Version of VS: VS2017 Community
Version of Xamarin: latest stable

### Steps to reproduce the Behavior
Create ipa file and test on iPhone 4s.

### Expected Behavior
It should show notification while application is in background as it is showing in debug mode.

### Actual Behavior
Its not showing notification while application is in background.

Let me know if any information is needed.
Please help us to figure out the issue.
Thanks.

**Comment by rdelrosario** [comment]
What's your code on the app delegate?

**Comment by ashishbpatil1** [comment]
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Foundation;
using UIKit;
using System.Diagnostics;
using System.IO;
using Plugin.FirebasePushNotification;
using Plugin.Settings.Abstractions;
using Plugin.Settings;

namespace SmartSensor.iOS
{
	// The UIApplicationDelegate for the application. This class is responsible for launching the 
	// User Interface of the application, as well as listening (and optionally responding) to 
	// application events from iOS.
	[Register("AppDelegate")]
	public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
	{
        private static ISettings AppSettings => CrossSettings.Current;
		//
		// This method is invoked when the application has loaded and is ready to run. In this 
		// method you should instantiate the window, load the UI into it and then make the window
		// visible.
		//
		// You have 17 seconds to return from this method, or iOS will terminate your application.
		//
		public override bool FinishedLaunching(UIApplication app, NSDictionary options)
		{

            AppDomain.CurrentDomain.UnhandledException += CurrentDomainOnUnhandledException;
            TaskScheduler.UnobservedTaskException += TaskSchedulerOnUnobservedTaskException;


            global::Xamarin.Forms.Forms.Init ();


            LoadApplication (new SmartSensor.App ());

            FirebasePushNotificationManager.Initialize(options, true);


            return base.FinishedLaunching (app, options);
		}

        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
#if DEBUG
            FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken, FirebaseTokenType.Sandbox);
#endif
#if RELEASE
                    FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken,FirebaseTokenType.Production);
#endif

        }

        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            base.FailedToRegisterForRemoteNotifications(application, error);
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);

        }
        // To receive notifications in foregroung on iOS 9 and below.
        // To receive notifications in background in any iOS version
        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            // If you are receiving a notification message while your app is in the background,
            // this callback will not be fired 'till the user taps on the notification launching the application.

            // If you disable method swizzling, you'll need to call this method. 
            // This lets FCM track message delivery and analytics, which is performed
            // automatically with method swizzling enabled.
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
            // Do your magic to handle the notification data
            System.Console.WriteLine(userInfo);


            NSObject infoType = userInfo[NSObject.FromObject("infoType")];
            NSObject notiType = userInfo[NSObject.FromObject("notiType")];


         }

        public override void OnActivated(UIApplication uiApplication)
        {
            FirebasePushNotificationManager.Connect();
            base.OnActivated(uiApplication);

        }
        public override void DidEnterBackground(UIApplication application)
        {
            // Use this method to release shared resources, save user data, invalidate timers and store the application state.
            // If your application supports background exection this method is called instead of WillTerminate when the user quits.
            FirebasePushNotificationManager.Disconnect();
        }


        #region Task Schedular Exception

        private static void TaskSchedulerOnUnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs unobservedTaskExceptionEventArgs)
        {
            var newExc = new Exception("TaskSchedulerOnUnobservedTaskException", unobservedTaskExceptionEventArgs.Exception);
            newExc.ToLogUnhandledException();
        }

        #endregion

        #region Current Domain Exception

        private static void CurrentDomainOnUnhandledException(object sender, UnhandledExceptionEventArgs unhandledExceptionEventArgs)
        {
            var newExc = new Exception("CurrentDomainOnUnhandledException", unhandledExceptionEventArgs.ExceptionObject as Exception);
            newExc.ToLogUnhandledException();
        }

        #endregion
        

    }
}

```

**Comment by ashishbpatil1** [comment]
Hello,

Did u find any issue with given app delegate file?

Today we tried with uploading new **Development** and **Production** certificates to firebase
(exporting the whole certificate (not private key) from Keychain Access).

And again it worked with debug and App-Store mode but not with the Add-Hoc mode.
We also tried to upload ipa file to test-flight with App-Store mode but we got following mail and we can't download ipa file from test-flight.

`missing push notification entitlement`

We will try to fix this issue tomorrow and let you know. If you know anything about this issue please let us know as we are new to firebase push notifications.
Thanks.

**Comment by ashishbpatil1** [comment]
It worked on **testflight** after enabling push notification in **Entitlements.plist** and by setting value of key `app-enviroment` to `production` (manually) and also by setting `FirebaseAppDelegateProxyEnabled` to `Yes` in **Info.plist**.

thanks, you can close the issue.

**Comment by rdelrosario** [comment]
Glad you were able to get it working. For me didn't had such problems on Release using Token-based (HTTP/2)

**Comment by sculptsoft-devs** [comment]
Hi @rdelrosario 

We are having same issue.  Getting notification in development but not in distribution profile. We have done same like @ashishbpatil1 , in Entitlements.plist aps-enviroment to production and FirebaseAppDelegateProxyEnabled to Yes in Info.plist. 

While uploading the IPA via app loader, I am getting following error.
Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'aps-environment' in com.company.MyApp.

I have also deleted all profile and re downloaded all profiles again. Still getting this. Any Help!!!

**Comment by vpiliado** [comment]
Hello.

What version of the plugin do you use in your project (Plugin.FirebasePushNotification)

thanks

**Comment by Shashidhar014** [comment]
Hi,
I am also having same problem, its works fine in Debug mode but in release mode its not working and I am using 2.3.5 version

**Comment by Shashidhar014** [comment]
@ashishbpatil1 solution works for me

**Comment by vpiliado** [comment]
@Shashidhar014 I managed to solve the problem, maybe you need to configure something. I'm taking version 2.3.5

**Comment by Umar3x** [comment]
@vpiliado How did you manage to get it work ? Setting FirebaseAppDelegateProxyEnabled to true ?
