### ISSUE TITLE
Missing HandleIntent (Intent p0) in FirebasePushNotificationPlugin 3.0.8

### ISSUE THREAD

**Issue by chibuta** [CrossGeeks/FirebasePushNotificationPlugin#280]
## Whats is the Alternative to "public unsafe override void HandleIntent (Intent p0);" in FirebaseMessagingService for FirebasePushNotificationPlugin 3.0.8?
I can no longer override the  HandleIntent (Intent p0) in Version 3.0.8. Which method can I use to handle notifications when the app in the background or closed state?

**Comment by rdelrosario** [comment]
Hi why you need to override HandleIntent? I think that doesn't exist anymore in the Firebase messaging clas

**Comment by chibuta** [comment]
It was there in version 2.3.6. I was using it to handle notifications when the app is the background to update the badge count.
