### ISSUE TITLE
java.lang.IllegalStateException on 3.0.3

### ISSUE THREAD

**Issue by TopSkillDeveloper** [CrossGeeks/FirebasePushNotificationPlugin#283]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

**The example works, but my app doesn't. Already checked all. Will have until on 2.3.6 until fix bug**

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: lg g4 (v8.1)
Simulator Tested On: pexel 2 (v8.1, v.9.0)
Version of VS: 16.4.2
Version of Xamarin: 4.4-sr2
Versions of other things you are using: no changes

I'm sorry, I couldn't reopen issue

**Comment by rdelrosario** [comment]
Just published a beta version with some changes related to project dependencies and targets. Please give it a try and let me know if fixes your issue:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.1.1-beta

**Comment by TopSkillDeveloper** [comment]
no, the error remained

**Comment by klementuel** [comment]
I have the same problem

**Comment by eramrit78** [comment]
I have same issue
