### ISSUE TITLE
Initialization problem on Android with version > 2.3.6

### ISSUE THREAD

**Issue by spelletier** [CrossGeeks/FirebasePushNotificationPlugin#284]
I have an Xamarin Forms app with version 2.3.6 of the plugin and try to update to a more recent version.

On iOS, no problems but on Android, I tried many versions and I always get this error during `FirebasePushNotificationManager.Initialize(this, true, createDefaultNotificationChannel:false)`

> Default FirebaseApp is not initialized in this process ... Make sure to call FirebaseApp.initializeApp(Context) first

My google-services.json file and package names are OK.

Here is my MainApplication init code, CreateNotificationChannels() create notifications channels if required.

Is there something in newer version that may require some code change ?

```
    public override void OnCreate() {
        base.OnCreate();

    if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O) {
            CreateNotificationChannels();
        }
        CrossFirebasePushNotification.Current.OnNotificationError += (object source, FirebasePushNotificationErrorEventArgs e) => {
            Console.WriteLine("OnNotificationError " + e.Message);
        };
        EchoMessager.Sync.Server.GetInstance().SetNotificationToken(CrossFirebasePushNotification.Current.Token);
        CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) => {
            EchoMessager.Sync.Server.GetInstance().SetNotificationToken(p.Token);
            Server.GetInstance().RegisterDevice();
        };

        CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) => {
            EchoMessager.Sync.Server.GetInstance().ProcessNotification(p.Data);
        };

#if DEBUG
        FirebasePushNotificationManager.Initialize(this, true, createDefaultNotificationChannel:false);
#else
        FirebasePushNotificationManager.Initialize(this,false, createDefaultNotificationChannel:false);
#endif
    }

```

## Bug Information

Version Number of Plugin: >2.3.6
Device Tested On:
Simulator Tested On: multiple (API level 
Version of VS: Mac 8.4.2

**Comment by Haza85** [comment]
I have the same problem

**Comment by Haza85** [comment]
I have add Xamarin.Firebase.Common package directly to Android project and it's work now

**Comment by Haza85** [comment]
I have add Xamarin.Firebase.Common package directly to Android project and it's work now. Don't forget to clean Anndoid project (manually delete bin and obj folders) and rebuild.

**Comment by fromstog** [comment]
> I have add Xamarin.Firebase.Common package directly to Android project and it's work now. Don't forget to clean Anndoid project (manually delete bin and obj folders) and rebuild.

I solved it your way. Thank you.

**Comment by Rothanan** [comment]
> I have add Xamarin.Firebase.Common package directly to Android project and it's work now. Don't forget to clean Anndoid project (manually delete bin and obj folders) and rebuild.

It worked for me as well, thank you.

**Comment by OmarHassan25** [comment]
> I have add Xamarin.Firebase.Common package directly to Android project and it's work now. Don't forget to clean Anndoid project (manually delete bin and obj folders) and rebuild.

It worked for me as well, thank you.

**Comment by TopSkillDeveloper** [comment]
> I have add Xamarin.Firebase.Common package directly to Android project and it's work now. Don't forget to clean Anndoid project (manually delete bin and obj folders) and rebuild.

Thank you, it started without errors.

**Comment by ivandharo** [comment]
> I have add Xamarin.Firebase.Common package directly to Android project and it's work now. Don't forget to clean Anndoid project (manually delete bin and obj folders) and rebuild.

Thanks for the solution bro!!!
