### ISSUE TITLE
OnNotificationReceived not firing on Android

### ISSUE THREAD

**Issue by stavroaudi** [CrossGeeks/FirebasePushNotificationPlugin#286]
Version Number of Plugin: 3.1.6
Device Tested On: Samsung S8
Version of VS: Professional 2019
Version of Xamarin: 4.4.0.991537

When I'm testing on my device, I receive the notification, but OnNotificationRecevied is not firing (when app is in background). When app is in foreground, it does fire. 

OnNotificationOpened executes twice when I click on a single notification when in background too. I've copied most of the code from an older, working project so I'm not sure what the issue could be.

**Comment by stavroaudi** [comment]
My payload: 

> {
>   "to" : "TOKEN",
>   "priority": "high",
>   "mutable_content": true,
>   "notification": {
>     "title": "Name",
>     "body" : "Test 1",
>     "sound":"default"
>   },
>   "data": {
>     "Notification_Type" : "News",
>     "notification_title": "Title",
>     "notification_subtitle": "Sub"
>   }
> }

**Comment by stavroaudi** [comment]
I also get this in my output when I send the notification in the background: 

01-31 09:35:18.043 W/FirebaseMessaging(19358): Unable to log event: analytics library is missing
01-31 09:35:18.068 W/FirebaseMessaging(19358): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.

**Comment by stavroaudi** [comment]
This worked: 

{
    "data": {
    "Notification_Type" : "News",
    "notification_title": "Pundai",
    "notification_subtitle": "Chunni"
     },
     "priority": "high",
     "to" : "TOKEN"
}

Anyone know why this does and not my old one? Is there a way I can have one payload that works for both iOS and Android that contains data?

**Comment by stavroaudi** [comment]
This worked:

{
"data": {
"Notification_Type" : "News",
"notification_title": "Test",
"notification_subtitle": "Test1"
},
"priority": "high",
"to" : "TOKEN"
}

Anyone know why this does and not my old one? Is there a way I can have one payload that works for both iOS and Android that contains data?

**Comment by rdelrosario** [comment]
You should use the new HTTP FCM api to send the notification to achieve that in just one payload.

https://firebase.google.com/docs/cloud-messaging/migrate-v1?hl=en
