### ISSUE TITLE
Android: Intercepting the push event received when the app is closed.

### ISSUE THREAD

**Issue by mdmota** [CrossGeeks/FirebasePushNotificationPlugin#287]
I'm having trouble intercepting the push event received when the app is closed on Android.
The notification is created in the status bar, but no event is called.
OnNotificationReceived is only triggered when I have the application open or when I click on the notification.

Which event is triggered to create the notification when the push is received, with the app closed?

## Bug Information

Version Number of Plugin: 3.1.6
Device Tested On: Asus Zenfone 4
Simulator Tested On:
Version of VS:  2019 16.4.4
Version of Xamarin Forms: 4.3.0

**Comment by Freddyvdh** [comment]
Still works for me with the latest version. (Updated from 2.3.6 to 3.1.6)

OnNotificationReceived is called.
If you are debugging, you must kill the app, launch the app normally and kill it again. After stop debugging OnNotificationReceived is not triggered.
