### ISSUE TITLE
Issue v3.1.6 when compiling after update from 2.3.6

### ISSUE THREAD

**Issue by AldairOrta** [CrossGeeks/FirebasePushNotificationPlugin#291]
I just decided to update the nuget from the app after everything worked fine with both Android and iOS.

The issue is that when I tried to compile with new version 3.1.6. it crashed my app. The error said that Firebase was not initialized at the moment of calling "FirebasePushNotificationManager.Initialize(this,true);" or directly subscribing the app to a topic.

I tried deleting Bin and Obj from all my project folders, so it worked once for me. but this time , this solution didn´t work.

I tried initializing Firebase via : FirebaseApp.initializeApp(this); but neither it worked.

The only solution was to downgrade again to 2.3.6 because the app is in "production".

Version Number of Plugin: 3.1.6
Device Tested On: Xiaomi mi 9t
Simulator Tested On: iOS Simulator
Version of VS: 8.3.11

**Comment by OmarHassan25** [comment]
I have the same issue, Any support?

**Comment by Rothanan** [comment]
I have the exact same issue.

**Comment by Rothanan** [comment]
See https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/284.

**Comment by OmarHassan25** [comment]
> See #284.

It worked for me as well, thank you.
