### ISSUE TITLE
iOS Remote Notifications never received.

### ISSUE THREAD

**Issue by seanmt13** [CrossGeeks/FirebasePushNotificationPlugin#292]
## Bug Information

Version Number of Plugin: 3.0.8
Device Tested On: iPhone 8 Plus
Version of VS: Visual Studio For Mac
Version of Xamarin: Xamarin.Forms 4.4
Versions of other things you are using:

### Steps to reproduce the Behavior
I have followed the guide and looked at the samples. Currently I am getting notifications just fine on Android. But I never receive them on iOS.

When I start the iOS app this method is getting called
```
public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
{
    FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken);
}
```
Which makes me believe that it is getting setup correctly. In-fact I know it is somewhat working because to test I subscribed to a NEW topic "TestiOS" and it shows up in the list of topics in the cloud messaging console in Firebase.

![Capture](https://user-images.githubusercontent.com/28146692/74356864-4957dd80-4d7c-11ea-9437-1ba57141f247.JPG)

However in my Xamarin.Forms application App.xaml.cs is never getting called in iOS. And, I never receive a notification

```
CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
{
     System.Diagnostics.Debug.WriteLine("Received");
};
```
Do I have to do something else to receive notifications on iOS? Yes I have my entitlements.plist, Google-Service-Info.plist and Info.plist setup correctly according to what I have read in the examples

### Expected Behavior
Get a notification
### Actual Behavior
No notification
### Code snippet
Here is my code for my AppDelegate.cs
```
namespace UtahLakeMobile.iOS
{
    // The UIApplicationDelegate for the application. This class is responsible for launching the 
    // User Interface of the application, as well as listening (and optionally responding) to 
    // application events from iOS.
    [Register("AppDelegate")]
    public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
    {
        //
        // This method is invoked when the application has loaded and is ready to run. In this 
        // method you should instantiate the window, load the UI into it and then make the window
        // visible.
        //
        // You have 17 seconds to return from this method, or iOS will terminate your application.
        //
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App());

            FirebasePushNotificationManager.Initialize(options, new NotificationUserCategory[]
            {
                new NotificationUserCategory("message",new List<NotificationUserAction> {
                    new NotificationUserAction("Reply","Reply",NotificationActionType.Foreground)
                }),
                new NotificationUserCategory("request",new List<NotificationUserAction> {
                    new NotificationUserAction("Accept","Accept"),
                    new NotificationUserAction("Reject","Reject",NotificationActionType.Destructive)
                })

            });

            return base.FinishedLaunching(app, options);
        }

        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken);

        }

        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);
        }

        // To receive notifications in foregroung on iOS 9 and below.
        // To receive notifications in background in any iOS version
        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            // If you are receiving a notification message while your app is in the background,
            // this callback will not be fired 'till the user taps on the notification launching the application.

            // If you disable method swizzling, you'll need to call this method. 
            // This lets FCM track message delivery and analytics, which is performed
            // automatically with method swizzling enabled.
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
            // Do your magic to handle the notification data
            System.Console.WriteLine(userInfo);

            completionHandler(UIBackgroundFetchResult.NewData);
        }

    }
}
```
I also put a breakpoint on DidReceiveRemoteNotification but it never gets called. And I am not seeing any errors in the console output. So I am not sure what I am doing wrong. Any help would be really great!

**Comment by Freddyvdh** [comment]
Hi,

are you sending [data messages](https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages)?

Important for iOS is to set the [content_available flag](https://firebase.google.com/docs/cloud-messaging/http-server-ref?hl=de)

**Comment by seanmt13** [comment]
So I have tried just sending notifications through the firebase cloud messaging console. Which you can't send data messages there. But I also have tried sending messages using a .net FirebaseAdmin.Messaging

Data message that works in Android
```
            var topic = "UtahLakeWindAlerts";

            // See documentation on defining a message payload.
            var message = new Message()
            {
                Data = new Dictionary<string, string>()
                {
                    { "UtahLakeLocationUpdate", "true" },
                    { "time", DateTime.Now.ToString() },
                    { "Alert", "true" },
                    { "silent", "true" }
                },
                Android = new AndroidConfig
                {
                    Priority = Priority.High,
                    Data = new Dictionary<string, string>()
                {
                    { "UtahLakeLocationUpdate", "true" },
                    { "time", DateTime.Now.ToString() },
                    { "Alert", "true" },
                    { "silent", "true" }
                },
                },
                Topic = topic,
            };
```

Notification Message that works in Android
```
            var message2 = new Message()
            {
                Notification = new Notification
                {
                    Title = "Utah Lake Wind Alert",
                    Body = "Winds fast approaching"
                },
                Android = new AndroidConfig
                {
                    Priority = Priority.High,
                    Notification = new AndroidNotification
                    {
                        Title = "Android Title",
                        Body = "Android Body",
                    }
                },
                Topic = topic
            };
```

So for the data message i can try adding the content_available flag but do i need to do this for a non data message? Also do i need to set any apns configuration? Thanks so much for your help!

**Comment by seanmt13** [comment]
I changed my data message and added the content_available flag but with no success

```
            var topic = "UtahLakeWindAlerts";

            // See documentation on defining a message payload.
            var message = new Message()
            {
                Data = new Dictionary<string, string>()
                {
                    { "UtahLakeLocationUpdate", "true" },
                    { "time", DateTime.Now.ToString() },
                    { "Alert", "true" },
                    { "silent", "true" },
                    { "content_available", "true" }
                },
                Android = new AndroidConfig
                {
                    Priority = Priority.High,
                    Data = new Dictionary<string, string>()
                {
                    { "UtahLakeLocationUpdate", "true" },
                    { "time", DateTime.Now.ToString() },
                    { "Alert", "true" },
                    { "silent", "true" }
                },
                },
                Topic = topic,
            };
```

**Comment by rdelrosario** [comment]
You are sending data messages, for iOS you should send notification messages instead

**Comment by seanmt13** [comment]
I thought a notification message was a message with no data. Which is what I had above. Is this not a notification message?

> Notification Message that works in Android.

> ```
> var message2 = new Message()
>             {
>                 Notification = new Notification
>                 {
>                     Title = "Utah Lake Wind Alert",
>                     Body = "Winds fast approaching"
>                 },
>                 Android = new AndroidConfig
>                 {
>                     Priority = Priority.High,
>                     Notification = new AndroidNotification
>                     {
>                         Title = "Android Title",
>                         Body = "Android Body",
>                     }
>                 },
>                 Topic = topic
>             };
> ```

I have also tried just sending a message from the firebase console which only sends notification message with no luck.

**Comment by seanmt13** [comment]
Ok I figured it out. It was my fault I missed a very crucial step in configuring firebase for iOS. I first started with android and didn't realize more needed to be done with firebase on the iOS side. Maybe this will hep someone out in the future.

> Configure APNs with FCM: https://firebase.google.com/docs/cloud-messaging/ios/certs
> 
> Upload iOS TLS certificate/auth token on Settings -> Cloud Messaging section:

**Comment by seanmt13** [comment]
This video also led me in the right direction on how to get the p12 to upload to firebase
[https://youtu.be/pVtIVfJJ35w](https://youtu.be/pVtIVfJJ35w)
