### ISSUE TITLE
CrossFirebasePushNotification.Current.Subscribe("") not working

### ISSUE THREAD

**Issue by JosFran21** [CrossGeeks/FirebasePushNotificationPlugin#294]
Hello

I started using the pluging, I have done the Getting Started section, I received the push notification sent directly from Firebase console and everything was good.

When I tried to make a POST request from Postman I received the next output:

{
    "multicast_id": 6409843917424094875,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "InvalidRegistration"
        }
    ]
}

The payload is:

{ "notification": {
 "title": "Portugal vs. Denmark",
 "body": "5 to 1"
},
 "content_available": true,
 "priority": "high",
 "to": "/test/testing"
}

I'ven searching and when I tried to look at my device token I realized the method CrossFirebasePushNotification.Current.OnTokenRefresh was never been called, looking into the issues section i notice my RegisteredForRemoteNotifications method was not receiving the same output as others, I'm receiving something like this:

{length = 32, bytes = 0x9845a651 ................ }

So I don't know what I am doing wrong, please let me know if you need more information, this is my first time publishing an issue, and thanks in advance for the help.

Version Number of Plugin: 3.1.6
Device Tested On: iPhone 11 Pro Max iOS 13.3
Version of VS: 8.3.10
Version of Xamarin: 4.4.0.991477

**Comment by JosFran21** [comment]
In the payload, I've changed the "to" part, now looks like this:

{ "notification": {
 "title": "Portugal vs. Denmark",
 "body": "5 to 1"
},
 "content_available": true,
 "priority": "high",
 "to": "/topics/pruebas"
}


And that change make my response to be different:

{
    "message_id": 67373555848118179
}


So I guess there is something missing in my code, but I have not found it.

**Comment by JosFran21** [comment]
I make a breakpoint in here

CrossFirebasePushNotification.Current.Subscribe("/topics/pruebas");
(on my AppDelegate)

and I discovered here is my device token, so i just tried the function using the token in the "to" section in my postman and it worked.


So I don't know how can I send the notification to all my users, using "/topics/my-topic" as documentation says didn't work for me, any help would be nice.

**Comment by JosFran21** [comment]
Ok, the problem is that I am not subscribing to any topic, I can say this because inside the breakpoint where I get my device token I can see there is nothing in the topics section

So what is the correct way to subscribe? Because I am doing it in FinishedLaunching it my AppDelegate.

And even I tried in OnStart in my App.cs (XamarinForms) and nothing has worked.

**Comment by mimunoz** [comment]
Hi, I have the subscribe in App.cs and it works as expected,

```
protected override void OnStart()
{ 
    // Handle when your app starts
    CrossFirebasePushNotification.Current.Subscribe("General");
    CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) => { ... }
...
}
```

Did you read the next [doc(FirebaseNotifications)](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FirebaseNotifications.md)?

**Comment by JosFran21** [comment]
Hello @mimunoz I have the subscribe in App.ccs too, but it still not working, and yes I have read the documentation, and I don't think is a problem with the way I send the notification via Postman, I think I am missing something, but I still don't know what.

Thank you for your reply.

**Comment by JosFran21** [comment]
Ok so I finally could subscribe to topics, and now I have working my notifications!!!

What did I do?

I have to downgrade the plugin, I was using 3.1.6 and using 3.0.22 was the solution, I think there is a problem with the last version.

Thank you so much!
