### ISSUE TITLE
Receiving success response but not notification showed

### ISSUE THREAD

**Issue by JosFran21** [CrossGeeks/FirebasePushNotificationPlugin#298]
Hello, I am having an issue, I am getting a response from Postman like this:

{
    "multicast_id": 4791289050690316244,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1582307649128863%aa441352aa441352"
        }
    ]
}

but I am not receiving notifications on my device, and also if I try to send a notification from the console in Firebase I am not receiving neither the notification.

I don't have problem with the device key generated and also I am subscribing to topics, so I don't know what I am missing.

Version Number of Plugin: 3.0.22
Device Tested On: iPhone 7 and 11 Pro Max iOS 13.3
Version of VS: 8.3.10
Version of Xamarin: 4.4.0.991477

**Comment by lngka** [comment]
I would like to report the same issue. I tried to rebuild multiple times with different devices. Notifications are always successfully sent but only received on iOS 12. 

Both the beta and latest stable version did not work

Plugin Version: 3.1.6 and 3.1.9 beta
VS: 16.4.2
iOS : 13.3.1
Xamarin: 4.4.0.991265

**Comment by JosFran21** [comment]
Hi @lngka I solve this by changing the value of FirebaseAppDelegateProxyEnabled in info.plist to true, let me know if this fix your problem.

**Comment by lngka** [comment]
@JosFran21 Thanks for the tips, but it didn't work for me.

I have a feeling that this might be iOS 13.3.1 trying to save battery by aggressively killing apps. The same behavior can be archived by manually killing the app (swipe up), which kill the DidReceiveRemoteNotification Handler while retaining the normal Push Notification message.

At the moment we are having a "wakeup" topic message which is sent to all iOS devices every 10 minutes to keep the DidReceiveRemoteNotification alive
