### ISSUE TITLE
notification in foreground with firebase console

### ISSUE THREAD

**Issue by angelru** [CrossGeeks/FirebasePushNotificationPlugin#299]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below.

Failure to fill out this information will result in this issue being closed. If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

Bug Information:
When my app is in foreground i am recieving the notification in notification trray.

Version Number of Plugin:3.1.6
Device Tested On: Xiaomi
Version of VS: 2019
Versions of other things you are using:
Xamarin Forms: 4.5

Steps to reproduce the Behavior
When my app is in foreground i am recieving the notification in notification trray.

Expected Behavior
When my app is in foreground it should not be reflrect in notification tray.

**Comment by Nadezhda-Popova** [comment]
Is there an update on this issue. I am still getting notification regardless of its type, event data massages have empty notification.

**Comment by angelru** [comment]
@rdelrosario any updates?
