### ISSUE TITLE
push notification not getting received

### ISSUE THREAD

**Issue by eyacoub** [CrossGeeks/FirebasePushNotificationPlugin#3]
CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) not getting fired on android and IOS

## Bug Information

Version Number of Plugin:1.0.4
Device Tested On:Samsung S5 android 6.0
Simulator Tested On:
Version of VS: visual studio for mac
Version of Xamarin:2.3.4
Versions of other things you are using:

**Comment by rdelrosario** [comment]
Did you get the token?

Can you put the payloads you are sending from the server?

**Comment by Nandulucky** [comment]
What about iOS?
I'm not receiving in iOS
