### ISSUE TITLE
Is it possible to test Push Notification using Genymotion Emulator for Android?

### ISSUE THREAD

**Issue by VictorK1902** [CrossGeeks/FirebasePushNotificationPlugin#30]
Also whats the minimum API requirement for Android? While installing the Plugin I had some version incompatibility. I ended up downloading the latest SDK and set the minimum (and target) API to be 24 (7.0). But I'm still having issue deploying the app to emulator, it keeps saying "FirebaseApp initialization unsuccessful".

I checked the logs and noticed that only the following Firebase-related assembly are loaded:

    Loaded assembly: /storage/emulated/0/Android/data/com.Test.Droid.QA/files/.__override__/Plugin.FirebasePushNotification.Abstractions.dll [External]
    Loaded assembly: /storage/emulated/0/Android/data/com.Test.Droid.QA/files/.__override__/Plugin.FirebasePushNotification.dll [External]
    Loaded assembly: /storage/emulated/0/Android/data/com.Test.Droid.QA/files/.__override__/Plugin.Messaging.Abstractions.dll [External]
    Loaded assembly: /storage/emulated/0/Android/data/com.Test.Droid.QA/files/.__override__/Plugin.Messaging.dll [External]
    Loaded assembly: /storage/emulated/0/Android/data/com.Test.Droid.QA/files/.__override__/Plugin.Settings.Abstractions.dll [External]
    Loaded assembly: /storage/emulated/0/Android/data/com.Test.Droid.QA/files/.__override__/Plugin.Settings.dll [External]

    Loaded assembly: /storage/emulated/0/Android/data/com.Test.Droid.QA/files/.__override__/Xamarin.Firebase.Common.dll [External]
    Loaded assembly: /storage/emulated/0/Android/data/com.Test.Droid.QA/files/.__override__/Xamarin.Firebase.Iid.dll [External]
    Loaded assembly: /storage/emulated/0/Android/data/com.Test.Droid.QA/files/.__override__/Xamarin.Firebase.Messaging.dll [External]

**Comment by VictorK1902** [comment]
I upgraded Genymotion to 2.1 which comes with Open GApps which then help install Google Play Service. I was able to get the token but still unable to receive the notification. The device is not counted towards monthly active user in FireBase Console DashBoard.

**Comment by rdelrosario** [comment]
It requires Android 7.0 as target because relays on Firebase Cloud Messaging package which needs Android 7.0 as target.
