### ISSUE TITLE
[iOS] Tapping on Notification crashes the app when the app is closed/killed/terminated

### ISSUE THREAD

**Issue by VictorK1902** [CrossGeeks/FirebasePushNotificationPlugin#300]
## Bug Information

Version Number of Plugin: 3.0.22
Device Tested On: iPhone 8 plus, iOS 13.1
Simulator Tested On:
Version of VS:  Microsoft Visual Studio Professional 2019 version 16.4.2
Version of Xamarin: Xamarin Forms 4.4.0.991640
Versions of other things you are using:

### Steps to reproduce the Behavior
Receiving a Push Notification while app is killed/terminated/closed.

### Expected Behavior
Tapping on Notification launches the app without crashing.
### Actual Behavior
App is launched and then crashes after a second or two.

### Code snippet

    public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler) {
        FirebasePushNotificationManager.DidReceiveMessage(userInfo);        
        // custom logic goes here
        completionHandler(UIBackgroundFetchResult.NewData);
    }

### Screenshots

This uses to work fine but I started getting the crash recently (details explained above).

The current fix for now is to comment the following line out:

    FirebasePushNotificationManager.DidReceiveMessage(userInfo);   

The comment for this mention method swizzling but I'm not entirely sure what it means:

        // If you disable method swizzling, you'll need to call this method. 
        // This lets FCM track message delivery and analytics, which is performed
        // automatically with method swizzling enabled.

**Comment by 15mgm15** [comment]
@VictorK1902 Did you find a solution to this?

**Comment by arditmezini** [comment]
> @VictorK1902 Did you find a solution to this?
The bug is still there.
Use the workaround to comment the line.

**Comment by arditmezini** [comment]
The bug is still there @15mgm15 .
Use the workaround to comment the line.

**Comment by anilrawatGH** [comment]
@VictorK1902 
Are you able to resolve your issue ? 
Did you find a solution to this?
