### ISSUE TITLE
RegisteredForRemoteNotifications is not called on iOS 13

### ISSUE THREAD

**Issue by WanftMoon** [CrossGeeks/FirebasePushNotificationPlugin#301]
## Bug Information

Version Number of Plugin: 3.16
Device Tested On: iPhone 8 (iOS 13)
Simulator Tested On: N/A
Version of VS:  VSMac (8.4.8 build 2)
Version of Xamarin: 4.5.0.356
Versions of other things you are using:
<img width="323" alt="Screen Shot 2020-03-05 at 16 48 07" src="https://user-images.githubusercontent.com/20956737/76019858-2a72e400-5f01-11ea-8b4f-34fe150305e0.png">

### Steps to reproduce the Behavior

Follow read.me:

1. setup xam forms project
2. setup firebase push notification plugin and dependencies
3. setup firebase site with apns certificates.

### Expected Behavior

To work on iOS 13. the same code works on iOS 12 devices + Android.

### Actual Behavior

It does not work on iOS 13.

### Code snippet

public override bool FinishedLaunching(UIApplication uiApplication, NSDictionary launchOptions)
        {
            global::Xamarin.Forms.Forms.SetFlags(
                "Shell_Experimental",
                "Visual_Experimental",
                "CollectionView_Experimental",
                "CarouselView_Experimental",
                "SwipeView_Experimental");
            global::Xamarin.Forms.Forms.Init();
 
            LoadApplication(new App());
      
            FirebasePushNotificationManager.Initialize(launchOptions, true);
            FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Badge | UNNotificationPresentationOptions.Sound;

            return base.FinishedLaunching(uiApplication, launchOptions);
        }

        /// <summary>
        /// THIS METHOD IS NOT CALLED ON IOS 13
        /// </summary>
        /// <param name="application"></param>
        /// <param name="deviceToken"></param>
        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken);
        }

### Screenshots

N/A

**Comment by js-ka** [comment]
Same here.
The method RegisteredForRemoteNotifications is never called on a device running iOS 13.
Therefore no notifications can be received under iOS 13.

**Comment by Lydecker** [comment]
no issues here on iOS 13.3.x or 13.4

**Comment by valentin-debris** [comment]
I'm facing the same issue. In iOS 12, it works great, but when I try with a device under iOS13, the registration is never called.
Maybe this is the main problem : https://dev.to/codeprototype/correctly-capture-ios-13-device-token-in-xamarin-1968

**Comment by Lydecker** [comment]
@valentin-debris the part that you have linked to has been implemented in this library.

I have this working great in iOS13 which is making me thing you might be missing a config somewhere - as the current version of the lib def works in iOS13....

**Comment by valentin-debris** [comment]
@Lydecker , what version of the plugin are you using ? The latest stable or the beta one ? 
The strange thing is if I plug an iPhone with iOS12, no problem, but the other one under 13 doesn't trigger the overrided functions at all...

**Comment by Lydecker** [comment]
@valentin-debris 3.1.6 (and I'm not using one of the forks of the main repository). 

What about yourself?

**Comment by valentin-debris** [comment]
@Lydecker , I ended up make it works. I was using the beta one (3.2.9), but getting back to 3.16 AND adding the nuget Xamarin.ios.CloudMessaging (4.1.1) works now. Without the CloudMessaging, the app crashs.
src : https://github.com/xamarin/GoogleApisForiOSComponents/issues/311#issuecomment-546046465
