### ISSUE TITLE
Incompatible with the latest version of Xamarin.Google.iOS.MobileAds (7.53.1)

### ISSUE THREAD

**Issue by dsancho** [CrossGeeks/FirebasePushNotificationPlugin#302]
## Bug Information

Version Number of Plugin: 3.1.6
Device Tested On: iPad (6th generation) iOS 13.3
Simulator Tested On: iPhone 8 iOS 13.3
Version of VS: 16.4.5 Community
Version of Xamarin: Xamarin Forms 4.4.0.991757
Versions of other things you are using: Xamarin.Google.iOS.MobileAds 7.53.1

### Steps to reproduce the Behavior
* Create a new Xamarin Forms app targeting iOS
* Update Xamarin Forms to version 4.4.0.991757
* Install Plugin.FirebasePushNotification 3.1.6
* Install Xamarin.Google.iOS.MobileAds 7.53.1

### Expected Behavior
Application run normally

### Actual Behavior
Application doesn't run. It starts and it's closed even before AppDelegate.FinishedLaunching it's called. No error it's thrown in the debugger.

### Code snippet
No code snippet need but I suppose it has to be with the version of Xamarin.Build.Download or Xamarin.Firebase.iOS.Core. This is what I see after installing Xamarin.Google.iOS.MobileAds:
Successfully uninstalled 'Xamarin.Build.Download 0.4.11' from FirebasePushIOSError.iOS
Successfully uninstalled 'Xamarin.Firebase.iOS.Core 6.1.0' from FirebasePushIOSError.iOS
Successfully installed 'Xamarin.Build.Download 0.9.0' to FirebasePushIOSError.iOS
Successfully installed 'Xamarin.Firebase.iOS.Core 6.6.0' to FirebasePushIOSError.iOS
Successfully installed 'Xamarin.Google.iOS.MobileAds 7.53.1' to FirebasePushIOSError.iOS

### Workaround
Install Xamarin.Google.iOS.MobileAds 7.47.0.1

**Comment by galadril** [comment]
I have the same issue.. iOS app doens't even start anymore (no logs) with this library installed

**Comment by dsancho** [comment]
I tried with latest version Xamarin.Google.iOS.MobileAds 7.57 but no luck.

I revert to Xamarin.Google.iOS.MobileAds 7.47.0.1.
