### ISSUE TITLE
Error while installing latest version of plugin

### ISSUE THREAD

**Issue by devWaleed** [CrossGeeks/FirebasePushNotificationPlugin#304]
## Bug Information

Version Number of Plugin: 3.1.6
Device Tested On: Windows 10
Simulator Tested On: iPhone 6s simulator with iOS 13.2
Version of VS: VS 2019
Version of Xamarin: Xamarin 4.5

## What's happening

Failing to install plugin on Xamarin 4.5, getting error:

Failed to add reference. The package 'Plugin.FirebasePushNotification' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component.

**Comment by devWaleed** [comment]
Error while trying a downgraded version as well

Version Number of Plugin: 2.3.6
Device Tested On: Windows 10
Simulator Tested On: iPhone 6s simulator with iOS 13.2
Version of VS: VS 2019
Version of Xamarin: Xamarin 4.4

Errors:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		] in FirebaseAnalytics(FIRAMeasurement_41f8c6ad6e1fd9e66100bee4ee2fdd35.o)	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		] in FirebaseAnalytics(FIRAMeasurement_41f8c6ad6e1fd9e66100bee4ee2fdd35.o)	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		] in FirebaseAnalytics(FIRAMeasurement_41f8c6ad6e1fd9e66100bee4ee2fdd35.o)	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		] in FirebaseAnalytics(FIRAMeasurement_41f8c6ad6e1fd9e66100bee4ee2fdd35.o)	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		] in FirebaseAnalytics(FIRADatabase_b4754c28a9ffffb63e9f2c51c2b58746.o)	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		] in FirebaseAnalytics(FIRADatabase_b4754c28a9ffffb63e9f2c51c2b58746.o)	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed. Please review the build log.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/mac/Library/Caches/Xamarin/mtbs/builds/mynamespace.forapps/9ef5ee707914368446455c2cad481b23/obj/iPhoneSimulator/Debug/Entitlements.xcent	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_two_pass_encoding. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_set_uint64. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_set_uint32. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_set_string. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_set_float. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_set_double. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_set_bool. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_init_array_info. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_free_string. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_encode_string. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_encode_repeated_uint64. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_encode_repeated_string. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_decode_string. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_decode_repeated_uint64. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _nano_decode_repeated_string. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOSetString. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOSetMessage. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOSetInt64. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOSetInt32. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOSetDouble. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOSetBool. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOSetArray. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOHasField. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOGetString. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOGetMessage. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOGetInt64. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOGetInt32. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOGetDouble. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOGetBool. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOGetArray. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _NANOClearField. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _kFIRNetworkHTTPStatusOK. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _kFIRNetworkHTTPStatusNoContent. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _kFIRNetworkHTTPStatusCodeUnavailable. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _kFIRNetworkHTTPStatusCodeNotModified. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _kFIRNetworkHTTPStatusCodeNotFound. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined symbol: _kFIRNetworkHTTPStatusCodeCannotAcceptTraffic. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined Objective-C class: FIRNetwork. The symbol '_OBJC_CLASS_$_FIRNetwork' could not be found in any of the libraries or frameworks linked with your application.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		Native linking failed, undefined Objective-C class: FIRMutableDictionary. The symbol '_OBJC_CLASS_$_FIRMutableDictionary' could not be found in any of the libraries or frameworks linked with your application.	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
> Error		linker command failed with exit code 1 (use -v to see invocation)	mynamespace.forapps	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	842	
>

**Comment by leocarona** [comment]
Hey. I'm experiencing the same erros while trying to upgrade plugin.firebasepushnotification from version 3.0.22 to verion 3.1.6 or later.
