### ISSUE TITLE
iOS OnNotificationOpened not firing from terminated app? - here's why

### ISSUE THREAD

**Issue by Lydecker** [CrossGeeks/FirebasePushNotificationPlugin#315]
Just a heads up - I was trying to figure out why `OnNotificationOpened `wasn't being fired when the app was being launched from a push notification (i.e the app is terminated, and you launch it by tapping on a notification). It turns out it was because there is core code commented out in this library's source:

![image](https://user-images.githubusercontent.com/12632602/81122287-84575080-8f28-11ea-8695-7072c705edf5.png)

As soon as I uncommented this - everything works on iOS as expected!

Would love an explanation as to why this is commented out....

**Comment by mimunoz** [comment]
@rdelrosario can you explain please?

**Comment by almirvuk** [comment]
Same here :( OnNotificationOpened is not called when the app is terminated and push notification is clicked.

**Comment by rdelrosario** [comment]
Actually I will update the code over the weekend uncommenting this and working with other needed fixes.

The reason this was commented was because at some point didn't seem to be needed.

**Comment by Lydecker** [comment]
Hi @rdelrosario ,

Thanks for spending time working on this this weekend.

Please can you also test `autoRegister = false` on BOTH Android and iOS. Currently it works on neither platform as expected (although the incorrect behaviour is different on each platform) #303  #307

**Comment by rdelrosario** [comment]
Can you let me know on which version is happening? On latest beta version?

**Comment by ivandharo** [comment]
@rdelrosario 
Hi rendy, i want to report this bug, when i use the code below to change default channelid and name, firebase still sending notifications through miscellaneous channel, why it's happening?

FirebasePushNotificationManager.DefaultNotificationChannelId = "General";

**Comment by Lydecker** [comment]
> Can you let me know on which version is happening? On latest beta version?

Hi @rdelrosario - people are experiencing the `autoRegister = false` issues on the latest version 3.1.6.

**Comment by almirvuk** [comment]
Hi @rdelrosario thank you for your weekend work on this one!

I have updated the project to 3.3.10, and I am experiencing the same behaviour, works fine when app is running and not terminated.

My setup code: 

`     FirebasePushNotificationManager.Initialize(options);

       FirebasePushNotificationManager.CurrentNotificationPresentationOption =
                UserNotifications.UNNotificationPresentationOptions.Alert |
                UserNotifications.UNNotificationPresentationOptions.Badge;

         return base.FinishedLaunching(app, options);
     }

     public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
     {
          FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken);
     }

     public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
     {
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);
     }
     
     public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
     {
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
            
            completionHandler(UIBackgroundFetchResult.NewData);
      }`

Notification payload contains, priority: high, for iOS I am using the notification part of payload, and notification is received but OnNotificationOpened, is not called when the app is terminated completely. Do I need to add something else, is it something wrong on my side of setup.

Thanks!

**Comment by almirvuk** [comment]
I was testing this via multiple notifications, and one of the times this worked. Not sure why, I have also added some bool value to Xamarin.Essentials Preferences just to set it before any other actions inside of OnNotificationOpened, just to check if my sample project (MasterDetail template from VS New Project) has race condition between ctor and OnNotificationOpened, but the value stays **false**.

But it is weird that it worked once in this testing, once again the problem is when the app is closed, terminated completely.

**Comment by almirvuk** [comment]
@Lydecker have you tested new version?

**Comment by almirvuk** [comment]
Just tested again, it has some kind of issue when the app is terminated. I received the notification, opened the app manually by clicking on the icon, and then tapped on the received notification and it worked, it triggered the OnNotificationOpened. But only if app was running already

**Comment by almirvuk** [comment]
I just moved the **CrossFirebasePushNotification.Current.OnNotificationOpened** to the **ctor** and it works fine like that, previously it was inside of **OnStart** method just like in sample project. It seems to work just fine when that part of code is inside of ctor. I will test this more and let you know.

**Comment by Lydecker** [comment]
Hi haven't had a chance to test yet... will do soon.

What do you mean 'ctor' ?

**Comment by almirvuk** [comment]
Constructor... I just edited the replies.

**Comment by Lydecker** [comment]
When you say constructor - do you mean in

```
   public App()
        {

}
```

?

Also what version of Xamarin.Forms are you using?

I'll trial the new plugin in a blank project in the next  48 hours and report back....

**Comment by almirvuk** [comment]
Yes, the constructor of App.cs class, latest XF.

**Comment by Lydecker** [comment]
Hi @almirvuk 

I have now tested the 3.1.10 with Android using the latest version of XF 4.4.x (i'm sticking with 4.4 in android due to issues in 4.5 and 4.6 on Android.

My findings when using this with a clean project are:

1) You still need to manually add the Xamarin.Firebase.Common library to the android project
2) autoRegister = false does not work in the init function
3) I sometimes get multiple calls of OnTokenRefresh
4) OnNotificationOpened is called EVERY time the app is launched, not only when the app is launched from a notification. In the scenario when it is called not from a notification being clicked on, the only data supplied is a key called 'profile' with a value of 0.

Otherwise - things work as expected, including events being fired when the app is terminated.

Do you experience the same issues as above?

I'll move onto iOS shortly and report back.
