### ISSUE TITLE
OnNotificationOpened never executed.

### ISSUE THREAD

**Issue by ahmedelsyaed** [CrossGeeks/FirebasePushNotificationPlugin#32]
device : android 6
plugin.firebasepushnotification : 1.0.7-beta

Hello I have a problem with OnNotificationOpened .

i successfully send and receive notification message ,  i added in main activity

>     protected override void OnNewIntent(Intent intent)
>         {
>             FirebasePushNotificationManager.ProcessIntent(intent);
>             base.OnNewIntent(intent);
>         }
but nothing has been change.

**Comment by rdelrosario** [comment]
Are you calling process intent on activity OnCreate method?

Could you put here your MainActivity code?

**Comment by ahmedelsyaed** [comment]
` protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            PullToRefreshLayoutRenderer.Init();
            ImageCircleRenderer.Init();
            LoadApplication(new App(new AndroidInitializer()));
            FirebasePushNotificationManager.ProcessIntent(Intent);
            
        }

        protected override void OnNewIntent(Intent intent)
        {
            FirebasePushNotificationManager.ProcessIntent(intent);
            base.OnNewIntent(intent);
        }
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Permission[] grantResults)
        {
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }
    public class AndroidInitializer : IPlatformInitializer
    {
        public void RegisterTypes(DryIoc.IContainer container)
        {

        }
    }`

**Comment by rdelrosario** [comment]
Do you get the notification on OnNotificationReceived ?

**Comment by ahmedelsyaed** [comment]
yeah i get notification on OnNotificationReceived, Besides OnNewIntent never triggered too.

**Comment by rdelrosario** [comment]
What's the launchmode of your activity?

**Comment by ahmedelsyaed** [comment]
LaunchMode = LaunchMode.SingleTop

**Comment by rdelrosario** [comment]
What's the payload you are sending?

**Comment by ahmedelsyaed** [comment]
{
   "data": 
   {
    "body" : "Body",
    "other_key" : true,
    "title" : "Title",
    "click_action":"message"
   },
     "priority": "high",
     "condition": "'general' in topics"
}

**Comment by rdelrosario** [comment]
So when you tap on the notification OnNotificationOpened doesn't get fired? Did you tried with the stable version?

**Comment by ahmedelsyaed** [comment]
not yet , i will try it right now .

**Comment by ahmedelsyaed** [comment]
the issue is that the  main activity  MainLauncher = false because i have splash activity for splash activity which have the MainLauncher= true.

what i have done is that in splash activity is

```
>  public class SplashActivity : Activity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            //Thread.Sleep(1000);
            StartActivity(typeof(MainActivity));
            FirebasePushNotificationManager.ProcessIntent(Intent);
            // Create your application here
        }
        protected override void OnNewIntent(Intent intent)
        {
            FirebasePushNotificationManager.ProcessIntent(intent);
            base.OnNewIntent(intent);
        }
    }
```
and i Removed FirebasePushNotificationManager.ProcessIntent(Intent) and OnNewIntent from the main activity.

now OnNotificationOpened has been triggered successfully. I do not know if that is most optimal solution or not so I wish add another solution if exist.

After solving it I would like to ask about A scenario that say I want to push two Different notification to  App  and according to the Click_Action on that notification i want to open a specific page for each notification, is it a good practice if I set a  "click_action":"message" in the payload and then in the OnNotificationOpened 

>  CrossFirebasePushNotification.Current.OnNotificationOpened += (s, p) =>
>             {
>                 if (p.Data.Values.Contains("message"))
>                 {
>                     
>                     NavigationService.NavigateAsync("NavigationPage/LoginPage");
>                     return;
>                 }
>                 else
>                 {
>                     NavigationService.NavigateAsync("NavigationPage/MainPage");
>                     return;
>                 }
>          }

thank you.

**Comment by rdelrosario** [comment]
The use of "click_action" is more about if you got multiple types of notifications that execute different actions. check the [Notification Actions](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/NotificationActions.md) section.

For your specific use case, I think you don't need it because seems you are not using actions or are you?

**Comment by ahmedelsyaed** [comment]
I manage to have multiple click_action .e.g(message,acceptance,news) and according to each one I will navigate to a specific page .

**Comment by rdelrosario** [comment]
Ok is fine then. You could use it or even use a custom new key for that.

**Comment by rdelrosario** [comment]
Either approach works just fine. If you are adding action buttons to the notification in the future definitely click_action key is the way to go.

**Comment by bhargavkumar040** [comment]
Hi, i heave face same problem. i followed above steps also but no use.
Can you suggest how it will resolve it.

**Comment by mimunoz** [comment]
@bhargavkumar040 I had the same problem, but with this I solved it. Follow the steps of @ahmedelsyaed "Removed FirebasePushNotificationManager.ProcessIntent(Intent) and OnNewIntent from the main activity", then put that code in the splash activity(what has MainLauncher=true). With that OnNotificationOpened event works in App class.

Regards.
