### ISSUE TITLE
Deprecated api used Firebase Messaging iOS Direct Channel

### ISSUE THREAD

**Issue by bluejeff31** [CrossGeeks/FirebasePushNotificationPlugin#322]
## 🐛 Bug Report

the firebase team has announced that Firebase Messaging iOS Direct Channel will be removed.  This plugin sets up direct connection:
https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/Plugin.FirebasePushNotification/FirebasePushNotificationManager.ios.cs#L239

can't APNs be used instead?

**Platform:** 
- [x] :iphone: iOS

**Comment by Cliffy786** [comment]
**MY COMMENT IS NOT A SOLUTION, IT'S EMPHASIS**

I Received the exact email from the firebase team not so long ago. Are there any plans in regard to this plugin to deal with the depreciation of the iOS Direct Channel ?
