### ISSUE TITLE
Data Messages

### ISSUE THREAD

**Issue by polieadie** [CrossGeeks/FirebasePushNotificationPlugin#325]
If I use Notification Message then I receive a push notification but limited to handle which activity to show.
The I tried using Data Message but here are my questions:
1. I don't receive a push notification, is it correct?
2. Is there a way for this plugin that I would still receive a push notification using Data Message?
Thanks.
Payload:
{"registration_ids":["key1","key2"],"data":{"title":"Polie Adie","body":"test","msg":"message","other_key":"true t","click_action":"Open_Activity 1"},"priority":"high"}

**Comment by angelru** [comment]
notification not showing at the top?

**Comment by polieadie** [comment]
If you mean using Data Message and not showing at the notification tray then YES.

**Comment by angelru** [comment]
The use of data messages and without "silence" "true" should appear in the tray, but does not appear

**Comment by polieadie** [comment]
I found the solution/work around somehow.
I used this payload:
{
    "data": {
        "message" : "my_custom_value",
        "notif_id": "asdf11"
        "body":"test"
     },
     "notification": {
       "body" : "evening",
       "title": "PAN JULIES",
        "content_available" : true
     },
     "priority": "high",
     "registration_ids": ["key"]
}
With this, notification from Firebase is shown.
Then onclick, you can then handle the "data" via Intent.

**Comment by angelru** [comment]
@polieadie #326

**Comment by polieadie** [comment]
@angelru 
still not working in my case.

**Comment by polieadie** [comment]
I receive the message but notification is not shown on tray.

**Comment by polieadie** [comment]
I really don't know what is missing in my case.
I already updated all my packages and still data messages does not show notification on tray.
Any suggestions for further checking? @rdelrosario 
Thanks

**Comment by angelru** [comment]
I am using the firebase sdk to send the notification
`https://github.com/firebase/firebase-admin-dotnet`

```
    var data = new Dictionary<string, string>
            {
                { "body", "Hello" },
                { "priority", "high" },
                { "silent", "false" },
                { "other_key", "true" }
            };

            var message = new Message
            {
                Android = new AndroidConfig
                {
                    Priority = Priority.High
                },

                //Token = token,
                Data = data,
                Topic = "topic"
            };
```

**Comment by polieadie** [comment]
I will try but based on documentation I can also use Postman for testing which I am doing.
Do you think it has some difference if I use Postman for testing?

**Comment by angelru** [comment]
it should work with the postman too, i just tried and everything is ok make sure you have the latest version of xamarin forms too

**Comment by polieadie** [comment]
I will try to create really a new app.
I was actually testing on my existing app so maybe there are some conflicts on it.
Will give you feedback asap.
Thanks.

**Comment by polieadie** [comment]
I am actually hoping some insights also from @rdelrosario :)

**Comment by polieadie** [comment]
Working now after updating everything.
