### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by angelru** [CrossGeeks/FirebasePushNotificationPlugin#326]
Hello,

```
            var data = new Dictionary<string, string>
            {
               { "body", "hola" },
               { "message", "hola" },
               { "id", "1" },
               { "other_key", "true" }
            };
```

```
            var message = new Message
            {
                Android = new AndroidConfig
                {
                    Priority = Priority.High
                },

                Token = token,
                //Notification = notification,
                Data = data,
                //Topic = "general"
            };
```

I get the notification and the event fires, but it doesn't show the notification in the tray, I have the application in the foreground

**Comment by rdelrosario** [comment]
Add "priority" : "high"

To data payload

**Comment by polieadie** [comment]
I just used this payload:
{
    "data": {
        "message" : "hola",
        "body":"test",
        "title":"title",
        "id": "1"
     },
     "priority": "high",
     "registration_ids": ["Key"]
}
Notification is still not shown on the tray.
What else could we try? @rdelrosario

**Comment by angelru** [comment]
@polieadie  

```
"data": {
"message" : "hola",
"body":"test",
"title":"title",
"priority": "high",
"id": "1"
}
```

now i can't prove
