### ISSUE TITLE
3.3.1 Breaks iOS notifications

### ISSUE THREAD

**Issue by seanmt13** [CrossGeeks/FirebasePushNotificationPlugin#333]
## 🔙 Regression
I was in the process of updating my packages and wanted to update my FirebasePushNotificationPlugin from 3.1.6 to the current version 3.3.10. After doing this I noticed my notification stopped working. To make my notifications work again I don't have to make any changes to my code all I have to do is use 3.1.6 and my notifications start working again. This leads me to believe there has been a change in the library. Has there been any breaking changes that require a different implementation from 3.1.6 to the newest version?
 

### Old (and correct) behavior
Receive a push notification with the following code

```
CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
{
     System.Diagnostics.Debug.WriteLine("Received");
     Do stuff with the message....
}
```
If I am subscribed to a topic and send a notification this method will be called.
### Current behavior
OnNotificationReceived is never called.

I have verified that the library at least thinks I am subscribed to the topic using this command.
```
var topics = CrossFirebasePushNotification.Current.SubscribedTopics;
```
### Reproduction steps
update FirebasePushNotificationPlugin from 3.1.6 to 3.3.10
### Configuration

**Version:** 3.3.10

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by gioggio79** [comment]
Any news or workaround with this problem?
In iOS if I try tu use a Subscriber no push notification arrived.

`
CrossFirebasePushNotification.Current.UnsubscribeAll();

List<string> subscriber = new List<string>();

subscriber.Add("Challenge" + platform + App.UserLang.ToUpper());

subscriber.Add("News" + platform + App.UserLang.ToUpper());

CrossFirebasePushNotification.Current.Subscribe(subscriber.ToArray());
`
Android works perfecly.
Other iOS notifications without Subscribe or with FirebaseID works perfecly

**Configuration**
Version: 3.3.10

Xamarin.Firebase.iOS.Core 6.6.6
Xamarin.Firebase.iOS.InstanceID 4.3.3
Xamarin.Firebase.iOS.CloudMessaging 4.3.0

Xamarin.Forms 4.7.0.1080

**Comment by gioggio79** [comment]
I leave here a really TMP workaround:

if (Device.iOS == Device.RuntimePlatform)
{
       DependencyService.Get<INotificationCustom>().RegisterForNotificationChannel("Challenge);
       DependencyService.Get<INotificationCustom>().RegisterForNotificationChannel("News");
}

INotificationCustom
public void RegisterForNotificationChannel(string notificationChannel)
{
       Messaging.SharedInstance.Subscribe($"{notificationChannel}");
}

I really don't know why the plugin doesn't work, i browse the code and the metod is the same...

**Comment by banjahman** [comment]
experiencing the same issue here.. Any updates?

**Comment by seanmt13** [comment]
I am no longer seeing the issue with the latest package.

**Comment by DeanZhuo** [comment]
still having this issue...

> I leave here a really TMP workaround:
> 
> if (Device.iOS == Device.RuntimePlatform)
> {
> DependencyService.Get().RegisterForNotificationChannel("Challenge);
> DependencyService.Get().RegisterForNotificationChannel("News");
> }
> 
> INotificationCustom
> public void RegisterForNotificationChannel(string notificationChannel)
> {
> Messaging.SharedInstance.Subscribe($"{notificationChannel}");
> }
> 
> I really don't know why the plugin doesn't work, i browse the code and the metod is the same...

but thanks to gioggio79 for theworkaround

**Comment by DeanZhuo** [comment]
got mine working. when I subscribed to "News" and send a notification via firebase console with the topic "News", it does subscribe but no notification received. mine works after I unsubscribe "News", subscribe to "NEWS", and send a notification with the topic "NEWS". I dunno, but maybe I shouldn't use mixed case letters? an explanation would help.
