### ISSUE TITLE
UIWebView 

### ISSUE THREAD

**Issue by angelru** [CrossGeeks/FirebasePushNotificationPlugin#336]
Does this plugin refer to UIWebView?

**Comment by arditmezini** [comment]
Hi @angelru, i have used this plugin and it has no reference to UIWebView.
Follow this [https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/webview?tabs=macos#uiwebview-deprecation-and-app-store-rejection-itms-90809](uiwebview deprecation) and the problem should be fixed.
