### ISSUE TITLE
unable to send push notifications using FCM/GCM?

### ISSUE THREAD

**Issue by SatyaRamprasad** [CrossGeeks/FirebasePushNotificationPlugin#34]
Go through this link 

https://forums.xamarin.com/discussion/104452/unable-to-send-push-notifications-using-fcm-gcm/p1?new=1

**Comment by rdelrosario** [comment]
Hi this seems related to send push notifications, not to the plugin. Did you try sending with postman?

**Comment by SatyaRamprasad** [comment]
Thanks for the reply.
No, i didn't tried with postman.

**Comment by SatyaRamprasad** [comment]
Now i tried with postman.
Here is the response
{
    "message_id": 8766887908899751000,
    "error": null
}

**Comment by rdelrosario** [comment]
Are you subscribing to the topic you are sending?

**Comment by SatyaRamprasad** [comment]
No, I want to send the notification to all devices. 

 To = "/topics/all",  // to send notifications for all devices, Is this Right?

**Comment by rdelrosario** [comment]
You need to subscribe to "all", there's not such topic by default

**Comment by rdelrosario** [comment]
//Subscribing to single topic
CrossFirebasePushNotification.Current.Subscribe("all");

**Comment by SatyaRamprasad** [comment]
Where I have to paste this in ( MainApplication )?
And 
To = "/topics/all", // to send notifications to all devices, Is this Right then?

**Comment by rdelrosario** [comment]
Is this a Xamarin Forms app or an Xamarin Android app?

**Comment by SatyaRamprasad** [comment]
Xamarin Forms App(PCL)

**Comment by rdelrosario** [comment]
I would do it typically just were the sample is doing it. On the App.cs

**Comment by SatyaRamprasad** [comment]
you have added the topic as general in the OnStart method.
To = "/topics/general"  is it fine now?

**Comment by SatyaRamprasad** [comment]
Yeah,  it's working now.
Thanks for the quick answers.
And How can i send to particular user using FCMClient?

**Comment by rdelrosario** [comment]
should be just as you were doing, but not sure since haven't used much.
