### ISSUE TITLE
Notification not showing while app is open

### ISSUE THREAD

**Issue by eko94** [CrossGeeks/FirebasePushNotificationPlugin#352]
## 💬 Questions and Help

I'm using v3.3.10 for Xamarin.Forms. On Android, notifications shows while app is not open, on another app or when phone is locked but while the app is open does not shows the notification, though event "OnNotificationReceived" is called.

Also I had to add these lines on proguard config file because the app was crashing while receving a notification.
```
-dontwarn com.google.android.gms.**
-keep class com.google.android.gms.** { *; }
-keep class com.google.firebase.** { *; }
```
Also is there an option to enable vibration while receiving a notification? I know that the user can enable manually that option, though.

Android target version: 11.0
I'm testing on Android 10.0

**Comment by joseavilees** [comment]
You must add the key-value _'priority': 'high'_ in the notification payload to be shown the notification in foreground

**Comment by eko94** [comment]
> You must add the key-value _'priority': 'high'_ in the notification payload to be shown the notification in foreground

Yes, this worked! Thank you!

**Comment by yfedo** [comment]
had same issue after updating the plugin to v3.3.10 for Xamarin.Forms. On Android
and proposed fix worked))))
