### ISSUE TITLE
Notifications in Background / Foreground oddities, or am I just using it wrong?

### ISSUE THREAD

**Issue by Gekidoku** [CrossGeeks/FirebasePushNotificationPlugin#359]
OnNotificationReceived In Forms project doesnt fire in foreground but it does in background. While OnNotificationReceived in the android project fires in both (foreground/ background) cases. 

## Bug Information

Version Number of Plugin: 3.3.10
Device Tested On: OnePlus 5T, Moto 5G, Samsung XCover Pro (Device of client)

Version of VS: 2019 Pro v16.6.3
Version of Xamarin: 4.2.0.778463 (Updating soon)

Versions of other things you are using:
Service uses FirebaseAdmin to do the pushes 1.6.0 [link](https://github.com/Firebase/firebase-admin-dotnet)

### Steps to reproduce the Behavior
Not exactly installed into an empty app so not sure if any other libs have anything to do with it.
But here is the best step by step I can produce

- Install latest version of plugin in Forms, Android and iOS projects.
In Forms project:
- Register for notifications.
- Setup some functions for TokenRefresh, Recieved and Opened (simple calls that give 0 errors so cant be the cause, if you wish to know them i can add them later on)
-The OnNewIntent overwrite thing. (already had this for NFC scanning and handling those intents so i just added it)

In Android project:
- Launchmode SingleTop
- Setup a notification channel like [this](https://pastebin.com/1TP3BU01)
- in mainapplication setup a OnNotificationReceived for background handling.
Stick this in. dont want it to make a new token every boot and i want it to use my channel not a default one.
` FirebasePushNotificationManager.Initialize(this, false,false,true);`

Ignoring iOS since that didnt give an issue as far as we know.

In the service we build our push message using FirebaseAdmin.
Like [so](https://pastebin.com/Z8tvDRem). 
Prio is max / high i was playing around with it to see if it made a difference.
TimeToLive is also a recent addition

### Expected Behavior
The OnNotificationReceived in the Forms project triggers while app is foregrounded and doesnt do anything while backgrounded. (If i read the documentation correctly its not supposed to work while backgrounded)

The OnNotificationReceived in the Android project works in the background.

### Actual Behavior

The OnNotificationReceived in the Forms project doesnt work when the app is foregrounded and does trigger when the app is backgrounded.

the OnNotificationReceived  in the Android project works in both cases. 

So when the app is backgrounded it shows the notification twice.

### Notes/Workaround

Dont know if im being a tad too lazy or doing things weird. But I added a way to the android project to see if the app is currently foregrounded. And wrapped the entire OnNotificationReceived in the android project in a giant if statement.  So the android OnNotificationReceived only fires when the app is in the foreground.

What is weird to me is that it says in the FAQ that I need to initialize on the android project and have a OnNotificationReceived  in the android project. But the OnNotificationReceived in the Forms project works just fine on the background while i think its not supposed to. And the notification is not shown in the foreground if i leave out my android OnNotificationReceived.

Regarding the message type. As far as i know im sending a data type push message. However even when i edited the message to be a Notification with data it still wouldnt show the notification in the foreground and it required the android OnNotificationReceived to be the one building the notification.

Please tell me if im doing it wrong or if i have things messed up. 
If this helps others or if you need any further details let me know.

**Comment by B2alex** [comment]
how are you initializing the plugin?

**Comment by Gekidoku** [comment]
For android its in Main Activity in OnCreate just after LoadApplication(new App());
`FirebasePushNotificationManager.DefaultNotificationChannelId = "MyChannel";
            FirebasePushNotificationManager.ProcessIntent(this, Intent);`

and then in OnNewIntent I have another `FirebasePushNotificationManager.ProcessIntent(this, intent);` As the documentation recommends

**Comment by dentep** [comment]
Having the same issue on iOS now

**Comment by zizusoft** [comment]
You need to make sure you have this line in you AppDeligate.cs FinishedLaunching():

`          FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Badge | UNNotificationPresentationOptions.Sound;`

**Comment by Gekidoku** [comment]
Turns out i was doing it wrong.
in the payload i was sending the priority value with a capital. so "High". changed this to "high" and it started working :)
