### ISSUE TITLE
Unregister devices

### ISSUE THREAD

**Issue by VictorK1902** [CrossGeeks/FirebasePushNotificationPlugin#37]
Whenever the user uninstall the app, is the plugin unregistering the device by default? Or would that be something we have to handle manually?

**Comment by rdelrosario** [comment]
That cannot be handled by the app because the app has no way of knowing was uninstalled, but if reinstalled will definitely get a new token.

**Comment by rdelrosario** [comment]
But if app uninstalled you won't get any notifications if that is your concern.

**Comment by VictorK1902** [comment]
Thanks. So I guess I don't have to worry about that part then, assuming FCM will take care of cleaning up unused tokens on their end

**Comment by rdelrosario** [comment]
Right on server side is were you will do this cleanup
