### ISSUE TITLE
Using this plugin with Autofac and Shell unable to display UI elements nor redirects

### ISSUE THREAD

**Issue by wrsullivan63** [CrossGeeks/FirebasePushNotificationPlugin#381]
I'm experiencing an issue that I've tried different ways to resolve and have been unsuccessful with.  Whenever receiving a message via CrossFirebasePushNotification.Current.OnNotificationReceived I get the payload and can read it, but I can't do anything "visual" in my app.  In other words, I get the notification but when I want to either redirect to another page or even display a DisplayAlert message, nothing happens.  MessagingCenter can be received, but any instructions within the procedure that have to do with redirecting or DisplayAlert (anything changing the UI it appears) will not be executed.  
Looking for help in how to visually show in the app the user has received a message.

This is in MainShell.xaml.cs (I've also placed it in App.xaml.cs too):

`          CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {

                System.Diagnostics.Debug.WriteLine("Received");  // this works
                foreach (var data in p.Data)
                {
                    System.Diagnostics.Debug.WriteLine($"{data.Key} : {data.Value}"); // this works
                }

                //TODO:  Code to determine if user is signed in
                if (true)
                {
                    System.Diagnostics.Debug.WriteLine("Debug:  Goto Registration page from MainShell"); // this works
                    //Task.Run(async () => await Shell.Current.GoToAsync("registration"));  // this does not work (just ignores it and doesn't fire constructor)                    
                    //Task.Run(async () => await Current.DisplayAlert("Request Received", "A message is waiting...", "Ok"));  // this does not work
                    MessagingCenter.Send(this, "RequestReceived"); // this works, the receiver will display debug info, but will not redirect nor display any UI messages or interact with the UI.

                }

            };`

Thank you for any help or guidance,

Robert

**Comment by michaldivis** [comment]
@wrsullivan63 Have you figured this out?

**Comment by wrsullivan63** [comment]
I have, but I've gone in a different direction.  I'm using Prism now and everything is working the way it's supposed to.
