### ISSUE TITLE
Notifications not working on Android

### ISSUE THREAD

**Issue by Paulpetta668** [CrossGeeks/FirebasePushNotificationPlugin#393]
## 💬 Questions and Help

Hi, I am currently working on a Xamarin.Forms application, recently I added the Plugin and It worked fine on iOS (Background/Foreground) but on Android it only works when the application is in the foreground

Version Number of Plugin: 3.3.10
Device Tested On: Samsung Galaxy A8
Simulator Tested On: Google Pixel 2
Version of VS: 16.10.4

### Code Snippet
``` //Set the default notification channel for your app when running Android Oreo
            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                FirebasePushNotificationManager.DefaultNotificationChannelId = "FirebasePushNotificationChannel";

                //Change for your default notification channel name here
                FirebasePushNotificationManager.DefaultNotificationChannelName = "General";

                FirebasePushNotificationManager.DefaultNotificationChannelImportance = NotificationImportance.High;
            }

            //If debug you should reset the token each time.
#if DEBUG
            FirebasePushNotificationManager.Initialize(this, true);
#else
            FirebasePushNotificationManager.Initialize(this, false);
#endif
```
The code part that I added to the application.cs.

**Comment by Paulpetta668** [comment]
Resolved
The problem was this line:
```FirebasePushNotificationManager.DefaultNotificationChannelImportance = NotificationImportance.High;```

**Comment by euquiq** [comment]
@Paulpetta668 Hi! Maybe you can help me: I am having a similar problem: 

When app is in background, on Android and a notification arrives, if I expand the taskbar and clic on the notification, this just opens the app  ... not firing the OnNotificationReceived iniside MainApplication.cs  and also not firing the OnNotificationOpened iniside App.xaml.cs ...

I've been at this for several days now, with no luck. Thanks !
