### ISSUE TITLE
CrossFirebasePushNotification.Current.OnNotificationOpened Event is not firing

### ISSUE THREAD

**Issue by moe-uxa** [CrossGeeks/FirebasePushNotificationPlugin#40]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.0.7
Device Tested On: Huawei Mate 8
Simulator Tested On: NA
Version of VS: 2017
Version of Xamarin: 2.4.0.282
Versions of other things you are using: Android 7

### Steps to reproduce the Behavior
Open received notification from Notification Bar
### Expected Behavior
Code inside CrossFirebasePushNotification.Current.OnNotificationOpened Event executed
### Actual Behavior
Application goes to main activity and event is not fired
### Code snippet
MainActivity.cs
    [Activity(Label = "@string/app_name", Theme = "@style/MyTheme", ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);
      

            global::Xamarin.Forms.Forms.Init(this, bundle);

            LoadApplication(new App());

            FirebasePushNotificationManager.ProcessIntent(Intent);

            CrossFirebasePushNotification.Current.Subscribe("general");
        }
    }

MainApplication.cs
        public override void OnCreate()
        {
            base.OnCreate();
            RegisterActivityLifecycleCallbacks(this);

            //If debug you should reset the token each time.
           #if DEBUG
            FirebasePushNotificationManager.Initialize(this, true);
           #else
            FirebasePushNotificationManager.Initialize(this,false);
           #endif

            //Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("Received");               
            };

            CrossFirebasePushNotification.Current.OnNotificationOpened += (ss, pp) =>
            {
                //System.Diagnostics.Debug.WriteLine(p.Identifier);

                System.Diagnostics.Debug.WriteLine("Opened");
                foreach (var data in pp.Data)
                {
                    System.Diagnostics.Debug.WriteLine($"{data.Key} : {data.Value}");
                }

                if (!string.IsNullOrEmpty(pp.Identifier))
                {
                    //Device.BeginInvokeOnMainThread(() =>
                    //{
                    //    App.OpenNotification(pp.Identifier);
                    //    //textLabel.Text = p.Identifier;
                    //});
                }
                else if (pp.Data.ContainsKey("aps.alert.title"))
                {
                    //Device.BeginInvokeOnMainThread(() =>
                    //{
                    //    //textLabel.Text = p.Data["aps.alert.title"];
                    //});

                }
            };
        }

**Comment by rdelrosario** [comment]
Seems your MainActivity is not the main launcher activity ** FirebasePushNotificationManager.ProcessIntent** goes on your  activity with MainLauncher = true , as the doc says:

On your main launcher activity **OnCreate** method (On the Activity you got MainLauncher= true set)

```csharp
 FirebasePushNotificationManager.ProcessIntent(Intent);
 ```
Do you have a splash activity? 

This seems to be a duplicate of:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/32

**Comment by rdelrosario** [comment]
If this doesn't fix the issue please reopen or open a new issue.

**Comment by moe-uxa** [comment]
@rdelrosario thanks that solved my problem for now.

Yes I have a splash screen and I removed it to set the MainActivity as the main launcher, do you have any idea how to handle this case notice that LoadApplication(new App()); is in my MainActivity which wont be the main launcher if I enabled the splash screen and according to the sample, FirebasePushNotificationManager.ProcessIntent(Intent); should be placed after the LoadApplication.

**Comment by bhargavkumar040** [comment]
Hi, i heave face same problem. i followed above steps also but no use.

**Comment by ashu271994** [comment]
Hi, I am facing the same problem. I have followed above steps also but no use. Also, my " MainLauncher = true" is set to true and have followed all the steps twice.
Can you please help me to configure this problem am using Latest stable 2.3.0
