### ISSUE TITLE
DidReceiveRemoteNotification is not called on iOS 15.2. Works on iOS 15.1 and lower versions.

### ISSUE THREAD

**Issue by FIELDPOINT** [CrossGeeks/FirebasePushNotificationPlugin#402]
## 🐛 Bug Report

DidReceiveRemoteNotification is not called on iOS 15.2. Works on iOS 15.1 and lower versions

### Expected behavior
DidReceiveRemoteNotification should be called when a PN is received.

### Reproduction steps
Use any device with iOS 15.2

### Configuration
Standard. Nothing special.

**Version:** 3.3.10

**Platform:** 
- [x] :iphone: iOS 15.2
- [ ] :robot: Android 
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by FIELDPOINT** [comment]
It looks like its not supposed to call in the case I described above. So I will close this issue.

**Comment by smart4energy** [comment]
Can you describe why its not supposed to call  ?

**Comment by marthinch** [comment]
Anyone has solution for this issue? I also get the same issue here.
