### ISSUE TITLE
iOS App Has Been Terminated Problem

### ISSUE THREAD

**Issue by Hamittrpn** [CrossGeeks/FirebasePushNotificationPlugin#414]
## 🐛 Bug Report

The application I developed with **Xamarin Forms (5.0.0.2337)** does not have any problems on the Android platform. But there is a problem with the **iOS** platform and the application **crashes** at launch. 

### Reproduction steps

1. I did everything according to the documentation
2. I deployed the application with Visual Studio 2019 in debug mode for testing (**iOS Simulator and Real iOS Device**)
3. App has been terminated

### Configuration
Version: Latest stable

**Platform:** 
- [ ] :iphone: iOS
- [ ] :monkey: Xamarin.Forms

The error message and detailed log are as follows;

- "Frameworks/protobuf.framework/protobuf' (no such file)" error which is reference from FirebaseMessaging.framework."
- [crash-log.pdf](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/8106843/crash-log.pdf)

**Comment by Hamittrpn** [comment]
Hi, First of all, I would like to thank you for all your hard work.

Is there any solution about this problem?

**Comment by quintonv** [comment]
Hi did you resolve this, I am also receiving this issue and using latest Nuget packages.

I think somehow this package is referencing it but it doesn't get included.

**Comment by Hamittrpn** [comment]
I tried many things for the problem and still can't solve it. I don't know what will happen next. But my app suffered a lot from this situation.

**Comment by quintonv** [comment]
> I tried many things for the problem and still can't solve it. I don't know what will happen next. But my app suffered a lot from this situation.

Just use another library, it's this push library that references protobuf which causes it to crash in iOS.
I am going to use another library.

**Comment by Hamittrpn** [comment]
> > I tried many things for the problem and still can't solve it. I don't know what will happen next. But my app suffered a lot from this situation.
> 
> Just use another library, it's this push library that references protobuf which causes it to crash in iOS. I am going to use another library.

I think so. That's why I'm trying to use this plugin.

https://github.com/CrossGeeks/PushNotificationPlugin

 If you have any advice, please share it with me.

**Comment by quintonv** [comment]
It's not a firebase issue, my Android project works with the plugin. If the project was better maintained or more active then someone could have fixed the bug.

I am using this on iOS and Android and it is working. A little harder to setup but won't take you long at all [Xamarin.Firebase.iOS.CloudMessaging](https://www.nuget.org/packages/Xamarin.Firebase.iOS.CloudMessaging/)

**Comment by Hamittrpn** [comment]
After I wrote all the code as in _"Getting Started"_ my iOS project was crashing on first boot. It didn't say anything as an error message either. I finally found the solution to the problem. After installing this plugin, I solved my error by adding the **Xamarin.Firebase.InstanceID** and **Xamarin.Firebase.CloudMessaging** packages that it specified as dependency to the iOS project. 

Also I was using Xamarin.Firebase.iOS.Analytics package in my project. **Firebase.Core.App.Configure()** in AppDelegate when using this package; I fixed all the problems by commenting the code as well. If your iOS platform terminates at application launch in your Xamarin project, you can solve the problem by doing these.

cc// @quintonv

**Comment by quintonv** [comment]
> After I wrote all the code as in _"Getting Started"_ my iOS project was crashing on first boot. It didn't say anything as an error message either. I finally found the solution to the problem. After installing this plugin, I solved my error by adding the **Xamarin.Firebase.InstanceID** and **Xamarin.Firebase.CloudMessaging** packages that it specified as dependency to the iOS project.
> 
> Also I was using Xamarin.Firebase.iOS.Analytics package in my project. **Firebase.Core.App.Configure()** in AppDelegate when using this package; I fixed all the problems by commenting the code as well. If your iOS platform terminates at application launch in your Xamarin project, you can solve the problem by doing these.
> 
> cc// @quintonv

Thanks for the information and reply, I will give it a try. Thanks again!!!
