### ISSUE TITLE
Java NoSuchMethodError getSerial() upon application startup

### ISSUE THREAD

**Issue by JHunterSpok** [CrossGeeks/FirebasePushNotificationPlugin#42]
Greetings,

I'm seeing Java NoSuchMethodError exceptions upon starting my Xamarin.Android application when using this plugin.

## Bug Information

Version Number of Plugin:  1.0.4
Device Tested On:  Samsung Galaxy Note running 4.4  and also on Pixel running 7
Simulator Tested On:
Version of VS:   VS Mac 7.1.5
Version of Xamarin:   Xamarin.Android 7.4.5.1
Versions of other things you are using:
HockeyApp

### Steps to reproduce the Behavior

Deploy a new release version of the app, and restart it.

### Expected Behavior

Release App start up without crashing

### Actual Behavior

App crashes upon initial startup, subsequent runs work, but crash info is uploaded to HockeyApp.   I can provide the stack traces if needed.    Unfortunately, I've not been able to recreate the error in Debug mode.

**Comment by rdelrosario** [comment]
Please check if related to: https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/35

**Comment by JHunterSpok** [comment]
Hi,  It's not related to that issue (though I have that one too)

We're getting this error reported in HockeyApp after the app crashes.

**_Xamarin caused by: java.lang.NoSuchMethodError: no static method "Landroid/os/Build;.getSerial()Ljava/lang/String;"_**

It seems to be caused when the app starts or after our user logs in (which makes a call to **_CrossFirebasePushNotification.Current.Token_**  to obtain the token to provide to our server)

// in our MyApp class OnCreate() method, called upon startup. 
           **try
            {
                // If debug you should reset the token each time.
#if DEBUG
                FirebasePushNotificationManager.Initialize( this, new PushNotificationHandler(), true );
#else
                FirebasePushNotificationManager.Initialize( this, new PushNotificationHandler(), false );
#endif
            }
            catch ( Exception exc )
            {
                Console.WriteLine( $"{DateTime.UtcNow} - Exception in MyApp.OnCreate:" );
                Console.WriteLine( $"{DateTime.UtcNow} - Message: {exc.Message}" );
                Console.WriteLine( $"{DateTime.UtcNow} - StackTrace: {exc.StackTrace}" );
            }**

The catch block unfortunately isn't logging anything to the output.

Is there any additional information that I can provide that might help?

**Comment by JHunterSpok** [comment]
NVM, it was a setup issue in my environment that was masking the real issue.
