### ISSUE TITLE
I receive notification in android only when app is killed or in the background

### ISSUE THREAD

**Issue by rubenc57** [CrossGeeks/FirebasePushNotificationPlugin#43]
Hi

When the app is open and running, I do not receive notifications, only if I close or kill the app.

Any idea why?

Thanks
rubenc

**Comment by rdelrosario** [comment]
How are you sending the payload?

**Comment by rubenc57** [comment]
I'm testing with notifications in firebase website: 
https://console.firebase.google.com/

**Comment by rubenc57** [comment]
Never mind, I understand better how it works, excellent job by the way
When the app is running i need to handle the UI, now I'm receiving them
Thanks
