### ISSUE TITLE
FirebasePushNotificationManager is missing on 3.4.25 version

### ISSUE THREAD

**Issue by vhugogarcia** [CrossGeeks/FirebasePushNotificationPlugin#431]
Hello friends,

After upgrading to the latest version (3.4.25) of the nuget pkg, I get an error on my MainApplication.cs (Android project) outlining that the FirebasePushNotificationManager is missing in the assembly.

I could not find it at all for a replacement. The using Plugin.FirebasePushNotification; is set correctly on the class file.

do you know what I could be missing?

thanks in advance

**Comment by Luisalvarenga** [comment]
I am facing the same issue when i tried to upgrade from version 3.1.6 to the 3.4.25 now everything is broken 💔

**Comment by draganDBL** [comment]
Same on my side  I'm still using 3.4.1

**Comment by carlosanpardo** [comment]
I am experiencing the same problem in a new project with version 3.4.25, any solution?

**Comment by themronion** [comment]
Set your target version to android 12 guys

**Comment by Luisalvarenga** [comment]
@themronion What I tried is that I upgraded vs2022, set android target version to 12 and update android sdk to accept 13 version, at first i got a debug error saying:  Could not load assembly 'Xamarin.Firebase.Iid'. I installed it manually and then i got this error message: 

 Error		Mono.Linker.MarkException: Error processing method: 'System.Void MyApp.Droid.Resource::UpdateIdValues()' in assembly: 'MyApp.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 Plugin.FirebasePushNotification.Resource/Animation::fragment_fast_out_extra_slow_in
   en Mono.Linker.Steps.MarkStep.HandleUnresolvedField(FieldReference reference)
   en Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   en Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   en Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   en Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of internal exception stack tracking ---
   en Mono.Linker.Steps.MarkStep.ProcessQueue()
   en Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   en Mono.Linker.Steps.MarkStep.Process()
   en Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   en MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   en Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   en Mono.Linker.Pipeline.Process(LinkContext context)
   en MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   en Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   en Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   en Microsoft.Android.Build.Tasks.AndroidTask.Execute() en /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:línea 17	MyApp.Android	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets	647	


Is there something else I am missing?

**Comment by germanjitsr** [comment]
Has anyone figured this out yet? or which version to fallback?

**Comment by RyansBello** [comment]
I just uninstall the lastest version and instal again with the version that running well before. After that just rebuild the app and everything going fine

**Comment by jamesmcmenamin** [comment]
Target android 12 sv2 (prob need to update your sdk's

**Comment by nodoid** [comment]
> Target android 12 sv2 (prob need to update your sdk's

Issue is also there in iOS

**Comment by sstahurski** [comment]
Anyone find a solution to this with IOS?

**Comment by LeeWhite187** [comment]
Same here. (In Xamarin) Switching the Android version to 12 does not solve this.
The FirebasePushNotificationManager is not showing available in the namespace of the library, on Android, in v11 or v12.

**Comment by germanjitsr** [comment]
If you are having  issues, Fall back to Plugin.FirebasePushNotification (3.0.3) It has that method we need and it works!

**Comment by sstahurski** [comment]
> If you are having issues, Fall back to Plugin.FirebasePushNotification (3.0.3) It has that method we need and it works!

For MAUI, even downgrading did not work for IOS.  Still have the issue.

**Comment by dylix** [comment]
This is still an issue!

**Comment by AlleSchonWeg** [comment]
If you compile what is the output in the VS error list?

**Comment by sstahurski** [comment]
/Platforms/iOS/AppDelegate.cs
using Plugin.FirebasePushNotification;
...
public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
    {
        FirebasePushNotificationManager.Initialize(launchOptions, true);

        return base.FinishedLaunching(application, launchOptions);

    }

Error | CS0103 | The name 'FirebasePushNotificationManager' does not exist in the current context 

VS cannot resolve or find the FirebasePushNotificationManager.

**Comment by AlleSchonWeg** [comment]
> FirebasePushNotificationManager.Initialize(launchOptions, true);

You are using .NET Maui. This Plugin is only for Xamarin Forms. It's because Maui needs .NET 6 and this plugin is compiled for: netstandard2.0;xamarin.ios10;monoandroid12. . You could look at the csproj : https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/Plugin.FirebasePushNotification/Plugin.FirebasePushNotification.csproj
You will see, that specific source code files are not included in the build for a specific platform. There is no entry for .Net 6 (net6.0-ios or .net6.0-android). As a result you see this error.
.NET 6  has breaking changes for iOS (net6.0-ios). It is not compatible with XF (xamarin.ios10):
https://github.com/dotnet/maui/issues/6221
https://github.com/xamarin/xamarin-macios/issues/13087

Android (.net6.0-android) is compatible with XF(monoandroid):
https://github.com/dotnet/maui/discussions/1743
Thats the reason, why android shows no error. This plugin needs at least Target Android Version12 and/or TargetFrameworkVersion 12.

**Comment by dylix** [comment]
that may be true for him, but still happens in xamarin forms. the original post of this problem still applies.

**Comment by AlleSchonWeg** [comment]
> that may be true for him, but still happens in xamarin forms. the original post of this problem still applies.

Have you changed the target framework version and target android version?

**Comment by dylix** [comment]
> > that may be true for him, but still happens in xamarin forms. the original post of this problem still applies.
> 
> Have you changed the target framework version and target android version?

I in fact did not. How silly of me, THANK YOU!

**Comment by MCAleckson** [comment]
Any word from the developers as to .Net 6 or .Net 7 support?  I've been a happy consumer of this plugin for my Platform.UNO apps in production for over 2 years, and now I'm stuck, unable to migrate my code base as some other packages and some additional functionality is calling for .net 6.  Thanks!

**Comment by hairkrishnanp88** [comment]
> Set your target version to android 12 guys



> Set your target version to android 12 guys
Yes Now that issue is resolved.. Thanks..

I am having one more issue, In foreground I am not receiving the notification. Below code sample. Insted of that i kept Alert message. I can get Alert message but Notification message not getting any idea.. Please help

 CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                try
                {
                    System.Diagnostics.Debug.WriteLine("Received");
                    if (p.Data.ContainsKey("body"))
                    {
                        Device.BeginInvokeOnMainThread(() =>
                        {
                            App.AppUtility.ShowAlert("MYSPS", p.Data["body"].ToString());
                        });

                    }
                }
                catch (Exception ex)
                {

                }

            };

**Comment by AlleSchonWeg** [comment]
@hairkrishnanp88 
On Android this condition must match to show the notification:
https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/d86266a9f45687b418f5f1e69c348681d1ff6e27/Plugin.FirebasePushNotification/DefaultPushNotificationHandler.android.cs#L151
Make sure that you send the correct parameters in your push message payload.
More info: https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/434

**Comment by caio27093** [comment]
I have this same issue in xamarin.forms, but my target application is android 13.0

**Comment by canerunutkan** [comment]
google plays min req is now target api 13(api level 33) so the solution must be for these target version othervise google play is not allowe to updated and new user installs. so any suggestion or fix guys?

**Comment by bitshftr** [comment]
Why was this closed?  We now have to target Android 14 (API level 34), and I'm getting the same problem (FirebasePushNotificationManager is missing)
