### ISSUE TITLE
Unable to start app after the "Getting Started" part

### ISSUE THREAD

**Issue by step4** [CrossGeeks/FirebasePushNotificationPlugin#44]
Hi,

I followed all the steps from "Firebase Setup" and "Getting Started" sections.
But when I try to start the app in an emualtor I'm getting a "An unhandled exception occured."

In the device log I only find th entry: "Firebase initialization unsuccessful"

I'm new to Xamarin and app development so I dont know whereto look exactly

**Comment by rdelrosario** [comment]
You should test in a real device.

**Comment by rdelrosario** [comment]
If getting <b>java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process {your_package_name}</b>. Make sure the google-services.json has the GoogleServicesJson build action. If you have that set, then clean and build again, this is a known issue when using Firebase Component. More info and fix here: https://bugzilla.xamarin.com/show_bug.cgi?id=56108.


    Add the following to the android project .csproj file:

    ```
	  <Target Name="RemoveGoogleServicesJsonStampFiles" BeforeTargets="BeforeBuild">
	    <Delete Files="$(IntermediateOutputPath)\ProcessGoogleServicesJson.stamp" />
	  </Target>
   ```

**Comment by step4** [comment]
I still get the error on a real device.
I will try the Strings.xml fix from the bugzilla page later.

**Comment by rdelrosario** [comment]
Is not on Strings.xml the fix. Is on the Android .csproj

**Comment by step4** [comment]
yes I did add the target in the .csproj of the Android project.
But I still get the error.
Is there an other way to include the google-services.json file?

**Comment by rdelrosario** [comment]
On this video is shown how to add it:
https://youtu.be/FrxPEMLfV-o

**Comment by step4** [comment]
I do every single step of the video in Visual Studio on Windows but still get the error.
Firebase is not able to initialize properly.

**Comment by step4** [comment]
I was able to get it to work.
I did the whole procedure on a MacBook and now it works.
Any clue why it won't work on windows for me?

**Comment by rdelrosario** [comment]
Not sure but this seems more enviroment than plugin related. Did you try resetting your PC?
