### ISSUE TITLE
Receiving a System.TypeLoadException: Could not find method due to a type load error in iOS

### ISSUE THREAD

**Issue by rubenc57** [CrossGeeks/FirebasePushNotificationPlugin#45]
Hi
I'm not sure if it is an error in the plugin or something I'm missing.
I made your plugin worked in android, but in iOS, i receive this error when running the app

## Bug Information

Version Number of Plugin: 1.0.7
Device Tested On: iPhone 6 Plus iOS 11.0
Simulator Tested On: iPhone 6 Plus iOS 11.0
Version of VS: 14.0.25431.01 update 3
Version of Xamarin: 4.7.10.22

Versions of other things you are using:

Microsoft.CSharp 4.4.0
Microsoft.NetCore.Platforms 2.0.0
Microsoft.WIn32.Primitives 4.3.0
NetStandard.Library 2.0.1
Newonsoft.Json 10.0.3
Plugin.Permission 2.1.0
sqlite-net-pcl 1.4.118
sqlitePCL.bundle_green 0.9.3
SQlitePCL.raw 0.9.3
SQlitePCL.raw.bundle_green  1.1.8
SQlitePCLRaw.core 1.1.8
SQLitePCLRaw.provider.sqlite3.ios_unifed 1.1.8
System.AppContext 4.3.0
System.Collections 4.3.0
System.Collections.Concurrent 4.3.0
System.ComponenModel.TyoeConverter 4.3.0
System.Console 4.3.0
System.Diagnostics.Debug 4.3.0
System.Diagnostics.Tools 4.3.0
System.Diagnostics.Tracing 4.3.0
System.Globalization 4.3.0
System.Globalization.Calendars 4.3.0
System.IO 4.3.0
System.IO.Compression 4.3.0
System.IO.Compression.Zipfile 4.3.0
System.IO.FileSystem 4.3.0
System.IO.FileSystem.Primitives 4.3.0
System.Linq 4.3.0
System.Linq.Expression 4.3.0
System.Net.Http 4.3.3
System.Net.Primitives 4.3.0
System.Net.Sockets 4.3.0
System.ObjectModel 4.3.0
System.Reflection 4.3.0
System.Reflection.Extentions 4.3.0
System.Reflection.Primitives 4.3.0
System.Resources.ResourceManager 4.3.0
System.Runtime 4.3.0
System.Runtime:extentions 4.3.0
System.Runtime.Handles 4.3.0
System.Runtime.InteropServices 4.3.0
System.Runtime.InteropServices.RuntimeInformation 4.3.0
System.Runtime.Numerics 4.3.0
System.Runtime.Serializations.Formatters 4.3.0
System.Runtime.Serializations.Primitives 4.3.0
System.Security.Cryptography.Algorithms 4.3.0
System.Security.Cryptography.Encoding 4.3.0
System.Security.Cryptography.Primitives 4.3.0
System.Security.Cryptography.X509Cerificates 4.3.1
System.ServiceModel.Primitives 4.4.0
System.Text.Encoding 4.3.0
System.TextEncoding.Extensions 4.3.0
System.Text.RegularExpressions 4.3.0
System.Threading 4.3.0
System.Threading.Tasks 4.3.0
System.Threading.Timer 4.3.0
System.Xml.ReaderWriter 4.3.0
System.Xml.XDocument 4.3.0
System.Xml.XmlDocument 4.3.0
Xam.Plugin.GeoLocator 4.1.1
Xam.Plugins.Messaging 4.0.0
Xam.Plugins.Settings 3.1.1
Xamarin.Build.Download 0.4.7
Xamarin.Firebase.iOS.Analytics 4.0.2
Xamarin.Firebase.iOS.InstanceID 2.0.0
Xamarin.Forms 2.4.0.18342
Xamarin.Forms.GoogleMaps 2.1.1
Xamarin.Google.iOS.Maps 2.1.0.2

### Steps to reproduce the Behavior

I just follow the steps from your tutorial

### Expected Behavior

To receive push notifications

### Actual Behavior

When the app is starting it crashes giving an error

### Code snippet
In the Main.cs  class when executing
   UIApplication.Main(args, null, "AppDelegate");

### Screenshots

![typeloadexception](https://user-images.githubusercontent.com/20931876/31919629-1db16a90-b821-11e7-8a05-8fcae771c2d3.png)

![typeloadexception1](https://user-images.githubusercontent.com/20931876/31919576-b32927e4-b820-11e7-9212-7a88f2792b53.png)

**Comment by rdelrosario** [comment]
You seem to be using the latest FCM package version on iOS. So install https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.0.1-alpha instead

**Comment by rubenc57** [comment]
I followed carefully your tutorial on CrossGeeks/FirebasePushNotificationPlugin 
Installing only what the tutorial says I should install and using the sample code provided.

I uninstalled 1.0.7 and install version 2.0.1-alpha
Now nothing works, so I think I should change the code also, where can I find the code I should use?
I cannot find the namespace for the new version

**Comment by rdelrosario** [comment]
Did you clean the solution and delete and restore packages?

**Comment by rubenc57** [comment]
Yeap

**Comment by rdelrosario** [comment]
Could you send me your app delegate?

**Comment by rubenc57** [comment]
[AppDelegate.zip](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1412662/AppDelegate.zip)

**Comment by rubenc57** [comment]
Ok, now I have version 2.0.1-alpha installed and working
I don't get the typeload error anymore :)

However I don't receive notifications in iOS, only in android
I'm using an APNs Authentication Key in cloud messaging in firebase website for iOS, that should work no?
Another thing when I run the app in iOS, it does not ask for permission to receive notifications...

**Comment by rdelrosario** [comment]
Did you created certificates on Apple portal or using Token-based (HTTP/2) Authentication for APNS ?

**Comment by rdelrosario** [comment]
If you don’t get the puah notification permission request then you will not get any. Make sure you have push notification check enabled for your App In Apple Developer Portal.

**Comment by rdelrosario** [comment]
Did you follow all these steps:

https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by rubenc57** [comment]
Thank you, I will review, I'll let you know

**Comment by rubenc57** [comment]
I double check and I have push notification enabled and have followed all the steps of the link
Firebase does send the messages, it says "Completed", but I don't receive in the App
Does this works in a iOS simulator? or has to be a physical device?

**Comment by rdelrosario** [comment]
It has to be a physical device, push notifications don't work on iOS simulator

**Comment by rdelrosario** [comment]
Let me know if it worked when tested on a physical device, will close this issue for now. But reopen if need any additional help.

**Comment by rubenc57** [comment]
Ok, I have tested in a physical device, when I run the app for the first time it asks me if I want to receive notifications, which is good
Then I go to the Firebase console to send a message but I don't receive any
I'm using an APNs Key
I have double checked the steps for iOS
I also have my Provisioning profile's App ID with push notifications enabled
(Enabled Services: Game Center, In-App Purchase, Push Notifications)
Although in Production's column says configurable whereas in Development's column it says Enabled

**Comment by rubenc57** [comment]
Do I receive notifications if I install the app in my iPhone with TestFlight?
That is what I did and I'm not receiving them

**Comment by rdelrosario** [comment]
For TestFight builds you need to set enable push notifications on your distribution certificate and also on your server use the push production certificate. You can't use development certificate on TestFlight.

**Comment by rdelrosario** [comment]
On Firebase you added the push development certificate or the production one?

**Comment by rubenc57** [comment]
I added the authkey .p8 file that I created and downloaded in my apple developer portal in Certificates, Identifiers & Profiles -> Keys -> All

In Firebase I went to Settings -> Cloud Messaging and Uploaded that file in APNs Authentication Key
Then I send a notification and it says Completed under status

**Comment by rubenc57** [comment]
Yes, in my production's certificate for distribution push notifications are enabled as well
This is the one I use in TestFlight

**Comment by rdelrosario** [comment]
Ok this is the same one you uploaded on Firebase portal?

**Comment by rubenc57** [comment]
yeap

**Comment by rubenc57** [comment]
Ok, In firebase, cloud messaging for iOS says:
"Firebase Cloud Messaging can use either an APNs authentication key or APNs certificate to connect with APNs"
So I uploaded an "APNs Authentication Key" (*.p8)
Firebase automatically disables the option to upload "APNs Certificates"
So "Development APNs certificate" and "Production APNs certificate"  are empty, I did not uploaded any certificates there.

**Comment by rubenc57** [comment]
Do I need this in info.plist?

	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.google.fcm</string>
			</array>
		</dict>
	</array>
