### ISSUE TITLE
Android 12 Java.Lang.IllegalArgumentException: 'com.infinity.estrats: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified 

### ISSUE THREAD

**Issue by BurhanMunir** [CrossGeeks/FirebasePushNotificationPlugin#450]
## Bug Information
I am developing the Application using Xamarin Forms. The App is working fine on all android devices less than api 31 or android 12 but when I run application on android 12 in debug mode the following exception occurs.
Java.Lang.IllegalArgumentException: 'com.infinity.estrats: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.'

Version Number of Plugin:3.4.35
Device Tested On:SamsungSM-P610(Android 12)
Simulator Tested On:
Version of VS: VS 2022(17.4.2)
Version of Xamarin:5.0.0.2515
Versions of other things you are using:

### Steps to reproduce the Behavior
Builds the app by selecting Android 12 device in debug mode, the mentioned exception occurs.
### Expected Behavior
The Application should run properly.
### Actual Behavior
The Application is crashing with Java.Lang.IllegalArgumentException: exception
###What I tried
pendingIntent =  PendingIntent.GetActivity(this, 0,intent, PendingIntentFlags.UpdateCurrent | PendingIntentFlags.Immutable);
I tried this code in main application Oncreate method but did not work at all.

###Android Manifest
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionName="1.1" package="com.infinity.estrats" android:installLocation="auto" android:versionCode="12">
	<queries>
		<package android:name="com.google.android.apps.maps" />
	</queries>
	<uses-sdk android:minSdkVersion="23" android:targetSdkVersion="31" />
	<application android:theme="@style/MainTheme" android:usesCleartextTraffic="true" android:icon="@drawable/ic_launcher" android:label="Infinity FSM">
		<meta-data android:name="Api Key" android:value="AIzaSyBiCLFW" />
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="${applicationId}.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
		</provider>
		<receiver android:name="com.google.firebase.iid.firebaseinstanceidinternalreceiver" android:exported="false"/>
		
		<service android:name="com.infinity.estrats.backgroundService"
         android:exported="false">
			<intent-filter>
				<action android:name="com.infinity.estrats.START_BACKGROUND" />
			</intent-filter>
		</service>
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		<uses-library android:name="org.apache.http.legacy" android:required="false" />
		<receiver android:name="crc64a0e0a82d0db9a07d.ConnectivityBroadcastReceiver" android:enabled="true" android:exported="false" android:label="Essentials Connectivity Broadcast Receiver"/>
		<service android:name="crc6494e14b9856016c30.PNFirebaseMessagingService" android:exported="false">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT" />
			</intent-filter>
		</service>
		<receiver android:name="crc6494e14b9856016c30.PushNotificationActionReceiver" android:exported="true"/>
		<receiver android:name="crc6494e14b9856016c30.PushNotificationDeletedReceiver" android:exported="true" />
		<activity android:configChanges="orientation|screenSize|uiMode" android:name="crc646957603ea1820544.MediaPickerActivity" android:exported="true" />
		<receiver android:enabled="true" android:exported="false" android:name="crc643f46942d9dd1fff9.PowerSaveModeBroadcastReceiver" />
		
	</application>
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
</manifest>

### Code snippet
 [Application]
    public class MainApplication : Application
    {
       

        public MainApplication(IntPtr handle, JniHandleOwnership transer)
          : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            CrossCurrentActivity.Current.Init(this);

            //Set the default notification channel for your app when running Android Oreo
            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                Intent intent =new Intent(this,typeof(MainActivity));
                FirebasePushNotificationManager.NotificationActivityFlags = ActivityFlags.ClearTop | ActivityFlags.SingleTop;
                //Change for your default notification channel id here
                FirebasePushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";
              //  FirebasePushNotificationManager.NotificationActivityFlags = (Android.Content.ActivityFlags?)PendingIntentFlags.Mutable;
                   
                //Change for your default notification channel name here
                FirebasePushNotificationManager.DefaultNotificationChannelName = "General";
                //var pendingintent=  PendingIntent.GetActivity(this, 1,intent, PendingIntentFlags.UpdateCurrent | PendingIntentFlags.Immutable);
                //pendingintent.Send();
                
            }

            //If debug you should reset the token each time.
#if DEBUG    

            FirebasePushNotificationManager.Initialize(this, new NotificationUserCategory[]
            {
            new NotificationUserCategory("message",new List<NotificationUserAction> {
                new NotificationUserAction("Reply","Reply",NotificationActionType.Foreground),
                new NotificationUserAction("Forward","Forward",NotificationActionType.Foreground)

            }),
            new NotificationUserCategory("request",new List<NotificationUserAction> {
                new NotificationUserAction("Accept","Accept",NotificationActionType.Default,"check"),
                new NotificationUserAction("Reject","Reject",NotificationActionType.Default,"cancel")
            })

            }, true);
#else
	            FirebasePushNotificationManager.Initialize(this,new NotificationUserCategory[]
		    {
			new NotificationUserCategory("message",new List<NotificationUserAction> {
			    new NotificationUserAction("Reply","Reply",NotificationActionType.Foreground),
			    new NotificationUserAction("Forward","Forward",NotificationActionType.Foreground)

			}),
			new NotificationUserCategory("request",new List<NotificationUserAction> {
			    new NotificationUserAction("Accept","Accept",NotificationActionType.Default,"check"),
			    new NotificationUserAction("Reject","Reject",NotificationActionType.Default,"cancel")
			})

		    },false);
#endif
            CrossFirebasePushNotification.Current.OnTokenRefresh += Current_OnTokenRefresh;
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                var message = p.Data["body"].ToString();
                var page = new MasterPage();
                page.HandleNotificationReceived(message, true);
            };

        }

        private void Current_OnTokenRefresh(object source, FirebasePushNotificationTokenEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine($"{e.Token}");
        }
    }
### Screenshots

![Screenshot (135)](https://user-images.githubusercontent.com/62692696/207295923-26f9dc9b-4b7f-47b4-874a-58f2ccdf45d8.png)

**Comment by BurhanMunir** [comment]
I tried many things but my issue resolved by installing Xamarin.AndroidX.Work.Runtime version 2.7.0 in android project. Remember version 2.7.0 worked for me not any other version worked me for my application.

**Comment by ranjan0805** [comment]
I can confirm that using Plugin.firebasePushNotification  causes this error even if I remove all the PendingIntent code from src code. Just removed this plugin and program worked. Urgently need to know which version author implemented FLag_immutable fix. latest version 3.4.35 src do have this flag used, in v2.3.5 src that flag is not there. However my code breaks if I use 3.4.35 as FirebasePushNotificationManager is not available (may be due to intermediate lib issue)
