### ISSUE TITLE
Plugin.FirebasePushNotifications crashing on Xamarin.IOS project and phisical iPhone

### ISSUE THREAD

**Issue by tmadwar** [CrossGeeks/FirebasePushNotificationPlugin#458]
## 🐛 Bug Report

For Xamarin.ios project while running on (iPhone) not simulator,
FirebaseNotificationManager.initialize(options,true)

Getting: Invalid use of null Object value not set 
Project gets instantly terminated

I have tried all versions of the plugin and still the same error, 
It fully works on android with no errors at all.
Just not working on iPhone

### Expected behavior
Should generate token on android and ios, and recieve push notifications.

### Reproduction steps
Simply create a new Xamarin.Forms application o latest version of VS 2022
Add the Plugin and integrate to android and ios.
It will full work on android
if you connected any phisical iPhone to the windows PC using itunes it will never work. 
and applicatio will crash on initilization point.

### Configuration
Xamarin.IOS Project

**Version:** all versions

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :monkey: Xamarin.Forms

**Comment by AlleSchonWeg** [comment]
Thats no bug. 
VS and iTunes using Hotrestart feature to connect an deploy an app on iphone. Hotrestart are working only with dynamic librarys. But Firebase is a static library.
If you want to test with our physical iPhone you need a mac, or a connection to a mac and create an ad hoc release.

**Comment by tmadwar** [comment]
Thank you very much for your great help, at least i know now how to test it properly.
