### ISSUE TITLE
UWP - System.NotImplementedException

### ISSUE THREAD

**Issue by Umar3x** [CrossGeeks/FirebasePushNotificationPlugin#46]
When trying to run my UWP project I got this error : 

> System.NotImplementedException : 'This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation

When I'm doing this : 

```
  CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>
            {
                LoginService.PushNotificationId = p.Token;
            };
```
I've been installing plugin on all 3rd platforms ofc

**Comment by rdelrosario** [comment]
There's no UWP support for this plugin

**Comment by Umar3x** [comment]
Well I thought there was as there is a UWP project in the sample....
