### ISSUE TITLE
Can't send push notification to iOS from POST 

### ISSUE THREAD

**Issue by step4** [CrossGeeks/FirebasePushNotificationPlugin#47]
hi,

I only have one problem left.
Push notifications are working on android and iOS now when I use the firebase console in the browser.
When I try to you Postman to send a message only my android device gets the notfication.

I'm using this POST body:
`
{
    "notification" : {
    "body" : "hello!",
    "title": "afruz",
    "sound": "default"
  },
    "priority": "high",
    "condition": "'general' in topics"
}`

and I'm subscribing to the general topic in the OnStart() function in the App.xaml.cs file.

Another question, where do I get device-IDs?

**Comment by rdelrosario** [comment]
When you are sending from firebase portal, are you using topics too?

**Comment by step4** [comment]
yes also from firebase portal with topic only the android device gets the push notification.
Only when I choose both apps directly from the portal both devices gets them.

**Comment by rdelrosario** [comment]
Send me your AppDelegate.cs

**Comment by step4** [comment]
`
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Foundation;
    using Plugin.FirebasePushNotification;
    using UIKit;

    namespace TestGPSBackround.iOS
    {
        [Register("AppDelegate")]
        public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
        {
            public override bool FinishedLaunching(UIApplication app, NSDictionary options)
            {
                global::Xamarin.Forms.Forms.Init();

                LoadApplication(new App());

                FirebasePushNotificationManager.Initialize(options, true);

                return base.FinishedLaunching(app, options);
            }

            public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken) { 
                #if DEBUG
                FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken, FirebaseTokenType.Sandbox);
                #endif
                #if RELEASE
                FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken,FirebaseTokenType.Production);
                #endif

            }

            public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
            {
                FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);

            }
            // To receive notifications in foregroung on iOS 9 and below.
            // To receive notifications in background in any iOS version
            public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
            {
                // If you are receiving a notification message while your app is in the background,
                // this callback will not be fired 'till the user taps on the notification launching the application.

                // If you disable method swizzling, you'll need to call this method. 
                // This lets FCM track message delivery and analytics, which is performed
                // automatically with method swizzling enabled.
                FirebasePushNotificationManager.DidReceiveMessage(userInfo);
                // Do your magic to handle the notification data
                System.Console.WriteLine(userInfo);
            }

            public override void OnActivated(UIApplication uiApplication)
            {
                FirebasePushNotificationManager.Connect();

            }
            public override void DidEnterBackground(UIApplication application)
            {
                // Use this method to release shared resources, save user data, invalidate timers and store the application state.
                // If your application supports background exection this method is called instead of WillTerminate when the user quits.
                FirebasePushNotificationManager.Disconnect();
            }
        }
    }
`

**Comment by rdelrosario** [comment]
Can you check the console logs to see if you get any errors?

**Comment by rdelrosario** [comment]
Please let me know if anything related to an error shows up on your apllication outout

**Comment by step4** [comment]
sorry I will check it out directly later today

**Comment by step4** [comment]
so I checked now and I don't get any errors in my application output. 
I'm subscribing in my App.xaml.cs in the OnStart() method. That is the right place for it, isn't it?

**Comment by rdelrosario** [comment]
Yes is a good place to do it.

You can get the token on:
```csharp

  CrossFirebasePushNotification.Current.OnTokenRefresh += (s,p) =>
  {
        System.Diagnostics.Debug.WriteLine($"TOKEN : {p.Token}");
  };

```

**Comment by rdelrosario** [comment]
btw, maybe the reason you are not getting the notifications is that you are using the GoogleService-Info.plist of the sample. I got a few push notifications some hours ago, not sure if were your tests:

![meme](https://user-images.githubusercontent.com/2547751/32329950-e27abdaa-bfb4-11e7-9e67-af3b0b4bc626.jpg)

**Comment by step4** [comment]
I don't think so because I receive the push notifications when I'm using my firebase GUI online.
I will test the sending with the device token later and if that works it will solve my problem I think

**Comment by rdelrosario** [comment]
how are you sending the payload?

**Comment by step4** [comment]
so my payload looks like this:

`{

    "notification" : {
	    "body" : "hello!",
	    "title": "afruz",
	    "sound": "default",
	            "click_action":"request"
	    
	  },
     
     "priority": "high",

         "condition": "'general' in topics"
}`

**Comment by rdelrosario** [comment]
Are you subscribing to general topic?

**Comment by step4** [comment]
yes I'm subscribing to general like this in the App.xaml.cs: 

`

namespace TestGPSBackround

{
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();
            MainPage = new TestGPSBackroundPage();

            
        }

        protected override void OnStart()
        {
            // Handle when your app starts
            CrossFirebasePushNotification.Current.Subscribe("general");
            CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine($"TOKEN : {p.Token}");
            };
            System.Diagnostics.Debug.WriteLine($"TOKEN: {CrossFirebasePushNotification.Current.Token}");


        }

        protected override void OnSleep()
        {
            // Handle when your app sleeps
        }

        protected override void OnResume()
        {
            // Handle when your app resumes
        }
    }
}
`

**Comment by rdelrosario** [comment]
Are you getting a token?

**Comment by step4** [comment]
Yes I do,

when I try to sind directly to the device with

`{
  "to" : "ejPGNUR476.......1QX2P6vKfFIoOH-2jz",
  "priority" : "high",
  "notification" : {
    "body" : "Hello world",
    "title" : "FCM Message",
  }
}`



I'll get:


`{
    "multicast_id": 6948550681908174964,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "MismatchSenderId"
        }
    ]
}`



I have checked that this token ist the last one written in the Debig console

**Comment by rdelrosario** [comment]
Still having this issue?

**Comment by step4** [comment]
With a complete new setup and installation of the solution it works now.
Dont know where the problem was.
