### ISSUE TITLE
Set custom icon for notifications

### ISSUE THREAD

**Issue by pascalgroner** [CrossGeeks/FirebasePushNotificationPlugin#48]
Hi,
how can i set a custom icon for notifications in stead of the application icon.

I create a separate black/white Icon to use as the notification indicator icon.
->this looks much better than my colored app icon (rendered to a flat round white ball in notifications)

**Comment by rdelrosario** [comment]
On Android project set this: FirebasePushNotificationManager.IconResource = Resource.Id.YourDrawable;

**Comment by Ucidbuild** [comment]
This works fine if the app is open.
But i still get still the application icon if the app is in background or closed.
Where can i set the icon used by the service?

**Comment by rdelrosario** [comment]
What payload are you sending?

**Comment by rdelrosario** [comment]
Also where did you set FirebasePushNotificationManager.IconResource = Resource.Id.YourDrawable; ?

A good place to do it is on the Application class not MainActivity

**Comment by pascalgroner** [comment]
I cant set icon as Resource.Id.<nameofthefile>; i put in drawable
so i use Resource.Drawable.push_icon3;
How to set the icon added to the .Id namespace?

I set the icon and as well the a message sound in MainActivity

```
            global::Xamarin.Forms.Forms.Init(this, bundle);
            FirebasePushNotificationManager.SoundUri = Android.Net.Uri.Parse("android.resource://ch.pve.LemonINFO/" + Resource.Raw.li_message2);
            FirebasePushNotificationManager.IconResource = Resource.Drawable.push_icon3;
            FirebasePushNotificationManager.ProcessIntent(Intent);
            LoadApplication(new App());
```

**Comment by rdelrosario** [comment]
Yes is like you do it inhad a typo is not using id

**Comment by edosusanto** [comment]
Hi, I'm also having trouble when changing notification icon to support lollipop.
I put this code in Application class. the notification icon only work when the app is opened and at foreground. when app in background or closed, it use app icon
`if(Build.VERSION.SdkInt <= BuildVersionCodes.LollipopMr1)
        {
            FirebasePushNotificationManager.IconResource = Resource.Drawable.car_icon;
        }`

Any idea how to resolve this?

**Comment by SyaoranChang** [comment]
I have same issue : when app in background or closed, it use app icon.
Plugin version:2.3.5-beta

**Comment by tvm-anand** [comment]
Change all icons in drawbles.
