### ISSUE TITLE
Android null pointer exceptions

### ISSUE THREAD

**Issue by pascalgroner** [CrossGeeks/FirebasePushNotificationPlugin#49]
Hi,
I have some unexpected app crashes with null pointer exception.

**Issue**
After building and deploying, the app fully crash after startup phase. 
Usually right after the white screen (or splash screen). 

**In Visual Studio you see**
_Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code)._
There is no more real usable information to get...

**In the debug log you find**
_...    I/FirebaseInitProvider( 2388): FirebaseApp initialization unsuccessful_

**Workaround Fix**
Do a full rebuild of the solution and then it works again...
If the app is running then it keeps running without further issues.

**Reproduce**
I create a new Xamarin project (pcl) then follow your documentation. Build run everything works fine.
Add / change resources in android project and just hit run. most of the time app crashes.
I use newest VS, Xamarin, Forms, normal and beta version of you plugin (used for IOS). 
Android Devices: Emulator, Sony, Samsung, Nokia 8...

**Additional Infos**
I figured out it seems only happen if i change something in the resource structure (change a property, add/remove files or just change text in the styles files):
Then the next build/deploy app will crash until you rebuild the complete solution.
Hope it helps you do some more exception handling pointing out why initialization unsuccessful. And hopefully help dealing with resource changes.

**Comment by rdelrosario** [comment]
This is a known issue when using Firebase Component. More info and fix here: https://bugzilla.xamarin.com/show_bug.cgi?id=56108.


    Add the following to the android project .csproj file:

    ```
	  <Target Name="RemoveGoogleServicesJsonStampFiles" BeforeTargets="BeforeBuild">
	    <Delete Files="$(IntermediateOutputPath)\ProcessGoogleServicesJson.stamp" />
	  </Target>
   ```
