### ISSUE TITLE
can not receive notifications in iOS only in Android in version 2.0.1-alpha

### ISSUE THREAD

**Issue by rubenc57** [CrossGeeks/FirebasePushNotificationPlugin#51]
#45 

In firebase, cloud messaging for iOS says:
 "Firebase Cloud Messaging can use either an APNs authentication key or APNs certificate to connect with APNs"
 So I uploaded an "APNs Authentication Key" (*.p8)
 Firebase automatically disables the option to upload "APNs Certificates"
 So "Development APNs certificate" and "Production APNs certificate" are empty, I did not uploaded any certificates there.

When I send notification to iOS devices from Firebase console, the status changes to 'completed'

I'm using a physical device, iPhone 6 plus 10.3.2

When I run the app for the first time it asks me if I want to receive notifications, which is good

My provisioning profile has the push notifications enabled

In my info-plist under capabilities I have remote notifications enabled

And all the code that you tutorial provides for iOS as well

But I don't receive notifications, any ideas?

**Comment by rdelrosario** [comment]
What payload are you sending?

**Comment by rubenc57** [comment]
I'm sending notifications from firebase console with the default parameters:

Message text:  test message
Message label: 
Delivery date: Send Now
Target: User segment
app: iOS app
priority: high
sound: Enabled
iOS badge: disabled
Expires: 4 weeks

**Comment by rdelrosario** [comment]
Did you try sending it using postman?

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/TestingPushNotifications.md

**Comment by rubenc57** [comment]
I tried this:

        public static string SendPushNotification()
        {
            string str = string.Empty;
            try
            {
                string applicationID = "A...9";
                string senderId = "9...9";
                WebRequest tRequest = WebRequest.Create("https://fcm.googleapis.com/fcm/send");
                tRequest.Method = "post";
                tRequest.ContentType = "application/json";
                var data = new
                {
                    to = "/topics/general",
                    priority = "high",
                    notification = new
                    {
                        body = "Hello world",
                        title = "FCM Message",
                    },
                };

                string jsons = Newtonsoft.Json.JsonConvert.SerializeObject(data);
                Byte[] byteArray = Encoding.UTF8.GetBytes(jsons);
                tRequest.Headers.Add(string.Format("Authorization: key={0}", applicationID));
                tRequest.Headers.Add(string.Format("Sender: id={0}", senderId));
                tRequest.ContentLength = byteArray.Length;

                using (Stream dataStream = tRequest.GetRequestStream())
                {
                    dataStream.Write(byteArray, 0, byteArray.Length);
                    using (WebResponse tResponse = tRequest.GetResponse())
                    {
                        using (Stream dataStreamResponse = tResponse.GetResponseStream())
                        {
                            using (StreamReader tReader = new StreamReader(dataStreamResponse))
                            {
                                String sResponseFromServer = tReader.ReadToEnd();
                                str = sResponseFromServer;
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                str = ex.Message;
            }
            return str;
        }

And I received this result: {"message_id":6775252883451665293}

**Comment by kwebmaster** [comment]
Hi,

I'm getting the same issue.
I tryed to send a push from Postman and received a message id but nothing happens on the iPhone.

I'm using the last version 2.0.1-alpha on a physical device (iPhone 5).

As soon as I open the app I receive a message to authorize the app to receive notification and I have defined everything as described in the technical guide.

Can you please give us support on how to fix it?

Regards

**Comment by rdelrosario** [comment]
When subscribing to topics. Can you check the console logs to see if you get any errors?

**Comment by kwebmaster** [comment]
Which console do you mean? How can I access it?
I tryed to send the push both from Firebase Console and Postman with several payloada but I always get the same result.

If you can explain me where I have to check I will do quickly.

Thank you so much

**Comment by rdelrosario** [comment]
I mean on the visual studio application output. Do you see any errors showing up there when subscribing to topics?

**Comment by kwebmaster** [comment]
I'm having trouble debugging so I'm testing directly on TestFlight.
Subscribing to topic seems to work but I never receive any push on iOS.

**Comment by kwebmaster** [comment]
I think that I'm getting issue with the "FirebasePushNotificationManager.Initialize(options)" method but it seems that "try..catch" on this doesn't work properly.

Can I also check if FirebasePushNotificationManager.Initialize is already been called? I mean something like "FirebasePushNotificationManager.IsInitialized" ??

**Comment by rubenc57** [comment]
When subscribing, I don't see an error in android or ios:
CrossFirebasePushNotification.Current.Subscribe("general");

But if I change the topic, in iOS I don't see an error
CrossFirebasePushNotification.Current.Subscribe("cms");

but in android the app crashes
![screenshot_01](https://user-images.githubusercontent.com/20931876/32182264-77ab3972-bd53-11e7-9e06-ad51ef618635.png)


If I debug, I receive this error:
![screenshot_error](https://user-images.githubusercontent.com/20931876/32182123-334759dc-bd53-11e7-962e-82832420453a.png)

**Comment by kwebmaster** [comment]
Hi,

I added that string in the info.Plist but it still doesn't working.
Initialize are right and registration to topics too but I still not receive any notification.

**Comment by rubenc57** [comment]
Ok, I can confirm that the subscription issue in another topic is fixed with the number 1 suggestion at FAQ under android thank you

Still not receiving notification in iOS though

**Comment by rubenc57** [comment]
@kwebmaster what string are you talking about?

**Comment by kwebmaster** [comment]
Hi,

I'm talking about the number 1 of https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md

Do you think it's possible that the app isn't receiving push because of I'm testing it on TestFlight?
The app has been compiled with a production provisioning profiles that has push notification enabled for the app id.

I'm trying everything but it's real hard to understand why it doesn't work properly

Any idea?

**Comment by rubenc57** [comment]
Yeah, I also tried that and it didn't make a difference
I am also testing with TestFlight because it has to be in a physical device
I'm also using a production pp

Let's wait a little bit longer to see what @rdelrosario or any other member of the team can do for us, remember is an alpha version.

**Comment by kwebmaster** [comment]
Yes of course, but I decided to try to publish a version of the app which is not yet used by many people.
I also reverse to the 1.0.7 version but still have the same issues.

Hope @rdelrosario can do something for us

**Comment by rubenc57** [comment]
TestFlight is the same as been at the app store technically speaking, because is the same last ipa version you released, the difference is that TestFlight is only for your testers...

**Comment by kwebmaster** [comment]
I'm talking about this because also with another about, that use GCM, I noticed that I don't receive push notification while from the same app published on the store I'm able to receive.

It's strange, I'm agree, but this is what is happening.

**Comment by rubenc57** [comment]
Strange indeed, thanks for sharing that, and good you tested

**Comment by kwebmaster** [comment]
I have not tested yet but I will try.
I experienced this on another app that is working with GCM and not with FCM.

**Comment by kwebmaster** [comment]
@rdelrosario I just debugging the app with Visual Studio and a physical device (iPhone 5s).
I didn't get any error while registering to topic but push never arrive.

**Comment by rubenc57** [comment]
@kwebmaster did you try publish in AppStore?

**Comment by kwebmaster** [comment]
Not yet because I readed that is not possible to downgrade the app version....that could be a problem.
Where did you subscribe to the topic?

Now I was trying to register in this event 

        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)

but I discover, with a breakpoint, that this method is never called.
I think this could be a problem. Did you tried it?

**Comment by kwebmaster** [comment]
I'm sorry, it seems that AppDelegate is not debuggable.
I put a breakpoint but it never stop anywhere even in the "FinishedLaunching" event.

I also discovered that the topic requested is not registered in the topic list of Firebase Console.
I my output window in Visual Studio I also get these messages:

2017-11-01 01:42:43.147: <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"
2017-11-01 01:42:43.146 ImaAppiOS[1458:] <FIRAnalytics/INFO> Firebase Analytics v.3600000 started
2017-11-01 01:42:43.179 ImaAppiOS[1458:] <FIRAnalytics/INFO> To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/Y0Yjwu)
2017-11-01 01:42:43.275 ImaAppiOS[1458:] <FIRAnalytics/INFO> Firebase Analytics enabled

**Comment by kwebmaster** [comment]
I finally received the push notification!
Just a last question it's possible to receive the notification also if the app is in foreground? This is the only case in which it's not shown to the user.

**Comment by rdelrosario** [comment]
@kwebmaster  Yes how is your  appdelegate set? you should be receiving notification events on foreground too

**Comment by rdelrosario** [comment]
Also how you were able to receive notifications now, what you changed?

**Comment by rdelrosario** [comment]
@kwebmaster Not sure if your issue is related to https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/6

**Comment by rubenc57** [comment]
@kwebmaster nice, what did you do to make it work?

**Comment by rubenc57** [comment]
@rdelrosario I am subscribing a topic for android called "android" and "ios" for iOS 

            if (Device.RuntimePlatform == Device.Android)
                CrossFirebasePushNotification.Current.Subscribe(new string[] { "general", "android" });
            else if (Device.RuntimePlatform == Device.iOS)
                CrossFirebasePushNotification.Current.Subscribe(new string[] { "general", "ios" });

In Firebase console I see the "general" and "android" topics, but there is no "ios" topic

![no_ios2](https://user-images.githubusercontent.com/20931876/32287072-dee2a360-beec-11e7-9362-111b607cf290.png)

I don't think that code for iOS is executing because even if I send a notification to "general" I don't receive it on iOS

I'm testing more...

**Comment by rubenc57** [comment]
More debugging, see what happens with Android and with iOS:

![debug_01](https://user-images.githubusercontent.com/20931876/32288884-8821ff48-bef2-11e7-8f29-f31b6aa358d9.png)
No subscribed topics on iOS

**Comment by kwebmaster** [comment]
I checked every library and this is the configuration that worked for me:

Xamarin.Google.iOS.Core.3.0.3.3
Xamarin.Google.iOS.InstanceID.1.2.1.5
Xamarin.Firebase.iOS.Core.4.0.3
Xamarin.Firebase.iOS.InstanceID.2.0.0
Xamarin.Firebase.iOS.Analytics.4.0.2
Xamarin.Firebase.iOS.CloudMessaging.2.0.0
Plugin.FirebasePushNotification.2.0.1-alpha

It doesn't work with Plugin.FirebasePushNotification.1.0.7

Moreover I completely remake certificate for the application id and exported again in p12, and registered on Firebase Console.
On AppDelegate.FinishedLaunching I'm just calling

- FirebasePushNotificationManager.Initialize(options);

while the other methods implemented are:

public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken,FirebaseTokenType.Production);
        }

        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);            
        }
		
        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
        }

        public override void OnActivated(UIApplication uiApplication)
        {
            FirebasePushNotificationManager.Connect();
            base.OnActivated(uiApplication);
        }
        public override void DidEnterBackground(UIApplication application)
        {
            FirebasePushNotificationManager.Disconnect();
        }

Now for the foreground problem I will try to add this in AppDelegate.FinishedLaunching (after initialized)

            FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Sound;

In this way I can receive push notification in dev mode and on testflight.

Subscribing to topics is done in a PCL forms with this line

                                CrossFirebasePushNotification.Current.Subscribe("topic");

In this way it works great to me.

**Comment by rubenc57** [comment]
Great, I will check...

**Comment by kwebmaster** [comment]
Ok, let me know if you need any other help.
Now I'm trying to implement in Android, in which I was using directly Firebase dlls.

I would like to use this plugin as it's really more simple.
I hope it will work without problem

**Comment by rubenc57** [comment]
Thanks

Right now there is an update for xamarin and many nuget packages but I'm holding everything until I make this work...

**Comment by rubenc57** [comment]
@kwebmaster How did you  exported your certificate in p12?

**Comment by kwebmaster** [comment]
Just install you downloaded Apple certificate (double click) in the login root of Keychain, then right click and select export with p12 format and set a password.

Can you please share your code and library version for Android? I'm getting some issues.

**Comment by rubenc57** [comment]
**MainActivity.cs**
Add 

		FirebasePushNotificationManager.ProcessIntent(Intent); 

after

		LoadApplication(new App());

in 		OnCreate

**AndroidMAnifest.xml**
Add

		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
				<category android:name="${applicationId}" />
			</intent-filter>
		</receiver>

inside the application section.

also add the internet permission

		<uses-permission android:name="android.permission.INTERNET" />

And of course add your **google-services.json** file in your adroid folder root and make sure the build action is set to GoogleServicesJson

**YourApp.Droid.csproj**
I also added 

		<Target Name="RemoveGoogleServicesJsonStampFiles" BeforeTargets="BeforeBuild">
		    <Delete Files="$(IntermediateOutputPath)\ProcessGoogleServicesJson.stamp" />
		</Target>

And the end and before

		</Project>

**Comment by kwebmaster** [comment]
Thanks,

where is your FirebasePushNotificationManager.Initialize() called and how?

**Comment by rubenc57** [comment]
Libraries:
Xamarin.GooglePlayServices v42.1021.1
Xamarin.Firebase  v42.1021.1
Plugin.FirebasePushNotification.2.0.1-alpha

you don't call FirebasePushNotificationManager.Initialize()  for android

**Comment by rubenc57** [comment]
I'm a little bit confuse with my certificates in keychain manager, what is the name of the certificate i should export?

**Comment by kwebmaster** [comment]
You have to connect to developers.apple.com and create a development and production certificate for your app id, enabling the push notifications.
After this you can download the .cer certificate and install in in Keychain.

To be able to export in p12 format you must select the node "login" in Keychain when you install the .cer

Once exported in p12 you have to upload this certificate in Firebase Console.

**Comment by rdelrosario** [comment]
You must call initialize but in android application class:


```csharp

    [Application]
    public class MainApplication : Application
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer) :base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            
            //If debug you should reset the token each time.
            #if DEBUG
              FirebasePushNotificationManager.Initialize(this,true);
            #else
              FirebasePushNotificationManager.Initialize(this,false);
            #endif

              //Handle notification when app is closed here
              CrossFirebasePushNotification.Current.OnNotificationReceived += (s,p) =>
              {


              };
         }
    }

```

**Comment by kwebmaster** [comment]
Yes I done this but @rubenc57 said that it works to him even without               FirebasePushNotificationManager.Initialize(this,false);


What is exactly the difference between 

              FirebasePushNotificationManager.Initialize(this,FALSE)
and

              FirebasePushNotificationManager.Initialize(this,TRUE)
?

**Comment by rdelrosario** [comment]
Because the second parameter is to reset the token, on DEBUG I set this to true to always get a new token because when you debug multiple times token registration gets invalid. On RELEASE we don't have that problem because you just increment the version number and will get a new token just when needed

**Comment by kwebmaster** [comment]
It worked to me in Android.
Now I would try to switch to 1.0.7 in order to get a stable version.

I will try without changing anything until the 2.0.1 stable will be published

**Comment by rdelrosario** [comment]
You can keep using 2.0.1 I will release this one as stable over the weeked probably

**Comment by kwebmaster** [comment]
Great!

**Comment by rubenc57** [comment]
Sorry, I was wrong, you run the FirebasePushNotificationManager.Initialize() as @rdelrosario said
You call it in an application class

whish certificate to export should I use, developer or distribution?

**Comment by kwebmaster** [comment]
@rdelrosario Maybe I will need to publish the app on Friday.
Do you think that I can consider stable the 2.0.1-alpha or it could be better to try to downgade to 1.0.7?

Thanks

**Comment by rdelrosario** [comment]
Yes you can consider it as stable.

**Comment by kwebmaster** [comment]
thanks!

**Comment by rdelrosario** [comment]
@rubenc57 let us know if you were able to get it working on iOS.

Btw, @rubenc57 @kwebmaster let me know if I can improve docs in any ways to make it easier for anyone to use this plugin. If there's any flaw or missing parts on the documentation that needs to be added, let me know is highly appreciated.

**Comment by kwebmaster** [comment]
@rdelrosario I think that adding that for Android you can add the changes that must be manually introduce in the csproj file (if not possible to add it automatically when install the plugin).

**Comment by kwebmaster** [comment]
@rdelrosario I confirm that on iOS adding this to AppDelegate.FinishedLaunching I'm able to receive push notification also while the app is in foreground

            FirebasePushNotificationManager.CurrentNotificationPresentationOption = UserNotifications.UNNotificationPresentationOptions.Alert | UserNotifications.UNNotificationPresentationOptions.Sound;

**Comment by rubenc57** [comment]
Another suggestion is to elaborate in the setup for firebase regarding iOS certificates

**Comment by rubenc57** [comment]
Confirm that push notifications for iOS are working great for me now...
Thanks @rdelrosario  and @kwebmaster

**Comment by rubenc57** [comment]
A couple of questions more:

Any ideas how to localize notifications?

Does the iOS app executes this code?

            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                try
                {
                    System.Diagnostics.Debug.WriteLine("Received");
                    if (p.Data.ContainsKey("body"))
                    {
                        Device.BeginInvokeOnMainThread(() =>
                        {
                            //textLabel.Text = p.Data["body"];
                            DisplayAlert(AppResources.Literal_Aviso, p.Data["body"], AppResources.Literal_Aceptar);
                        });

                    }
                }
                catch (Exception ex)
                {

                }

            };

            CrossFirebasePushNotification.Current.OnNotificationOpened += (s, p) =>
            {
                //System.Diagnostics.Debug.WriteLine(p.Identifier);

                System.Diagnostics.Debug.WriteLine("Opened");
                foreach (var data in p.Data)
                {
                    System.Diagnostics.Debug.WriteLine($"{data.Key} : {data.Value}");
                }

                if (!string.IsNullOrEmpty(p.Identifier))
                {
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        //textLabel.Text = p.Identifier;
                        DisplayAlert(AppResources.Literal_Aviso, p.Identifier, AppResources.Literal_Aceptar);
                    });
                }
                else if (p.Data.ContainsKey("aps.alert.title"))
                {
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        //textLabel.Text = p.Data["aps.alert.title"];
                        DisplayAlert(AppResources.Literal_Aviso, p.Data["aps.alert.title"], AppResources.Literal_Aceptar);
                    });

                }
            };

**Comment by rdelrosario** [comment]
Unfortunately, you cannot use RESX localization for this cases because notifications are associated with iOS default platform localization.

On the iOS project you have to add **Localizable.strings** (Build action for these files should be Bundle Resource) for each language you need to support. This is the file where you will define your keys and values based on the language.

These files are organized by language, in specially named directories with an **.lproj** suffix.

**Base.lproj** is the directory that contains resources for the default language. It is often located in the project root (but can also be placed in the Resources folder).

**.lproj** directories are created for each supported language, usually in the Resources folder.

Once you add this files your structure should look similar to this:

![image](https://user-images.githubusercontent.com/2547751/32307919-f2d3131e-bf37-11e7-8f14-041585071342.png)

This is an example Base.lproj/Localizable.strings (default language) file:

```
"NOTIFICATION_TITLE" = "Hello World";
"NOTIFICATION_MESSAGE" = "This is a message";
```


This is an example es.lproj/Localizable.strings (ie. Spanish) file:

```
"NOTIFICATION_TITLE" = "Hola Mundo";
"NOTIFICATION_MESSAGE" = "Esto es un mensaje";
```

On the payload instead of using **title**  and **message** keys, we will use **title-loc-key** to represent the key for our localized title and **loc-key** to represent the key for our localized message.

Finally, when sending the payload would look like this:

```json
{
     "notification": {
            "title-loc-key" : "NOTIFICATION_TITLE",
            "loc-key" : "NOTIFICATION_MESSAGE"
     },
     "priority": "high",
     "condition": "'general' in topics"
}
```

That works out just fine for a static message but if you have variable parameters in the content then you will need some extra keys on your payloads and define the value for your Localizable.strings differently. Let's say my payload have variable content on the title and message, then there are two additional keys we need to add **title-loc-args** (represents the variable parameters for the title) and **loc-args** (represents the variable parameters for the message).

```json
{
     "notification": {
            "title-loc-key" : "NOTIFICATION_TITLE",
            "loc-key" : "NOTIFICATION_MESSAGE",
            "title-loc-args" : ["Dominican Republic"],
            "loc-args" : ["Rendy"]
     },
     "priority": "high",
     "condition": "'general' in topics"
}
```
Each of this two payload keys is a string array so you can have as many string arguments as you need. Here's how should **Localizable.strings** files look like when using arguments:

This is an example Base.lproj/Localizable.strings (default language) file:

```
"NOTIFICATION_TITLE" = "Hello %@";
"NOTIFICATION_MESSAGE" = "This is a message for %@";
```


This is an example es.lproj/Localizable.strings (ie. Spanish) file:

```
"NOTIFICATION_TITLE" = "Hola %@";
"NOTIFICATION_MESSAGE" = "Esto es un mensaje para %@";
```
Each %@ represents a parameter or parameters if more than one.


If you need more information on this, is all based on this references:

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW9

https://developer.xamarin.com/guides/ios/advanced_topics/localization_and_internationalization/

**Comment by rubenc57** [comment]
Thanks

**Comment by rubenc57** [comment]
Do you recommend to install latest xamarin and nuget packages updates or wait for your stable version?

**Comment by rdelrosario** [comment]
I'll be adding localization to Android next week will follow a similar approach as iOS. Will update the docs with this information too.

Is safe to keep the alpha, I will be releasing it a stable in a  few days.

**Comment by rubenc57** [comment]
Good Job, thank you for your hard work.

**Comment by rdelrosario** [comment]
You're welcome. I will close this long issue since fortunately all situations well solved, was a great teamwork solving this issues.

**Comment by kwebmaster** [comment]
Thanks to you @rdelrosario 
That's really a powerfull plugin and that's because I'm pleased to help you.
Let me know if you need any help!

Also thank to you @rubenc57 for helping me in solving the Android issue.

**Comment by aslam051** [comment]
Not receive notification.error 
The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
