### ISSUE TITLE
Events triggers multiple times. - Continuation of Issue 50

### ISSUE THREAD

**Issue by ravikanasagra1** [CrossGeeks/FirebasePushNotificationPlugin#52]
It is a continuation of issue 50. URL - [https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/50](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/50 )

My code setup is same as explained in issue 50. 

I have register notification events in App class constructor. These events trigger multiple times on successive notification clicks. As these events are register every time I click on notification, it calls App class constructor using LoadApplication method in MainActivity in Xamarin.Android. I have tried removing registered event and then register again but still event called multiple times. :(

Below code I tried but did not work. 

```
public App()
        {
            InitializeComponent();

            MainPage = new MainPage();

            try
            {
                CrossFirebasePushNotification.Current.OnTokenRefresh -= FCM_OnTokenRefresh;
                CrossFirebasePushNotification.Current.OnTokenRefresh += FCM_OnTokenRefresh;
                CrossFirebasePushNotification.Current.OnNotificationReceived -= FCM_OnNotificationReceived;
                CrossFirebasePushNotification.Current.OnNotificationReceived += FCM_OnNotificationReceived;
                CrossFirebasePushNotification.Current.OnNotificationOpened -= FCM_OnNotificationOpened;
                CrossFirebasePushNotification.Current.OnNotificationOpened += FCM_OnNotificationOpened;
            }
            catch (Exception ex)
            {
                var msg = ex.Message;
            }


        }
```

**Comment by rdelrosario** [comment]
Preferably listed to this events on OnStart method.

How are you tapping multiple times, it is suppose to delete la notification after application is opened. You mean you are tappingg multiple times before it opens?

Also please check if your issue is related to:
https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/14

**Comment by rdelrosario** [comment]
Did you aolve your issue?

**Comment by ravikanasagra1** [comment]
No, it did not. :(

I am not taping on notification multiple times. This is a issue of multiple event registration. 

Let  me explain to you again. I have written event registration methods into my App class constructor.

Now, when I click notification, control flow would be from -> Main Activity -> LoadApplication(new App()) -> inside App constructor -> it will register events second time. 

Lets say I click on another notification, control flow would be from -> Main Activity -> LoadApplication(new App()) -> inside App constructor -> it will register events third time. and so on.

So, these events would be called multiple times on notifications clicks one after another. 

As I have explained earlier, I tried to remove events before register it again to stop this multiple registration but it did not help and events were registered multiple times.

I need to find a way to only register event once.

**Comment by collaorodrigo7** [comment]
@ravikanasagra1 I do not know if you noticed they reference this issue on [issue 14](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/14)
In case you have not seen it and to help you is not you taping multiple times :) , what happens is that everytime you tap the notification a new instance of App gets created handling the event again, and that will happen everytime you open a new one. If you notice the more notifications you open, the more times you will see your event reaching.  
This is the solution:
1. Is better to hanlde the events overriding the OnStart() method on App.xaml.cs
```C#
   protected override void OnStart()
   {
            // Handle when your app starts
            CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>{ //handle here };

            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>{//handle here};
            CrossFirebasePushNotification.Current.OnNotificationOpened += async (s, p) =>{//handle here};
  }
```
2. As claudiocleberson explains on  [issue 14](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/14) , you should 
_Put the LaunchMode = LaunchMode.SingleTop in the MainActivity class. That should do the trick._
That means modify the line on top your main activity class like this:
```C#
[Activity(LaunchMode = LaunchMode.SingleTop, Label = "MainAuthApp", Icon = "@drawable/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity{...}
```
3. Add ```C#
using Android.Content;
```
4. Just like claudiocleberson explains later on #14 , Override OnNewIntent method on MainActivity
```C#
/// Called when the app is in the background and a notification is clicked on (also called each time the app is minimized and the brought back up), a new Intent is created
        /// and sent out, since we use LaunchMode set to SingleTop this method is called instead of the app being restarted.
        ///
        /// The Intent that was set when the call was made. If started from a notification click, extra string values can be extracted.
        protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            FirebasePushNotificationManager.ProcessIntent(intent);
        }
```
I was having the same issues than you and I was able to fix it by following those steps.
Let me know if it fixes the your problem or if you need more help. If you had already figured it out, hope it helps someone else.

**Comment by rdelrosario** [comment]
@collaorodrigo7 Thanks for helping with this issue.

@ravikanasagra1 I will close this issue for now, but feel free of reopening it if still having it after this information.

**Comment by abrari** [comment]
Same here on Android, using the latest version of the plugin and all of the above workarounds. 

Steps to reproduce:
1. Open app (first open)
2. Press back button, app exited
3. Reopen the app (second open)
4. Send a notification
5. Open the notification, the `OnNotificationOpened` event will be fired twice

If I exited and reopened the app for the third time, the `OnNotificationOpened` event will be fired three times. The number of app reopen is the number of the event fired.

**Comment by abrari** [comment]
Inspecting `_onNotificationOpened.GetInvocationList()` under debugger, the event subtraction `_onNotificationOpened -= value` doesn't remove anything from the list.

The solution is by setting the event handler method as `static`. So we can't use lambdas here. The same goes for the other events (`OnTokenRefresh` etc).

**Comment by guihlk** [comment]
Hi, I recently implemented the push notification platform to my app, and I was apparently facing the exact same issue when customizing my notifications. However, although the notification was popping up twice on my screen, the event wasn't indeed fired twice - my breakpoints would only be hit once.
So i decided to change the color of the notification I was handling on the OnNotificationReceived to red, and the duplicate notifications were then appearing with different colors - the original and the personalized one. 
I tried everything suggested here, including the valuable remarks from @collaorodrigo7, also tried what @abrari suggested - however i needed access to instantiated objects in my class - therefore static was not, for me particularly, doable. Nothing seemed to work.
I've found, though, a workaround that pretty much solved my problem:
adding `silent = true` to my request, like this:
```
{
  "to" : "/topics/general",
  "data" : {
    "title" : "Title - test",
    "body" : "This is a test.",
    "silent" : "true"
  },
}
```
I'm convinced this is not the desired solution, but, as i said, pretty much solved my issue...
Maybe what we're missing is a way of explicitly telling the plugin not to fire the notification we're customizing on the event? (as in my case, I'm firing it after I create a `builder`)
Or am I missing something here, and this is something already implemented? I couldn't find anything on the documentation.

PS: as this was an open issue for duplicate notifications/events being fired more than once, I decided to contribute to this particular issue, instead of opening another one.

Cheers

**Comment by raphaelsilvasage** [comment]
> Same here on Android, using the latest version of the plugin and all of the above workarounds.
> 
> Steps to reproduce:
> 
> 1. Open app (first open)
> 2. Press back button, app exited
> 3. Reopen the app (second open)
> 4. Send a notification
> 5. Open the notification, the `OnNotificationOpened` event will be fired twice
> 
> If I exited and reopened the app for the third time, the `OnNotificationOpened` event will be fired three times. The number of app reopen is the number of the event fired.

I'm with the same error. Did you make it work?

**Comment by abrari** [comment]
> I'm with the same error. Did you make it work?

Yes, by setting the event handler method as `static`.

**Comment by raphaelsilvasage** [comment]
> > I'm with the same error. Did you make it work?
> 
> Yes, by setting the event handler method as `static`.

I did it, but it didn't work :(

Could you please paste here the code?

**Comment by pablogupi** [comment]
In my case, when app is open in Android, event  CrossFirebasePushNotification.Current.OnNotificationReceived is fired as many times as notifications received. Example:

Receive notification_id=1 => OnNotificationReceived fired one time
Receive notification_id=2 => OnNotificationReceived fired two times
Receive notification_id=3 => OnNotificationReceived fired three times
Receive notification_id=4 => OnNotificationReceived fired four times

but any notification send only one time.

Any solution? Thanks

**Comment by bashkf** [comment]
> > Same here on Android, using the latest version of the plugin and all of the above workarounds.
> > Steps to reproduce:
> > 
> > 1. Open app (first open)
> > 2. Press back button, app exited
> > 3. Reopen the app (second open)
> > 4. Send a notification
> > 5. Open the notification, the `OnNotificationOpened` event will be fired twice
> > 
> > If I exited and reopened the app for the third time, the `OnNotificationOpened` event will be fired three times. The number of app reopen is the number of the event fired.
> 


I'm with the same error ... can someone help to solve it?
