### ISSUE TITLE
Problem on Android - error on executing (2.0.1-alpha)

### ISSUE THREAD

**Issue by kwebmaster** [CrossGeeks/FirebasePushNotificationPlugin#53]
Hi,

I implemented the FirebasePushNotificationPlugin on Android but I'm getting errors.
Here my packages details installed:

Xamarin.GooglePlayServices.Basement.42.1021.1
Xamarin.GooglePlayServices.Tasks.42.1021.1
Xamarin.Firebase.Common.42.1021.1
Xamarin.Firebase.Iid.42.1021.1
Xamarin.Firebase.Messaging.42.1021.1
Xamarin.GooglePlayServices.Base.42.1021.1
Xamarin.Firebase.iOS.Analytics.4.0.2
Xamarin.Firebase.iOS.InstanceID.2.0.0
Xamarin.Firebase.iOS.Core.4.0.3

I'm getting errors as soon as this method is excuted

public override void OnCreate()
        {
            base.OnCreate();
            RegisterActivityLifecycleCallbacks(this);

            FirebasePushNotificationManager.Initialize(this, false);
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("NOTIFICATION RECEIVED", p.Data);
            };
}

I also added google-services.json to my project with "GoogleServiceJson" as build action.

Do you have any idea?

**Comment by rdelrosario** [comment]
What errors are you getting?

**Comment by rdelrosario** [comment]
Please check if related to:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/2

**Comment by kwebmaster** [comment]
Yes the problem was that I need to add in csproj file

<Target Name="RemoveGoogleServicesJsonStampFiles" BeforeTargets="BeforeBuild"> <Delete Files="$(IntermediateOutputPath)\ProcessGoogleServicesJson.stamp" /> </Target>

I think it could be better to insert this in the documentation.
I don't understand if in Android is necessary or not to call the             FirebasePushNotificationManager.Initialize(this, false) method in the MainApplication

**Comment by rdelrosario** [comment]
Is on the doc on FAQ section: (first item)

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md

**Comment by rdelrosario** [comment]
@kwebmaster Yes is necessary to call FirebasePushNotificationManager.Initialize(this, false) method in the MainApplication, just as I posted on the other issue.

**Comment by kwebmaster** [comment]
I'm sorry I haven't seen this because I followed instructions reported in the Readme.md file

Thank you so much!

**Comment by kwebmaster** [comment]
@rdelrosario I completed the configuration on Android and it works, but not when the app is closed.
In works only when app is in foreground or background but not when it's closed.

Do you have any idea?

**Comment by kwebmaster** [comment]
It seems to work now as described in point 3

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md
