### ISSUE TITLE
No notification when app closed

### ISSUE THREAD

**Issue by Nuada26** [CrossGeeks/FirebasePushNotificationPlugin#54]
Hello ,

I receive push notification when my app is on foreground and background, but when i'm close application i don't receive this .
 For register application to firebase server i use an interface beetwen Portable class and native class. So i send notification push with postman with this json : 

{
	"to":"device token",
    "data": {
        "message" : "my_custom_value",
        "other_key" : true,
        "body":"tornado"
     }
}

This is work for foreground and background, but when i send notification when app is closed, i receive nothing, any idea ?

## Bug Information

Version Number of Plugin: 1.0.7
Device Tested On: Wiko Fever SE
Version of VS: 15.4.2
Version of Xamarin:  4.7.10

**Comment by rdelrosario** [comment]
Did you initialize on an Android application class? as specified in the Getting started guide?

**Comment by rdelrosario** [comment]
If none if this is your case please reopen this issue again.

**Comment by golo98** [comment]
@rdelrosario @Nuada26 , Hi to comment about this issue, I have testing to integrate the plugin on my app (android/ios), on Debug mode in my android App, I can receive notifications on foreground and background with tokens or topics, but if the app is completely closed (killed) cannot receive notifications, using Postman to testing if send directly to the last token generated, the response from the FCM server is token not registered, this happen after +- 30 seconds that the app is closed.

The plugin version used is 2.1.3

Thanks for any advice.

**Comment by CesareSoldani** [comment]
Hi,

I'm not receiving notifications once the app has been closed

v2.3.0

Xamarin.Firebase.Messaging v60.1142.0

**Comment by rdelrosario** [comment]
@CesareSoldani Did you check FAQ 2, 3 and 4? on: https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md

**Comment by CesareSoldani** [comment]
Hi,

the only one I'm not 100% about is no. 4, I can't see anything obvious, its a Galaxy Tab S. I am just about to try it on my Sony Xperia phone to see if it works there..

**Comment by rdelrosario** [comment]
Are you calling ProcessIntent on MainActivity OnCreate and OnNewIntent?

**Comment by rdelrosario** [comment]
Also when you deployed the release version did you increment the build number or uninstalled the previous debug version installed?

**Comment by rdelrosario** [comment]
What is your code block on OnNotificationReceived?

**Comment by CesareSoldani** [comment]
Are you calling ProcessIntent on MainActivity OnCreate and OnNewIntent? Yes

Also when you deployed the release version did you increment the build number or uninstalled the previous debug version installed? Both

What is your code block on OnNotificationReceived?

            // Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += async (s, p) =>
            {
                Log.WriteLine(LogPriority.Debug, "Firebase", p.Data.ToString());
                await App.DataManager.Sync(App.Foreground);
            };

I'll try commenting this out, as I assume the notification should still be displayed without this..

Cesare

ps. many thanks for your help on this.

**Comment by rdelrosario** [comment]
Where are you instantiating App.DataManager ? if is after MainActivity and not on MainApplication your app is crashing when closed because App.DataManager doesn't exist. MainActivity doesn't exist when app is closed so you need to instantiate App.DataManager on MainApplication instead.

**Comment by CesareSoldani** [comment]
kk, yeah, the notification came through when I commented out that code

many thanks

Cesare

**Comment by Srusti-Thakkar** [comment]
Hi "await App.DataManager.Sync(App.Foreground);" what is this meaning. I am not able to find App.DataManager. Can you please tell me How can I work If app is not in background neither in foreground how can I receive Notification?

**Comment by CesareSoldani** [comment]
await App.DataManager.Sync(App.Foreground); is my own code, inside it was trying to use Xamarin.Forms, which was not instatiated (Forms.Init(this, bundle);) when the app was in the background and so was crashing, which prevented the notification from displaying.

**Comment by Srusti-Thakkar** [comment]
Okay. Thanks for your quick reply.

**Comment by jainavinash845** [comment]
notification does not received when the app is not running state .
