### ISSUE TITLE
Error while building/deploying on IOS

### ISSUE THREAD

**Issue by icechat** [CrossGeeks/FirebasePushNotificationPlugin#55]
Latest Xamarin for iOS 
VS 2015 - Or Visual Studio Community for Mac
Using FirebasePushNotification 1.07
When compiling the app, get the following error:

Error		Can't resolve the reference 'System.Void Firebase.Analytics.App::Configure()', referenced from the method 'System.Void Plugin.FirebasePushNotification.FirebasePushNotificationManager/<Initialize>d__35::MoveNext()' in 'Firebase.Analytics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by rdelrosario** [comment]
You seem to be using latest iOS FCM version. So use this instead:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.0.1-alpha

**Comment by Greg767** [comment]
Hi,
The docs says this: Xamarin.Firebase.iOS.CloudMessaging (>= 1.2.1.3)
So which version should be used if we wanted the latest stable plugin version?
Thanks.

**Comment by rdelrosario** [comment]
@Greg767 Just released the latest stable version: https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.1.3
