### ISSUE TITLE
iOS not receiving notifications 

### ISSUE THREAD

**Issue by carlasampaio01** [CrossGeeks/FirebasePushNotificationPlugin#57]
I did all the steps in the tutorial in order to receive notifications. I send by Firebase a notification and nothing. The token I get in the app is different that the ones registered in firebase. Is that why it doesn't work? I am using the version 2.0.1

**Comment by rdelrosario** [comment]
When you open the application do you get the push notifications permission popup alert?

**Comment by carlasampaio01** [comment]
Yes i do. I get no errors on console. And Im sending via Postman:

`
{
    "data": {
        "message" : "my_custom_value",
        "other_key" : true,
        "body":"test"
     },
     "notification": {
       "body" : "hello",
       "title": "firebase",
       "sound": "default",
        "content_available" : true
     },
     "priority": "high",
     "condition": "'general' in topics"
}
`

and getting a message_id as result, but no notifications on phone.

**Comment by carlasampaio01** [comment]
I am sorry, its working. I don't know why, but connected to the WIFI of the company it doesn't work.

**Comment by rdelrosario** [comment]
There might be a firewall or port blocking on the WIFI of your company that might be affecting the push notifications to arrive.
