### ISSUE TITLE
Can I receive notifications in android when app is running without an UI interface?

### ISSUE THREAD

**Issue by rubenc57** [CrossGeeks/FirebasePushNotificationPlugin#59]
Hello
Can I receive notifications in android when app is running without the need of writing an UI interface?

Just like in iOS, on the top of the screen, like a banner with sound...

#51

**Comment by rdelrosario** [comment]
You mean on background?

**Comment by rubenc57** [comment]
no, on foreground

**Comment by rdelrosario** [comment]
Just release support for this on: 
https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.1.2-beta

Depending on the value of "priority" key in your data payload. It will set the notification priority. Posible values are: "max", "high","default","low","min".

The behaviour for these values:

**MAX** Use for critical and urgent notifications that alert the user to a condition that is time-critical or needs to be resolved before they can continue with a particular task.

**HIGH** Use primarily for important communication, such as message or chat events with content that is particularly interesting for the user. High-priority notifications trigger the heads-up notification display.

**DEFAULT** Use for all notifications that don't fall into any of the other priorities described here and if the application does not prioritize its own notifications

**LOW** Use for notifications that you want the user to be informed about, but that are less urgent. Low-priority notifications tend to show up at the bottom of the list, which makes them a good choice for things like public or undirected social updates: The user has asked to be notified about them, but these notifications should never take precedence over urgent or direct communication.

**MIN** Use for contextual or background information such as weather information or contextual location information. Minimum-priority notifications do not appear in the status bar. The user discovers them on expanding the notification shade.

If no priority is set then "priority" is default.

For heads-up notification send inside your payload data key "priority" : "high" within your other keys:

```json
{
   "data" : {
     "priority":"high"
  }
}

Note: This is an exclusive Android feature, doesn't do nothing on iOS.

**Comment by rubenc57** [comment]
I will try it today, thanks

**Comment by rubenc57** [comment]
Ok, I installed version 2.1.2-beta

Priority only works with "high"

"max", "default", "low" and "min" give this error:
Error on the remote server: (400) Incorrect request.

      "data" : {
          "priority": "max",
          "notification" : {
              "body"   : "test",
              "title"     : "title",
              "sound" : "Default",
           },
          "condition": "'t_android' in topics && 't_en' in topics",
      },

**Comment by rdelrosario** [comment]
Your payload should be:
```json
"data" : {
             "priority": "max",
              "body"   : "test",
              "title"     : "title",
              "sound" : "default",
              "condition": "'t_android' in topics && 't_en' in topics",
      },
```

**Comment by rubenc57** [comment]
Ok, now I don't get an error but  I don't receive the notifications with any priority assigned:

    {
        "data" : {
            "priority": "high",
            "body"    : "body",
            "title"   : "title",
            "sound"   : "default",
        },
        "condition": "'t_android' in topics && 't_en' in topics",
    },

It says message sent:

    {"message_id":6545698582888474852}

**Comment by rubenc57** [comment]
Ok
Now I receive the notifications in android with the app in the foreground with any priority, I don't see a difference though.

But in the background or with the app killed, I don't receive any notifications with any priority

**Comment by rdelrosario** [comment]
Check 3 and 4 on the FAQ section to see if your issue is related to one of those.

**Comment by rubenc57** [comment]
Not related

**Comment by rubenc57** [comment]
if I use notification messages on android I receive all notifications, back and foreground and killed, when I use data messages instead I only receive notifications in foreground (without any code change)

**Comment by rubenc57** [comment]
Code block is same as your tutorial, haven't change anything, it was working on  1-1-beta, I installed 1-2-beta and change the payload as you suggested and now I don't receive notifications in background or when killed

**Comment by rdelrosario** [comment]
This is on iOS, android or both?

**Comment by rubenc57** [comment]
I have only tested on Android

**Comment by rdelrosario** [comment]
Try on latest version

**Comment by VinoliyaPrincy** [comment]
helo

**Comment by VinoliyaPrincy** [comment]
when clicking notification is not redirecting to page when app is background or killed
