### ISSUE TITLE
Notifications when app is in foreground in iOS 10

### ISSUE THREAD

**Issue by bilson** [CrossGeeks/FirebasePushNotificationPlugin#6]
Please, add ability to show notifications when app is in foreground in iOS 10.

Example code:

```csharp
// To receive notifications in foreground on iOS 10 devices.
[Export("userNotificationCenter:willPresentNotification:withCompletionHandler:")]
public async void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
{
    // Do your magic to handle the notification data
    System.Diagnostics.Debug.WriteLine("WillPresentNotification");

    // Tell system to display the notification anyway or use
    // `None` to say we have handled the display locally.
    completionHandler(UNNotificationPresentationOptions.Alert);
}
```

Thanks

**Comment by rdelrosario** [comment]
Planning on adding this in the next few days

**Comment by claudiocleberson** [comment]
That would be great to have. I overrode the current behavior on iOS by implementing the IPushNotificationHandler, but also the notification only show on background.

**Comment by claudiocleberson** [comment]
Guys maybe that will help. Taken from StackOverflow.

[https://stackoverflow.com/questions/40942988/how-do-i-use-delegates-within-xamarin-specifically-unusernotificationcenterdele](url)

Delegate:
 public class UserNotificationCenterDelegate : UNUserNotificationCenterDelegate
    {
        [Export("userNotificationCenter:willPresentNotification:withCompletionHandler:")]
        public override void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
        {
                completionHandler(UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Sound);
                Console.WriteLine(notification);
        }
    }

Called from FinishedLaunching:

 UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();

But still for the push notification to show, I needed to handled as a Local notification(ACR Notifications Plugin ) via the method: 

public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            // If you are receiving a notification message while your app is in the background,
            // this callback will not be fired 'till the user taps on the notification launching the application.

            NSDictionary aps = userInfo.ObjectForKey(new NSString("aps")) as NSDictionary;
            int badge = 1;

            if (aps.ContainsKey(new NSString("content-available")))
            {
                CrossNotifications.Current.SetBadge(badge);
                CrossNotifications.Current.Send(new Plugin.Notifications.Notification
                {
                    Title = "Test",
                    Message = "test",
                    Vibrate = true,
                    Sound = "default",
                    When = TimeSpan.FromMilliseconds(2000),
                });
            }
           // If you disable method swizzling, you'll need to call this method. 
            // This lets FCM track message delivery and analytics, which is performed
            // automatically with method swizzling enabled.
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
            // Do your magic to handle the notification data
            System.Console.WriteLine("Receive notification AppDelegate: "+userInfo);
        }

**Comment by rdelrosario** [comment]
Just added this feature is available on: https://www.nuget.org/packages/Plugin.FirebasePushNotification/1.0.7-beta

Let me know your feedback guys and if satisfy your needs. Any suggestions are well received :)

Here what I added on the docs:

### iOS Specifics Customization

You can set UNNotificationPresentationOptions to get an alert, badge, sound when notification is received in foreground by setting static property **FirebasePushNotificationManager.CurrentNotificationPresentationOption**. By default is set to UNNotificationPresentationOptions.None.

```csharp
     public enum UNNotificationPresentationOptions
	 {
	 	 Alert,	//Display the notification as an alert, using the notification text.
		 Badge,	//Display the notification badge value in the application's badge.
		 None,	//No options are set.
		 Sound  //Play the notification sound.
	 }
```

Usage sample on iOS Project:

```csharp
   //To set for alert
   FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert;

   //You can also combine them
   FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Badge;
```

A good place to do this would be on the **OnReceived** method of a custom push notification handler if it changes depending on the notification, if not you can just set it once on the AppDelegate **FinishLaunching**.

**Note: this feature is available from 1.0.7-beta version on.**

**Comment by bilson** [comment]
Hi,

Thanks for adding :)

I test adding to FinishLaunching:

```csharp
FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Badge;
```

Alert works fine, but I don't see badge increment. I don't know if need add another option or code for badge?

**Comment by rdelrosario** [comment]
Are you sending a badge number on the payload?

**Comment by bilson** [comment]
That's my mistake!
Thanks for help... I think now I can close this issue 👍

@rdelrosario 🥇

**Comment by varun13487** [comment]
Hi everyone,
I am new to xamarin forms. Can any of you tell me how to check if the app is in foreground or background using this nuget package. Also if you can tell me when the beta version will be released as a new version.

**Comment by mabdollahiasl** [comment]
I have a problem I set the following code:
            FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Sound| UNNotificationPresentationOptions.Badge;

on finish launching . but when notification arrived, just play the sound and do not show any thing!
