### ISSUE TITLE
Android O

### ISSUE THREAD

**Issue by Foxsterc** [CrossGeeks/FirebasePushNotificationPlugin#60]
Does this plugin support Android O? So, has it been tested and confirmed as working?

Thanks,

**Comment by rdelrosario** [comment]
It should work fine on Android O, only that we have not yet implemented the new features that offers Android O like notification channels.

**Comment by Foxsterc** [comment]
The main issue with Android O is they have changed the way things work with notifications and the like so I'm guessing this may not work with Android O.

https://developer.android.com/about/versions/oreo/background.html

Which would result in 

java.lang.RuntimeException: Unable to start receiver com.onesignal.BootUpReceiver: java.lang.IllegalStateException: Not allowed to start service Intent

**Comment by rdelrosario** [comment]
It should work just fine on Android O the only major change we don’t support yet are the notifications channels
