### ISSUE TITLE
ProcessIntent null

### ISSUE THREAD

**Issue by Nuada26** [CrossGeeks/FirebasePushNotificationPlugin#61]
Hello,

Sommetimes when my application start, i have this error : 

Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
Plugin.FirebasePushNotification.FirebasePushNotificationManager.ProcessIntent(Intent intent, bool enableDelayedResponse)<a6098c6da7584c698c2aba6c0ff69dc5>:0

But sometimes it's not do this error.

Any idea for that?

**Comment by rdelrosario** [comment]
Check number 1 on https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md

To see if this is your issue.

**Comment by rdelrosario** [comment]
Did this fixed your issue?

**Comment by Nuada26** [comment]
I will try that today. sorry for be late.

**Comment by Nuada26** [comment]
I will explain more , it's works when i'm in debug with visual studio but when i upload on hockey app for exemple, randomly i have this error.

**Comment by rdelrosario** [comment]
But you tried the solution on the FAQ?

**Comment by Nuada26** [comment]
Yes i tried but it's not work.

**Comment by rdelrosario** [comment]
Are you initializing the plugin on an Android application class?

**Comment by rdelrosario** [comment]
Will close this issue for now if still having issues feel free to reopen or create a new issue.

**Comment by CamelCaseMaster** [comment]
I'm initializing the plugin on an Android application class yet this happens, If i debug using F5 it works if I run the debugged app without F5 it hangs
------------------------------
Time: 26/03/2019 10:26:01
Error: Unhandled Exception
System.Exception: CurrentDomainOnUnhandledException ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Plugin.FirebasePushNotification.FirebasePushNotificationManager.ProcessIntent (Android.App.Activity activity, Android.Content.Intent intent, System.Boolean enableDelayedResponse) [0x0008e] in <2ba41857a9494280b267965392fe8d5b>:0 
  at MyOPSApp.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x000fc] in <0e8204d8606948b28584e45ea887cc19>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <95d915721ad748108ff096dce8f8f32c>:0 
  at (wrapper dynamic-method) System.Object.8(intptr,intptr,intptr)
   --- End of inner exception stack trace ---

**Comment by CamelCaseMaster** [comment]
@rdelrosario  Setting Application attributes in assemblyInfo causes the exception for me

This works
------
#if DEBUG
    [Application(AllowBackup = false, Debuggable = true, HardwareAccelerated = true, Icon = "@mipmap/icon", Label = AppSettings.APP_Name, LargeHeap = true)]
#else
    [Application(AllowBackup = false, Debuggable = false, HardwareAccelerated = true, Icon = "@mipmap/icon", Label = AppSettings.APP_Name, LargeHeap = true)]
#endif
    public class MainApplication : Application
    {

This doesn't work
------
AssemblyInfo.cs

#if DEBUG
[assembly: Application(AllowBackup = false, Debuggable = true, HardwareAccelerated = true, Icon = "@mipmap/icon", Label = AppSettings.APP_Name, LargeHeap = true)]
#else
[assembly: Application(AllowBackup = false, Debuggable = false, HardwareAccelerated = true, Icon = "@mipmap/icon", Label = AppSettings.APP_Name, LargeHeap = true)]
#endif
