### ISSUE TITLE
Is it possible to open another Intent ?

### ISSUE THREAD

**Issue by YordanYanakiev** [CrossGeeks/FirebasePushNotificationPlugin#62]
I need to open when clicked on the notification another intent instead of the main application intent.
( Android PCL Native ).
- Is it possible, and how if it is ?

**Comment by rdelrosario** [comment]
Hi

You mean opening other activity rather than MainLauncher Activity?

**Comment by YordanYanakiev** [comment]
Yes.

**Comment by rdelrosario** [comment]
Ok this is definitely coming on next version. You will be able to set the type for the activity and the flags for launchmode that will be started on the intent when opening notifications.

I expect to release next version sometime next week.

**Comment by YordanYanakiev** [comment]
Nice ! Very nice ! 
Thank You very much in advance ! :)

**Comment by YordanYanakiev** [comment]
by the way I am not sure if this is a bug, but I have a hybride application.
A PCL app with native Android, which is used as a PCL on a PCL of a Forms app which is having Android and iOS branches. When I install the plugin - some weird files are added "MainApplication.cs" which prevents me from compiling further. I am suppressing this by setting this file to build action : None.

**Comment by rdelrosario** [comment]
Could you send a screenshot of what files are being added?

**Comment by YordanYanakiev** [comment]
The file inside the archive
[MainApplication.zip](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1477655/MainApplication.zip)

**Comment by rdelrosario** [comment]
This seems more to be added when installing the Current Activity plugin, this plugin doesn't have this dependency or add any files.

Maybe you have another plugin that is installing this and has as dependency the current activity plugin.

**Comment by YordanYanakiev** [comment]
You are awesome rdelrosario ! The nugets are restored in bunch, and probably this cause this misunderstanding ! Waiting inpationately for the new version with the activity if possible ! :)

**Comment by rdelrosario** [comment]
Just released https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.1.3  :)

Checkout:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/AndroidCustomization.md
