### ISSUE TITLE
firebase token is null

### ISSUE THREAD

**Issue by slopezmorales** [CrossGeeks/FirebasePushNotificationPlugin#63]
Hello. I’m having a problem with the implementation in production on iOS. It works fine on an app with development APNS certificate; now, when I use the production certificate on that same app, I get test messages via FCM but I can’t get the token. With "RegisteredForRemoteNotifications" or "OnNotificationReceived", Firebase.InstanceID.InstanceId.SharedInstance.Token method always returns nil. If I don’t get that token, I can’t send messages to the device. Is there anything else required in iOS production environment?
Thank you

**Comment by rdelrosario** [comment]
This you uninstall the app before testing on Release?

**Comment by slopezmorales** [comment]
No, I didn't unistall it. Anyway, I see now that with the RegisteredForRemoteNotifications method I was always using FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken, FirebaseTokenType.Sandbox). I changed it to FirebaseTokenType.Production and got the FCM token. Thanks for your prompt reply

**Comment by rdelrosario** [comment]
Every time you test on release will recommend uninstalling first. Let me know if works if you do this.

**Comment by rdelrosario** [comment]
After doing this, still got the issue?

**Comment by Afur** [comment]
I have same issue. `FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken, FirebaseTokenType.Sandbox` works pretty well but after change to `FirebaseTokenType.Sandbox` value of `CrossFirebasePushNotification.Current.Token` is `null`. Uninstalling and rebuilding does not help. 
Any ideas?

**Comment by slopezmorales** [comment]
Uninstalling and reinstalling the application did not work. While debugging, I was able to get the token by changing FirebaseTokenType.Sandbox to FirebaseTokenType.Production in DidRegisterRemoteNotifications.

**Comment by rdelrosario** [comment]
Please try on latest version. If still having issues then reopen or open a new issue.
