### ISSUE TITLE
Android silent notification

### ISSUE THREAD

**Issue by rodrigueslg** [CrossGeeks/FirebasePushNotificationPlugin#64]
Can I send silent notification for an Android device?

I want to send a notification with badge : 0 with no message, only to clear the icon badge.

Is there a way to do that?

**Comment by rdelrosario** [comment]
Send “silent” : true inside the data payload

**Comment by rodrigueslg** [comment]
it doesn't work

**Comment by rdelrosario** [comment]
How are you sending the payload?

**Comment by rdelrosario** [comment]
Check Android Customization section. There’s a payload sample there
