### ISSUE TITLE
Failed to fetch APNS token Error Domain

### ISSUE THREAD

**Issue by nmano2188** [CrossGeeks/FirebasePushNotificationPlugin#65]
Im getting the following error. i'm using device to test app.
Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"

How to fix this ?

**Comment by rdelrosario** [comment]
Are you testing on a simulator or device?

**Comment by nmano2188** [comment]
Its device

**Comment by rdelrosario** [comment]
Are you getting the token after this log?

**Comment by rdelrosario** [comment]
Install latest version, if still having issues reopen this issue or create a new one.
