### ISSUE TITLE
iOS notification is not shown if app is opened

### ISSUE THREAD

**Issue by rodrigueslg** [CrossGeeks/FirebasePushNotificationPlugin#66]
After I updated XCode and Xamarin SDK to the iOS 11 the notification stopped being shown when the app is open. This behavior was working before the update.

Android is fine.

## Bug Information

Version Number of Plugin: 1.0.7
Device Tested On: iPhone 4 and iPhone 5
Simulator Tested On: 
Version of VS: 15.4.0
Version of Xamarin: 4.7.10.22
Versions of other things you are using: xcode: 9.1.9B55, xamarin ios 11.2.0.11,

**Comment by rdelrosario** [comment]
Weird I tested this on iOS 11 and didn't have any issues. Notification was showing on foreground when using:

   FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert;


Are you setting this?

**Comment by rodrigueslg** [comment]
Yes,

public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, System.Action<UIBackgroundFetchResult> completionHandler)
        {
            FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert;
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
        }

**Comment by rdelrosario** [comment]
Move it to the FinishLaunching method instead

**Comment by rodrigueslg** [comment]
Thanks man, it worked.

But I've reinstalled the plugin too, now I don't now what was the solution, but its working fine now.

**Comment by VansW** [comment]
I'm setting CurrentNotificationPresentationOption in FinishedLaunching but it is not working. Do we need to set this before initialization call or after?
