### ISSUE TITLE
Default FirebaseApp is not initialized in this process *. Make sure to call FirebaseApp.initializeApp(Context) first.

### ISSUE THREAD

**Issue by stepanic** [CrossGeeks/FirebasePushNotificationPlugin#67]
## Bug Information

Version Number of Plugin: 42.1024.0
Device Tested On: Android 7.0 Samsung Galaxy S6
Simulator Tested On:
Version of VS: 
Version of Xamarin: 
Versions of other things you are using:
Xamarin.Forms 2.5.0

### Steps to reproduce the Behavior
Follow these instructions on fresh new Xamarin.Forms application
https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/GettingStarted.md

### Expected Behavior
To work without these workaround
https://forums.xamarin.com/discussion/comment/308465/#Comment_308465

And without Xamarin.GooglePlayServices.Basement v60.1142.0-rc1
https://bugzilla.xamarin.com/show_bug.cgi?id=56108#c41

Please update FAQ with these workaround until stable Xamarin.GooglePlayServices.Basement will be fixed.

### Actual Behavior
This workaround in FAQ.Android.1 is not working
https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md#android
```
  <Target Name="RemoveGoogleServicesJsonStampFiles" BeforeTargets="BeforeBuild">
    <Delete Files="$(IntermediateOutputPath)\ProcessGoogleServicesJson.stamp" />
  </Target>
```

### Code snippet

This is required:
```
var options = new FirebaseOptions.Builder()
                                             .SetApplicationId("")
                                             .SetApiKey("")
                                             .SetDatabaseUrl("https://*.firebaseio.com")
                                             .SetStorageBucket("*.appspot.com")
                                             .SetGcmSenderId("").Build();
            this.firebaseApp = FirebaseApp.InitializeApp(this, options);
```
Before:
```
FirebasePushNotificationManager.Initialize(this, true);
```

### Screenshots
![screen shot 2017-11-25 at 00 29 40](https://user-images.githubusercontent.com/315282/33225450-09bc3720-d178-11e7-9200-21b46f0d6309.png)

**Comment by rdelrosario** [comment]
Thanks for this finding! Just updated the FAQ section.

**Comment by HoangTri81** [comment]
I have same problem when to retrieve token device `super.onCreate(savedInstanceState);
        FirebaseApp.initializeApp(this);FirebaseInstanceId.getInstance().getInstanceId()
                .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                    @Override
                    public void onComplete(@NonNull Task<InstanceIdResult> task) {
                        if (!task.isSuccessful()) {
                            Log.w("FCM", "getInstanceId failed", task.getException());
                            return;
                        }
                        // Get new Instance ID token
                        String token = task.getResult().getToken(); String msg = getString(R.string.msg_token_fmt, token);
                        Log.d("FCM", msg);
                        Toast.makeText(MainActivity.this, msg, Toast.LENGTH_SHORT).show();
                    }
                });`
Somebody help me fix it
