### ISSUE TITLE
Configure when using Database as well

### ISSUE THREAD

**Issue by Greg767** [CrossGeeks/FirebasePushNotificationPlugin#68]
Hi,

Would there be a way to know at what point I can call Firebase Database operations? If I try to get data at OnStartup I get an exception saying FirebaseApp has not been configured.
If I add a 2 sec delay before calling the Database its ok, but its not a clean solution.
Calling Firebase.Core.App.Configure(); after FirebasePushNotificationManager.Initialize(options); results in an exception saying App has already been configured.
Thanks!

**Comment by rdelrosario** [comment]
Hi could you put here you initialization code? without any private data of course.

**Comment by Greg767** [comment]
`protected override void OnCreate (Bundle bundle)
		{
			if (Build.VERSION.SdkInt >= BuildVersionCodes.Lollipop)
			{
				// Kill status bar underlay added by FormsAppCompatActivity
				// Must be done before calling FormsAppCompatActivity.OnCreate()
				var statusBarHeightInfo = typeof (FormsAppCompatActivity).GetField ("statusBarHeight", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
				if (statusBarHeightInfo == null)
				{
					statusBarHeightInfo = typeof (FormsAppCompatActivity).GetField ("_statusBarHeight", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
				}
				statusBarHeightInfo?.SetValue (this, 0);
			}

            int themeId = this.Resources.GetIdentifier("MyTheme", "style", this.PackageName);
            base.SetTheme(themeId);
			base.OnCreate (bundle);

            ToastNotification.Init(this, new PlatformOptions(){ SmallIconDrawable = Resource.Drawable.icon180 });
			DependencyService.Register<ToastNotification>();

			Forms.Init (this, bundle);

			MR.Gestures.Android.Settings.LicenseKey = "xxxxx";
			ZXing.Net.Mobile.Forms.Android.Platform.Init ();
			FormsControls.Droid.Main.Init (this);

			LoadApplication (new App ());

			CrashManager.Register (this, "xxxxxx");

            //FirebaseApp.InitializeApp(this);

			if ((int)Build.VERSION.SdkInt >= 19)
			{
				var decorView = this.Window.DecorView;
				var uiOptions = (int)decorView.SystemUiVisibility;
				var newUiOptions = (int)uiOptions;

				newUiOptions |= (int)SystemUiFlags.Fullscreen;
				newUiOptions |= (int)SystemUiFlags.HideNavigation;
				newUiOptions |= (int)SystemUiFlags.Immersive;

				decorView.SystemUiVisibility = (StatusBarVisibility)newUiOptions;
			}
			else
			{
				var attrs = this.Window.Attributes;
				attrs.Flags |= WindowManagerFlags.Fullscreen;
				this.Window.Attributes = attrs;
            }
            //If debug you should reset the token each time.
            #if DEBUG
                FirebasePushNotificationManager.Initialize(this, true);
            #else
                FirebasePushNotificationManager.Initialize(this,false);
            #endif

            //Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                foreach (var data in p.Data)
                {
                    if (data.Key.Equals(NotificationActions.OpenEstablishment))
                    {
                        App.OpenEstablishmentAfterStartup = (string)data.Value;
                    }
                }
            };
            FirebasePushNotificationManager.ProcessIntent(Intent);
            FirebasePushNotificationManager.IconResource = Resource.Drawable.notificationwhite;
		}`

**Comment by Greg767** [comment]
`protected override void OnCreate (Bundle bundle)
		{
			if (Build.VERSION.SdkInt >= BuildVersionCodes.Lollipop)
			{
				// Kill status bar underlay added by FormsAppCompatActivity
				// Must be done before calling FormsAppCompatActivity.OnCreate()
				var statusBarHeightInfo = typeof (FormsAppCompatActivity).GetField ("statusBarHeight", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
				if (statusBarHeightInfo == null)
				{
					statusBarHeightInfo = typeof (FormsAppCompatActivity).GetField ("_statusBarHeight", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
				}
				statusBarHeightInfo?.SetValue (this, 0);
			}

            int themeId = this.Resources.GetIdentifier("MyTheme", "style", this.PackageName);
            base.SetTheme(themeId);
			base.OnCreate (bundle);

            ToastNotification.Init(this, new PlatformOptions(){ SmallIconDrawable = Resource.Drawable.icon180 });
			DependencyService.Register<ToastNotification>();

			Forms.Init (this, bundle);

			MR.Gestures.Android.Settings.LicenseKey = "xxxx";
			ZXing.Net.Mobile.Forms.Android.Platform.Init ();
			FormsControls.Droid.Main.Init (this);

			LoadApplication (new App ());

			CrashManager.Register (this, "xxxxxx");

            //FirebaseApp.InitializeApp(this);

			if ((int)Build.VERSION.SdkInt >= 19)
			{
				var decorView = this.Window.DecorView;
				var uiOptions = (int)decorView.SystemUiVisibility;
				var newUiOptions = (int)uiOptions;

				newUiOptions |= (int)SystemUiFlags.Fullscreen;
				newUiOptions |= (int)SystemUiFlags.HideNavigation;
				newUiOptions |= (int)SystemUiFlags.Immersive;

				decorView.SystemUiVisibility = (StatusBarVisibility)newUiOptions;
			}
			else
			{
				var attrs = this.Window.Attributes;
				attrs.Flags |= WindowManagerFlags.Fullscreen;
				this.Window.Attributes = attrs;
            }
            //If debug you should reset the token each time.
            #if DEBUG
                FirebasePushNotificationManager.Initialize(this, true);
            #else
                FirebasePushNotificationManager.Initialize(this,false);
            #endif

            //Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                foreach (var data in p.Data)
                {
                    if (data.Key.Equals(NotificationActions.OpenEstablishment))
                    {
                        App.OpenEstablishmentAfterStartup = (string)data.Value;
                    }
                }
            };
            FirebasePushNotificationManager.ProcessIntent(Intent);
            FirebasePushNotificationManager.IconResource = Resource.Drawable.notificationwhite;
		}`

**Comment by rdelrosario** [comment]
Where are you calling the database?

**Comment by rdelrosario** [comment]
Still having issues?

**Comment by Greg767** [comment]
Hi Rendy! Sorry for the silence! In my project I can use the plugin now without the 2 seconds delay and with Database. I am just under stress these days but I will retest your sample project as well and will give feedback.
Thanks a lot for your quick responses!

**Comment by rdelrosario** [comment]
Ok let me know if you had to do anything additional or special in the initialization to add it to the docs. Will close this issue for now.
