### ISSUE TITLE
Java.Lang.IllegalStateException in latest sample project at startup

### ISSUE THREAD

**Issue by Greg767** [CrossGeeks/FirebasePushNotificationPlugin#69]
## Bug Information

Version Number of Plugin: 2.1.3
Device Tested On: Samsung Galaxy S7
Simulator Tested On: - 
Version of VS: 7.2.2 build 11
Version of Xamarin:Xamarin.Android Version: 8.0.2.1 (Visual Studio Community)
Versions of other things you are using: default

### Steps to reproduce the Behavior
I downloaded the sample project and only changed the google-services.json file to be able to send notifications to this app. Everything else is untouched.

### Expected Behavior
App should start up

### Actual Behavior
App crashes on startup

### Code snippet
Code is not changed

### Error
Default FirebaseApp is not initialized in this process com.crossgeeks.firebasepushnotificationsample. Make sure to call FirebaseApp.initializeApp(Context) first.

**Comment by rdelrosario** [comment]
Did you do clean before running and still get the exception?

**Comment by rdelrosario** [comment]
Also what's the Xamarin.GooglePlayServices.Basement package version installed?

**Comment by rdelrosario** [comment]
Retested the sample and seems fine, let me know if still have issues just reopen this.

**Comment by Greg767** [comment]
It seems that cleaning and rebuilding solves this issue. Whenever I change the project properties, like going from debug to release, need to do this.
Thanks!
