### ISSUE TITLE
Doesn't receive notification when in release mode and linker Sdk and User Assemblies

### ISSUE THREAD

**Issue by paradisehuman** [CrossGeeks/FirebasePushNotificationPlugin#71]
Hi. When I use Sdk Assemblies only , everything is working fine , but when I change linker option to link all, app doesn't receive notification at all!
Is anything most preserve or configure or skip? 
I have tested in real device and emulator.

**Comment by rdelrosario** [comment]
Did you uninstalled the debug version before installing release or increment your version number once you change to release?

**Comment by paradisehuman** [comment]
I increment version number when publish it in release mode , but I dont sure that I uninstall debuge version before installing release mode.

**Comment by paradisehuman** [comment]
@rdelrosario I can run my app and receive notification in release mode in sdk only.
My problem is when I choose linker option to linkAll !

**Comment by rdelrosario** [comment]
I don't think this has to do with the plugin, this seems more a linking issue.

**Comment by paradisehuman** [comment]
@rdelrosario Do you know how can i find any instruction or solution to solve it ?

**Comment by rdelrosario** [comment]
This is on iOS or Android?

**Comment by paradisehuman** [comment]
Android

**Comment by rdelrosario** [comment]
Did you check these:

https://developer.xamarin.com/guides/android/advanced_topics/linking/
https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/publishing_an_application/part_1_-_preparing_an_application_for_release/#Configure_the_Linker

**Comment by paradisehuman** [comment]
@rdelrosario Thank you for your guidance. I investigated my build and I figured out it wasn’t linker problem. It was a connection problem to FCM.
In setup guide it says:
 Important: While debugging set resetToken parameter to true.

Why we must not reset token in release mode ?

**Comment by rdelrosario** [comment]
Because you don’t want to reset the token each time when released only when is actually needed.

When version number increases or token expired.

**Comment by paradisehuman** [comment]
I solved my problem by linkskip your plugin assembly and firebase and google play services assemblies . 
It's complicated when testing firebase by emulator. I tested it on real device and everything going back to normal, thank you for your support.
