### ISSUE TITLE
Error to handle Push Notifications after upgrade from v1.0.7 to v2.1.3

### ISSUE THREAD

**Issue by tonholis** [CrossGeeks/FirebasePushNotificationPlugin#73]
As mentioned in the title, after update NuGet package I can't handle push messages anymore.
An unhandled exception is thrown before run the OnNotificationReceived event.

## Bug Information

Version Number of Plugin: 2.1.3
Device Tested On: Huawei CAN-L01 with Android 6.0
Version of VS: 15.4.5
Version of Xamarin: 4.7.10.38
Versions of other things you are using:

* Plugin.FirebasePushNotification version="2.1.3"
* Xamarin.Android.Arch.Core.Common version="1.0.0"
* Xamarin.Android.Arch.Lifecycle.Common version="1.0.1"
* Xamarin.Android.Arch.Lifecycle.Runtime version="1.0.0"
* Xamarin.Android.Support.Animated.Vector.Drawable version="26.1.0.1"
* Xamarin.Android.Support.Annotations version="26.1.0.1"
* Xamarin.Android.Support.Compat version="26.1.0.1"
* Xamarin.Android.Support.Core.UI version="26.1.0.1"
* Xamarin.Android.Support.Core.Utils version="26.1.0.1"
* Xamarin.Android.Support.Design version="26.1.0.1"
* Xamarin.Android.Support.Fragment version="26.1.0.1"
* Xamarin.Android.Support.Media.Compat version="26.1.0.1"
* Xamarin.Android.Support.Transition version="26.1.0.1"
* Xamarin.Android.Support.v4 version="26.1.0.1"
* Xamarin.Android.Support.v7.AppCompat version="26.1.0.1"
* Xamarin.Android.Support.v7.CardView version="26.1.0.1"
* Xamarin.Android.Support.v7.MediaRouter version="26.1.0.1"
* Xamarin.Android.Support.v7.Palette version="26.1.0.1"
* Xamarin.Android.Support.v7.RecyclerView version="26.1.0.1"
* Xamarin.Android.Support.Vector.Drawable version="26.1.0.1"
* Xamarin.Build.Download version="0.4.7"
* Xamarin.Firebase.Common version="42.1021.1"
* Xamarin.Firebase.Iid version="42.1021.1"
* Xamarin.Firebase.Messaging version="42.1021.1"
* Xamarin.Forms version="2.5.0.121934"
* Xamarin.GooglePlayServices.Base version="42.1021.1"
* Xamarin.GooglePlayServices.Basement version="42.1021.1"
* Xamarin.GooglePlayServices.Tasks version="42.1021.1"

### Steps to reproduce the Behavior

* Implement OnNotificationReceived event as described in Readme using version 1.0.7
* Upgrade to 2.1.3
* Send a push notification using Firebase console

### Expected Behavior

It should handle push notifications successfully as in the previous version.

### Actual Behavior

It is throwing an exception when a new push notification arrives as described in stacktrace bellow:

```
12-05 17:03:58.345 I/MonoDroid(30993): UNHANDLED EXCEPTION:
12-05 17:03:58.390 I/MonoDroid(30993): System.MissingMethodException: Method 'Plugin.FirebasePushNotification.Abstractions.FirebasePushNotificationDataEventArgs.get_Data' not found.
12-05 17:03:58.390 I/MonoDroid(30993):   at Plugin.FirebasePushNotification.FirebasePushNotificationManager.RegisterData (System.Collections.Generic.IDictionary`2[TKey,TValue] data) [0x00000] in C:\Plugins\FirebasePushNotification\src\Plugin.FirebasePushNotification.Android\FirebasePushNotificationManager.cs:359 
12-05 17:03:58.390 I/MonoDroid(30993):   at Plugin.FirebasePushNotification.PNFirebaseMessagingService.OnMessageReceived (Firebase.Messaging.RemoteMessage message) [0x0014f] in C:\Plugins\FirebasePushNotification\src\Plugin.FirebasePushNotification.Android\PNFirebaseMessagingService.cs:59 
12-05 17:03:58.390 I/MonoDroid(30993):   at Firebase.Messaging.FirebaseMessagingService.n_OnMessageReceived_Lcom_google_firebase_messaging_RemoteMessage_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_message) [0x00011] in <9d0d1f3bc0ed4aa895271e840e47dc1a>:0 
12-05 17:03:58.390 I/MonoDroid(30993):   at (wrapper dynamic-method) System.Object:c5c3b802-7e41-4d7d-9c72-62a6a8aa806c (intptr,intptr,intptr)
12-05 17:03:58.407 W/art     (30993): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
```

**Comment by rdelrosario** [comment]
Did you update your PCL project as well?

**Comment by rdelrosario** [comment]
It seems not on all of the projects that use the package in the solution, package might not be updated in all.

**Comment by tonholis** [comment]
Yes, you right. Somehow VS left a wrong reference after updating the packages.
I deleted packages folder, bin and obj in PCL, Droid and iOS projects, recompile and it worked. 

Thanks!
