### ISSUE TITLE
Object reference not set to an instance of an object. error

### ISSUE THREAD

**Issue by nmano2188** [CrossGeeks/FirebasePushNotificationPlugin#74]
After updating to lastest i got this error while build iOS app. Have any idea?

Target "_XamarinBuildDownloadCore: (TargetId:75)" in file "E:\FirebasePushSample\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.targets" from project "E:\FirebasePushSample\FirebasePushSample.iOS\FirebasePushSample.iOS.csproj" (target "_XamarinBuildDownload" depends on it):
1>Set Property: XamarinBuildDownloadUser7ZipPath=\Common7\IDE\Extensions\Xamarin.VisualStudio\7-Zip\7z.exe
1>Using "XamarinDownloadArchives" task from assembly "E:\FirebasePushSample\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.dll".
1>Task "XamarinDownloadArchives" (TaskId:44)
1>  Task Parameter:
1>      Archives=
1>          FInstncID-2.0.0
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/921adf5f4d0ba359/FirebaseInstanceID-2.0.4.tar.gz
1>          FCr-4.0.8
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/a62ba73f1f65cd7b/FirebaseCore-4.0.8.tar.gz
1>          FAnlytcs-4.0.4
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/15a4dd6c971f8bbf/FirebaseAnalytics-4.0.4.tar.gz
1>          FCldM-2.0.4
1>                  Kind=Tgz
1>                  Url=https://dl.google.com/dl/cpdc/d0ac220cfb625fd2/FirebaseMessaging-2.0.4.tar.gz (TaskId:44)
1>  Task Parameter:DestinationBase=C:\Users\user\AppData\Local\XamarinBuildDownloadCache\ (TaskId:44)
1>  Task Parameter:CacheDirectory=C:\Users\user\AppData\Local\XamarinBuildDownloadCache\ (TaskId:44)
1>  Task Parameter:User7ZipPath=\Common7\IDE\Extensions\Xamarin.VisualStudio\7-Zip\7z.exe (TaskId:44)
1>E:\FirebasePushSample\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.targets(52,3): error : Object reference not set to an instance of an object.
1>Done executing task "XamarinDownloadArchives" -- FAILED. (TaskId:44)
1>Done building target "_XamarinBuildDownloadCore" in project "FirebasePushSample.iOS.csproj" -- FAILED.: (TargetId:75)
1>

**Comment by rdelrosario** [comment]
Did you try:
- Deleting bin/obj folders
- Clean
- Rebuild

**Comment by rdelrosario** [comment]
Will close this for now since doesn't seem to be related to the sample but to the dev enviroment, let me know if what I suggested fixed your issue.

**Comment by VictorK1902** [comment]
I ran into this exact same issue after upgrading to the latest version (2.1.3). It might have something to do with the Xamarin.Build.Download dependency (version >=0.4.6)

    .....\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.targets(52,3): error : Object reference not set to an instance of an object.

I notice that starting from version 1.2.2, Xamarin.Firebase.iOS.CloudMessaging dependency requires Xamarin.Build.Download >= 0.4.6 and somehow this causes the issues as stated above.

I'm not entirely sure how to resolve this cause I already tried your suggestion above but didn't help.

I ended up downgrading our package to 1.0.7 which accepts Xamarin.Firebase.iOS.CloudMessaging 1.2.1.3 which is ok with Xamarin.Build.Download 0.4.3. And that solves the problem for now.

**Comment by VictorK1902** [comment]
@rdelrosario Could you confirm this?

**Comment by nmano2188** [comment]
Issue not yet fixed. Any work around?

**Comment by ahmadalgarni** [comment]
I am facing the same Issue, When I try to add the any Nuget package that depends on Xamarin.build.download  >= 0.4.6, 

Any solutions ?

**Comment by ahmadalgarni** [comment]
I ever tried Older versions of Xamarin.build.download, but still having the same issue,

**Comment by jpessini** [comment]
Open the following file:
C:\<path to your app>\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.targets

Search for:
<XamarinBuildDownloadUser7ZipPath Condition="'$(OS)'!='Unix' and '$(XamarinBuildDownloadUser7ZipPath)'==''">$(VsInstallRoot)\Common7\IDE\Extensions\Xamarin\Xamarin.VisualStudio\7-Zip\7z.exe</XamarinBuildDownloadUser7ZipPath>

And replace with the correct path:
<XamarinBuildDownloadUser7ZipPath>C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Xamarin\Xamarin.VisualStudio\7-Zip\7z.exe</XamarinBuildDownloadUser7ZipPath>

;)

**Comment by ahmadalgarni** [comment]
@jpessini  thank you sooooo much this solved the problem after 2 days of trying

Thank you again

**Comment by alejob54** [comment]
I can´t find "Packages" folder in the project Path in VS2017 15.8.8, Xamarin 4.11.0.776, any ideas ?
