### ISSUE TITLE
Support for older versions of Android

### ISSUE THREAD

**Issue by jpetty96** [CrossGeeks/FirebasePushNotificationPlugin#75]
I guess this is a feature request, confused as to why the [guides](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/GettingStarted.md) say this only supports versions of Android API 24+..?

Firebase natively supports Android 4.0 (API 14+) as stated in the [Firebase docs](https://firebase.google.com/docs/android/setup).

I think it'd be nice to see this package support some older version of Android, at least back to version 6.0 (API 23).

To start the discussion, what aspects of this package are restricting it to such a new version of Android?

**Comment by rdelrosario** [comment]
The Target framework should be API 24+. But the Target Android version and Minimum Android version could be a lower API Level.

Here explained the difference of each one:


Target Framework – Specifies which framework to use in building your application. This API level is used at compile time by Xamarin.Android.

Minimum Android Version – Specifies the oldest Android version that you want your app to support. This API level is used at run time by Android.

Target Android Version – Specifies the version of Android that your app is intended to run on. This API level is used at run time by Android.

**Comment by jpetty96** [comment]
Thanks for clarifying the difference there.

I'll have a play and do some testing on a device with a lower API level and see how it goes.

**Comment by rdelrosario** [comment]
Ok let me know if you have any issues when doing, if so just reopen this issue. will close it meanwhile.
