### ISSUE TITLE
Force renewale of token

### ISSUE THREAD

**Issue by Umar3x** [CrossGeeks/FirebasePushNotificationPlugin#76]
Hello,

This is relative to another issue where I asked that here => #17 

Hello @rdelrosario

Thank you for your answer. So I've tried .Reset(), it works, but it does not seems to trigger a renew for the token. It is empty when I log in again after calling this method. Thought that by resetting token it will force firebase to generates a new one ... but what I've got is just "".

Thanks.

**Comment by rdelrosario** [comment]
After reset you should get the token here:

```csharp

  CrossFirebasePushNotification.Current.OnTokenRefresh += (s,p) =>
  {
        System.Diagnostics.Debug.WriteLine($"TOKEN : {p.Token}");
  };

```

You are not getting the token there?

**Comment by evilanf** [comment]
this is not working for me either, it resets fine but does not fire the event to referesh. Also how do you reset on iOS?
