### ISSUE TITLE
Getting Error "Default FirebaseApp is not initialized in this process"  after updating to xamarin 2.5

### ISSUE THREAD

**Issue by eyacoub** [CrossGeeks/FirebasePushNotificationPlugin#77]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:2.1.3
Device Tested On:Note 8
Simulator Tested On:
Version of VS: 2017 v15.5
Version of Xamarin: 2.5.0.1219
Versions of other things you are using:

**Comment by rdelrosario** [comment]
Did you check the workarounds on the FAQ section:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md

**Comment by eyacoub** [comment]
yes of course i did, it was working fine for the past 3 months, but after update the Xamarin forms, i'm having now this issue.

**Comment by rdelrosario** [comment]
So none of these 3 workarounds works for you:

**Workaround 1**

Add the following to the android project .csproj file:

```xml
   <Target Name="RemoveGoogleServicesJsonStampFiles" BeforeTargets="BeforeBuild">
    <Delete Files="$(IntermediateOutputPath)\ProcessGoogleServicesJson.stamp" />
   </Target>
```
   
**Workaround 2**

Add the following call:
	
```cs
   var options = new FirebaseOptions.Builder()
		.SetApplicationId("")
		.SetApiKey("")
		.SetDatabaseUrl("https://*.firebaseio.com")
		.SetStorageBucket("*.appspot.com")
		.SetGcmSenderId("").Build();
    this.firebaseApp = FirebaseApp.InitializeApp(this, options);
```
	
Before:

```cs
    FirebasePushNotificationManager.Initialize(this, true);
```
	
**Workaround 3**

Install Xamarin.GooglePlayServices.Basement v60.1142.0-rc1 on Android

**Comment by rdelrosario** [comment]
@eyacoub let me know if any of these workarounds worked for you

**Comment by eyacoub** [comment]
dear, unfortunately none of the above did the trick, i'm still getting the same error, and in every step i'm cleaning and deleting the BIN and OBJ folder.
when trying workaround 2, I'm getting the following error 
Java.Lang.IllegalArgumentException: <Timeout exceeded getting exception details>

**Comment by jaspervanmegroot** [comment]
Have the same issue

**Comment by jaspervanmegroot** [comment]
After many tries the second workaround was the solution!

**Comment by eyacoub** [comment]
can you please tell me how did you use the second workaround, as it's giving an compile error this.firebaseApp unknown member.

**Comment by aubykhan** [comment]
I get this issue intermittently. What works for me is, to clean the Android project and rebuild it.

**Comment by JTrotta** [comment]
@aubykhan , me too. I restarted the PC, cleaned and rebuilt the project. Now it works.

**Comment by rdelrosario** [comment]
If anyone still has this issue try installing:

[https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.2.0-beta](https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.2.0-beta)

Still testing this beta but will release it stable soon
