### ISSUE TITLE
Notification Customization

### ISSUE THREAD

**Issue by AnthonyLatty** [CrossGeeks/FirebasePushNotificationPlugin#78]
I am currently using this plugin to implement push notification in my application. I was wondering if the notifications can be customized a bit more. For example, i would like when the notification is in the application drawer on Android and the user clicks that notification it opens the application and also opens a DisplayAlert containing the details of that notification.

What are the steps i should take when implementing this feature with this plugin or does this plugin support things like that?

Thanks for response in advance.

**Comment by rdelrosario** [comment]
You can use a push notification handler

### Push Notification Handler

A push notification handler is the way to provide ui push notification customization(on Android) and events feedback on native platforms by implementing **IPushNotificationHandler** interface. The plugin has a default push notification handler implementation and it's the one used by default.

```csharp
public interface IPushNotificationHandler
{
        //Method triggered when an error occurs
        void OnError(string error);
        //Method triggered when a notification is opened
        void OnOpened(NotificationResponse response);
        //Method triggered when a notification is received
        void OnReceived(IDictionary<string, string> parameters);
}
```
An example of a custom handler use is the [DefaultPushNotificationHandler](../src/Plugin.FirebasePushNotification.Android/DefaultPushNotificationHandler.cs) which is the plugin default implementation to render the push notification ui when sending data messages and supporting notification actions on Android.

### Initialize using a custom PushHandler on Application class on Android:

Application class **OnCreate** on Android:

```csharp
    #if DEBUG
      FirebasePushNotificationManager.Initialize(this,new CustomPushHandler(),true);
    #else
      FirebasePushNotificationManager.Initialize(this,new CustomPushHandler(),false);
    #endif
```
To keep the default push notification handler functionality but make small adjustments or customizations to the notification. You can inherit from **DefaultPushNotificationHandler** and implement **OnBuildNotification** method which can be used to e.g. load an image from the web and set it as the 'LargeIcon' of a notification (notificationBuilder.SetLargeIcon) or other modifications to the resulting notification.

**Note: If you use a custom push notification handler on Android, you will have full control on the notification arrival, so will be in charge of creating the notification ui for data messages when needed.**
