### ISSUE TITLE
Current_OnNotificationReceived not raised on message send.

### ISSUE THREAD

**Issue by christophedemey** [CrossGeeks/FirebasePushNotificationPlugin#8]
Hi

I am trying to get the plugin to work but am not receiving my notifications using Xamarin Forms.

In my App() constructor in the PCL project i put :  

```
CrossFirebasePushNotification.Current.OnTokenRefresh += Current_OnTokenRefresh;
CrossFirebasePushNotification.Current.OnNotificationReceived += Current_OnNotificationReceived; ;
CrossFirebasePushNotification.Current.OnNotificationOpened += Current_OnNotificationOpened;
CrossFirebasePushNotification.Current.OnNotificationError += Current_OnNotificationError;
```

In my Android app in MainActivity.OnCreate i put :  

```
LoadApplication(new App());
#if DEBUG
            FirebasePushNotificationManager.Initialize(this, true);
#else
              FirebasePushNotificationManager.Initialize(this,false);
#endif
            
            //Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                
            };

            FirebasePushNotificationManager.ProcessIntent(Intent);
```

When i start the app i get the event in my PCL library : Current_OnTokenRefresh which contains a token.

I then take the example from the docs here using firebasenet and send to that token a message.
The response from the request is 'success:1' inside the returned json.
But the event Current_OnNotificationReceived is not received nor is there any notification in the notification tray.

Any help is greatly appreciated.

**Comment by christophedemey** [comment]
Ok changed 2 things by reading the docs.
- Put the initialize stuff in MainApplication.cs
- Left the ProcessIntent in MainActivity.
- Set my Android minimum version to API Level 22.

I still am not getting messages sent by the example code firebasenet and i also tried from firebase console.

**Comment by rdelrosario** [comment]
What payload are you sending?

**Comment by rdelrosario** [comment]
Did you try sending it using Firebase portal? to confirm configuration is correct

**Comment by christophedemey** [comment]
Hi @rdelrosario 

I tested with firebasenet and from the console all say everything is ok, i did see the general tag i created now in the topics.

I followed the video multiple times, however i am using visual studio and more steps are required then the video describes, i've recreated the project in a fresh empty project to make sure it's not my project screwing up the plugin, it yields same results except i only get 1x the token event so thats good :)

I created a git repo here, please let me know if you cloned it so i can remove it again since it contains my google server key.
https://github.com/christophedemey/firebase

It contains the console app where i perform the firebase request from and the xamarin forms project with an android project.
Thanks.

**Comment by rdelrosario** [comment]
Just cloned it

**Comment by christophedemey** [comment]
Ok, thanks, been experimenting all day, no luck so far.

**Comment by rdelrosario** [comment]
Move this calls:
```cs
           CrossFirebasePushNotification.Current.OnTokenRefresh += (s, p) =>
            {
                string token = p.Token;
            };

            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                int x = 1 + 1;
            };
```
To the OnStart method instead of constructor

**Comment by rdelrosario** [comment]
Also noticed the app is missing icon, version name and version on Application properties

**Comment by rdelrosario** [comment]
Ok just figured out your issue. On your AndroidManifest you have the receivers outside the application section not inside.

You have it like this:

```xml
<application android:label="AmazingApp1" android:icon="@drawable/icon"></application>
<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
	<intent-filter>
		<action android:name="com.google.android.c2dm.intent.RECEIVE" />
		<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
		<category android:name="${applicationId}" />
	</intent-filter>
</receiver>
```
Receivers should be inside the application section, like this:

```xml
<application android:label="AmazingApp1" android:icon="@drawable/icon">
   <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
   <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
	        <intent-filter>
	            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
	            <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
	            <category android:name="${applicationId}" />
	        </intent-filter>
    </receiver>
</application>
```

**Comment by christophedemey** [comment]
Hi @rdelrosario 

Bah, i feel so stupid, thank you for pointing this out to me.
I tested and everything is working great on the example app and on the production app.
I will try and read the fucking manual better next time.

Thanks!
