### ISSUE TITLE
MyApp Stops when run on my device

### ISSUE THREAD

**Issue by EdgarNunezTrejo** [CrossGeeks/FirebasePushNotificationPlugin#81]
Version Number of Plugin:2.1.3
Device Tested On:Samsung GT-I810L Android 4.1 Api 16
Simulator Tested On: None
Version of VS: VS Community 2017 15.2
Version of Xamarin: 4.5.0.486
Versions of other things you are using: Xamarin Andoid.SDK 7.3.1.2

###Steps to reproduce the Behavior
Run the app on the device
### Expected Behavior
Open the app
### Actual Behavior
When it starts on deploy, I just get this: Android application is debugging.
This debug engine does not support exception conditions. The condition(s) will be ignored.
Then myApp close, i just get this issue when add FireBasePushNotification, I tried reinstall but it doesnt work.
I also set my output verbosity on detailed and the thing i get but i dont know where is 1>Name cannot begin with the '$' character, hexadecimal value 0x24.

I hope you can help me. Thanks!

**Comment by rdelrosario** [comment]
Please check the FAQ section:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md

**Comment by EdgarNunezTrejo** [comment]
Thank you! Let me check it out

**Comment by EdgarNunezTrejo** [comment]
I've tried adding the google service package but i get this error:

Severity Code Description Project File Line Suppression State
Error Could not install package 'Xamarin.Firebase.Common 60.1142.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I've seen forums and they said to set the "target version" and the "compile with version" in the same and the last i have, then i set them as 7.1 but im still having the same issue.

I made a new project and tried to install Firebase, but the same issue comes up

**Comment by EdgarNunezTrejo** [comment]
Hey! I couldnt install the google services basement package but i tried with another device version 6.0 and it seems to work, but I still have problems in android 4.1

**Comment by rdelrosario** [comment]
Are you still having this issue?

**Comment by rdelrosario** [comment]
If you are still having this issue, feel free to reopen this issue or create a new one.
