### ISSUE TITLE
Not able to get push notifications in android

### ISSUE THREAD

**Issue by Simple-codinger** [CrossGeeks/FirebasePushNotificationPlugin#82]
Version Number of Plugin: 2.1.3
Device Tested On: OnePlus 5
Simulator Tested On: 
Version of VS: Visual Studio 2017 for Mac version 7.3 
Version of Xamarin: Xamarin Forms 2.5.0.91635

I'am using this plugin in an Xamarin forms application. It works on iOS devices but not on android.

**Comment by rdelrosario** [comment]
Did you check the FAQ section already?

https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md

**Comment by Simple-codinger** [comment]
Yes, but there are no related topics.

This is my Application Output.

[FirebaseApp] com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
[InstanceID] App restored, clearing state
[FirebaseInstanceId] Failed to resolve target intent service, skipping classname enforcement
[FirebaseInstanceId] Error while delivering the message: ServiceIntent not found.
[FirebaseInstanceId] Failed to resolve target intent service, skipping classname enforcement
[FirebaseInstanceId] Error while delivering the message: ServiceIntent not found.
[FirebaseApp] com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
[FA] App measurement is starting up, version: 11400
[FA] To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
[FA] To enable faster debug mode event logging run:
[FA]   adb shell setprop debug.firebase.analytics.app tuerantuer.app.integreat

**Comment by rdelrosario** [comment]
Are you using Android Oreo?

**Comment by Simple-codinger** [comment]
Yes I do

**Comment by rdelrosario** [comment]
Ok that might be the issue. Please try:

[https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.2.0-beta](https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.2.0-beta)

Added support to Android O on this beta, let me know if works for you.

**Comment by aslam051** [comment]
I am using the same example also follow your video tutorial but not getting a notification.please help

**Comment by aslam051** [comment]
Version Number of Plugin: 2.1.3
Device Tested On Nexux 5...6.0.1

**Comment by aslam051** [comment]
I have change xamrin.form version to  2.3.4.247.its work for me.

**Comment by rdelrosario** [comment]
Will close this issue now. Just released the latest stable version with this fix.

**Comment by minafaw3** [comment]
I have the same issue with latest version 2.2.3 

[FirebaseApp] com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
[FirebaseInstanceId] Failed to resolve target intent service, skipping classname enforcement
[FirebaseInstanceId] Error while delivering the message: ServiceIntent not found.
[FirebaseApp] com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
[FirebaseApp] com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
[FirebaseInitProvider] FirebaseApp initialization successful

**Comment by autosoftmultimedia** [comment]
me too
