### ISSUE TITLE
Couldn't build the application after adding the Plugin.FirebasePushNotification

### ISSUE THREAD

**Issue by RagulChandra** [CrossGeeks/FirebasePushNotificationPlugin#86]
I am getting following error after adding the Plugin.FirebasePushNotification.

project/iOS/clang: Error: no such file or directory: 'project/iOS/obj/iPhone/Release/mtouch-cache/FirebaseMessaging' (project.iOS)
project/iOS/clang: Error: no such file or directory: 'project/iOS/obj/iPhone/Release/mtouch-cache/FirebaseInstanceID' (project.iOS)
project/iOS/clang: Error: no such file or directory: 'project/iOS/obj/iPhone/Release/mtouch-cache/FirebaseCore' (project.iOS)
project/iOS/clang: Error: no such file or directory: 'project/iOS/obj/iPhone/Release/mtouch-cache/FirebaseCoreDiagnostics' (project.iOS)
project/iOS/clang: Error: no such file or directory: 'project/iOS/obj/iPhone/Release/mtouch-cache/FirebaseNanoPB' (project.iOS)
project/iOS/clang: Error: no such file or directory: 'project/iOS/obj/iPhone/Release/mtouch-cache/FirebaseAnalytics' (project.iOS)
project/iOS/error MT5209: Error: clang: error: no such file or directory: \

**Comment by rdelrosario** [comment]
This seems more related to your local environment. Did you delete bin and obj folders?

Also clean the project and rebuild

**Comment by rdelrosario** [comment]
Will close this issue for now since seems not to be related to the plugin. Let me know if keep getting it.
