### ISSUE TITLE
OnNotificationOpened fired but not completely execute in release & debug mode

### ISSUE THREAD

**Issue by Umar3x** [CrossGeeks/FirebasePushNotificationPlugin#88]
Hello,

**Version Number of Plugin: 2.1.3
Device Tested On: Samsung A5 2017 Android Nougat
Simulator Tested On:
Version of VS: 15.4.4
Version of Xamarin: 2.4.0.282
Versions of other things you are using:** 

Everything works fine for this plugin except when handling open notification in release & debug mode (for Android only atm, did not test for iOS)

I configured everything as documented (in mainActivity, mainApplication, process intent and so), listening to the OnNotificationOpened in the OnStart() Method : 
```

        CrossFirebasePushNotification.Current.OnNotificationOpened += async (s, p) =>
            {
                await PushNotificationService.ProcessReceivedPushNotificationAsync(p);
            };
```
**Update** : the event seems to be fired but it seems that in release & debug when my ProcessReceivedPushNotificationAsync is called and execute it does not wait until end of task and just leave the handler before the end of the execution

This is a dataMessage with ids stored in the Data Dictionary<>. 

Wanted behavior : When a notification is received and the user clicks on it, process data sent and doing some work on the UI. 

I can't find out what's going on as when I put break points it works, w/o it depends ... sometimes it executes everything well, sometimes nothing happens ...

Thanks

**Comment by rdelrosario** [comment]
When building on release:

Did you uninstall the previous debug version before installing release version or increase the version build number?

Need to do one or the other for it to work on release.

**Comment by Umar3x** [comment]
Hello,

Thanks for your fast answer. I always uninstall the previous debug version before installing the release one yes. I updated my post as it seems it's well called but does not wait until completion of task to leave handler ...

**Comment by Umar3x** [comment]
For more info, here is the function I call in the handler :  
public async Task ProcessReceivedPushNotificationAsync(FirebasePushNotificationResponseEventArgs pushNotif)
        {
            if (!pushNotif.Data.ContainsKey("type") && !pushNotif.Data.ContainsKey("trade_id")) return;
            var type = pushNotif.Data["type"].ToString();
            var tradeUserId = pushNotif.Data["trade_id"].ToString();
            //var newMatchedItem = pushNotif.Data["new_item_id"].ToString();
            //var currentConnectedUserItem = pushNotif.Data["user_item_id"].ToString();
            //Dictionary<string, string> fillingPoints = new Dictionary<string, string>
            //{
            //    { "newMatchedItem", newMatchedItem },
            //    { "currentConnectedUserItem", currentConnectedUserItem }
            //};
**_EXCEUTION STOPS SOMEWHERE HERE AND LEAVE FUNCTION_**
            await LoadingService.OnLoading();
            var trade = await TradeService.GetPublicTrade(int.Parse(tradeUserId));
            await LoadingService.EndLoading();
            if (trade == null) return;
            switch (type)
            {   case NotificationType.NewSearchResultPush:
                    //await ((MasterDetailPage) Application.Current.MainPage).Detail.Navigation.PopToRootAsync();
                    //MessagingCenter.Send(this,"TriggerMatchingOnPin", fillingPoints);
                    break;
                case NotificationType.NewTradeUserInterested:
                    TradeService.ProcessResumeTrade(trade);
                    break;
                case NotificationType.NewTradeQuotationRequested:
                    TradeService.ProcessResumeTrade(trade);
                    break;
            }
        }

**Comment by rdelrosario** [comment]
Maybe the issue is you need to run ui stuff on MainThread. LoadingService is for ui?

**Comment by Umar3x** [comment]
Yep. It pushes a popup with an activity indicator on it ... Im going to try to run it on the UI thread then might be a clue ! ty

**Comment by rdelrosario** [comment]
either OnStart or constructor should be good.

**Comment by Umar3x** [comment]
Okay, solved the prob ... was a code of mine that was causing issue. I ran loadingService on UIThread but did not have any link with the prob too. Thanks for your fast support.
