### ISSUE TITLE
Receiving and opening notifications with app in background increments number of events performed

### ISSUE THREAD

**Issue by MauroBocci** [CrossGeeks/FirebasePushNotificationPlugin#89]
Receiving and opening notification with app in background increments number of OnNotificationOpened events performed, and OnNotificationReceived for foreground notification (
both defined in MainPage.xaml.cs)

Version Number of Plugin: 2.1.3
Device Tested On: Samsung S7 Android 7.0 Api 24
Simulator Tested On: Android 6.0 Api 23
Version of VS: Visual Studio Professional 2017 version 15.5.2
Xamarin 4.8.0.753
Xamarin.Android SDK 8.1.0.25

I tested both your sample (samples\FirebasePushSample with Xamarin.Forms 2.3.4.247) and my app (with Xamarin.Forms 2.5.0.121934) with the same result.
How to reproduce:
1 - start app
2 - background the app
3 - send a notification by Firebase
4 - open notification and in debug output you see that OnNotificationOpened is performed twice
5 - leave app in foreground and send a notification
6 - in debug output you see OnNotificationReceived is performed twice, and when you open notification the same for OnNotificationOpened
7 - background the app, send and open a notification ...  in debug output you see OnNotificationOpened is performed three times
8 - and so on ... every time app is in background and receives and open a notification, the number of OnNotificationOpened executed is incremented

**Comment by rdelrosario** [comment]
Do you have a splash activity?

**Comment by MauroBocci** [comment]
Hi, no I have not a splash activity.
Please note that I am getting what described also using your sample (https://github.com/CrossGeeks/FirebasePushNotificationPlugin/tree/master/samples/FirebasePushSample)

**Comment by tonholis** [comment]
Same problem here.

**Comment by MauroBocci** [comment]
Any news about this issue?
Sorry, for me it is very important because I have to perform actions on OnNotificationOpened event and I have to perform only one action for each notification opened.

**Comment by rdelrosario** [comment]
I ran the sample with this same steps and just got the event once

**Comment by MauroBocci** [comment]
Ok thanks, I will try to change something in my development environment; any suggestion would be appreciated.

**Comment by rdelrosario** [comment]
Are you sure you have the NuGet packages for this plugin up to date with latest version on all your projects? (Because 1.0.7 version did had that issue you reported)

Also where are you subscribing to events?

**Comment by rdelrosario** [comment]
Will close this issue now, just released the latest stable version. if still having issues please let me know to see how I can help.

**Comment by Umar3x** [comment]
Hello,

I meet this prob too when app is in background. When user click on the notification it is being triggered as many times as the number of notifications I received. 

Every time app is in background and receives and open a notification, the number of OnNotificationOpened executed is incremented

**Comment by Umar3x** [comment]
@rdelrosario 

Any chance to get an answer :) ? this is quite an annoying behavior ....

**Comment by abrari** [comment]
@Umar3x : where and how do you attach the OnNotificationOpened event handler? In my case, I have to use static method (not a lambda) for the event handler.

**Comment by tonholis** [comment]
@Umar3x Sorry for the delayed response...

On Android, I ended up implementing push notification without using this component.

**Comment by tonholis** [comment]
> @tonholis - How are you opening specific view when clicking on notification and when app in foreground?

No. I didn't need to do that...

**Comment by arvindrajachourasiya** [comment]
ohk, Thank you. One quick question. Are you opening able to open specif view on notification tap, when app terminated. Same as this issue https://stackoverflow.com/questions/53594512/specific-view-not-opening-on-notification-tap-when-app-is-terminated

**Comment by Umar3x** [comment]
Hello @arvindrajachourasiya ,

If you want to open a specific view when app is closed and you click on the notification what I did is using cache strategy with Akavache and some custom Bootstraping. Considering push notif click opens your app (what it should do).

In the app.cs 
```
   protected override async void OnStart()
        {
            PushNotificationService.PushNotificationHandlers();
            ....
        }

```
Handlers when notification is opened 

```
 public void PushNotificationHandlers()
        {
            CrossFirebasePushNotification.Current.OnNotificationOpened += async (s, p) =>
            {
                if (App.AppBeenResumed)
                {
                    await BlobCache.UserAccount.InsertObject("pushNotifData", p.Data);
                }
                else
                {
                    await ProcessReceivedPushNotification(p.Data);
                    await BlobCache.UserAccount.InvalidateAllObjects<IDictionary<string, object>>();
                }
            };
}
```
On the first page users are landing on (assuming your MainPage), in the OnAppearing method, just check if key is present in the blob cache of akavache. 

    ```
 private async void HandlePushNotificationIfExists()
        {
            await Task.Delay(1000);
            IDictionary<string, object> pushNotifData;
            try
            {
                pushNotifData = await BlobCache.UserAccount.GetObject<IDictionary<string, object>>("pushNotifData");
            }
            catch (KeyNotFoundException)
            {
                pushNotifData = null;
            }

            if (pushNotifData == null) return;
            await BlobCache.UserAccount.InvalidateAllObjects<IDictionary<string, object>>();
            await PushNotificationService.ProcessReceivedPushNotification(pushNotifData);
        }
```
I have a PushNotificationService that treats every type of push notif, but you could simply push a new page or whatever you want. As we have a lot of different push notifs, I created a service that does the job alone considering pushNotifData content.

**Comment by liu12010** [comment]
Any solution?Met the same problem here :(

**Comment by raphaelsilvasage** [comment]
Any solution @rdelrosario ? Same problem here too

**Comment by swasti29** [comment]
Any solution of this problem, the event once attached not removing. Any idea what i am doing wrong?

**Comment by khaos258** [comment]
Same problem
