### ISSUE TITLE
Cannot display Heads-up notification

### ISSUE THREAD

**Issue by maian1891** [CrossGeeks/FirebasePushNotificationPlugin#9]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
Some devices can display Heads-up notification and badge (Xiaomi android 6.0) but LG g3 (android 6.0) cannot. 
Could you help me, pls? Could I permission for it??? 
Version Number of Plugin:
Device Tested On: LG g3 6.0 
Simulator Tested On: 
Version of VS: 
Version of Xamarin: 
Versions of other things you are using:

**Comment by rdelrosario** [comment]
As the documentation says you can implement your own PushNotificationHandler to achieve this kind of customization at the end of https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FirebaseNotifications.md. Anyways I might add this to the DefaultPushNotificationHandler in the future.

**Comment by maian1891** [comment]
Tks so much 👍
