### ISSUE TITLE
[Question] Mark as opened/remove notification from system programmatically

### ISSUE THREAD

**Issue by Nietoperek** [CrossGeeks/FirebasePushNotificationPlugin#90]
I got important and normal(parameter in data) notifications in my application. In some cases my application opens important notifications automatically, and when that happens I want to remove it from system notifications. I'm using default implementation with onReceived event to open it.
Can anyone tell me if that's possible? And is there any simple resolution?

**Comment by rdelrosario** [comment]
You men to delete notifications programatically instead of when notification is opened?

**Comment by Nietoperek** [comment]
Yes, Sir.

**Comment by mimunoz** [comment]
+1

**Comment by nemexyz** [comment]
+1

**Comment by rohitvipin** [comment]
You need to use android notification builder and update the notification you want to. You can't delete the notification but change the content to deleted.
