### ISSUE TITLE
Custom UI

### ISSUE THREAD

**Issue by idimkk** [CrossGeeks/FirebasePushNotificationPlugin#91]
Hello!
How can I use your plugin to create my own notification interface?
For example, to use a large picture in the notification for Android?
For example:
[large-icon](https://developer.xamarin.com/guides/android/application_fundamentals/notifications/local_notifications_in_android/#large-icon-format)
[image-style](https://developer.xamarin.com/guides/android/application_fundamentals/notifications/local_notifications_in_android/#image-style)

**Comment by rdelrosario** [comment]
You can initialize using a push notification handler. Check this at the end of https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FirebaseNotifications.md
