### ISSUE TITLE
Crash when Release on Android

### ISSUE THREAD

**Issue by Marsgames** [CrossGeeks/FirebasePushNotificationPlugin#92]
## Bug Information

Version Number of Plugin: 2.1.3
Device Tested On: Samsung SM-N910F API 23 (Galaxy Note 4)
Version of VS: 7.3.3 build 5
Version of Xamarin: 2.5.0.122203

### Steps to reproduce the Behavior
Run application on device in release

### Expected Behavior
Application work

### Actual Behavior
Application crash

### Code snippet
https://gist.github.com/Marsgames/acb3ccb1aff10576bf840b84e96a8caa
https://gist.github.com/Marsgames/2e7cfa83c2f61209b4ba4a5ff317300a

### Screenshots
![screenshot_2018-01-15-11-27-15](https://user-images.githubusercontent.com/9108765/34938098-57ba024e-f9e7-11e7-81e6-744a235ac051.png)

**Comment by Marsgames** [comment]
Seams to work if I remove bin and obj folder and clean solution.

Now I'm not able to receive any notification on android even in debug.
google-services ok, I'm registered in topics but don't receive any notification on topics or directly using token. Nothing happen.

**Comment by rdelrosario** [comment]
Ok Could you send me your AndroidManifest to check if is configured correctly?

**Comment by Marsgames** [comment]
For sure 

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionName="1.0" package="koders.airria" android:installLocation="preferExternal" android:versionCode="3">
	<uses-sdk android:minSdkVersion="15" />
	<uses-permission android:name="android.permission.INTERNET" />
	<application android:label="Airria" android:icon="@drawable/airrialogo">
	</application>
	<receiver android:name="localnotifications.plugin.ScheduledAlarmHandler" android:enabled="true">
	</receiver>
	<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
	<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
		<intent-filter>
			<action android:name="com.google.android.c2dm.intent.RECEIVE" />
			<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
			<category android:name="${applicationId}" />
		</intent-filter>
	</receiver>
</manifest>`

**Comment by rdelrosario** [comment]
Should be:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionName="1.0" package="koders.airria" android:installLocation="preferExternal" android:versionCode="3">
        <uses-sdk android:minSdkVersion="15" />
        <uses-permission android:name="android.permission.INTERNET" />
        <application android:label="Airria" android:icon="@drawable/airrialogo">
             <receiver android:name="localnotifications.plugin.ScheduledAlarmHandler" android:enabled="true">
             </receiver>
            <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
           <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
                <intent-filter>
                        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                        <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                        <category android:name="${applicationId}" />
                </intent-filter>
           </receiver>
        </application>
</manifest>
```

**Comment by Marsgames** [comment]
Thank you so much, it works perfectly now. You and your plugin are the best ;)
