### ISSUE TITLE
Object 

### ISSUE THREAD

**Issue by tallmanBS** [CrossGeeks/FirebasePushNotificationPlugin#93]
I loaded the sample project in VS2017 and ran the IOS with IphoneSimulator Iphone 5 IOS 9.3, and received "System.NullReferenceException: Object reference not set to an instance of an object" before I made any changes.  Stop shows up on window in UIApplication.Main(args, null, "ApDelegate");

I changed the googleservice.plist and appid to mine, still same error.  Below is the debug output.  I'm not sure how to find the object.  I put breakpoints throughout delegate and OnActivated was the last method handled went through.  Didn't see anything obvious.

Thanks for any help.  I've spent days trying to get firebase to work on my own, so I'm hoping your plugin will do the trick.
Brent

`Launching 'FirebasePushSample.iOS' on 'iPhone 5 iOS 9.3'...
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/.monotouch-32/Xamarin.iOS.dll [External]
Resolved pending breakpoint for 'UIKit.UIApplication.Main(string[], string, string)' to /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/src/UIKit/UIApplication.cs:61 [0x00000].
Resolved pending breakpoint for 'UIKit.UIApplication.Main(string[], System.Type, System.Type)' to /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/src/UIKit/UIApplication.cs:68 [0x00000].
Resolved pending breakpoint for 'UIKit.UIApplication.Main(string[])' to /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/src/UIKit/UIApplication.cs:73 [0x00000].
Resolved pending breakpoint for 'UIKit.UIApplication.Main(string[], System.IntPtr, System.IntPtr)' to /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/src/UIKit/UIApplication.cs:78 [0x00000].
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.dll [External]
Thread started:  #2
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/FirebasePushSample.iOS.exe
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Xamarin.Forms.Platform.iOS.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Xamarin.Forms.Core.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Runtime.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.ObjectModel.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Core.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Mono.Security.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Xml.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.ComponentModel.Composition.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Collections.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Diagnostics.Debug.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Threading.Tasks.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Globalization.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.ComponentModel.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Reflection.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Linq.Expressions.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.IO.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Dynamic.Runtime.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Threading.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Xamarin.Forms.Platform.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Runtime.Extensions.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Linq.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Reflection.Extensions.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Net.Http.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Runtime.Serialization.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.ServiceModel.Internals.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/FirebasePushSample.dll
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Resources.ResourceManager.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Xamarin.Forms.Xaml.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Text.RegularExpressions.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/System.Diagnostics.Tools.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Plugin.FirebasePushNotification.Abstractions.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Plugin.FirebasePushNotification.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Firebase.CloudMessaging.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Firebase.InstanceID.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Firebase.Core.dll [External]
Loaded assembly: /Users/adam/Library/Developer/CoreSimulator/Devices/DF58DA25-7445-4360-A24B-ED7F08F0FC26/data/Containers/Bundle/Application/9823F69D-5A1A-4C91-9E81-0F39958F3E7A/FirebasePushSample.iOS.app/Firebase.Analytics.dll [External]
Loaded assembly: /Users/adam/Library/Caches/Xamarin/XMA/Agents/Inspector/iOS/Xamarin.Interactive.iOS.dll [External]
Loaded assembly: /Users/adam/Library/Caches/Xamarin/XMA/Agents/Inspector/iOS/Xamarin.Interactive.dll [External]
2018-01-15 10:55:44.670 FirebasePushSample.iOS[9917] <Notice> [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40002000 started
2018-01-15 10:55:44.670 FirebasePushSample.iOS[9917] <Notice> [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2018-01-15 10:55:44.816 FirebasePushSample.iOS[9917] <Notice> [Firebase/Analytics][I-ACS023012] Firebase Analytics enabled
[0:] TOKEN: 
2018-01-15 10:55:44.848 FirebasePushSample.iOS[9917:223741] Error loading /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib:  dlopen(/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib, 262): no suitable image found.  Did find:
	/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib: mach-o, but not built for iOS simulator
2018-01-15 10:55:44.848 FirebasePushSample.iOS[9917:223741] Cannot find function pointer IOHIDLibFactory for factory 13AA9C44-6F1B-11D4-907C-0005028F18D5 in CFBundle/CFPlugIn 0x7a17c4a0 </System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin> (bundle, not loaded)
2018-01-15 10:55:44.849 FirebasePushSample.iOS[9917:223741] Error loading /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib:  dlopen(/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib, 262): no suitable image found.  Did find:
	/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib: mach-o, but not built for iOS simulator
2018-01-15 10:55:44.849 FirebasePushSample.iOS[9917:223741] Cannot find function pointer IOHIDLibFactory for factory 13AA9C44-6F1B-11D4-907C-0005028F18D5 in CFBundle/CFPlugIn 0x7a17c4a0 </System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin> (b
undle, not loaded)
Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object`

**Comment by tallmanBS** [comment]
FYI, I didn't receive the error on IOS 11.3 Iphone 5s, only on 9.3.
Brent

**Comment by rdelrosario** [comment]
Did you try on a real device?

**Comment by tallmanBS** [comment]
Hello.  Thanks for the response.  I finally was able to get on a real device version 9.3 a bit ago, so I'm good and can close the case.  I didn't realize the simulators don't support Push notifications.
