### ISSUE TITLE
error : Object reference not set to an instance of an object. in iOS

### ISSUE THREAD

**Issue by nmano2188** [CrossGeeks/FirebasePushNotificationPlugin#94]
3>Target "ResolveReferences" in file "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets" from project "E:\Cavintek\Cflow-Mobile\CflowApp Latest\CflowApp\CflowApp.iOS\CflowApp.iOS.csproj" (target "_UnpackLibraryResources" depends on it):
3>Done building target "ResolveReferences" in project "CflowApp.iOS.csproj".
3>Target "_CollectBundleResources" skipped. Previously built successfully.
3>Target "_FirebaseCoreItemsFolder" in file "E:\Cavintek\Cflow-Mobile\CflowApp Latest\packages\Xamarin.Firebase.iOS.Core.4.0.3\build\Xamarin.Firebase.iOS.Core.targets" from project "E:\Cavintek\Cflow-Mobile\CflowApp Latest\CflowApp\CflowApp.iOS\CflowApp.iOS.csproj" (target "_XamarinBuildAddDownloadedItems" depends on it):
3>Done building target "_FirebaseCoreItemsFolder" in project "CflowApp.iOS.csproj".
3>Target "_FirebaseInstanceIDItems" in file "E:\Cavintek\Cflow-Mobile\CflowApp Latest\packages\Xamarin.Firebase.iOS.InstanceID.2.0.0\build\Xamarin.Firebase.iOS.InstanceID.targets" from project "E:\Cavintek\Cflow-Mobile\CflowApp Latest\CflowApp\CflowApp.iOS\CflowApp.iOS.csproj" (target "_XamarinBuildAddDownloadedItems" depends on it):
3>Done building target "_FirebaseInstanceIDItems" in project "CflowApp.iOS.csproj".
3>Target "_FirebaseAnalyticsItems" in file "E:\Cavintek\Cflow-Mobile\CflowApp Latest\packages\Xamarin.Firebase.iOS.Analytics.4.0.2\build\Xamarin.Firebase.iOS.Analytics.targets" from project "E:\Cavintek\Cflow-Mobile\CflowApp Latest\CflowApp\CflowApp.iOS\CflowApp.iOS.csproj" (target "_XamarinBuildAddDownloadedItems" depends on it):
3>Done building target "_FirebaseAnalyticsItems" in project "CflowApp.iOS.csproj".
3>Target "_FirebaseCloudMessagingItems" in file "E:\Cavintek\Cflow-Mobile\CflowApp Latest\packages\Xamarin.Firebase.iOS.CloudMessaging.1.2.1.3\build\Xamarin.Firebase.iOS.CloudMessaging.targets" from project "E:\Cavintek\Cflow-Mobile\CflowApp Latest\CflowApp\CflowApp.iOS\CflowApp.iOS.csproj" (target "_XamarinBuildAddDownloadedItems" depends on it):
3>Done building target "_FirebaseCloudMessagingItems" in project "CflowApp.iOS.csproj".
3>Target "_XamarinBuildAddDownloadedItems" in file "E:\Cavintek\Cflow-Mobile\CflowApp Latest\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.targets" from project "E:\Cavintek\Cflow-Mobile\CflowApp Latest\CflowApp\CflowApp.iOS\CflowApp.iOS.csproj" (target "_XamarinBuildDownload" depends on it):
3>Done building target "_XamarinBuildAddDownloadedItems" in project "CflowApp.iOS.csproj".
3>Target "_XamarinBuildDownloadCore" in file "E:\Cavintek\Cflow-Mobile\CflowApp Latest\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.targets" from project "E:\Cavintek\Cflow-Mobile\CflowApp Latest\CflowApp\CflowApp.iOS\CflowApp.iOS.csproj" (target "_XamarinBuildDownload" depends on it):
3>Using "XamarinDownloadArchives" task from assembly "E:\Cavintek\Cflow-Mobile\CflowApp Latest\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.dll".
3>Task "XamarinDownloadArchives"
3>E:\Cavintek\Cflow-Mobile\CflowApp Latest\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.targets(52,3): error : Object reference not set to an instance of an object.
3>Done executing task "XamarinDownloadArchives" -- FAILED.
3>Done building target "_XamarinBuildDownloadCore" in project "CflowApp.iOS.csproj" -- FAILED.
3>
3>Build FAILED.
3>
3>Time Elapsed 00:00:30.76

**Comment by nmano2188** [comment]
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Visual C# 2015   00322-90150-00969-AA829
Microsoft Visual C# 2015

Visual C++ 2015   00322-90150-00969-AA829
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-90150-00969-AA829
Windows Phone SDK 8.0 - ENU

Mono Debugging for Visual Studio   4.8.4-pre (3fe64e3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.8.0.757 (7f9ec2a)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.8.191 (9ee2a69e8)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android   8.1.0.13 (f241f51)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.Android SDK   8.1.3.0 (HEAD/ef47226b7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS   11.6.1.2 (6857dfc)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS and Xamarin.Mac SDK   11.6.1.2 (6857dfc)

**Comment by rdelrosario** [comment]
which plugin version?

**Comment by nmano2188** [comment]
I faced this issue in both 2.1.3 and 1.0.7.

**Comment by nmano2188** [comment]
currently using 1.0.7

**Comment by rdelrosario** [comment]
I think your iOS .csproj is still referencing the old version and that might be the issue. Try deleting the packages folder and them restoring them all. Use version 2.1.3

**Comment by VictorK1902** [comment]
Can confirm that this is still an issue after 1.0.7. Tried deleting and restoring packages but to no avail.

@nmano2188 if you downgrade from 2.1.3 to 1.0.7, make sure you downgrade the following 2 packages as well:

Xamarin.Firebase.iOS.CloudMessaging --> 1.2.1.3 
Xamarin.Build.Download --> 0.4.3

I was able to build my iOS project after downgrading the above 2.

@rdelrosario I'm not sure if this will help, but I think the issue has something to do with the Xamarin.Build.Download package (version > 0.4.3)

    2>......\packages\Xamarin.Build.Download.0.4.6\build\Xamarin.Build.Download.targets(52,3): error : Object reference not set to an instance of an object.

**Comment by nmano2188** [comment]
@rdelrosario Done deleting & restoring package folder. But no use. 

@VictorK1902 I did all mentioned above. Still i'm facing problem. 

.......\packages\Xamarin.Build.Download.0.4.3\build\Xamarin.Build.Download.targets(51,3): error : Object reference not set to an instance of an object.

**Comment by rdelrosario** [comment]
Try installing:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.2.0-beta

**Comment by nmano2188** [comment]
@rdelrosario 2.2.0-beta version installed and deleted bin & obj folders
then cleaned and rebuild solution. Nothing works.

**Comment by VictorK1902** [comment]
That was strange you couldn't build it still. I guess keep downgrading the component until you can build it.

Also I installed all pending updates for Visual Studio, hoping it would fix for any version >1.0.7, but issue still persists. I guess I'll stick with 1.0.7 for now. Attached is my VS about.

[aboutVS.txt](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/files/1643972/aboutVS.txt)

**Comment by rdelrosario** [comment]
What SDK you have set as target in your Android project?

**Comment by nmano2188** [comment]
Android 8.0 Oreo

**Comment by nmano2188** [comment]
Any updates?

**Comment by rdelrosario** [comment]
Tried the sample is compiling and working without any issues, so this seems an environment issue. Anyways I released the latest version to stable if you want to try it out, the repository sample is using it now:

https://www.nuget.org/packages/Plugin.FirebasePushNotification/2.2.1

**Comment by jpessini** [comment]
Open the following file:
C:<path to your app>\packages\Xamarin.Build.Download.0.4.7\build\Xamarin.Build.Download.targets

Search for:
$(VsInstallRoot)\Common7\IDE\Extensions\Xamarin\Xamarin.VisualStudio\7-Zip\7z.exe

And replace with the correct path:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Xamarin\Xamarin.VisualStudio\7-Zip\7z.exe

;)

**Comment by nmano2188** [comment]
Thank you i will try it.

**Comment by nmano2188** [comment]
@rdelrosario  @jpessini Updating 2.2.1 and changing 7z.exe path fixed my issue


Thanks
