### ISSUE TITLE
Not all topics work

### ISSUE THREAD

**Issue by Marsgames** [CrossGeeks/FirebasePushNotificationPlugin#95]
Hey,

I use this code to register to my topics : 
``` C#
if(App.PROFILE == "AG-DIR") {
    CrossFirebasePushNotification.Current.Unsubscribe("AG-TECH");
    CrossFirebasePushNotification.Current.Subscribe(new string[] { "AG-DIR", "USER" });
} else {
    CrossFirebasePushNotification.Current.Unsubscribe("AG-DIR");
    CrossFirebasePushNotification.Current.Subscribe(new string[] { "AG-TECH", "USER" });
}
```

If I try to send notifications to USER with this code it work perfectly
``` Ruby
curl -H "Authorization:key= *****" -H "Content-Type:application/json" -X POST -d'{"to":"/topics/USER","priority":"high","data":{	"message":"","other_key":true,"body":"body data"},	"notification":{	"body":"Notification to USER", "title":"Notif USER","sound":"default","content_available":true, "badge": 1},}' https://fcm.googleapis.com/fcm/send
```

But if I do the same, replacing USER by AG-DIR or AG-TECH it won't receive notification

**Comment by rdelrosario** [comment]
I tested this same topics on the repo sample and worked fine. Your issue is on Android or iOS?

**Comment by Marsgames** [comment]
Issue is on both. But I noted that sometimes both topics work, sometimes not. Maybe a firebase issue and not because of the plugin

**Comment by rdelrosario** [comment]
Try the sample I tested this same scenario you post here and worked.

**Comment by rdelrosario** [comment]
Please let me know if tested the sample

**Comment by rdelrosario** [comment]
Will close this issue since doesn’t seem to be issue of the plugin. Anyways let me know how to help with this
