### ISSUE TITLE
Hiding Notification From notification are when App in Foreground

### ISSUE THREAD

**Issue by skyritsis** [CrossGeeks/FirebasePushNotificationPlugin#96]
I would like to ask you, if there is a way to hide the notification area, when the is in the foreground.

Thank you in advance for your time.

**Comment by rdelrosario** [comment]
On Android?

**Comment by skyritsis** [comment]
On Android I was able to solve it by using p.Data.Add("silent", "true").
This does not seem to work on IOS though. Should it work the same way on IOS too?

**Comment by rdelrosario** [comment]
By default you don't get the notification on the notification center on iOS if app is on foreground visible

**Comment by skyritsis** [comment]
Thank you for the info. I'm probably messing some other place.
