### ISSUE TITLE
Doubt notifications in background

### ISSUE THREAD

**Issue by simon25608** [CrossGeeks/FirebasePushNotificationPlugin#98]
I have a doubt, when the application is completely closed, notifications are received in:

 //Handle notifications when app closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("NOTIFICATION RECEIVED", p.Data);
            };

That I have to manually create the notification here?

**Comment by rdelrosario** [comment]
No it will be created automatically

**Comment by simon25608** [comment]
I feel the delay, I was on vacation, thank you very much.
